
drug_interaction('Mefloquine', 'Moxifloxacin').
drug_interaction('Mefloquine', 'Olanzapine').
drug_interaction('Mefloquine', 'Pregabalin').
drug_interaction('Mefloquine', 'Procyclidine').
drug_interaction('Mefloquine', 'Topiramate').
drug_interaction('Drotrecogin alfa', 'Phenindione').
drug_interaction('Amlodipine', 'Betaxolol').
drug_interaction('Amlodipine', 'Caffeine').
drug_interaction('Amlodipine', 'Calcium Acetate').
drug_interaction('Amlodipine', 'Clotrimazole').
drug_interaction('Amlodipine', 'Dofetilide').
drug_interaction('Amlodipine', 'Doxycycline').
drug_interaction('Amlodipine', 'Duloxetine').
drug_interaction('Amlodipine', 'Esmolol').
drug_interaction('Amlodipine', 'Fluconazole').
drug_interaction('Amlodipine', 'Fosinopril').
drug_interaction('Amlodipine', 'Gemcitabine').
drug_interaction('Amlodipine', 'Lansoprazole').
drug_interaction('Amlodipine', 'Nitroprusside').
drug_interaction('Amlodipine', 'Olanzapine').
drug_interaction('Amlodipine', 'Ropivacaine').
drug_interaction('Amlodipine', 'Secobarbital').
drug_interaction('Amlodipine', 'Triamterene').
drug_interaction('Amlodipine', 'Valsartan').
drug_interaction('Doxycycline', 'Dronabinol').
drug_interaction('Doxycycline', 'Ergocalciferol').
drug_interaction('Doxycycline', 'Fluorometholone').
drug_interaction('Doxycycline', 'Lansoprazole').
drug_interaction('Doxycycline', 'Levonorgestrel').
drug_interaction('Doxycycline', 'Mefloquine').
drug_interaction('Doxycycline', 'Pantoprazole').
drug_interaction('Doxycycline', 'Phenindione').
drug_interaction('Doxycycline', 'Reboxetine').
drug_interaction('Doxycycline', 'Ropivacaine').
drug_interaction('Doxycycline', 'Secobarbital').
drug_interaction('Doxycycline', 'Sulfadiazine').
drug_interaction('Doxycycline', 'Terfenadine').
drug_interaction('Doxycycline', 'Theophylline').
drug_interaction('Doxycycline', 'Vindesine').
drug_interaction('Olanzapine', 'Pantoprazole').
drug_interaction('Olanzapine', 'Phentermine').
drug_interaction('Olanzapine', 'Pregabalin').
drug_interaction('Olanzapine', 'Reboxetine').
drug_interaction('Olanzapine', 'Ropivacaine').
drug_interaction('Olanzapine', 'Rosiglitazone').
drug_interaction('Olanzapine', 'Secobarbital').
drug_interaction('Olanzapine', 'Tacrine').
drug_interaction('Olanzapine', 'Terfenadine').
drug_interaction('Olanzapine', 'Theophylline').
drug_interaction('Olanzapine', 'Topiramate').
drug_interaction('Fosinopril', 'Nitroprusside').
drug_interaction('Fosinopril', 'Pregabalin').
drug_interaction('Fosinopril', 'Ropivacaine').
drug_interaction('Fosinopril', 'Secobarbital').
drug_interaction('Fosinopril', 'Theophylline').
drug_interaction('Fosinopril', 'Triamterene').
drug_interaction('Fosinopril', 'Valsartan').
drug_interaction('Sulfadiazine', 'Terfenadine').
drug_interaction('Sulfadiazine', 'Theophylline').
drug_interaction('Sulfadiazine', 'Valsartan').
drug_interaction('Triamterene', 'Valsartan').
drug_interaction('Adapalene', 'Betaxolol').
drug_interaction('Adapalene', 'Desmopressin').
drug_interaction('Adapalene', 'Doxycycline').
drug_interaction('Adapalene', 'Enoxacin').
drug_interaction('Adapalene', 'Esmolol').
drug_interaction('Adapalene', 'Fluorometholone').
drug_interaction('Adapalene', 'Fosinopril').
drug_interaction('Adapalene', 'Levonorgestrel').
drug_interaction('Adapalene', 'Moxifloxacin').
drug_interaction('Adapalene', 'Phenindione').
drug_interaction('Adapalene', 'Triamterene').
drug_interaction('Adapalene', 'Valsartan').
drug_interaction('Clotrimazole', 'Dofetilide').
drug_interaction('Clotrimazole', 'Dronabinol').
drug_interaction('Clotrimazole', 'Duloxetine').
drug_interaction('Clotrimazole', 'Ergocalciferol').
drug_interaction('Clotrimazole', 'Fluorometholone').
drug_interaction('Clotrimazole', 'Gemcitabine').
drug_interaction('Clotrimazole', 'Lansoprazole').
drug_interaction('Clotrimazole', 'Levonorgestrel').
drug_interaction('Clotrimazole', 'Mefloquine').
drug_interaction('Clotrimazole', 'Menadione').
drug_interaction('Clotrimazole', 'Olanzapine').
drug_interaction('Clotrimazole', 'Pantoprazole').
drug_interaction('Clotrimazole', 'Pregabalin').
drug_interaction('Clotrimazole', 'Reboxetine').
drug_interaction('Clotrimazole', 'Ropivacaine').
drug_interaction('Clotrimazole', 'Rosiglitazone').
drug_interaction('Clotrimazole', 'Sulfadiazine').
drug_interaction('Clotrimazole', 'Tacrine').
drug_interaction('Clotrimazole', 'Terfenadine').
drug_interaction('Clotrimazole', 'Theophylline').
drug_interaction('Clotrimazole', 'Triamterene').
drug_interaction('Clotrimazole', 'Valsartan').
drug_interaction('Clotrimazole', 'Vindesine').
drug_interaction('Buspirone', 'Caffeine').
drug_interaction('Buspirone', 'Cetirizine').
drug_interaction('Buspirone', 'Cholecalciferol').
drug_interaction('Buspirone', 'Clotrimazole').
drug_interaction('Buspirone', 'Doxycycline').
drug_interaction('Buspirone', 'Dronabinol').
drug_interaction('Buspirone', 'Duloxetine').
drug_interaction('Buspirone', 'Fluconazole').
drug_interaction('Buspirone', 'Gemcitabine').
drug_interaction('Buspirone', 'Lansoprazole').
drug_interaction('Buspirone', 'Lorazepam').
drug_interaction('Buspirone', 'Methocarbamol').
drug_interaction('Buspirone', 'Olanzapine').
drug_interaction('Buspirone', 'Pregabalin').
drug_interaction('Buspirone', 'Ropivacaine').
drug_interaction('Buspirone', 'Secobarbital').
drug_interaction('Buspirone', 'Topiramate').
drug_interaction('Menadione', 'Theophylline').
drug_interaction('Cholecalciferol', 'Clotrimazole').
drug_interaction('Cholecalciferol', 'Doxycycline').
drug_interaction('Cholecalciferol', 'Dronabinol').
drug_interaction('Cholecalciferol', 'Duloxetine').
drug_interaction('Cholecalciferol', 'Ergocalciferol').
drug_interaction('Cholecalciferol', 'Fluconazole').
drug_interaction('Cholecalciferol', 'Lansoprazole').
drug_interaction('Cholecalciferol', 'Olanzapine').
drug_interaction('Cholecalciferol', 'Pantoprazole').
drug_interaction('Cholecalciferol', 'Ropivacaine').
drug_interaction('Cholecalciferol', 'Rosiglitazone').
drug_interaction('Cholecalciferol', 'Sulfadiazine').
drug_interaction('Cholecalciferol', 'Terfenadine').
drug_interaction('Cholecalciferol', 'Theophylline').
drug_interaction('Cholecalciferol', 'Valsartan').
drug_interaction('Ropivacaine', 'Secobarbital').
drug_interaction('Ropivacaine', 'Theophylline').
drug_interaction('Ropivacaine', 'Topiramate').
drug_interaction('Ropivacaine', 'Triamterene').
drug_interaction('Ropivacaine', 'Valsartan').
drug_interaction('Gramicidin D', 'Lansoprazole').
drug_interaction('Gramicidin D', 'Olanzapine').
drug_interaction('Dicloxacillin', 'Doxycycline').
drug_interaction('Dicloxacillin', 'Phenindione').
drug_interaction('Interferon Alfa-2a, Recombinant', 'Theophylline').
drug_interaction('Pantoprazole', 'Theophylline').
drug_interaction('Pantoprazole', 'Topiramate').
drug_interaction('Pyridoxine', 'Secobarbital').
drug_interaction('Amsacrine', 'Betaxolol').
drug_interaction('Amsacrine', 'Caffeine').
drug_interaction('Amsacrine', 'Cholecalciferol').
drug_interaction('Amsacrine', 'Clotrimazole').
drug_interaction('Amsacrine', 'Duloxetine').
drug_interaction('Amsacrine', 'Gemcitabine').
drug_interaction('Amsacrine', 'Lansoprazole').
drug_interaction('Amsacrine', 'Olanzapine').
drug_interaction('Procyclidine', 'Tacrine').
drug_interaction('Procyclidine', 'Topiramate').
drug_interaction('Dronabinol', 'Fluconazole').
drug_interaction('Dronabinol', 'Gemcitabine').
drug_interaction('Dronabinol', 'Lansoprazole').
drug_interaction('Dronabinol', 'Lorazepam').
drug_interaction('Dronabinol', 'Methocarbamol').
drug_interaction('Dronabinol', 'Midodrine').
drug_interaction('Dronabinol', 'Olanzapine').
drug_interaction('Dronabinol', 'Pantoprazole').
drug_interaction('Dronabinol', 'Phentermine').
drug_interaction('Dronabinol', 'Pregabalin').
drug_interaction('Dronabinol', 'Procyclidine').
drug_interaction('Dronabinol', 'Pyrimethamine').
drug_interaction('Dronabinol', 'Ropivacaine').
drug_interaction('Dronabinol', 'Secobarbital').
drug_interaction('Dronabinol', 'Sulfadiazine').
drug_interaction('Dronabinol', 'Topiramate').
drug_interaction('Dronabinol', 'Valsartan').
drug_interaction('Fluorometholone', 'Mefloquine').
drug_interaction('Fluorometholone', 'Moxifloxacin').
drug_interaction('Fluorometholone', 'Tacrine').
drug_interaction('Betaxolol', 'Buspirone').
drug_interaction('Betaxolol', 'Caffeine').
drug_interaction('Betaxolol', 'Cholecalciferol').
drug_interaction('Betaxolol', 'Clotrimazole').
drug_interaction('Betaxolol', 'Duloxetine').
drug_interaction('Betaxolol', 'Esmolol').
drug_interaction('Betaxolol', 'Fosinopril').
drug_interaction('Betaxolol', 'Isoetarine').
drug_interaction('Betaxolol', 'Mefloquine').
drug_interaction('Betaxolol', 'Midodrine').
drug_interaction('Betaxolol', 'Nitroprusside').
drug_interaction('Betaxolol', 'Olanzapine').
drug_interaction('Betaxolol', 'Ropivacaine').
drug_interaction('Betaxolol', 'Secobarbital').
drug_interaction('Betaxolol', 'Tacrine').
drug_interaction('Betaxolol', 'Terfenadine').
drug_interaction('Betaxolol', 'Theophylline').
drug_interaction('Betaxolol', 'Triamterene').
drug_interaction('Betaxolol', 'Valsartan').
drug_interaction('Anistreplase', 'Phenindione').
drug_interaction('Methocarbamol', 'Olanzapine').
drug_interaction('Methocarbamol', 'Pregabalin').
drug_interaction('Methocarbamol', 'Ropivacaine').
drug_interaction('Methocarbamol', 'Secobarbital').
drug_interaction('Methocarbamol', 'Topiramate').
drug_interaction('Phentermine', 'Terfenadine').
drug_interaction('Calcium Acetate', 'Cholecalciferol').
drug_interaction('Calcium Acetate', 'Doxycycline').
drug_interaction('Calcium Acetate', 'Enoxacin').
drug_interaction('Calcium Acetate', 'Ergocalciferol').
drug_interaction('Calcium Acetate', 'Moxifloxacin').
drug_interaction('Calcium Acetate', 'Pregabalin').
drug_interaction('Pyrimethamine', 'Rosiglitazone').
drug_interaction('Pyrimethamine', 'Sulfadiazine').
drug_interaction('Pyrimethamine', 'Terfenadine').
drug_interaction('Pyrimethamine', 'Theophylline').
drug_interaction('Pyrimethamine', 'Valsartan').
drug_interaction('Miglustat', 'Olanzapine').
drug_interaction('Miglustat', 'Sulfadiazine').
drug_interaction('Duloxetine', 'Esmolol').
drug_interaction('Duloxetine', 'Fosinopril').
drug_interaction('Duloxetine', 'Insulin Human').
drug_interaction('Duloxetine', 'Isoetarine').
drug_interaction('Duloxetine', 'Lorazepam').
drug_interaction('Duloxetine', 'Methocarbamol').
drug_interaction('Duloxetine', 'Midodrine').
drug_interaction('Duloxetine', 'Nitroprusside').
drug_interaction('Duloxetine', 'Olanzapine').
drug_interaction('Duloxetine', 'Phenindione').
drug_interaction('Duloxetine', 'Pregabalin').
drug_interaction('Duloxetine', 'Ropivacaine').
drug_interaction('Duloxetine', 'Rosiglitazone').
drug_interaction('Duloxetine', 'Secobarbital').
drug_interaction('Duloxetine', 'Sulfadiazine').
drug_interaction('Duloxetine', 'Terfenadine').
drug_interaction('Duloxetine', 'Theophylline').
drug_interaction('Duloxetine', 'Topiramate').
drug_interaction('Duloxetine', 'Triamterene').
drug_interaction('Duloxetine', 'Valsartan').
drug_interaction('Megestrol acetate', 'Miglustat').
drug_interaction('Megestrol acetate', 'Olanzapine').
drug_interaction('Megestrol acetate', 'Phenindione').
drug_interaction('Megestrol acetate', 'Rosiglitazone').
drug_interaction('Rosiglitazone', 'Secobarbital').
drug_interaction('Rosiglitazone', 'Sulfadiazine').
drug_interaction('Rosiglitazone', 'Theophylline').
drug_interaction('Rosiglitazone', 'Valsartan').
drug_interaction('Esmolol', 'Fosinopril').
drug_interaction('Esmolol', 'Isoetarine').
drug_interaction('Esmolol', 'Mefloquine').
drug_interaction('Esmolol', 'Midodrine').
drug_interaction('Esmolol', 'Nitroprusside').
drug_interaction('Esmolol', 'Ropivacaine').
drug_interaction('Esmolol', 'Secobarbital').
drug_interaction('Esmolol', 'Tacrine').
drug_interaction('Esmolol', 'Theophylline').
drug_interaction('Esmolol', 'Triamterene').
drug_interaction('Esmolol', 'Valsartan').
drug_interaction('Terfenadine', 'Valsartan').
drug_interaction('Moxifloxacin', 'Olanzapine').
drug_interaction('Moxifloxacin', 'Phenindione').
drug_interaction('Moxifloxacin', 'Rosiglitazone').
drug_interaction('Moxifloxacin', 'Sulfadiazine').
drug_interaction('Moxifloxacin', 'Theophylline').
drug_interaction('Interferon alfa-n1', 'Theophylline').
drug_interaction('Lorazepam', 'Mefloquine').
drug_interaction('Lorazepam', 'Methocarbamol').
drug_interaction('Lorazepam', 'Olanzapine').
drug_interaction('Lorazepam', 'Pregabalin').
drug_interaction('Lorazepam', 'Ropivacaine').
drug_interaction('Lorazepam', 'Secobarbital').
drug_interaction('Lorazepam', 'Theophylline').
drug_interaction('Lorazepam', 'Topiramate').
drug_interaction('Secobarbital', 'Sulfadiazine').
drug_interaction('Secobarbital', 'Terfenadine').
drug_interaction('Secobarbital', 'Theophylline').
drug_interaction('Secobarbital', 'Topiramate').
drug_interaction('Secobarbital', 'Triamterene').
drug_interaction('Secobarbital', 'Valsartan').
drug_interaction('Dofetilide', 'Doxycycline').
drug_interaction('Dofetilide', 'Fluconazole').
drug_interaction('Dofetilide', 'Leuprolide').
drug_interaction('Dofetilide', 'Mefloquine').
drug_interaction('Dofetilide', 'Megestrol acetate').
drug_interaction('Dofetilide', 'Moxifloxacin').
drug_interaction('Dofetilide', 'Olanzapine').
drug_interaction('Dofetilide', 'Triamterene').
drug_interaction('Cetirizine', 'Dronabinol').
drug_interaction('Cetirizine', 'Duloxetine').
drug_interaction('Cetirizine', 'Lorazepam').
drug_interaction('Cetirizine', 'Methocarbamol').
drug_interaction('Cetirizine', 'Olanzapine').
drug_interaction('Cetirizine', 'Phentermine').
drug_interaction('Cetirizine', 'Pregabalin').
drug_interaction('Cetirizine', 'Ropivacaine').
drug_interaction('Cetirizine', 'Secobarbital').
drug_interaction('Cetirizine', 'Topiramate').
drug_interaction('Midodrine', 'Phentermine').
drug_interaction('Fluconazole', 'Fluorometholone').
drug_interaction('Fluconazole', 'Gemcitabine').
drug_interaction('Fluconazole', 'Lansoprazole').
drug_interaction('Fluconazole', 'Leuprolide').
drug_interaction('Fluconazole', 'Levonorgestrel').
drug_interaction('Fluconazole', 'Mefloquine').
drug_interaction('Fluconazole', 'Moxifloxacin').
drug_interaction('Fluconazole', 'Olanzapine').
drug_interaction('Fluconazole', 'Pantoprazole').
drug_interaction('Fluconazole', 'Phenindione').
drug_interaction('Fluconazole', 'Pregabalin').
drug_interaction('Fluconazole', 'Reboxetine').
drug_interaction('Fluconazole', 'Ropivacaine').
drug_interaction('Fluconazole', 'Rosiglitazone').
drug_interaction('Fluconazole', 'Sulfadiazine').
drug_interaction('Fluconazole', 'Terfenadine').
drug_interaction('Fluconazole', 'Theophylline').
drug_interaction('Fluconazole', 'Valsartan').
drug_interaction('Fluconazole', 'Vindesine').
drug_interaction('Peginterferon alfa-2a', 'Theophylline').
drug_interaction('Alprazolam', 'Buspirone').
drug_interaction('Alprazolam', 'Cetirizine').
drug_interaction('Alprazolam', 'Cholecalciferol').
drug_interaction('Alprazolam', 'Clotrimazole').
drug_interaction('Alprazolam', 'Dofetilide').
drug_interaction('Alprazolam', 'Doxycycline').
drug_interaction('Alprazolam', 'Dronabinol').
drug_interaction('Alprazolam', 'Duloxetine').
drug_interaction('Alprazolam', 'Fluconazole').
drug_interaction('Alprazolam', 'Fosinopril').
drug_interaction('Alprazolam', 'Lorazepam').
drug_interaction('Alprazolam', 'Methocarbamol').
drug_interaction('Alprazolam', 'Olanzapine').
drug_interaction('Alprazolam', 'Pregabalin').
drug_interaction('Alprazolam', 'Pyrimethamine').
drug_interaction('Alprazolam', 'Ropivacaine').
drug_interaction('Alprazolam', 'Secobarbital').
drug_interaction('Alprazolam', 'Sulfadiazine').
drug_interaction('Alprazolam', 'Theophylline').
drug_interaction('Alprazolam', 'Topiramate').
drug_interaction('Alprazolam', 'Valsartan').
drug_interaction('Insulin Human', 'Miglustat').
drug_interaction('Insulin Human', 'Moxifloxacin').
drug_interaction('Insulin Human', 'Rosiglitazone').
drug_interaction('Insulin Human', 'Sulfadiazine').
drug_interaction('Desmopressin', 'Duloxetine').
drug_interaction('Leuprolide', 'Mefloquine').
drug_interaction('Leuprolide', 'Miglustat').
drug_interaction('Leuprolide', 'Moxifloxacin').
drug_interaction('Leuprolide', 'Olanzapine').
drug_interaction('Leuprolide', 'Rosiglitazone').
drug_interaction('Gemcitabine', 'Gramicidin D').
drug_interaction('Gemcitabine', 'Lansoprazole').
drug_interaction('Gemcitabine', 'Mefloquine').
drug_interaction('Gemcitabine', 'Megestrol acetate').
drug_interaction('Gemcitabine', 'Mitomycin').
drug_interaction('Gemcitabine', 'Pantoprazole').
drug_interaction('Gemcitabine', 'Reboxetine').
drug_interaction('Gemcitabine', 'Tacrine').
drug_interaction('Gemcitabine', 'Terfenadine').
drug_interaction('Phenindione', 'Rosiglitazone').
drug_interaction('Phenindione', 'Secobarbital').
drug_interaction('Phenindione', 'Sulfadiazine').
drug_interaction('Enoxacin', 'Fluorometholone').
drug_interaction('Enoxacin', 'Insulin Human').
drug_interaction('Enoxacin', 'Phenindione').
drug_interaction('Enoxacin', 'Rosiglitazone').
drug_interaction('Enoxacin', 'Sulfadiazine').
drug_interaction('Enoxacin', 'Theophylline').
drug_interaction('Lansoprazole', 'Mefloquine').
drug_interaction('Lansoprazole', 'Megestrol acetate').
drug_interaction('Lansoprazole', 'Mitomycin').
drug_interaction('Lansoprazole', 'Olanzapine').
drug_interaction('Lansoprazole', 'Pantoprazole').
drug_interaction('Lansoprazole', 'Phenindione').
drug_interaction('Lansoprazole', 'Pyrimethamine').
drug_interaction('Lansoprazole', 'Reboxetine').
drug_interaction('Lansoprazole', 'Rosiglitazone').
drug_interaction('Lansoprazole', 'Secobarbital').
drug_interaction('Lansoprazole', 'Sulfadiazine').
drug_interaction('Lansoprazole', 'Tacrine').
drug_interaction('Lansoprazole', 'Terfenadine').
drug_interaction('Lansoprazole', 'Topiramate').
drug_interaction('Lansoprazole', 'Valsartan').
drug_interaction('Tacrine', 'Theophylline').
drug_interaction('Nitroprusside', 'Pregabalin').
drug_interaction('Nitroprusside', 'Ropivacaine').
drug_interaction('Nitroprusside', 'Secobarbital').
drug_interaction('Nitroprusside', 'Triamterene').
drug_interaction('Nitroprusside', 'Valsartan').
drug_interaction('Theophylline', 'Triamterene').
drug_interaction('Theophylline', 'Valsartan').
drug_interaction('Pregabalin', 'Ropivacaine').
drug_interaction('Pregabalin', 'Rosiglitazone').
drug_interaction('Pregabalin', 'Secobarbital').
drug_interaction('Pregabalin', 'Topiramate').
drug_interaction('Acetyldigitoxin', 'Aminoglutethimide').
drug_interaction('Acetyldigitoxin', 'Amsacrine').
drug_interaction('Acetyldigitoxin', 'Betaxolol').
drug_interaction('Acetyldigitoxin', 'Calcium Acetate').
drug_interaction('Acetyldigitoxin', 'Cholecalciferol').
drug_interaction('Acetyldigitoxin', 'Cladribine').
drug_interaction('Acetyldigitoxin', 'Enoxacin').
drug_interaction('Acetyldigitoxin', 'Ergocalciferol').
drug_interaction('Acetyldigitoxin', 'Esmolol').
drug_interaction('Acetyldigitoxin', 'Gemcitabine').
drug_interaction('Acetyldigitoxin', 'Leuprolide').
drug_interaction('Acetyldigitoxin', 'Megestrol acetate').
drug_interaction('Acetyldigitoxin', 'Midodrine').
drug_interaction('Acetyldigitoxin', 'Mitomycin').
drug_interaction('Acetyldigitoxin', 'Moxifloxacin').
drug_interaction('Acetyldigitoxin', 'Raltitrexed').
drug_interaction('Acetyldigitoxin', 'Triamterene').
drug_interaction('Acetyldigitoxin', 'Vindesine').
drug_interaction('Ergocalciferol', 'Fluconazole').
drug_interaction('Glucagon recombinant', 'Phenindione').
drug_interaction('Glucagon recombinant', 'Procyclidine').
drug_interaction('Caffeine', 'Cholecalciferol').
drug_interaction('Caffeine', 'Clotrimazole').
drug_interaction('Caffeine', 'Doxycycline').
drug_interaction('Caffeine', 'Dronabinol').
drug_interaction('Caffeine', 'Duloxetine').
drug_interaction('Caffeine', 'Fluconazole').
drug_interaction('Caffeine', 'Gemcitabine').
drug_interaction('Caffeine', 'Gramicidin D').
drug_interaction('Caffeine', 'Lansoprazole').
drug_interaction('Caffeine', 'Mefloquine').
drug_interaction('Caffeine', 'Megestrol acetate').
drug_interaction('Caffeine', 'Menadione').
drug_interaction('Caffeine', 'Mitomycin').
drug_interaction('Caffeine', 'Olanzapine').
drug_interaction('Caffeine', 'Pantoprazole').
drug_interaction('Caffeine', 'Pyrimethamine').
drug_interaction('Caffeine', 'Reboxetine').
drug_interaction('Caffeine', 'Ropivacaine').
drug_interaction('Caffeine', 'Rosiglitazone').
drug_interaction('Caffeine', 'Secobarbital').
drug_interaction('Caffeine', 'Sulfadiazine').
drug_interaction('Caffeine', 'Tacrine').
drug_interaction('Caffeine', 'Terfenadine').
drug_interaction('Caffeine', 'Theophylline').
drug_interaction('Caffeine', 'Triamterene').
drug_interaction('Caffeine', 'Valsartan').
drug_interaction('Levonorgestrel', 'Miglustat').
drug_interaction('Levonorgestrel', 'Phenindione').
drug_interaction('Levonorgestrel', 'Rosiglitazone').
drug_interaction('Levonorgestrel', 'Secobarbital').
drug_interaction('Levonorgestrel', 'Topiramate').
drug_interaction('Mitomycin', 'Olanzapine').
drug_interaction('Mitomycin', 'Vindesine').
drug_interaction('Acetohexamide', 'Betaxolol').
drug_interaction('Acetohexamide', 'Esmolol').
drug_interaction('Acetohexamide', 'Fluconazole').
drug_interaction('Acetohexamide', 'Insulin Human').
drug_interaction('Acetohexamide', 'Leuprolide').
drug_interaction('Acetohexamide', 'Levonorgestrel').
drug_interaction('Acetohexamide', 'Megestrol acetate').
drug_interaction('Acetohexamide', 'Olanzapine').
drug_interaction('Acetohexamide', 'Phenindione').
drug_interaction('Acetohexamide', 'Rosiglitazone').
drug_interaction('Acetohexamide', 'Sulfadiazine').
drug_interaction('Moxifloxacin', 'Mefloquine').
drug_interaction('Olanzapine', 'Mefloquine').
drug_interaction('Pregabalin', 'Mefloquine').
drug_interaction('Procyclidine', 'Mefloquine').
drug_interaction('Topiramate', 'Mefloquine').
drug_interaction('Phenindione', 'Drotrecogin alfa').
drug_interaction('Betaxolol', 'Amlodipine').
drug_interaction('Caffeine', 'Amlodipine').
drug_interaction('Calcium Acetate', 'Amlodipine').
drug_interaction('Clotrimazole', 'Amlodipine').
drug_interaction('Dofetilide', 'Amlodipine').
drug_interaction('Doxycycline', 'Amlodipine').
drug_interaction('Duloxetine', 'Amlodipine').
drug_interaction('Esmolol', 'Amlodipine').
drug_interaction('Fluconazole', 'Amlodipine').
drug_interaction('Fosinopril', 'Amlodipine').
drug_interaction('Gemcitabine', 'Amlodipine').
drug_interaction('Lansoprazole', 'Amlodipine').
drug_interaction('Nitroprusside', 'Amlodipine').
drug_interaction('Olanzapine', 'Amlodipine').
drug_interaction('Ropivacaine', 'Amlodipine').
drug_interaction('Secobarbital', 'Amlodipine').
drug_interaction('Triamterene', 'Amlodipine').
drug_interaction('Valsartan', 'Amlodipine').
drug_interaction('Dronabinol', 'Doxycycline').
drug_interaction('Ergocalciferol', 'Doxycycline').
drug_interaction('Fluorometholone', 'Doxycycline').
drug_interaction('Lansoprazole', 'Doxycycline').
drug_interaction('Levonorgestrel', 'Doxycycline').
drug_interaction('Mefloquine', 'Doxycycline').
drug_interaction('Pantoprazole', 'Doxycycline').
drug_interaction('Phenindione', 'Doxycycline').
drug_interaction('Reboxetine', 'Doxycycline').
drug_interaction('Ropivacaine', 'Doxycycline').
drug_interaction('Secobarbital', 'Doxycycline').
drug_interaction('Sulfadiazine', 'Doxycycline').
drug_interaction('Terfenadine', 'Doxycycline').
drug_interaction('Theophylline', 'Doxycycline').
drug_interaction('Vindesine', 'Doxycycline').
drug_interaction('Pantoprazole', 'Olanzapine').
drug_interaction('Phentermine', 'Olanzapine').
drug_interaction('Pregabalin', 'Olanzapine').
drug_interaction('Reboxetine', 'Olanzapine').
drug_interaction('Ropivacaine', 'Olanzapine').
drug_interaction('Rosiglitazone', 'Olanzapine').
drug_interaction('Secobarbital', 'Olanzapine').
drug_interaction('Tacrine', 'Olanzapine').
drug_interaction('Terfenadine', 'Olanzapine').
drug_interaction('Theophylline', 'Olanzapine').
drug_interaction('Topiramate', 'Olanzapine').
drug_interaction('Nitroprusside', 'Fosinopril').
drug_interaction('Pregabalin', 'Fosinopril').
drug_interaction('Ropivacaine', 'Fosinopril').
drug_interaction('Secobarbital', 'Fosinopril').
drug_interaction('Theophylline', 'Fosinopril').
drug_interaction('Triamterene', 'Fosinopril').
drug_interaction('Valsartan', 'Fosinopril').
drug_interaction('Terfenadine', 'Sulfadiazine').
drug_interaction('Theophylline', 'Sulfadiazine').
drug_interaction('Valsartan', 'Sulfadiazine').
drug_interaction('Valsartan', 'Triamterene').
drug_interaction('Betaxolol', 'Adapalene').
drug_interaction('Desmopressin', 'Adapalene').
drug_interaction('Doxycycline', 'Adapalene').
drug_interaction('Enoxacin', 'Adapalene').
drug_interaction('Esmolol', 'Adapalene').
drug_interaction('Fluorometholone', 'Adapalene').
drug_interaction('Fosinopril', 'Adapalene').
drug_interaction('Levonorgestrel', 'Adapalene').
drug_interaction('Moxifloxacin', 'Adapalene').
drug_interaction('Phenindione', 'Adapalene').
drug_interaction('Triamterene', 'Adapalene').
drug_interaction('Valsartan', 'Adapalene').
drug_interaction('Dofetilide', 'Clotrimazole').
drug_interaction('Dronabinol', 'Clotrimazole').
drug_interaction('Duloxetine', 'Clotrimazole').
drug_interaction('Ergocalciferol', 'Clotrimazole').
drug_interaction('Fluorometholone', 'Clotrimazole').
drug_interaction('Gemcitabine', 'Clotrimazole').
drug_interaction('Lansoprazole', 'Clotrimazole').
drug_interaction('Levonorgestrel', 'Clotrimazole').
drug_interaction('Mefloquine', 'Clotrimazole').
drug_interaction('Menadione', 'Clotrimazole').
drug_interaction('Olanzapine', 'Clotrimazole').
drug_interaction('Pantoprazole', 'Clotrimazole').
drug_interaction('Pregabalin', 'Clotrimazole').
drug_interaction('Reboxetine', 'Clotrimazole').
drug_interaction('Ropivacaine', 'Clotrimazole').
drug_interaction('Rosiglitazone', 'Clotrimazole').
drug_interaction('Sulfadiazine', 'Clotrimazole').
drug_interaction('Tacrine', 'Clotrimazole').
drug_interaction('Terfenadine', 'Clotrimazole').
drug_interaction('Theophylline', 'Clotrimazole').
drug_interaction('Triamterene', 'Clotrimazole').
drug_interaction('Valsartan', 'Clotrimazole').
drug_interaction('Vindesine', 'Clotrimazole').
drug_interaction('Caffeine', 'Buspirone').
drug_interaction('Cetirizine', 'Buspirone').
drug_interaction('Cholecalciferol', 'Buspirone').
drug_interaction('Clotrimazole', 'Buspirone').
drug_interaction('Doxycycline', 'Buspirone').
drug_interaction('Dronabinol', 'Buspirone').
drug_interaction('Duloxetine', 'Buspirone').
drug_interaction('Fluconazole', 'Buspirone').
drug_interaction('Gemcitabine', 'Buspirone').
drug_interaction('Lansoprazole', 'Buspirone').
drug_interaction('Lorazepam', 'Buspirone').
drug_interaction('Methocarbamol', 'Buspirone').
drug_interaction('Olanzapine', 'Buspirone').
drug_interaction('Pregabalin', 'Buspirone').
drug_interaction('Ropivacaine', 'Buspirone').
drug_interaction('Secobarbital', 'Buspirone').
drug_interaction('Topiramate', 'Buspirone').
drug_interaction('Theophylline', 'Menadione').
drug_interaction('Clotrimazole', 'Cholecalciferol').
drug_interaction('Doxycycline', 'Cholecalciferol').
drug_interaction('Dronabinol', 'Cholecalciferol').
drug_interaction('Duloxetine', 'Cholecalciferol').
drug_interaction('Ergocalciferol', 'Cholecalciferol').
drug_interaction('Fluconazole', 'Cholecalciferol').
drug_interaction('Lansoprazole', 'Cholecalciferol').
drug_interaction('Olanzapine', 'Cholecalciferol').
drug_interaction('Pantoprazole', 'Cholecalciferol').
drug_interaction('Ropivacaine', 'Cholecalciferol').
drug_interaction('Rosiglitazone', 'Cholecalciferol').
drug_interaction('Sulfadiazine', 'Cholecalciferol').
drug_interaction('Terfenadine', 'Cholecalciferol').
drug_interaction('Theophylline', 'Cholecalciferol').
drug_interaction('Valsartan', 'Cholecalciferol').
drug_interaction('Secobarbital', 'Ropivacaine').
drug_interaction('Theophylline', 'Ropivacaine').
drug_interaction('Topiramate', 'Ropivacaine').
drug_interaction('Triamterene', 'Ropivacaine').
drug_interaction('Valsartan', 'Ropivacaine').
drug_interaction('Lansoprazole', 'Gramicidin D').
drug_interaction('Olanzapine', 'Gramicidin D').
drug_interaction('Doxycycline', 'Dicloxacillin').
drug_interaction('Phenindione', 'Dicloxacillin').
drug_interaction('Theophylline', 'Interferon Alfa-2a, Recombinant').
drug_interaction('Theophylline', 'Pantoprazole').
drug_interaction('Topiramate', 'Pantoprazole').
drug_interaction('Secobarbital', 'Pyridoxine').
drug_interaction('Betaxolol', 'Amsacrine').
drug_interaction('Caffeine', 'Amsacrine').
drug_interaction('Cholecalciferol', 'Amsacrine').
drug_interaction('Clotrimazole', 'Amsacrine').
drug_interaction('Duloxetine', 'Amsacrine').
drug_interaction('Gemcitabine', 'Amsacrine').
drug_interaction('Lansoprazole', 'Amsacrine').
drug_interaction('Olanzapine', 'Amsacrine').
drug_interaction('Tacrine', 'Procyclidine').
drug_interaction('Topiramate', 'Procyclidine').
drug_interaction('Fluconazole', 'Dronabinol').
drug_interaction('Gemcitabine', 'Dronabinol').
drug_interaction('Lansoprazole', 'Dronabinol').
drug_interaction('Lorazepam', 'Dronabinol').
drug_interaction('Methocarbamol', 'Dronabinol').
drug_interaction('Midodrine', 'Dronabinol').
drug_interaction('Olanzapine', 'Dronabinol').
drug_interaction('Pantoprazole', 'Dronabinol').
drug_interaction('Phentermine', 'Dronabinol').
drug_interaction('Pregabalin', 'Dronabinol').
drug_interaction('Procyclidine', 'Dronabinol').
drug_interaction('Pyrimethamine', 'Dronabinol').
drug_interaction('Ropivacaine', 'Dronabinol').
drug_interaction('Secobarbital', 'Dronabinol').
drug_interaction('Sulfadiazine', 'Dronabinol').
drug_interaction('Topiramate', 'Dronabinol').
drug_interaction('Valsartan', 'Dronabinol').
drug_interaction('Mefloquine', 'Fluorometholone').
drug_interaction('Moxifloxacin', 'Fluorometholone').
drug_interaction('Tacrine', 'Fluorometholone').
drug_interaction('Buspirone', 'Betaxolol').
drug_interaction('Caffeine', 'Betaxolol').
drug_interaction('Cholecalciferol', 'Betaxolol').
drug_interaction('Clotrimazole', 'Betaxolol').
drug_interaction('Duloxetine', 'Betaxolol').
drug_interaction('Esmolol', 'Betaxolol').
drug_interaction('Fosinopril', 'Betaxolol').
drug_interaction('Isoetarine', 'Betaxolol').
drug_interaction('Mefloquine', 'Betaxolol').
drug_interaction('Midodrine', 'Betaxolol').
drug_interaction('Nitroprusside', 'Betaxolol').
drug_interaction('Olanzapine', 'Betaxolol').
drug_interaction('Ropivacaine', 'Betaxolol').
drug_interaction('Secobarbital', 'Betaxolol').
drug_interaction('Tacrine', 'Betaxolol').
drug_interaction('Terfenadine', 'Betaxolol').
drug_interaction('Theophylline', 'Betaxolol').
drug_interaction('Triamterene', 'Betaxolol').
drug_interaction('Valsartan', 'Betaxolol').
drug_interaction('Phenindione', 'Anistreplase').
drug_interaction('Olanzapine', 'Methocarbamol').
drug_interaction('Pregabalin', 'Methocarbamol').
drug_interaction('Ropivacaine', 'Methocarbamol').
drug_interaction('Secobarbital', 'Methocarbamol').
drug_interaction('Topiramate', 'Methocarbamol').
drug_interaction('Terfenadine', 'Phentermine').
drug_interaction('Cholecalciferol', 'Calcium Acetate').
drug_interaction('Doxycycline', 'Calcium Acetate').
drug_interaction('Enoxacin', 'Calcium Acetate').
drug_interaction('Ergocalciferol', 'Calcium Acetate').
drug_interaction('Moxifloxacin', 'Calcium Acetate').
drug_interaction('Pregabalin', 'Calcium Acetate').
drug_interaction('Rosiglitazone', 'Pyrimethamine').
drug_interaction('Sulfadiazine', 'Pyrimethamine').
drug_interaction('Terfenadine', 'Pyrimethamine').
drug_interaction('Theophylline', 'Pyrimethamine').
drug_interaction('Valsartan', 'Pyrimethamine').
drug_interaction('Olanzapine', 'Miglustat').
drug_interaction('Sulfadiazine', 'Miglustat').
drug_interaction('Esmolol', 'Duloxetine').
drug_interaction('Fosinopril', 'Duloxetine').
drug_interaction('Insulin Human', 'Duloxetine').
drug_interaction('Isoetarine', 'Duloxetine').
drug_interaction('Lorazepam', 'Duloxetine').
drug_interaction('Methocarbamol', 'Duloxetine').
drug_interaction('Midodrine', 'Duloxetine').
drug_interaction('Nitroprusside', 'Duloxetine').
drug_interaction('Olanzapine', 'Duloxetine').
drug_interaction('Phenindione', 'Duloxetine').
drug_interaction('Pregabalin', 'Duloxetine').
drug_interaction('Ropivacaine', 'Duloxetine').
drug_interaction('Rosiglitazone', 'Duloxetine').
drug_interaction('Secobarbital', 'Duloxetine').
drug_interaction('Sulfadiazine', 'Duloxetine').
drug_interaction('Terfenadine', 'Duloxetine').
drug_interaction('Theophylline', 'Duloxetine').
drug_interaction('Topiramate', 'Duloxetine').
drug_interaction('Triamterene', 'Duloxetine').
drug_interaction('Valsartan', 'Duloxetine').
drug_interaction('Miglustat', 'Megestrol acetate').
drug_interaction('Olanzapine', 'Megestrol acetate').
drug_interaction('Phenindione', 'Megestrol acetate').
drug_interaction('Rosiglitazone', 'Megestrol acetate').
drug_interaction('Secobarbital', 'Rosiglitazone').
drug_interaction('Sulfadiazine', 'Rosiglitazone').
drug_interaction('Theophylline', 'Rosiglitazone').
drug_interaction('Valsartan', 'Rosiglitazone').
drug_interaction('Fosinopril', 'Esmolol').
drug_interaction('Isoetarine', 'Esmolol').
drug_interaction('Mefloquine', 'Esmolol').
drug_interaction('Midodrine', 'Esmolol').
drug_interaction('Nitroprusside', 'Esmolol').
drug_interaction('Ropivacaine', 'Esmolol').
drug_interaction('Secobarbital', 'Esmolol').
drug_interaction('Tacrine', 'Esmolol').
drug_interaction('Theophylline', 'Esmolol').
drug_interaction('Triamterene', 'Esmolol').
drug_interaction('Valsartan', 'Esmolol').
drug_interaction('Valsartan', 'Terfenadine').
drug_interaction('Olanzapine', 'Moxifloxacin').
drug_interaction('Phenindione', 'Moxifloxacin').
drug_interaction('Rosiglitazone', 'Moxifloxacin').
drug_interaction('Sulfadiazine', 'Moxifloxacin').
drug_interaction('Theophylline', 'Moxifloxacin').
drug_interaction('Theophylline', 'Interferon alfa-n1').
drug_interaction('Mefloquine', 'Lorazepam').
drug_interaction('Methocarbamol', 'Lorazepam').
drug_interaction('Olanzapine', 'Lorazepam').
drug_interaction('Pregabalin', 'Lorazepam').
drug_interaction('Ropivacaine', 'Lorazepam').
drug_interaction('Secobarbital', 'Lorazepam').
drug_interaction('Theophylline', 'Lorazepam').
drug_interaction('Topiramate', 'Lorazepam').
drug_interaction('Sulfadiazine', 'Secobarbital').
drug_interaction('Terfenadine', 'Secobarbital').
drug_interaction('Theophylline', 'Secobarbital').
drug_interaction('Topiramate', 'Secobarbital').
drug_interaction('Triamterene', 'Secobarbital').
drug_interaction('Valsartan', 'Secobarbital').
drug_interaction('Doxycycline', 'Dofetilide').
drug_interaction('Fluconazole', 'Dofetilide').
drug_interaction('Leuprolide', 'Dofetilide').
drug_interaction('Mefloquine', 'Dofetilide').
drug_interaction('Megestrol acetate', 'Dofetilide').
drug_interaction('Moxifloxacin', 'Dofetilide').
drug_interaction('Olanzapine', 'Dofetilide').
drug_interaction('Triamterene', 'Dofetilide').
drug_interaction('Dronabinol', 'Cetirizine').
drug_interaction('Duloxetine', 'Cetirizine').
drug_interaction('Lorazepam', 'Cetirizine').
drug_interaction('Methocarbamol', 'Cetirizine').
drug_interaction('Olanzapine', 'Cetirizine').
drug_interaction('Phentermine', 'Cetirizine').
drug_interaction('Pregabalin', 'Cetirizine').
drug_interaction('Ropivacaine', 'Cetirizine').
drug_interaction('Secobarbital', 'Cetirizine').
drug_interaction('Topiramate', 'Cetirizine').
drug_interaction('Phentermine', 'Midodrine').
drug_interaction('Fluorometholone', 'Fluconazole').
drug_interaction('Gemcitabine', 'Fluconazole').
drug_interaction('Lansoprazole', 'Fluconazole').
drug_interaction('Leuprolide', 'Fluconazole').
drug_interaction('Levonorgestrel', 'Fluconazole').
drug_interaction('Mefloquine', 'Fluconazole').
drug_interaction('Moxifloxacin', 'Fluconazole').
drug_interaction('Olanzapine', 'Fluconazole').
drug_interaction('Pantoprazole', 'Fluconazole').
drug_interaction('Phenindione', 'Fluconazole').
drug_interaction('Pregabalin', 'Fluconazole').
drug_interaction('Reboxetine', 'Fluconazole').
drug_interaction('Ropivacaine', 'Fluconazole').
drug_interaction('Rosiglitazone', 'Fluconazole').
drug_interaction('Sulfadiazine', 'Fluconazole').
drug_interaction('Terfenadine', 'Fluconazole').
drug_interaction('Theophylline', 'Fluconazole').
drug_interaction('Valsartan', 'Fluconazole').
drug_interaction('Vindesine', 'Fluconazole').
drug_interaction('Theophylline', 'Peginterferon alfa-2a').
drug_interaction('Buspirone', 'Alprazolam').
drug_interaction('Cetirizine', 'Alprazolam').
drug_interaction('Cholecalciferol', 'Alprazolam').
drug_interaction('Clotrimazole', 'Alprazolam').
drug_interaction('Dofetilide', 'Alprazolam').
drug_interaction('Doxycycline', 'Alprazolam').
drug_interaction('Dronabinol', 'Alprazolam').
drug_interaction('Duloxetine', 'Alprazolam').
drug_interaction('Fluconazole', 'Alprazolam').
drug_interaction('Fosinopril', 'Alprazolam').
drug_interaction('Lorazepam', 'Alprazolam').
drug_interaction('Methocarbamol', 'Alprazolam').
drug_interaction('Olanzapine', 'Alprazolam').
drug_interaction('Pregabalin', 'Alprazolam').
drug_interaction('Pyrimethamine', 'Alprazolam').
drug_interaction('Ropivacaine', 'Alprazolam').
drug_interaction('Secobarbital', 'Alprazolam').
drug_interaction('Sulfadiazine', 'Alprazolam').
drug_interaction('Theophylline', 'Alprazolam').
drug_interaction('Topiramate', 'Alprazolam').
drug_interaction('Valsartan', 'Alprazolam').
drug_interaction('Miglustat', 'Insulin Human').
drug_interaction('Moxifloxacin', 'Insulin Human').
drug_interaction('Rosiglitazone', 'Insulin Human').
drug_interaction('Sulfadiazine', 'Insulin Human').
drug_interaction('Duloxetine', 'Desmopressin').
drug_interaction('Mefloquine', 'Leuprolide').
drug_interaction('Miglustat', 'Leuprolide').
drug_interaction('Moxifloxacin', 'Leuprolide').
drug_interaction('Olanzapine', 'Leuprolide').
drug_interaction('Rosiglitazone', 'Leuprolide').
drug_interaction('Gramicidin D', 'Gemcitabine').
drug_interaction('Lansoprazole', 'Gemcitabine').
drug_interaction('Mefloquine', 'Gemcitabine').
drug_interaction('Megestrol acetate', 'Gemcitabine').
drug_interaction('Mitomycin', 'Gemcitabine').
drug_interaction('Pantoprazole', 'Gemcitabine').
drug_interaction('Reboxetine', 'Gemcitabine').
drug_interaction('Tacrine', 'Gemcitabine').
drug_interaction('Terfenadine', 'Gemcitabine').
drug_interaction('Rosiglitazone', 'Phenindione').
drug_interaction('Secobarbital', 'Phenindione').
drug_interaction('Sulfadiazine', 'Phenindione').
drug_interaction('Fluorometholone', 'Enoxacin').
drug_interaction('Insulin Human', 'Enoxacin').
drug_interaction('Phenindione', 'Enoxacin').
drug_interaction('Rosiglitazone', 'Enoxacin').
drug_interaction('Sulfadiazine', 'Enoxacin').
drug_interaction('Theophylline', 'Enoxacin').
drug_interaction('Mefloquine', 'Lansoprazole').
drug_interaction('Megestrol acetate', 'Lansoprazole').
drug_interaction('Mitomycin', 'Lansoprazole').
drug_interaction('Olanzapine', 'Lansoprazole').
drug_interaction('Pantoprazole', 'Lansoprazole').
drug_interaction('Phenindione', 'Lansoprazole').
drug_interaction('Pyrimethamine', 'Lansoprazole').
drug_interaction('Reboxetine', 'Lansoprazole').
drug_interaction('Rosiglitazone', 'Lansoprazole').
drug_interaction('Secobarbital', 'Lansoprazole').
drug_interaction('Sulfadiazine', 'Lansoprazole').
drug_interaction('Tacrine', 'Lansoprazole').
drug_interaction('Terfenadine', 'Lansoprazole').
drug_interaction('Topiramate', 'Lansoprazole').
drug_interaction('Valsartan', 'Lansoprazole').
drug_interaction('Theophylline', 'Tacrine').
drug_interaction('Pregabalin', 'Nitroprusside').
drug_interaction('Ropivacaine', 'Nitroprusside').
drug_interaction('Secobarbital', 'Nitroprusside').
drug_interaction('Triamterene', 'Nitroprusside').
drug_interaction('Valsartan', 'Nitroprusside').
drug_interaction('Triamterene', 'Theophylline').
drug_interaction('Valsartan', 'Theophylline').
drug_interaction('Ropivacaine', 'Pregabalin').
drug_interaction('Rosiglitazone', 'Pregabalin').
drug_interaction('Secobarbital', 'Pregabalin').
drug_interaction('Topiramate', 'Pregabalin').
drug_interaction('Aminoglutethimide', 'Acetyldigitoxin').
drug_interaction('Amsacrine', 'Acetyldigitoxin').
drug_interaction('Betaxolol', 'Acetyldigitoxin').
drug_interaction('Calcium Acetate', 'Acetyldigitoxin').
drug_interaction('Cholecalciferol', 'Acetyldigitoxin').
drug_interaction('Cladribine', 'Acetyldigitoxin').
drug_interaction('Enoxacin', 'Acetyldigitoxin').
drug_interaction('Ergocalciferol', 'Acetyldigitoxin').
drug_interaction('Esmolol', 'Acetyldigitoxin').
drug_interaction('Gemcitabine', 'Acetyldigitoxin').
drug_interaction('Leuprolide', 'Acetyldigitoxin').
drug_interaction('Megestrol acetate', 'Acetyldigitoxin').
drug_interaction('Midodrine', 'Acetyldigitoxin').
drug_interaction('Mitomycin', 'Acetyldigitoxin').
drug_interaction('Moxifloxacin', 'Acetyldigitoxin').
drug_interaction('Raltitrexed', 'Acetyldigitoxin').
drug_interaction('Triamterene', 'Acetyldigitoxin').
drug_interaction('Vindesine', 'Acetyldigitoxin').
drug_interaction('Fluconazole', 'Ergocalciferol').
drug_interaction('Phenindione', 'Glucagon recombinant').
drug_interaction('Procyclidine', 'Glucagon recombinant').
drug_interaction('Cholecalciferol', 'Caffeine').
drug_interaction('Clotrimazole', 'Caffeine').
drug_interaction('Doxycycline', 'Caffeine').
drug_interaction('Dronabinol', 'Caffeine').
drug_interaction('Duloxetine', 'Caffeine').
drug_interaction('Fluconazole', 'Caffeine').
drug_interaction('Gemcitabine', 'Caffeine').
drug_interaction('Gramicidin D', 'Caffeine').
drug_interaction('Lansoprazole', 'Caffeine').
drug_interaction('Mefloquine', 'Caffeine').
drug_interaction('Megestrol acetate', 'Caffeine').
drug_interaction('Menadione', 'Caffeine').
drug_interaction('Mitomycin', 'Caffeine').
drug_interaction('Olanzapine', 'Caffeine').
drug_interaction('Pantoprazole', 'Caffeine').
drug_interaction('Pyrimethamine', 'Caffeine').
drug_interaction('Reboxetine', 'Caffeine').
drug_interaction('Ropivacaine', 'Caffeine').
drug_interaction('Rosiglitazone', 'Caffeine').
drug_interaction('Secobarbital', 'Caffeine').
drug_interaction('Sulfadiazine', 'Caffeine').
drug_interaction('Tacrine', 'Caffeine').
drug_interaction('Terfenadine', 'Caffeine').
drug_interaction('Theophylline', 'Caffeine').
drug_interaction('Triamterene', 'Caffeine').
drug_interaction('Valsartan', 'Caffeine').
drug_interaction('Miglustat', 'Levonorgestrel').
drug_interaction('Phenindione', 'Levonorgestrel').
drug_interaction('Rosiglitazone', 'Levonorgestrel').
drug_interaction('Secobarbital', 'Levonorgestrel').
drug_interaction('Topiramate', 'Levonorgestrel').
drug_interaction('Olanzapine', 'Mitomycin').
drug_interaction('Vindesine', 'Mitomycin').
drug_interaction('Betaxolol', 'Acetohexamide').
drug_interaction('Esmolol', 'Acetohexamide').
drug_interaction('Fluconazole', 'Acetohexamide').
drug_interaction('Insulin Human', 'Acetohexamide').
drug_interaction('Leuprolide', 'Acetohexamide').
drug_interaction('Levonorgestrel', 'Acetohexamide').
drug_interaction('Megestrol acetate', 'Acetohexamide').
drug_interaction('Olanzapine', 'Acetohexamide').
drug_interaction('Phenindione', 'Acetohexamide').
drug_interaction('Rosiglitazone', 'Acetohexamide').
drug_interaction('Sulfadiazine', 'Acetohexamide').

