
drug_interaction('Fosinopril', 'Guanadrel').
drug_interaction('Fosinopril', 'Imipramine').
drug_interaction('Fosinopril', 'Mesalazine').
drug_interaction('Fosinopril', 'Minoxidil').
drug_interaction('Fosinopril', 'Nimodipine').
drug_interaction('Fosinopril', 'Nisoldipine').
drug_interaction('Fosinopril', 'Nitroprusside').
drug_interaction('Fosinopril', 'Olmesartan').
drug_interaction('Fosinopril', 'Streptokinase').
drug_interaction('Fosinopril', 'Tolmetin').
drug_interaction('Fosinopril', 'Triamterene').
drug_interaction('Dicoumarol', 'Diethylstilbestrol').
drug_interaction('Dicoumarol', 'Duloxetine').
drug_interaction('Dicoumarol', 'Etanercept').
drug_interaction('Dicoumarol', 'Fluconazole').
drug_interaction('Dicoumarol', 'Fluvoxamine').
drug_interaction('Dicoumarol', 'Glucagon recombinant').
drug_interaction('Dicoumarol', 'Imipramine').
drug_interaction('Dicoumarol', 'Lansoprazole').
drug_interaction('Dicoumarol', 'Levonorgestrel').
drug_interaction('Dicoumarol', 'Levothyroxine').
drug_interaction('Dicoumarol', 'Liothyronine').
drug_interaction('Dicoumarol', 'Mesalazine').
drug_interaction('Dicoumarol', 'Omeprazole').
drug_interaction('Dicoumarol', 'Phenindione').
drug_interaction('Dicoumarol', 'Phenoxymethylpenicillin').
drug_interaction('Dicoumarol', 'Piperacillin').
drug_interaction('Dicoumarol', 'Streptokinase').
drug_interaction('Dicoumarol', 'Tolmetin').
drug_interaction('Clozapine', 'Digoxin').
drug_interaction('Clozapine', 'Dihydroergotamine').
drug_interaction('Clozapine', 'Doxylamine').
drug_interaction('Clozapine', 'Duloxetine').
drug_interaction('Clozapine', 'Etomidate').
drug_interaction('Clozapine', 'Fluconazole').
drug_interaction('Clozapine', 'Fluvoxamine').
drug_interaction('Clozapine', 'Fosinopril').
drug_interaction('Clozapine', 'Gramicidin D').
drug_interaction('Clozapine', 'Imipramine').
drug_interaction('Clozapine', 'Insulin Pork').
drug_interaction('Clozapine', 'Interferon alfa-n3').
drug_interaction('Clozapine', 'Lansoprazole').
drug_interaction('Clozapine', 'Levothyroxine').
drug_interaction('Clozapine', 'Liothyronine').
drug_interaction('Clozapine', 'Methadone').
drug_interaction('Clozapine', 'Methocarbamol').
drug_interaction('Clozapine', 'Minoxidil').
drug_interaction('Clozapine', 'Nimodipine').
drug_interaction('Clozapine', 'Nisoldipine').
drug_interaction('Clozapine', 'Nitroprusside').
drug_interaction('Clozapine', 'Olmesartan').
drug_interaction('Clozapine', 'Omeprazole').
drug_interaction('Clozapine', 'Palonosetron').
drug_interaction('Clozapine', 'Raltitrexed').
drug_interaction('Clozapine', 'Ranolazine').
drug_interaction('Clozapine', 'Ritonavir').
drug_interaction('Clozapine', 'Streptokinase').
drug_interaction('Clozapine', 'Tacrine').
drug_interaction('Clozapine', 'Terfenadine').
drug_interaction('Clozapine', 'Triamterene').
drug_interaction('Becaplermin', 'Bivalirudin').
drug_interaction('Becaplermin', 'Dicoumarol').
drug_interaction('Becaplermin', 'Diethylstilbestrol').
drug_interaction('Becaplermin', 'Etanercept').
drug_interaction('Becaplermin', 'Levonorgestrel').
drug_interaction('Becaplermin', 'Mesalazine').
drug_interaction('Becaplermin', 'Phenindione').
drug_interaction('Becaplermin', 'Streptokinase').
drug_interaction('Becaplermin', 'Tolmetin').
drug_interaction('Interferon Alfa-2a, Recombinant', 'Methadone').
drug_interaction('Etanercept', 'Fluorometholone').
drug_interaction('Etanercept', 'Folic Acid').
drug_interaction('Etanercept', 'Fosinopril').
drug_interaction('Etanercept', 'Mesalazine').
drug_interaction('Etanercept', 'Olmesartan').
drug_interaction('Etanercept', 'Phenindione').
drug_interaction('Etanercept', 'Tolmetin').
drug_interaction('Etanercept', 'Triamterene').
drug_interaction('Etanercept', 'Valrubicin').
drug_interaction('Abciximab', 'Aminosalicylic Acid').
drug_interaction('Abciximab', 'Becaplermin').
drug_interaction('Abciximab', 'Bivalirudin').
drug_interaction('Abciximab', 'Dicoumarol').
drug_interaction('Abciximab', 'Diethylstilbestrol').
drug_interaction('Abciximab', 'Etanercept').
drug_interaction('Abciximab', 'Levonorgestrel').
drug_interaction('Abciximab', 'Mesalazine').
drug_interaction('Abciximab', 'Phenindione').
drug_interaction('Abciximab', 'Streptokinase').
drug_interaction('Abciximab', 'Tolmetin').
drug_interaction('Mesalazine', 'Olmesartan').
drug_interaction('Mesalazine', 'Omeprazole').
drug_interaction('Mesalazine', 'Phenindione').
drug_interaction('Mesalazine', 'Streptokinase').
drug_interaction('Mesalazine', 'Tolmetin').
drug_interaction('Mesalazine', 'Triamterene').
drug_interaction('Mesalazine', 'Valrubicin').
drug_interaction('Levonorgestrel', 'Phenindione').
drug_interaction('Levonorgestrel', 'Ranolazine').
drug_interaction('Levonorgestrel', 'Ritonavir').
drug_interaction('Palonosetron', 'Ranolazine').
drug_interaction('Palonosetron', 'Ritonavir').
drug_interaction('Duloxetine', 'Etomidate').
drug_interaction('Duloxetine', 'Fluvoxamine').
drug_interaction('Duloxetine', 'Fosinopril').
drug_interaction('Duloxetine', 'Imipramine').
drug_interaction('Duloxetine', 'Levothyroxine').
drug_interaction('Duloxetine', 'Liothyronine').
drug_interaction('Duloxetine', 'Methadone').
drug_interaction('Duloxetine', 'Methocarbamol').
drug_interaction('Duloxetine', 'Minoxidil').
drug_interaction('Duloxetine', 'Nimodipine').
drug_interaction('Duloxetine', 'Nisoldipine').
drug_interaction('Duloxetine', 'Nitroprusside').
drug_interaction('Duloxetine', 'Olmesartan').
drug_interaction('Duloxetine', 'Palonosetron').
drug_interaction('Duloxetine', 'Phenindione').
drug_interaction('Duloxetine', 'Ranolazine').
drug_interaction('Duloxetine', 'Ritonavir').
drug_interaction('Duloxetine', 'Streptokinase').
drug_interaction('Duloxetine', 'Terfenadine').
drug_interaction('Duloxetine', 'Triamterene').
drug_interaction('Digoxin', 'Dihydroergotamine').
drug_interaction('Digoxin', 'Ergocalciferol').
drug_interaction('Digoxin', 'Etanercept').
drug_interaction('Digoxin', 'Fluconazole').
drug_interaction('Digoxin', 'Flutamide').
drug_interaction('Digoxin', 'Fluvoxamine').
drug_interaction('Digoxin', 'Fosinopril').
drug_interaction('Digoxin', 'Gramicidin D').
drug_interaction('Digoxin', 'Imipramine').
drug_interaction('Digoxin', 'Lansoprazole').
drug_interaction('Digoxin', 'Levothyroxine').
drug_interaction('Digoxin', 'Liothyronine').
drug_interaction('Digoxin', 'Mesalazine').
drug_interaction('Digoxin', 'Methadone').
drug_interaction('Digoxin', 'Metocurine Iodide').
drug_interaction('Digoxin', 'Nisoldipine').
drug_interaction('Digoxin', 'Omeprazole').
drug_interaction('Digoxin', 'Pipobroman').
drug_interaction('Digoxin', 'Raltitrexed').
drug_interaction('Digoxin', 'Ranolazine').
drug_interaction('Digoxin', 'Ritonavir').
drug_interaction('Digoxin', 'Tacrine').
drug_interaction('Digoxin', 'Terfenadine').
drug_interaction('Digoxin', 'Tolmetin').
drug_interaction('Digoxin', 'Triamterene').
drug_interaction('Digoxin', 'Valrubicin').
drug_interaction('Digoxin', 'Verteporfin').
drug_interaction('Phenoxymethylpenicillin', 'Valrubicin').
drug_interaction('Omeprazole', 'Phenindione').
drug_interaction('Omeprazole', 'Ranolazine').
drug_interaction('Omeprazole', 'Ritonavir').
drug_interaction('Omeprazole', 'Terfenadine').
drug_interaction('Phenindione', 'Phenoxymethylpenicillin').
drug_interaction('Phenindione', 'Piperacillin').
drug_interaction('Phenindione', 'Streptokinase').
drug_interaction('Phenindione', 'Tolmetin').
drug_interaction('Buspirone', 'Carisoprodol').
drug_interaction('Buspirone', 'Clemastine').
drug_interaction('Buspirone', 'Clotrimazole').
drug_interaction('Buspirone', 'Clozapine').
drug_interaction('Buspirone', 'Diethylstilbestrol').
drug_interaction('Buspirone', 'Digoxin').
drug_interaction('Buspirone', 'Dihydroergotamine').
drug_interaction('Buspirone', 'Doxylamine').
drug_interaction('Buspirone', 'Duloxetine').
drug_interaction('Buspirone', 'Etomidate').
drug_interaction('Buspirone', 'Fluconazole').
drug_interaction('Buspirone', 'Fluvoxamine').
drug_interaction('Buspirone', 'Imipramine').
drug_interaction('Buspirone', 'Lansoprazole').
drug_interaction('Buspirone', 'Methadone').
drug_interaction('Buspirone', 'Methocarbamol').
drug_interaction('Buspirone', 'Palonosetron').
drug_interaction('Buspirone', 'Ranolazine').
drug_interaction('Buspirone', 'Ritonavir').
drug_interaction('Buspirone', 'Terconazole').
drug_interaction('Tolmetin', 'Triamterene').
drug_interaction('Tolmetin', 'Valrubicin').
drug_interaction('Amsacrine', 'Atenolol').
drug_interaction('Amsacrine', 'Betamethasone').
drug_interaction('Amsacrine', 'Clemastine').
drug_interaction('Amsacrine', 'Clotrimazole').
drug_interaction('Amsacrine', 'Clozapine').
drug_interaction('Amsacrine', 'Diethylstilbestrol').
drug_interaction('Amsacrine', 'Digoxin').
drug_interaction('Amsacrine', 'Duloxetine').
drug_interaction('Amsacrine', 'Fluvoxamine').
drug_interaction('Amsacrine', 'Imipramine').
drug_interaction('Amsacrine', 'Lansoprazole').
drug_interaction('Amsacrine', 'Methadone').
drug_interaction('Amsacrine', 'Ranolazine').
drug_interaction('Amsacrine', 'Ritonavir').
drug_interaction('Glucagon recombinant', 'Metixene').
drug_interaction('Glucagon recombinant', 'Phenindione').
drug_interaction('Metixene', 'Tacrine').
drug_interaction('Lansoprazole', 'Levothyroxine').
drug_interaction('Lansoprazole', 'Liothyronine').
drug_interaction('Lansoprazole', 'Mesalazine').
drug_interaction('Lansoprazole', 'Methadone').
drug_interaction('Lansoprazole', 'Nisoldipine').
drug_interaction('Lansoprazole', 'Omeprazole').
drug_interaction('Lansoprazole', 'Phenindione').
drug_interaction('Lansoprazole', 'Ranolazine').
drug_interaction('Lansoprazole', 'Ritonavir').
drug_interaction('Lansoprazole', 'Tacrine').
drug_interaction('Lansoprazole', 'Terfenadine').
drug_interaction('Methadone', 'Methocarbamol').
drug_interaction('Methadone', 'Metixene').
drug_interaction('Methadone', 'Omeprazole').
drug_interaction('Methadone', 'Palonosetron').
drug_interaction('Methadone', 'Ranolazine').
drug_interaction('Methadone', 'Ritonavir').
drug_interaction('Methadone', 'Terfenadine').
drug_interaction('Methadone', 'Triamterene').
drug_interaction('Carisoprodol', 'Clemastine').
drug_interaction('Carisoprodol', 'Clotrimazole').
drug_interaction('Carisoprodol', 'Clozapine').
drug_interaction('Carisoprodol', 'Doxylamine').
drug_interaction('Carisoprodol', 'Duloxetine').
drug_interaction('Carisoprodol', 'Etomidate').
drug_interaction('Carisoprodol', 'Fluconazole').
drug_interaction('Carisoprodol', 'Fluvoxamine').
drug_interaction('Carisoprodol', 'Imipramine').
drug_interaction('Carisoprodol', 'Methadone').
drug_interaction('Carisoprodol', 'Methocarbamol').
drug_interaction('Carisoprodol', 'Omeprazole').
drug_interaction('Cefmetazole', 'Dicoumarol').
drug_interaction('Cefmetazole', 'Phenindione').
drug_interaction('Betamethasone', 'Buspirone').
drug_interaction('Betamethasone', 'Chlorthalidone').
drug_interaction('Betamethasone', 'Clotrimazole').
drug_interaction('Betamethasone', 'Diethylstilbestrol').
drug_interaction('Betamethasone', 'Digoxin').
drug_interaction('Betamethasone', 'Dihydroergotamine').
drug_interaction('Betamethasone', 'Etanercept').
drug_interaction('Betamethasone', 'Fluconazole').
drug_interaction('Betamethasone', 'Fluvoxamine').
drug_interaction('Betamethasone', 'Gramicidin D').
drug_interaction('Betamethasone', 'Hyaluronidase').
drug_interaction('Betamethasone', 'Imipramine').
drug_interaction('Betamethasone', 'Insulin Pork').
drug_interaction('Betamethasone', 'Lansoprazole').
drug_interaction('Betamethasone', 'Levothyroxine').
drug_interaction('Betamethasone', 'Liothyronine').
drug_interaction('Betamethasone', 'Mesalazine').
drug_interaction('Betamethasone', 'Methadone').
drug_interaction('Betamethasone', 'Nisoldipine').
drug_interaction('Betamethasone', 'Omeprazole').
drug_interaction('Betamethasone', 'Ranolazine').
drug_interaction('Betamethasone', 'Ritonavir').
drug_interaction('Betamethasone', 'Tacrine').
drug_interaction('Betamethasone', 'Terfenadine').
drug_interaction('Betamethasone', 'Tolmetin').
drug_interaction('Fluorometholone', 'Fluvoxamine').
drug_interaction('Fluorometholone', 'Hyaluronidase').
drug_interaction('Fluorometholone', 'Mesalazine').
drug_interaction('Fluorometholone', 'Ranolazine').
drug_interaction('Fluorometholone', 'Ritonavir').
drug_interaction('Fluorometholone', 'Tacrine').
drug_interaction('Fluorometholone', 'Tolmetin').
drug_interaction('Guanadrel', 'Minoxidil').
drug_interaction('Guanadrel', 'Nimodipine').
drug_interaction('Guanadrel', 'Nisoldipine').
drug_interaction('Guanadrel', 'Nitroprusside').
drug_interaction('Guanadrel', 'Olmesartan').
drug_interaction('Botulinum Toxin Type B', 'Metixene').
drug_interaction('Botulinum Toxin Type B', 'Metocurine Iodide').
drug_interaction('Botulinum Toxin Type B', 'Valrubicin').
drug_interaction('Ritonavir', 'Tacrine').
drug_interaction('Ritonavir', 'Terfenadine').
drug_interaction('Flutamide', 'Fluvoxamine').
drug_interaction('Flutamide', 'Omeprazole').
drug_interaction('Flutamide', 'Ranolazine').
drug_interaction('Flutamide', 'Ritonavir').
drug_interaction('Acetohexamide', 'Atenolol').
drug_interaction('Acetohexamide', 'Betamethasone').
drug_interaction('Acetohexamide', 'Chlorthalidone').
drug_interaction('Acetohexamide', 'Clozapine').
drug_interaction('Acetohexamide', 'Dicoumarol').
drug_interaction('Acetohexamide', 'Fluconazole').
drug_interaction('Acetohexamide', 'Levonorgestrel').
drug_interaction('Acetohexamide', 'Lipoic Acid').
drug_interaction('Acetohexamide', 'Phenindione').
drug_interaction('Acetohexamide', 'Ritonavir').
drug_interaction('Carbimazole', 'Dicoumarol').
drug_interaction('Carbimazole', 'Digoxin').
drug_interaction('Carbimazole', 'Phenindione').
drug_interaction('Olmesartan', 'Streptokinase').
drug_interaction('Olmesartan', 'Tolmetin').
drug_interaction('Olmesartan', 'Triamterene').
drug_interaction('Fluvoxamine', 'Imipramine').
drug_interaction('Fluvoxamine', 'Lansoprazole').
drug_interaction('Fluvoxamine', 'Levonorgestrel').
drug_interaction('Fluvoxamine', 'Levothyroxine').
drug_interaction('Fluvoxamine', 'Liothyronine').
drug_interaction('Fluvoxamine', 'Methadone').
drug_interaction('Fluvoxamine', 'Methocarbamol').
drug_interaction('Fluvoxamine', 'Nimodipine').
drug_interaction('Fluvoxamine', 'Nisoldipine').
drug_interaction('Fluvoxamine', 'Omeprazole').
drug_interaction('Fluvoxamine', 'Palonosetron').
drug_interaction('Fluvoxamine', 'Phenindione').
drug_interaction('Fluvoxamine', 'Ranolazine').
drug_interaction('Fluvoxamine', 'Ritonavir').
drug_interaction('Fluvoxamine', 'Tacrine').
drug_interaction('Fluvoxamine', 'Terfenadine').
drug_interaction('Fluvoxamine', 'Triamterene').
drug_interaction('Clemastine', 'Clozapine').
drug_interaction('Clemastine', 'Digoxin').
drug_interaction('Clemastine', 'Dihydroergotamine').
drug_interaction('Clemastine', 'Doxylamine').
drug_interaction('Clemastine', 'Duloxetine').
drug_interaction('Clemastine', 'Ergocalciferol').
drug_interaction('Clemastine', 'Etomidate').
drug_interaction('Clemastine', 'Fluorometholone').
drug_interaction('Clemastine', 'Flutamide').
drug_interaction('Clemastine', 'Fluvoxamine').
drug_interaction('Clemastine', 'Hyaluronidase').
drug_interaction('Clemastine', 'Imipramine').
drug_interaction('Clemastine', 'Lansoprazole').
drug_interaction('Clemastine', 'Levonorgestrel').
drug_interaction('Clemastine', 'Levothyroxine').
drug_interaction('Clemastine', 'Methadone').
drug_interaction('Clemastine', 'Methocarbamol').
drug_interaction('Clemastine', 'Nimodipine').
drug_interaction('Clemastine', 'Nisoldipine').
drug_interaction('Clemastine', 'Omeprazole').
drug_interaction('Clemastine', 'Palonosetron').
drug_interaction('Clemastine', 'Ranolazine').
drug_interaction('Clemastine', 'Ritonavir').
drug_interaction('Clemastine', 'Terfenadine').
drug_interaction('Hyaluronidase', 'Mesalazine').
drug_interaction('Hyaluronidase', 'Terfenadine').
drug_interaction('Clotrimazole', 'Clozapine').
drug_interaction('Clotrimazole', 'Dicoumarol').
drug_interaction('Clotrimazole', 'Diethylstilbestrol').
drug_interaction('Clotrimazole', 'Digoxin').
drug_interaction('Clotrimazole', 'Dihydroergotamine').
drug_interaction('Clotrimazole', 'Duloxetine').
drug_interaction('Clotrimazole', 'Ergocalciferol').
drug_interaction('Clotrimazole', 'Fluorometholone').
drug_interaction('Clotrimazole', 'Flutamide').
drug_interaction('Clotrimazole', 'Fluvoxamine').
drug_interaction('Clotrimazole', 'Folic Acid').
drug_interaction('Clotrimazole', 'Imipramine').
drug_interaction('Clotrimazole', 'Lansoprazole').
drug_interaction('Clotrimazole', 'Levonorgestrel').
drug_interaction('Clotrimazole', 'Levothyroxine').
drug_interaction('Clotrimazole', 'Methadone').
drug_interaction('Clotrimazole', 'Nimodipine').
drug_interaction('Clotrimazole', 'Nisoldipine').
drug_interaction('Clotrimazole', 'Omeprazole').
drug_interaction('Clotrimazole', 'Palonosetron').
drug_interaction('Clotrimazole', 'Ranolazine').
drug_interaction('Clotrimazole', 'Ritonavir').
drug_interaction('Clotrimazole', 'Tacrine').
drug_interaction('Clotrimazole', 'Terfenadine').
drug_interaction('Clotrimazole', 'Triamterene').
drug_interaction('Piperacillin', 'Valrubicin').
drug_interaction('Bivalirudin', 'Dicoumarol').
drug_interaction('Bivalirudin', 'Diethylstilbestrol').
drug_interaction('Bivalirudin', 'Digoxin').
drug_interaction('Bivalirudin', 'Dihydroergotamine').
drug_interaction('Bivalirudin', 'Etanercept').
drug_interaction('Bivalirudin', 'Imipramine').
drug_interaction('Bivalirudin', 'Levonorgestrel').
drug_interaction('Bivalirudin', 'Mesalazine').
drug_interaction('Bivalirudin', 'Phenindione').
drug_interaction('Bivalirudin', 'Streptokinase').
drug_interaction('Bivalirudin', 'Tolmetin').
drug_interaction('Dihydroergotamine', 'Dipivefrin').
drug_interaction('Dihydroergotamine', 'Duloxetine').
drug_interaction('Dihydroergotamine', 'Ergocalciferol').
drug_interaction('Dihydroergotamine', 'Fluconazole').
drug_interaction('Dihydroergotamine', 'Fluorometholone').
drug_interaction('Dihydroergotamine', 'Flutamide').
drug_interaction('Dihydroergotamine', 'Fluvoxamine').
drug_interaction('Dihydroergotamine', 'Fosinopril').
drug_interaction('Dihydroergotamine', 'Imipramine').
drug_interaction('Dihydroergotamine', 'Lansoprazole').
drug_interaction('Dihydroergotamine', 'Levonorgestrel').
drug_interaction('Dihydroergotamine', 'Levothyroxine').
drug_interaction('Dihydroergotamine', 'Methadone').
drug_interaction('Dihydroergotamine', 'Nimodipine').
drug_interaction('Dihydroergotamine', 'Nisoldipine').
drug_interaction('Dihydroergotamine', 'Omeprazole').
drug_interaction('Dihydroergotamine', 'Palonosetron').
drug_interaction('Dihydroergotamine', 'Ranolazine').
drug_interaction('Dihydroergotamine', 'Ritonavir').
drug_interaction('Dihydroergotamine', 'Terfenadine').
drug_interaction('Nimodipine', 'Nisoldipine').
drug_interaction('Nimodipine', 'Nitroprusside').
drug_interaction('Nimodipine', 'Olmesartan').
drug_interaction('Nimodipine', 'Ranolazine').
drug_interaction('Nimodipine', 'Ritonavir').
drug_interaction('Nimodipine', 'Streptokinase').
drug_interaction('Nimodipine', 'Terconazole').
drug_interaction('Nimodipine', 'Triamterene').
drug_interaction('Diethylstilbestrol', 'Digoxin').
drug_interaction('Diethylstilbestrol', 'Dihydroergotamine').
drug_interaction('Diethylstilbestrol', 'Fluconazole').
drug_interaction('Diethylstilbestrol', 'Fluorometholone').
drug_interaction('Diethylstilbestrol', 'Fluvoxamine').
drug_interaction('Diethylstilbestrol', 'Fosinopril').
drug_interaction('Diethylstilbestrol', 'Gramicidin D').
drug_interaction('Diethylstilbestrol', 'Hyaluronidase').
drug_interaction('Diethylstilbestrol', 'Imipramine').
drug_interaction('Diethylstilbestrol', 'Lansoprazole').
drug_interaction('Diethylstilbestrol', 'Levothyroxine').
drug_interaction('Diethylstilbestrol', 'Liothyronine').
drug_interaction('Diethylstilbestrol', 'Methadone').
drug_interaction('Diethylstilbestrol', 'Nisoldipine').
drug_interaction('Diethylstilbestrol', 'Omeprazole').
drug_interaction('Diethylstilbestrol', 'Phenindione').
drug_interaction('Diethylstilbestrol', 'Ranolazine').
drug_interaction('Diethylstilbestrol', 'Ritonavir').
drug_interaction('Diethylstilbestrol', 'Tacrine').
drug_interaction('Diethylstilbestrol', 'Terfenadine').
drug_interaction('Minoxidil', 'Nimodipine').
drug_interaction('Minoxidil', 'Nisoldipine').
drug_interaction('Minoxidil', 'Nitroprusside').
drug_interaction('Minoxidil', 'Olmesartan').
drug_interaction('Minoxidil', 'Streptokinase').
drug_interaction('Minoxidil', 'Triamterene').
drug_interaction('Aminosalicylic Acid', 'Becaplermin').
drug_interaction('Aminosalicylic Acid', 'Betamethasone').
drug_interaction('Aminosalicylic Acid', 'Bivalirudin').
drug_interaction('Aminosalicylic Acid', 'Dicoumarol').
drug_interaction('Aminosalicylic Acid', 'Fluorometholone').
drug_interaction('Aminosalicylic Acid', 'Fosinopril').
drug_interaction('Aminosalicylic Acid', 'Hyaluronidase').
drug_interaction('Aminosalicylic Acid', 'Mesalazine').
drug_interaction('Aminosalicylic Acid', 'Phenindione').
drug_interaction('Aminosalicylic Acid', 'Streptokinase').
drug_interaction('Doxylamine', 'Duloxetine').
drug_interaction('Doxylamine', 'Etomidate').
drug_interaction('Doxylamine', 'Fluvoxamine').
drug_interaction('Doxylamine', 'Hyaluronidase').
drug_interaction('Doxylamine', 'Imipramine').
drug_interaction('Doxylamine', 'Methadone').
drug_interaction('Doxylamine', 'Methocarbamol').
drug_interaction('Ceftazidime', 'Dicoumarol').
drug_interaction('Ceftazidime', 'Phenindione').
drug_interaction('Gramicidin D', 'Imipramine').
drug_interaction('Gramicidin D', 'Lansoprazole').
drug_interaction('Gramicidin D', 'Ranolazine').
drug_interaction('Gramicidin D', 'Ritonavir').
drug_interaction('Cefalotin', 'Dicoumarol').
drug_interaction('Cefalotin', 'Phenindione').
drug_interaction('Insulin Pork', 'Levonorgestrel').
drug_interaction('Insulin Pork', 'Lipoic Acid').
drug_interaction('Insulin Pork', 'Ritonavir').
drug_interaction('Atenolol', 'Betamethasone').
drug_interaction('Atenolol', 'Bethanidine').
drug_interaction('Atenolol', 'Buspirone').
drug_interaction('Atenolol', 'Chlorthalidone').
drug_interaction('Atenolol', 'Clotrimazole').
drug_interaction('Atenolol', 'Clozapine').
drug_interaction('Atenolol', 'Diethylstilbestrol').
drug_interaction('Atenolol', 'Digoxin').
drug_interaction('Atenolol', 'Dihydroergotamine').
drug_interaction('Atenolol', 'Dipivefrin').
drug_interaction('Atenolol', 'Duloxetine').
drug_interaction('Atenolol', 'Etanercept').
drug_interaction('Atenolol', 'Etomidate').
drug_interaction('Atenolol', 'Fluconazole').
drug_interaction('Atenolol', 'Fluvoxamine').
drug_interaction('Atenolol', 'Fosinopril').
drug_interaction('Atenolol', 'Gramicidin D').
drug_interaction('Atenolol', 'Guanadrel').
drug_interaction('Atenolol', 'Imipramine').
drug_interaction('Atenolol', 'Insulin Pork').
drug_interaction('Atenolol', 'Lansoprazole').
drug_interaction('Atenolol', 'Levothyroxine').
drug_interaction('Atenolol', 'Liothyronine').
drug_interaction('Atenolol', 'Mesalazine').
drug_interaction('Atenolol', 'Methadone').
drug_interaction('Atenolol', 'Minoxidil').
drug_interaction('Atenolol', 'Nimodipine').
drug_interaction('Atenolol', 'Nisoldipine').
drug_interaction('Atenolol', 'Nitroprusside').
drug_interaction('Atenolol', 'Olmesartan').
drug_interaction('Atenolol', 'Omeprazole').
drug_interaction('Atenolol', 'Ranolazine').
drug_interaction('Atenolol', 'Ritonavir').
drug_interaction('Atenolol', 'Streptokinase').
drug_interaction('Atenolol', 'Tacrine').
drug_interaction('Atenolol', 'Terfenadine').
drug_interaction('Atenolol', 'Tolmetin').
drug_interaction('Atenolol', 'Triamterene').
drug_interaction('Folic Acid', 'Mesalazine').
drug_interaction('Folic Acid', 'Raltitrexed').
drug_interaction('Folic Acid', 'Tolmetin').
drug_interaction('Fluconazole', 'Fluorometholone').
drug_interaction('Fluconazole', 'Flutamide').
drug_interaction('Fluconazole', 'Imipramine').
drug_interaction('Fluconazole', 'Lansoprazole').
drug_interaction('Fluconazole', 'Levonorgestrel').
drug_interaction('Fluconazole', 'Levothyroxine').
drug_interaction('Fluconazole', 'Methadone').
drug_interaction('Fluconazole', 'Nimodipine').
drug_interaction('Fluconazole', 'Nisoldipine').
drug_interaction('Fluconazole', 'Omeprazole').
drug_interaction('Fluconazole', 'Palonosetron').
drug_interaction('Fluconazole', 'Phenindione').
drug_interaction('Fluconazole', 'Ranolazine').
drug_interaction('Fluconazole', 'Ritonavir').
drug_interaction('Fluconazole', 'Terfenadine').
drug_interaction('Nisoldipine', 'Nitroprusside').
drug_interaction('Nisoldipine', 'Olmesartan').
drug_interaction('Nisoldipine', 'Ranolazine').
drug_interaction('Nisoldipine', 'Ritonavir').
drug_interaction('Nisoldipine', 'Streptokinase').
drug_interaction('Nisoldipine', 'Terconazole').
drug_interaction('Nisoldipine', 'Triamterene').
drug_interaction('Levothyroxine', 'Phenindione').
drug_interaction('Levothyroxine', 'Ranolazine').
drug_interaction('Levothyroxine', 'Ritonavir').
drug_interaction('Dipivefrin', 'Duloxetine').
drug_interaction('Dipivefrin', 'Imipramine').
drug_interaction('Chlorthalidone', 'Clozapine').
drug_interaction('Chlorthalidone', 'Digoxin').
drug_interaction('Chlorthalidone', 'Dipivefrin').
drug_interaction('Chlorthalidone', 'Duloxetine').
drug_interaction('Chlorthalidone', 'Ergocalciferol').
drug_interaction('Chlorthalidone', 'Etanercept').
drug_interaction('Chlorthalidone', 'Fluorometholone').
drug_interaction('Chlorthalidone', 'Fluvoxamine').
drug_interaction('Chlorthalidone', 'Fosinopril').
drug_interaction('Chlorthalidone', 'Guanadrel').
drug_interaction('Chlorthalidone', 'Imipramine').
drug_interaction('Chlorthalidone', 'Insulin Pork').
drug_interaction('Chlorthalidone', 'Mesalazine').
drug_interaction('Chlorthalidone', 'Methadone').
drug_interaction('Chlorthalidone', 'Metixene').
drug_interaction('Chlorthalidone', 'Minoxidil').
drug_interaction('Chlorthalidone', 'Nimodipine').
drug_interaction('Chlorthalidone', 'Nisoldipine').
drug_interaction('Chlorthalidone', 'Nitroprusside').
drug_interaction('Chlorthalidone', 'Olmesartan').
drug_interaction('Chlorthalidone', 'Streptokinase').
drug_interaction('Chlorthalidone', 'Tolmetin').
drug_interaction('Chlorthalidone', 'Triamterene').
drug_interaction('Nitroprusside', 'Olmesartan').
drug_interaction('Nitroprusside', 'Streptokinase').
drug_interaction('Nitroprusside', 'Triamterene').
drug_interaction('Interferon alfa-n3', 'Methadone').
drug_interaction('Metocurine Iodide', 'Valrubicin').
drug_interaction('Etomidate', 'Fluvoxamine').
drug_interaction('Etomidate', 'Imipramine').
drug_interaction('Etomidate', 'Methadone').
drug_interaction('Etomidate', 'Methocarbamol').
drug_interaction('Imipramine', 'Lansoprazole').
drug_interaction('Imipramine', 'Levothyroxine').
drug_interaction('Imipramine', 'Liothyronine').
drug_interaction('Imipramine', 'Methadone').
drug_interaction('Imipramine', 'Methocarbamol').
drug_interaction('Imipramine', 'Minoxidil').
drug_interaction('Imipramine', 'Nimodipine').
drug_interaction('Imipramine', 'Nisoldipine').
drug_interaction('Imipramine', 'Nitroprusside').
drug_interaction('Imipramine', 'Olmesartan').
drug_interaction('Imipramine', 'Omeprazole').
drug_interaction('Imipramine', 'Palonosetron').
drug_interaction('Imipramine', 'Phenindione').
drug_interaction('Imipramine', 'Ranolazine').
drug_interaction('Imipramine', 'Ritonavir').
drug_interaction('Imipramine', 'Streptokinase').
drug_interaction('Imipramine', 'Tacrine').
drug_interaction('Imipramine', 'Terfenadine').
drug_interaction('Imipramine', 'Triamterene').
drug_interaction('Ranolazine', 'Ritonavir').
drug_interaction('Ranolazine', 'Tacrine').
drug_interaction('Ranolazine', 'Terconazole').
drug_interaction('Ranolazine', 'Terfenadine').
drug_interaction('Streptokinase', 'Triamterene').
drug_interaction('Interferon Alfa-2b, Recombinant', 'Methadone').
drug_interaction('Liothyronine', 'Phenindione').
drug_interaction('Liothyronine', 'Ritonavir').
drug_interaction('Ergocalciferol', 'Fluconazole').
drug_interaction('Ergocalciferol', 'Fluvoxamine').
drug_interaction('Ergocalciferol', 'Ranolazine').
drug_interaction('Ergocalciferol', 'Ritonavir').
drug_interaction('Bethanidine', 'Chlorthalidone').
drug_interaction('Bethanidine', 'Duloxetine').
drug_interaction('Bethanidine', 'Fosinopril').
drug_interaction('Bethanidine', 'Guanadrel').
drug_interaction('Bethanidine', 'Imipramine').
drug_interaction('Bethanidine', 'Minoxidil').
drug_interaction('Bethanidine', 'Nimodipine').
drug_interaction('Bethanidine', 'Nisoldipine').
drug_interaction('Bethanidine', 'Nitroprusside').
drug_interaction('Bethanidine', 'Olmesartan').
drug_interaction('Guanadrel', 'Fosinopril').
drug_interaction('Imipramine', 'Fosinopril').
drug_interaction('Mesalazine', 'Fosinopril').
drug_interaction('Minoxidil', 'Fosinopril').
drug_interaction('Nimodipine', 'Fosinopril').
drug_interaction('Nisoldipine', 'Fosinopril').
drug_interaction('Nitroprusside', 'Fosinopril').
drug_interaction('Olmesartan', 'Fosinopril').
drug_interaction('Streptokinase', 'Fosinopril').
drug_interaction('Tolmetin', 'Fosinopril').
drug_interaction('Triamterene', 'Fosinopril').
drug_interaction('Diethylstilbestrol', 'Dicoumarol').
drug_interaction('Duloxetine', 'Dicoumarol').
drug_interaction('Etanercept', 'Dicoumarol').
drug_interaction('Fluconazole', 'Dicoumarol').
drug_interaction('Fluvoxamine', 'Dicoumarol').
drug_interaction('Glucagon recombinant', 'Dicoumarol').
drug_interaction('Imipramine', 'Dicoumarol').
drug_interaction('Lansoprazole', 'Dicoumarol').
drug_interaction('Levonorgestrel', 'Dicoumarol').
drug_interaction('Levothyroxine', 'Dicoumarol').
drug_interaction('Liothyronine', 'Dicoumarol').
drug_interaction('Mesalazine', 'Dicoumarol').
drug_interaction('Omeprazole', 'Dicoumarol').
drug_interaction('Phenindione', 'Dicoumarol').
drug_interaction('Phenoxymethylpenicillin', 'Dicoumarol').
drug_interaction('Piperacillin', 'Dicoumarol').
drug_interaction('Streptokinase', 'Dicoumarol').
drug_interaction('Tolmetin', 'Dicoumarol').
drug_interaction('Digoxin', 'Clozapine').
drug_interaction('Dihydroergotamine', 'Clozapine').
drug_interaction('Doxylamine', 'Clozapine').
drug_interaction('Duloxetine', 'Clozapine').
drug_interaction('Etomidate', 'Clozapine').
drug_interaction('Fluconazole', 'Clozapine').
drug_interaction('Fluvoxamine', 'Clozapine').
drug_interaction('Fosinopril', 'Clozapine').
drug_interaction('Gramicidin D', 'Clozapine').
drug_interaction('Imipramine', 'Clozapine').
drug_interaction('Insulin Pork', 'Clozapine').
drug_interaction('Interferon alfa-n3', 'Clozapine').
drug_interaction('Lansoprazole', 'Clozapine').
drug_interaction('Levothyroxine', 'Clozapine').
drug_interaction('Liothyronine', 'Clozapine').
drug_interaction('Methadone', 'Clozapine').
drug_interaction('Methocarbamol', 'Clozapine').
drug_interaction('Minoxidil', 'Clozapine').
drug_interaction('Nimodipine', 'Clozapine').
drug_interaction('Nisoldipine', 'Clozapine').
drug_interaction('Nitroprusside', 'Clozapine').
drug_interaction('Olmesartan', 'Clozapine').
drug_interaction('Omeprazole', 'Clozapine').
drug_interaction('Palonosetron', 'Clozapine').
drug_interaction('Raltitrexed', 'Clozapine').
drug_interaction('Ranolazine', 'Clozapine').
drug_interaction('Ritonavir', 'Clozapine').
drug_interaction('Streptokinase', 'Clozapine').
drug_interaction('Tacrine', 'Clozapine').
drug_interaction('Terfenadine', 'Clozapine').
drug_interaction('Triamterene', 'Clozapine').
drug_interaction('Bivalirudin', 'Becaplermin').
drug_interaction('Dicoumarol', 'Becaplermin').
drug_interaction('Diethylstilbestrol', 'Becaplermin').
drug_interaction('Etanercept', 'Becaplermin').
drug_interaction('Levonorgestrel', 'Becaplermin').
drug_interaction('Mesalazine', 'Becaplermin').
drug_interaction('Phenindione', 'Becaplermin').
drug_interaction('Streptokinase', 'Becaplermin').
drug_interaction('Tolmetin', 'Becaplermin').
drug_interaction('Methadone', 'Interferon Alfa-2a, Recombinant').
drug_interaction('Fluorometholone', 'Etanercept').
drug_interaction('Folic Acid', 'Etanercept').
drug_interaction('Fosinopril', 'Etanercept').
drug_interaction('Mesalazine', 'Etanercept').
drug_interaction('Olmesartan', 'Etanercept').
drug_interaction('Phenindione', 'Etanercept').
drug_interaction('Tolmetin', 'Etanercept').
drug_interaction('Triamterene', 'Etanercept').
drug_interaction('Valrubicin', 'Etanercept').
drug_interaction('Aminosalicylic Acid', 'Abciximab').
drug_interaction('Becaplermin', 'Abciximab').
drug_interaction('Bivalirudin', 'Abciximab').
drug_interaction('Dicoumarol', 'Abciximab').
drug_interaction('Diethylstilbestrol', 'Abciximab').
drug_interaction('Etanercept', 'Abciximab').
drug_interaction('Levonorgestrel', 'Abciximab').
drug_interaction('Mesalazine', 'Abciximab').
drug_interaction('Phenindione', 'Abciximab').
drug_interaction('Streptokinase', 'Abciximab').
drug_interaction('Tolmetin', 'Abciximab').
drug_interaction('Olmesartan', 'Mesalazine').
drug_interaction('Omeprazole', 'Mesalazine').
drug_interaction('Phenindione', 'Mesalazine').
drug_interaction('Streptokinase', 'Mesalazine').
drug_interaction('Tolmetin', 'Mesalazine').
drug_interaction('Triamterene', 'Mesalazine').
drug_interaction('Valrubicin', 'Mesalazine').
drug_interaction('Phenindione', 'Levonorgestrel').
drug_interaction('Ranolazine', 'Levonorgestrel').
drug_interaction('Ritonavir', 'Levonorgestrel').
drug_interaction('Ranolazine', 'Palonosetron').
drug_interaction('Ritonavir', 'Palonosetron').
drug_interaction('Etomidate', 'Duloxetine').
drug_interaction('Fluvoxamine', 'Duloxetine').
drug_interaction('Fosinopril', 'Duloxetine').
drug_interaction('Imipramine', 'Duloxetine').
drug_interaction('Levothyroxine', 'Duloxetine').
drug_interaction('Liothyronine', 'Duloxetine').
drug_interaction('Methadone', 'Duloxetine').
drug_interaction('Methocarbamol', 'Duloxetine').
drug_interaction('Minoxidil', 'Duloxetine').
drug_interaction('Nimodipine', 'Duloxetine').
drug_interaction('Nisoldipine', 'Duloxetine').
drug_interaction('Nitroprusside', 'Duloxetine').
drug_interaction('Olmesartan', 'Duloxetine').
drug_interaction('Palonosetron', 'Duloxetine').
drug_interaction('Phenindione', 'Duloxetine').
drug_interaction('Ranolazine', 'Duloxetine').
drug_interaction('Ritonavir', 'Duloxetine').
drug_interaction('Streptokinase', 'Duloxetine').
drug_interaction('Terfenadine', 'Duloxetine').
drug_interaction('Triamterene', 'Duloxetine').
drug_interaction('Dihydroergotamine', 'Digoxin').
drug_interaction('Ergocalciferol', 'Digoxin').
drug_interaction('Etanercept', 'Digoxin').
drug_interaction('Fluconazole', 'Digoxin').
drug_interaction('Flutamide', 'Digoxin').
drug_interaction('Fluvoxamine', 'Digoxin').
drug_interaction('Fosinopril', 'Digoxin').
drug_interaction('Gramicidin D', 'Digoxin').
drug_interaction('Imipramine', 'Digoxin').
drug_interaction('Lansoprazole', 'Digoxin').
drug_interaction('Levothyroxine', 'Digoxin').
drug_interaction('Liothyronine', 'Digoxin').
drug_interaction('Mesalazine', 'Digoxin').
drug_interaction('Methadone', 'Digoxin').
drug_interaction('Metocurine Iodide', 'Digoxin').
drug_interaction('Nisoldipine', 'Digoxin').
drug_interaction('Omeprazole', 'Digoxin').
drug_interaction('Pipobroman', 'Digoxin').
drug_interaction('Raltitrexed', 'Digoxin').
drug_interaction('Ranolazine', 'Digoxin').
drug_interaction('Ritonavir', 'Digoxin').
drug_interaction('Tacrine', 'Digoxin').
drug_interaction('Terfenadine', 'Digoxin').
drug_interaction('Tolmetin', 'Digoxin').
drug_interaction('Triamterene', 'Digoxin').
drug_interaction('Valrubicin', 'Digoxin').
drug_interaction('Verteporfin', 'Digoxin').
drug_interaction('Valrubicin', 'Phenoxymethylpenicillin').
drug_interaction('Phenindione', 'Omeprazole').
drug_interaction('Ranolazine', 'Omeprazole').
drug_interaction('Ritonavir', 'Omeprazole').
drug_interaction('Terfenadine', 'Omeprazole').
drug_interaction('Phenoxymethylpenicillin', 'Phenindione').
drug_interaction('Piperacillin', 'Phenindione').
drug_interaction('Streptokinase', 'Phenindione').
drug_interaction('Tolmetin', 'Phenindione').
drug_interaction('Carisoprodol', 'Buspirone').
drug_interaction('Clemastine', 'Buspirone').
drug_interaction('Clotrimazole', 'Buspirone').
drug_interaction('Clozapine', 'Buspirone').
drug_interaction('Diethylstilbestrol', 'Buspirone').
drug_interaction('Digoxin', 'Buspirone').
drug_interaction('Dihydroergotamine', 'Buspirone').
drug_interaction('Doxylamine', 'Buspirone').
drug_interaction('Duloxetine', 'Buspirone').
drug_interaction('Etomidate', 'Buspirone').
drug_interaction('Fluconazole', 'Buspirone').
drug_interaction('Fluvoxamine', 'Buspirone').
drug_interaction('Imipramine', 'Buspirone').
drug_interaction('Lansoprazole', 'Buspirone').
drug_interaction('Methadone', 'Buspirone').
drug_interaction('Methocarbamol', 'Buspirone').
drug_interaction('Palonosetron', 'Buspirone').
drug_interaction('Ranolazine', 'Buspirone').
drug_interaction('Ritonavir', 'Buspirone').
drug_interaction('Terconazole', 'Buspirone').
drug_interaction('Triamterene', 'Tolmetin').
drug_interaction('Valrubicin', 'Tolmetin').
drug_interaction('Atenolol', 'Amsacrine').
drug_interaction('Betamethasone', 'Amsacrine').
drug_interaction('Clemastine', 'Amsacrine').
drug_interaction('Clotrimazole', 'Amsacrine').
drug_interaction('Clozapine', 'Amsacrine').
drug_interaction('Diethylstilbestrol', 'Amsacrine').
drug_interaction('Digoxin', 'Amsacrine').
drug_interaction('Duloxetine', 'Amsacrine').
drug_interaction('Fluvoxamine', 'Amsacrine').
drug_interaction('Imipramine', 'Amsacrine').
drug_interaction('Lansoprazole', 'Amsacrine').
drug_interaction('Methadone', 'Amsacrine').
drug_interaction('Ranolazine', 'Amsacrine').
drug_interaction('Ritonavir', 'Amsacrine').
drug_interaction('Metixene', 'Glucagon recombinant').
drug_interaction('Phenindione', 'Glucagon recombinant').
drug_interaction('Tacrine', 'Metixene').
drug_interaction('Levothyroxine', 'Lansoprazole').
drug_interaction('Liothyronine', 'Lansoprazole').
drug_interaction('Mesalazine', 'Lansoprazole').
drug_interaction('Methadone', 'Lansoprazole').
drug_interaction('Nisoldipine', 'Lansoprazole').
drug_interaction('Omeprazole', 'Lansoprazole').
drug_interaction('Phenindione', 'Lansoprazole').
drug_interaction('Ranolazine', 'Lansoprazole').
drug_interaction('Ritonavir', 'Lansoprazole').
drug_interaction('Tacrine', 'Lansoprazole').
drug_interaction('Terfenadine', 'Lansoprazole').
drug_interaction('Methocarbamol', 'Methadone').
drug_interaction('Metixene', 'Methadone').
drug_interaction('Omeprazole', 'Methadone').
drug_interaction('Palonosetron', 'Methadone').
drug_interaction('Ranolazine', 'Methadone').
drug_interaction('Ritonavir', 'Methadone').
drug_interaction('Terfenadine', 'Methadone').
drug_interaction('Triamterene', 'Methadone').
drug_interaction('Clemastine', 'Carisoprodol').
drug_interaction('Clotrimazole', 'Carisoprodol').
drug_interaction('Clozapine', 'Carisoprodol').
drug_interaction('Doxylamine', 'Carisoprodol').
drug_interaction('Duloxetine', 'Carisoprodol').
drug_interaction('Etomidate', 'Carisoprodol').
drug_interaction('Fluconazole', 'Carisoprodol').
drug_interaction('Fluvoxamine', 'Carisoprodol').
drug_interaction('Imipramine', 'Carisoprodol').
drug_interaction('Methadone', 'Carisoprodol').
drug_interaction('Methocarbamol', 'Carisoprodol').
drug_interaction('Omeprazole', 'Carisoprodol').
drug_interaction('Dicoumarol', 'Cefmetazole').
drug_interaction('Phenindione', 'Cefmetazole').
drug_interaction('Buspirone', 'Betamethasone').
drug_interaction('Chlorthalidone', 'Betamethasone').
drug_interaction('Clotrimazole', 'Betamethasone').
drug_interaction('Diethylstilbestrol', 'Betamethasone').
drug_interaction('Digoxin', 'Betamethasone').
drug_interaction('Dihydroergotamine', 'Betamethasone').
drug_interaction('Etanercept', 'Betamethasone').
drug_interaction('Fluconazole', 'Betamethasone').
drug_interaction('Fluvoxamine', 'Betamethasone').
drug_interaction('Gramicidin D', 'Betamethasone').
drug_interaction('Hyaluronidase', 'Betamethasone').
drug_interaction('Imipramine', 'Betamethasone').
drug_interaction('Insulin Pork', 'Betamethasone').
drug_interaction('Lansoprazole', 'Betamethasone').
drug_interaction('Levothyroxine', 'Betamethasone').
drug_interaction('Liothyronine', 'Betamethasone').
drug_interaction('Mesalazine', 'Betamethasone').
drug_interaction('Methadone', 'Betamethasone').
drug_interaction('Nisoldipine', 'Betamethasone').
drug_interaction('Omeprazole', 'Betamethasone').
drug_interaction('Ranolazine', 'Betamethasone').
drug_interaction('Ritonavir', 'Betamethasone').
drug_interaction('Tacrine', 'Betamethasone').
drug_interaction('Terfenadine', 'Betamethasone').
drug_interaction('Tolmetin', 'Betamethasone').
drug_interaction('Fluvoxamine', 'Fluorometholone').
drug_interaction('Hyaluronidase', 'Fluorometholone').
drug_interaction('Mesalazine', 'Fluorometholone').
drug_interaction('Ranolazine', 'Fluorometholone').
drug_interaction('Ritonavir', 'Fluorometholone').
drug_interaction('Tacrine', 'Fluorometholone').
drug_interaction('Tolmetin', 'Fluorometholone').
drug_interaction('Minoxidil', 'Guanadrel').
drug_interaction('Nimodipine', 'Guanadrel').
drug_interaction('Nisoldipine', 'Guanadrel').
drug_interaction('Nitroprusside', 'Guanadrel').
drug_interaction('Olmesartan', 'Guanadrel').
drug_interaction('Metixene', 'Botulinum Toxin Type B').
drug_interaction('Metocurine Iodide', 'Botulinum Toxin Type B').
drug_interaction('Valrubicin', 'Botulinum Toxin Type B').
drug_interaction('Tacrine', 'Ritonavir').
drug_interaction('Terfenadine', 'Ritonavir').
drug_interaction('Fluvoxamine', 'Flutamide').
drug_interaction('Omeprazole', 'Flutamide').
drug_interaction('Ranolazine', 'Flutamide').
drug_interaction('Ritonavir', 'Flutamide').
drug_interaction('Atenolol', 'Acetohexamide').
drug_interaction('Betamethasone', 'Acetohexamide').
drug_interaction('Chlorthalidone', 'Acetohexamide').
drug_interaction('Clozapine', 'Acetohexamide').
drug_interaction('Dicoumarol', 'Acetohexamide').
drug_interaction('Fluconazole', 'Acetohexamide').
drug_interaction('Levonorgestrel', 'Acetohexamide').
drug_interaction('Lipoic Acid', 'Acetohexamide').
drug_interaction('Phenindione', 'Acetohexamide').
drug_interaction('Ritonavir', 'Acetohexamide').
drug_interaction('Dicoumarol', 'Carbimazole').
drug_interaction('Digoxin', 'Carbimazole').
drug_interaction('Phenindione', 'Carbimazole').
drug_interaction('Streptokinase', 'Olmesartan').
drug_interaction('Tolmetin', 'Olmesartan').
drug_interaction('Triamterene', 'Olmesartan').
drug_interaction('Imipramine', 'Fluvoxamine').
drug_interaction('Lansoprazole', 'Fluvoxamine').
drug_interaction('Levonorgestrel', 'Fluvoxamine').
drug_interaction('Levothyroxine', 'Fluvoxamine').
drug_interaction('Liothyronine', 'Fluvoxamine').
drug_interaction('Methadone', 'Fluvoxamine').
drug_interaction('Methocarbamol', 'Fluvoxamine').
drug_interaction('Nimodipine', 'Fluvoxamine').
drug_interaction('Nisoldipine', 'Fluvoxamine').
drug_interaction('Omeprazole', 'Fluvoxamine').
drug_interaction('Palonosetron', 'Fluvoxamine').
drug_interaction('Phenindione', 'Fluvoxamine').
drug_interaction('Ranolazine', 'Fluvoxamine').
drug_interaction('Ritonavir', 'Fluvoxamine').
drug_interaction('Tacrine', 'Fluvoxamine').
drug_interaction('Terfenadine', 'Fluvoxamine').
drug_interaction('Triamterene', 'Fluvoxamine').
drug_interaction('Clozapine', 'Clemastine').
drug_interaction('Digoxin', 'Clemastine').
drug_interaction('Dihydroergotamine', 'Clemastine').
drug_interaction('Doxylamine', 'Clemastine').
drug_interaction('Duloxetine', 'Clemastine').
drug_interaction('Ergocalciferol', 'Clemastine').
drug_interaction('Etomidate', 'Clemastine').
drug_interaction('Fluorometholone', 'Clemastine').
drug_interaction('Flutamide', 'Clemastine').
drug_interaction('Fluvoxamine', 'Clemastine').
drug_interaction('Hyaluronidase', 'Clemastine').
drug_interaction('Imipramine', 'Clemastine').
drug_interaction('Lansoprazole', 'Clemastine').
drug_interaction('Levonorgestrel', 'Clemastine').
drug_interaction('Levothyroxine', 'Clemastine').
drug_interaction('Methadone', 'Clemastine').
drug_interaction('Methocarbamol', 'Clemastine').
drug_interaction('Nimodipine', 'Clemastine').
drug_interaction('Nisoldipine', 'Clemastine').
drug_interaction('Omeprazole', 'Clemastine').
drug_interaction('Palonosetron', 'Clemastine').
drug_interaction('Ranolazine', 'Clemastine').
drug_interaction('Ritonavir', 'Clemastine').
drug_interaction('Terfenadine', 'Clemastine').
drug_interaction('Mesalazine', 'Hyaluronidase').
drug_interaction('Terfenadine', 'Hyaluronidase').
drug_interaction('Clozapine', 'Clotrimazole').
drug_interaction('Dicoumarol', 'Clotrimazole').
drug_interaction('Diethylstilbestrol', 'Clotrimazole').
drug_interaction('Digoxin', 'Clotrimazole').
drug_interaction('Dihydroergotamine', 'Clotrimazole').
drug_interaction('Duloxetine', 'Clotrimazole').
drug_interaction('Ergocalciferol', 'Clotrimazole').
drug_interaction('Fluorometholone', 'Clotrimazole').
drug_interaction('Flutamide', 'Clotrimazole').
drug_interaction('Fluvoxamine', 'Clotrimazole').
drug_interaction('Folic Acid', 'Clotrimazole').
drug_interaction('Imipramine', 'Clotrimazole').
drug_interaction('Lansoprazole', 'Clotrimazole').
drug_interaction('Levonorgestrel', 'Clotrimazole').
drug_interaction('Levothyroxine', 'Clotrimazole').
drug_interaction('Methadone', 'Clotrimazole').
drug_interaction('Nimodipine', 'Clotrimazole').
drug_interaction('Nisoldipine', 'Clotrimazole').
drug_interaction('Omeprazole', 'Clotrimazole').
drug_interaction('Palonosetron', 'Clotrimazole').
drug_interaction('Ranolazine', 'Clotrimazole').
drug_interaction('Ritonavir', 'Clotrimazole').
drug_interaction('Tacrine', 'Clotrimazole').
drug_interaction('Terfenadine', 'Clotrimazole').
drug_interaction('Triamterene', 'Clotrimazole').
drug_interaction('Valrubicin', 'Piperacillin').
drug_interaction('Dicoumarol', 'Bivalirudin').
drug_interaction('Diethylstilbestrol', 'Bivalirudin').
drug_interaction('Digoxin', 'Bivalirudin').
drug_interaction('Dihydroergotamine', 'Bivalirudin').
drug_interaction('Etanercept', 'Bivalirudin').
drug_interaction('Imipramine', 'Bivalirudin').
drug_interaction('Levonorgestrel', 'Bivalirudin').
drug_interaction('Mesalazine', 'Bivalirudin').
drug_interaction('Phenindione', 'Bivalirudin').
drug_interaction('Streptokinase', 'Bivalirudin').
drug_interaction('Tolmetin', 'Bivalirudin').
drug_interaction('Dipivefrin', 'Dihydroergotamine').
drug_interaction('Duloxetine', 'Dihydroergotamine').
drug_interaction('Ergocalciferol', 'Dihydroergotamine').
drug_interaction('Fluconazole', 'Dihydroergotamine').
drug_interaction('Fluorometholone', 'Dihydroergotamine').
drug_interaction('Flutamide', 'Dihydroergotamine').
drug_interaction('Fluvoxamine', 'Dihydroergotamine').
drug_interaction('Fosinopril', 'Dihydroergotamine').
drug_interaction('Imipramine', 'Dihydroergotamine').
drug_interaction('Lansoprazole', 'Dihydroergotamine').
drug_interaction('Levonorgestrel', 'Dihydroergotamine').
drug_interaction('Levothyroxine', 'Dihydroergotamine').
drug_interaction('Methadone', 'Dihydroergotamine').
drug_interaction('Nimodipine', 'Dihydroergotamine').
drug_interaction('Nisoldipine', 'Dihydroergotamine').
drug_interaction('Omeprazole', 'Dihydroergotamine').
drug_interaction('Palonosetron', 'Dihydroergotamine').
drug_interaction('Ranolazine', 'Dihydroergotamine').
drug_interaction('Ritonavir', 'Dihydroergotamine').
drug_interaction('Terfenadine', 'Dihydroergotamine').
drug_interaction('Nisoldipine', 'Nimodipine').
drug_interaction('Nitroprusside', 'Nimodipine').
drug_interaction('Olmesartan', 'Nimodipine').
drug_interaction('Ranolazine', 'Nimodipine').
drug_interaction('Ritonavir', 'Nimodipine').
drug_interaction('Streptokinase', 'Nimodipine').
drug_interaction('Terconazole', 'Nimodipine').
drug_interaction('Triamterene', 'Nimodipine').
drug_interaction('Digoxin', 'Diethylstilbestrol').
drug_interaction('Dihydroergotamine', 'Diethylstilbestrol').
drug_interaction('Fluconazole', 'Diethylstilbestrol').
drug_interaction('Fluorometholone', 'Diethylstilbestrol').
drug_interaction('Fluvoxamine', 'Diethylstilbestrol').
drug_interaction('Fosinopril', 'Diethylstilbestrol').
drug_interaction('Gramicidin D', 'Diethylstilbestrol').
drug_interaction('Hyaluronidase', 'Diethylstilbestrol').
drug_interaction('Imipramine', 'Diethylstilbestrol').
drug_interaction('Lansoprazole', 'Diethylstilbestrol').
drug_interaction('Levothyroxine', 'Diethylstilbestrol').
drug_interaction('Liothyronine', 'Diethylstilbestrol').
drug_interaction('Methadone', 'Diethylstilbestrol').
drug_interaction('Nisoldipine', 'Diethylstilbestrol').
drug_interaction('Omeprazole', 'Diethylstilbestrol').
drug_interaction('Phenindione', 'Diethylstilbestrol').
drug_interaction('Ranolazine', 'Diethylstilbestrol').
drug_interaction('Ritonavir', 'Diethylstilbestrol').
drug_interaction('Tacrine', 'Diethylstilbestrol').
drug_interaction('Terfenadine', 'Diethylstilbestrol').
drug_interaction('Nimodipine', 'Minoxidil').
drug_interaction('Nisoldipine', 'Minoxidil').
drug_interaction('Nitroprusside', 'Minoxidil').
drug_interaction('Olmesartan', 'Minoxidil').
drug_interaction('Streptokinase', 'Minoxidil').
drug_interaction('Triamterene', 'Minoxidil').
drug_interaction('Becaplermin', 'Aminosalicylic Acid').
drug_interaction('Betamethasone', 'Aminosalicylic Acid').
drug_interaction('Bivalirudin', 'Aminosalicylic Acid').
drug_interaction('Dicoumarol', 'Aminosalicylic Acid').
drug_interaction('Fluorometholone', 'Aminosalicylic Acid').
drug_interaction('Fosinopril', 'Aminosalicylic Acid').
drug_interaction('Hyaluronidase', 'Aminosalicylic Acid').
drug_interaction('Mesalazine', 'Aminosalicylic Acid').
drug_interaction('Phenindione', 'Aminosalicylic Acid').
drug_interaction('Streptokinase', 'Aminosalicylic Acid').
drug_interaction('Duloxetine', 'Doxylamine').
drug_interaction('Etomidate', 'Doxylamine').
drug_interaction('Fluvoxamine', 'Doxylamine').
drug_interaction('Hyaluronidase', 'Doxylamine').
drug_interaction('Imipramine', 'Doxylamine').
drug_interaction('Methadone', 'Doxylamine').
drug_interaction('Methocarbamol', 'Doxylamine').
drug_interaction('Dicoumarol', 'Ceftazidime').
drug_interaction('Phenindione', 'Ceftazidime').
drug_interaction('Imipramine', 'Gramicidin D').
drug_interaction('Lansoprazole', 'Gramicidin D').
drug_interaction('Ranolazine', 'Gramicidin D').
drug_interaction('Ritonavir', 'Gramicidin D').
drug_interaction('Dicoumarol', 'Cefalotin').
drug_interaction('Phenindione', 'Cefalotin').
drug_interaction('Levonorgestrel', 'Insulin Pork').
drug_interaction('Lipoic Acid', 'Insulin Pork').
drug_interaction('Ritonavir', 'Insulin Pork').
drug_interaction('Betamethasone', 'Atenolol').
drug_interaction('Bethanidine', 'Atenolol').
drug_interaction('Buspirone', 'Atenolol').
drug_interaction('Chlorthalidone', 'Atenolol').
drug_interaction('Clotrimazole', 'Atenolol').
drug_interaction('Clozapine', 'Atenolol').
drug_interaction('Diethylstilbestrol', 'Atenolol').
drug_interaction('Digoxin', 'Atenolol').
drug_interaction('Dihydroergotamine', 'Atenolol').
drug_interaction('Dipivefrin', 'Atenolol').
drug_interaction('Duloxetine', 'Atenolol').
drug_interaction('Etanercept', 'Atenolol').
drug_interaction('Etomidate', 'Atenolol').
drug_interaction('Fluconazole', 'Atenolol').
drug_interaction('Fluvoxamine', 'Atenolol').
drug_interaction('Fosinopril', 'Atenolol').
drug_interaction('Gramicidin D', 'Atenolol').
drug_interaction('Guanadrel', 'Atenolol').
drug_interaction('Imipramine', 'Atenolol').
drug_interaction('Insulin Pork', 'Atenolol').
drug_interaction('Lansoprazole', 'Atenolol').
drug_interaction('Levothyroxine', 'Atenolol').
drug_interaction('Liothyronine', 'Atenolol').
drug_interaction('Mesalazine', 'Atenolol').
drug_interaction('Methadone', 'Atenolol').
drug_interaction('Minoxidil', 'Atenolol').
drug_interaction('Nimodipine', 'Atenolol').
drug_interaction('Nisoldipine', 'Atenolol').
drug_interaction('Nitroprusside', 'Atenolol').
drug_interaction('Olmesartan', 'Atenolol').
drug_interaction('Omeprazole', 'Atenolol').
drug_interaction('Ranolazine', 'Atenolol').
drug_interaction('Ritonavir', 'Atenolol').
drug_interaction('Streptokinase', 'Atenolol').
drug_interaction('Tacrine', 'Atenolol').
drug_interaction('Terfenadine', 'Atenolol').
drug_interaction('Tolmetin', 'Atenolol').
drug_interaction('Triamterene', 'Atenolol').
drug_interaction('Mesalazine', 'Folic Acid').
drug_interaction('Raltitrexed', 'Folic Acid').
drug_interaction('Tolmetin', 'Folic Acid').
drug_interaction('Fluorometholone', 'Fluconazole').
drug_interaction('Flutamide', 'Fluconazole').
drug_interaction('Imipramine', 'Fluconazole').
drug_interaction('Lansoprazole', 'Fluconazole').
drug_interaction('Levonorgestrel', 'Fluconazole').
drug_interaction('Levothyroxine', 'Fluconazole').
drug_interaction('Methadone', 'Fluconazole').
drug_interaction('Nimodipine', 'Fluconazole').
drug_interaction('Nisoldipine', 'Fluconazole').
drug_interaction('Omeprazole', 'Fluconazole').
drug_interaction('Palonosetron', 'Fluconazole').
drug_interaction('Phenindione', 'Fluconazole').
drug_interaction('Ranolazine', 'Fluconazole').
drug_interaction('Ritonavir', 'Fluconazole').
drug_interaction('Terfenadine', 'Fluconazole').
drug_interaction('Nitroprusside', 'Nisoldipine').
drug_interaction('Olmesartan', 'Nisoldipine').
drug_interaction('Ranolazine', 'Nisoldipine').
drug_interaction('Ritonavir', 'Nisoldipine').
drug_interaction('Streptokinase', 'Nisoldipine').
drug_interaction('Terconazole', 'Nisoldipine').
drug_interaction('Triamterene', 'Nisoldipine').
drug_interaction('Phenindione', 'Levothyroxine').
drug_interaction('Ranolazine', 'Levothyroxine').
drug_interaction('Ritonavir', 'Levothyroxine').
drug_interaction('Duloxetine', 'Dipivefrin').
drug_interaction('Imipramine', 'Dipivefrin').
drug_interaction('Clozapine', 'Chlorthalidone').
drug_interaction('Digoxin', 'Chlorthalidone').
drug_interaction('Dipivefrin', 'Chlorthalidone').
drug_interaction('Duloxetine', 'Chlorthalidone').
drug_interaction('Ergocalciferol', 'Chlorthalidone').
drug_interaction('Etanercept', 'Chlorthalidone').
drug_interaction('Fluorometholone', 'Chlorthalidone').
drug_interaction('Fluvoxamine', 'Chlorthalidone').
drug_interaction('Fosinopril', 'Chlorthalidone').
drug_interaction('Guanadrel', 'Chlorthalidone').
drug_interaction('Imipramine', 'Chlorthalidone').
drug_interaction('Insulin Pork', 'Chlorthalidone').
drug_interaction('Mesalazine', 'Chlorthalidone').
drug_interaction('Methadone', 'Chlorthalidone').
drug_interaction('Metixene', 'Chlorthalidone').
drug_interaction('Minoxidil', 'Chlorthalidone').
drug_interaction('Nimodipine', 'Chlorthalidone').
drug_interaction('Nisoldipine', 'Chlorthalidone').
drug_interaction('Nitroprusside', 'Chlorthalidone').
drug_interaction('Olmesartan', 'Chlorthalidone').
drug_interaction('Streptokinase', 'Chlorthalidone').
drug_interaction('Tolmetin', 'Chlorthalidone').
drug_interaction('Triamterene', 'Chlorthalidone').
drug_interaction('Olmesartan', 'Nitroprusside').
drug_interaction('Streptokinase', 'Nitroprusside').
drug_interaction('Triamterene', 'Nitroprusside').
drug_interaction('Methadone', 'Interferon alfa-n3').
drug_interaction('Valrubicin', 'Metocurine Iodide').
drug_interaction('Fluvoxamine', 'Etomidate').
drug_interaction('Imipramine', 'Etomidate').
drug_interaction('Methadone', 'Etomidate').
drug_interaction('Methocarbamol', 'Etomidate').
drug_interaction('Lansoprazole', 'Imipramine').
drug_interaction('Levothyroxine', 'Imipramine').
drug_interaction('Liothyronine', 'Imipramine').
drug_interaction('Methadone', 'Imipramine').
drug_interaction('Methocarbamol', 'Imipramine').
drug_interaction('Minoxidil', 'Imipramine').
drug_interaction('Nimodipine', 'Imipramine').
drug_interaction('Nisoldipine', 'Imipramine').
drug_interaction('Nitroprusside', 'Imipramine').
drug_interaction('Olmesartan', 'Imipramine').
drug_interaction('Omeprazole', 'Imipramine').
drug_interaction('Palonosetron', 'Imipramine').
drug_interaction('Phenindione', 'Imipramine').
drug_interaction('Ranolazine', 'Imipramine').
drug_interaction('Ritonavir', 'Imipramine').
drug_interaction('Streptokinase', 'Imipramine').
drug_interaction('Tacrine', 'Imipramine').
drug_interaction('Terfenadine', 'Imipramine').
drug_interaction('Triamterene', 'Imipramine').
drug_interaction('Ritonavir', 'Ranolazine').
drug_interaction('Tacrine', 'Ranolazine').
drug_interaction('Terconazole', 'Ranolazine').
drug_interaction('Terfenadine', 'Ranolazine').
drug_interaction('Triamterene', 'Streptokinase').
drug_interaction('Methadone', 'Interferon Alfa-2b, Recombinant').
drug_interaction('Phenindione', 'Liothyronine').
drug_interaction('Ritonavir', 'Liothyronine').
drug_interaction('Fluconazole', 'Ergocalciferol').
drug_interaction('Fluvoxamine', 'Ergocalciferol').
drug_interaction('Ranolazine', 'Ergocalciferol').
drug_interaction('Ritonavir', 'Ergocalciferol').
drug_interaction('Chlorthalidone', 'Bethanidine').
drug_interaction('Duloxetine', 'Bethanidine').
drug_interaction('Fosinopril', 'Bethanidine').
drug_interaction('Guanadrel', 'Bethanidine').
drug_interaction('Imipramine', 'Bethanidine').
drug_interaction('Minoxidil', 'Bethanidine').
drug_interaction('Nimodipine', 'Bethanidine').
drug_interaction('Nisoldipine', 'Bethanidine').
drug_interaction('Nitroprusside', 'Bethanidine').
drug_interaction('Olmesartan', 'Bethanidine').

