
drug_interaction('Carbachol', 'Esmolol').
drug_interaction('Carbachol', 'Timolol').
drug_interaction('Esmolol', 'Indomethacin').
drug_interaction('Esmolol', 'Ketorolac').
drug_interaction('Esmolol', 'Lidocaine').
drug_interaction('Esmolol', 'Mesalazine').
drug_interaction('Esmolol', 'Nabilone').
drug_interaction('Esmolol', 'Nitroprusside').
drug_interaction('Esmolol', 'Norepinephrine').
drug_interaction('Esmolol', 'Octreotide').
drug_interaction('Esmolol', 'Pramipexole').
drug_interaction('Esmolol', 'Promazine').
drug_interaction('Esmolol', 'Ropinirole').
drug_interaction('Esmolol', 'Secobarbital').
drug_interaction('Esmolol', 'Tenoxicam').
drug_interaction('Esmolol', 'Theophylline').
drug_interaction('Esmolol', 'Thiethylperazine').
drug_interaction('Esmolol', 'Timolol').
drug_interaction('Esmolol', 'Triflupromazine').
drug_interaction('Chlorzoxazone', 'Clozapine').
drug_interaction('Chlorzoxazone', 'Fluvoxamine').
drug_interaction('Chlorzoxazone', 'Hydromorphone').
drug_interaction('Chlorzoxazone', 'Lidocaine').
drug_interaction('Chlorzoxazone', 'Nabilone').
drug_interaction('Chlorzoxazone', 'Pramipexole').
drug_interaction('Chlorzoxazone', 'Promazine').
drug_interaction('Chlorzoxazone', 'Ropinirole').
drug_interaction('Chlorzoxazone', 'Secobarbital').
drug_interaction('Chlorzoxazone', 'Temazepam').
drug_interaction('Chlorzoxazone', 'Theophylline').
drug_interaction('Chlorzoxazone', 'Triflupromazine').
drug_interaction('Chlorzoxazone', 'Zolpidem').
drug_interaction('Hydromorphone', 'Lidocaine').
drug_interaction('Hydromorphone', 'Nabilone').
drug_interaction('Hydromorphone', 'Omeprazole').
drug_interaction('Hydromorphone', 'Pramipexole').
drug_interaction('Hydromorphone', 'Procyclidine').
drug_interaction('Hydromorphone', 'Promazine').
drug_interaction('Hydromorphone', 'Pyrimethamine').
drug_interaction('Hydromorphone', 'Ropinirole').
drug_interaction('Hydromorphone', 'Secobarbital').
drug_interaction('Hydromorphone', 'Sorafenib').
drug_interaction('Hydromorphone', 'Succinylcholine').
drug_interaction('Hydromorphone', 'Temazepam').
drug_interaction('Hydromorphone', 'Thiethylperazine').
drug_interaction('Hydromorphone', 'Triflupromazine').
drug_interaction('Hydromorphone', 'Trimethoprim').
drug_interaction('Hydromorphone', 'Zolpidem').
drug_interaction('Trimethoprim', 'Zolpidem').
drug_interaction('Nitroprusside', 'Pramipexole').
drug_interaction('Nitroprusside', 'Ropinirole').
drug_interaction('Nitroprusside', 'Secobarbital').
drug_interaction('Nitroprusside', 'Timolol').
drug_interaction('Secobarbital', 'Sorafenib').
drug_interaction('Secobarbital', 'Temazepam').
drug_interaction('Secobarbital', 'Tenoxicam').
drug_interaction('Secobarbital', 'Theophylline').
drug_interaction('Secobarbital', 'Timolol').
drug_interaction('Secobarbital', 'Triflupromazine').
drug_interaction('Secobarbital', 'Trimethoprim').
drug_interaction('Secobarbital', 'Zolpidem').
drug_interaction('Ropinirole', 'Secobarbital').
drug_interaction('Ropinirole', 'Temazepam').
drug_interaction('Ropinirole', 'Theophylline').
drug_interaction('Ropinirole', 'Timolol').
drug_interaction('Ropinirole', 'Triflupromazine').
drug_interaction('Ropinirole', 'Zolpidem').
drug_interaction('Peginterferon alfa-2a', 'Theophylline').
drug_interaction('Timolol', 'Triflupromazine').
drug_interaction('Timolol', 'Trimethoprim').
drug_interaction('Nabilone', 'Nitroprusside').
drug_interaction('Nabilone', 'Norepinephrine').
drug_interaction('Nabilone', 'Pramipexole').
drug_interaction('Nabilone', 'Procyclidine').
drug_interaction('Nabilone', 'Promazine').
drug_interaction('Nabilone', 'Ropinirole').
drug_interaction('Nabilone', 'Secobarbital').
drug_interaction('Nabilone', 'Temazepam').
drug_interaction('Nabilone', 'Timolol').
drug_interaction('Nabilone', 'Triflupromazine').
drug_interaction('Nabilone', 'Zolpidem').
drug_interaction('Octreotide', 'Promazine').
drug_interaction('Octreotide', 'Timolol').
drug_interaction('Cetirizine', 'Chlorzoxazone').
drug_interaction('Cetirizine', 'Clozapine').
drug_interaction('Cetirizine', 'Fluvoxamine').
drug_interaction('Cetirizine', 'Hydromorphone').
drug_interaction('Cetirizine', 'Lidocaine').
drug_interaction('Cetirizine', 'Nabilone').
drug_interaction('Cetirizine', 'Pramipexole').
drug_interaction('Cetirizine', 'Promazine').
drug_interaction('Cetirizine', 'Ropinirole').
drug_interaction('Cetirizine', 'Secobarbital').
drug_interaction('Cetirizine', 'Temazepam').
drug_interaction('Cetirizine', 'Triflupromazine').
drug_interaction('Cetirizine', 'Zolpidem').
drug_interaction('Calcitriol', 'Diflorasone').
drug_interaction('Calcitriol', 'Flunisolide').
drug_interaction('Calcitriol', 'Fluvoxamine').
drug_interaction('Lidocaine', 'Menadione').
drug_interaction('Lidocaine', 'Nabilone').
drug_interaction('Lidocaine', 'Omeprazole').
drug_interaction('Lidocaine', 'Pramipexole').
drug_interaction('Lidocaine', 'Progesterone').
drug_interaction('Lidocaine', 'Promazine').
drug_interaction('Lidocaine', 'Pyrimethamine').
drug_interaction('Lidocaine', 'Ropinirole').
drug_interaction('Lidocaine', 'Secobarbital').
drug_interaction('Lidocaine', 'Sorafenib').
drug_interaction('Lidocaine', 'Temazepam').
drug_interaction('Lidocaine', 'Theophylline').
drug_interaction('Lidocaine', 'Timolol').
drug_interaction('Lidocaine', 'Triflupromazine').
drug_interaction('Lidocaine', 'Trimethoprim').
drug_interaction('Lidocaine', 'Zolpidem').
drug_interaction('Diflorasone', 'Indomethacin').
drug_interaction('Diflorasone', 'Ketorolac').
drug_interaction('Diflorasone', 'Mesalazine').
drug_interaction('Diflorasone', 'Moxifloxacin').
drug_interaction('Diflorasone', 'Tenoxicam').
drug_interaction('Acetyldigitoxin', 'Amikacin').
drug_interaction('Acetyldigitoxin', 'Bleomycin').
drug_interaction('Acetyldigitoxin', 'Calcitriol').
drug_interaction('Acetyldigitoxin', 'Chlorambucil').
drug_interaction('Acetyldigitoxin', 'Chlorotrianisene').
drug_interaction('Acetyldigitoxin', 'Dexrazoxane').
drug_interaction('Acetyldigitoxin', 'Esmolol').
drug_interaction('Acetyldigitoxin', 'Megestrol acetate').
drug_interaction('Acetyldigitoxin', 'Mesalazine').
drug_interaction('Acetyldigitoxin', 'Moxifloxacin').
drug_interaction('Acetyldigitoxin', 'Octreotide').
drug_interaction('Acetyldigitoxin', 'Sorafenib').
drug_interaction('Acetyldigitoxin', 'Succinylcholine').
drug_interaction('Acetyldigitoxin', 'Timolol').
drug_interaction('Acetyldigitoxin', 'Tositumomab').
drug_interaction('Acetyldigitoxin', 'Verteporfin').
drug_interaction('Acetyldigitoxin', 'Vindesine').
drug_interaction('Acetyldigitoxin', 'Vitamin A').
drug_interaction('Betamethasone', 'Calcitriol').
drug_interaction('Betamethasone', 'Chlorotrianisene').
drug_interaction('Betamethasone', 'Fluvoxamine').
drug_interaction('Betamethasone', 'Gramicidin D').
drug_interaction('Betamethasone', 'Indomethacin').
drug_interaction('Betamethasone', 'Ketorolac').
drug_interaction('Betamethasone', 'Lidocaine').
drug_interaction('Betamethasone', 'Megestrol acetate').
drug_interaction('Betamethasone', 'Mesalazine').
drug_interaction('Betamethasone', 'Moxifloxacin').
drug_interaction('Betamethasone', 'Omeprazole').
drug_interaction('Betamethasone', 'Progesterone').
drug_interaction('Betamethasone', 'Sorafenib').
drug_interaction('Betamethasone', 'Tenoxicam').
drug_interaction('Betamethasone', 'Triflupromazine').
drug_interaction('Betamethasone', 'Trimethoprim').
drug_interaction('Menadione', 'Ropinirole').
drug_interaction('Menadione', 'Theophylline').
drug_interaction('Promazine', 'Pyrimethamine').
drug_interaction('Promazine', 'Ropinirole').
drug_interaction('Promazine', 'Secobarbital').
drug_interaction('Promazine', 'Sorafenib').
drug_interaction('Promazine', 'Temazepam').
drug_interaction('Promazine', 'Theophylline').
drug_interaction('Promazine', 'Timolol').
drug_interaction('Promazine', 'Triflupromazine').
drug_interaction('Promazine', 'Trimethoprim').
drug_interaction('Promazine', 'Zolpidem').
drug_interaction('Theophylline', 'Timolol').
drug_interaction('Theophylline', 'Trimethoprim').
drug_interaction('Theophylline', 'Zolpidem').
drug_interaction('Alfuzosin', 'Clozapine').
drug_interaction('Alfuzosin', 'Dipivefrin').
drug_interaction('Alfuzosin', 'Esmolol').
drug_interaction('Alfuzosin', 'Fluvoxamine').
drug_interaction('Alfuzosin', 'Moxifloxacin').
drug_interaction('Alfuzosin', 'Nitroprusside').
drug_interaction('Alfuzosin', 'Norepinephrine').
drug_interaction('Alfuzosin', 'Promazine').
drug_interaction('Alfuzosin', 'Timolol').
drug_interaction('Tenoxicam', 'Timolol').
drug_interaction('Tenoxicam', 'Trimethoprim').
drug_interaction('Tenoxicam', 'Zoledronic acid').
drug_interaction('Progesterone', 'Promazine').
drug_interaction('Progesterone', 'Pyrimethamine').
drug_interaction('Progesterone', 'Ropinirole').
drug_interaction('Progesterone', 'Secobarbital').
drug_interaction('Progesterone', 'Sorafenib').
drug_interaction('Progesterone', 'Theophylline').
drug_interaction('Progesterone', 'Timolol').
drug_interaction('Progesterone', 'Triflupromazine').
drug_interaction('Progesterone', 'Trimethoprim').
drug_interaction('Moxifloxacin', 'Octreotide').
drug_interaction('Moxifloxacin', 'Promazine').
drug_interaction('Moxifloxacin', 'Sorafenib').
drug_interaction('Moxifloxacin', 'Tenoxicam').
drug_interaction('Moxifloxacin', 'Theophylline').
drug_interaction('Moxifloxacin', 'Trimethoprim').
drug_interaction('Aminohippuric acid', 'Betamethasone').
drug_interaction('Aminohippuric acid', 'Clozapine').
drug_interaction('Aminohippuric acid', 'Indomethacin').
drug_interaction('Aminohippuric acid', 'Progesterone').
drug_interaction('Aminohippuric acid', 'Sorafenib').
drug_interaction('Aminohippuric acid', 'Timolol').
drug_interaction('Sorafenib', 'Temazepam').
drug_interaction('Sorafenib', 'Tenoxicam').
drug_interaction('Sorafenib', 'Theophylline').
drug_interaction('Sorafenib', 'Timolol').
drug_interaction('Sorafenib', 'Triflupromazine').
drug_interaction('Sorafenib', 'Trimethoprim').
drug_interaction('Sorafenib', 'Zolpidem').
drug_interaction('Chlorambucil', 'Clozapine').
drug_interaction('Chlorotrianisene', 'Diflorasone').
drug_interaction('Chlorotrianisene', 'Flunisolide').
drug_interaction('Chlorotrianisene', 'Ropinirole').
drug_interaction('Chlorotrianisene', 'Secobarbital').
drug_interaction('Chlorotrianisene', 'Theophylline').
drug_interaction('Temazepam', 'Theophylline').
drug_interaction('Temazepam', 'Triflupromazine').
drug_interaction('Temazepam', 'Trimethoprim').
drug_interaction('Temazepam', 'Zolpidem').
drug_interaction('Adalimumab', 'Anakinra').
drug_interaction('Adalimumab', 'Theophylline').
drug_interaction('Dipivefrin', 'Esmolol').
drug_interaction('Dipivefrin', 'Timolol').
drug_interaction('Fluvoxamine', 'Hydromorphone').
drug_interaction('Fluvoxamine', 'Indomethacin').
drug_interaction('Fluvoxamine', 'Lidocaine').
drug_interaction('Fluvoxamine', 'Menadione').
drug_interaction('Fluvoxamine', 'Nabilone').
drug_interaction('Fluvoxamine', 'Nitrofural').
drug_interaction('Fluvoxamine', 'Octreotide').
drug_interaction('Fluvoxamine', 'Omeprazole').
drug_interaction('Fluvoxamine', 'Pramipexole').
drug_interaction('Fluvoxamine', 'Progesterone').
drug_interaction('Fluvoxamine', 'Promazine').
drug_interaction('Fluvoxamine', 'Ropinirole').
drug_interaction('Fluvoxamine', 'Secobarbital').
drug_interaction('Fluvoxamine', 'Sorafenib').
drug_interaction('Fluvoxamine', 'Temazepam').
drug_interaction('Fluvoxamine', 'Tenoxicam').
drug_interaction('Fluvoxamine', 'Theophylline').
drug_interaction('Fluvoxamine', 'Thiethylperazine').
drug_interaction('Fluvoxamine', 'Timolol').
drug_interaction('Fluvoxamine', 'Triflupromazine').
drug_interaction('Fluvoxamine', 'Trimethoprim').
drug_interaction('Fluvoxamine', 'Vindesine').
drug_interaction('Fluvoxamine', 'Zolpidem').
drug_interaction('Omeprazole', 'Progesterone').
drug_interaction('Omeprazole', 'Promazine').
drug_interaction('Omeprazole', 'Pyrimethamine').
drug_interaction('Omeprazole', 'Ropinirole').
drug_interaction('Omeprazole', 'Secobarbital').
drug_interaction('Omeprazole', 'Sorafenib').
drug_interaction('Omeprazole', 'Temazepam').
drug_interaction('Omeprazole', 'Tenoxicam').
drug_interaction('Omeprazole', 'Theophylline').
drug_interaction('Omeprazole', 'Timolol').
drug_interaction('Omeprazole', 'Trimethoprim').
drug_interaction('Omeprazole', 'Zoledronic acid').
drug_interaction('Omeprazole', 'Zolpidem').
drug_interaction('Mesalazine', 'Moxifloxacin').
drug_interaction('Mesalazine', 'Octreotide').
drug_interaction('Mesalazine', 'Omeprazole').
drug_interaction('Mesalazine', 'Tenoxicam').
drug_interaction('Mesalazine', 'Timolol').
drug_interaction('Mesalazine', 'Zoledronic acid').
drug_interaction('Ethopropazine', 'Glucagon recombinant').
drug_interaction('Ethopropazine', 'Hydromorphone').
drug_interaction('Ethopropazine', 'Nabilone').
drug_interaction('Ethopropazine', 'Procyclidine').
drug_interaction('Pramipexole', 'Promazine').
drug_interaction('Pramipexole', 'Ropinirole').
drug_interaction('Pramipexole', 'Secobarbital').
drug_interaction('Pramipexole', 'Temazepam').
drug_interaction('Pramipexole', 'Timolol').
drug_interaction('Pramipexole', 'Triflupromazine').
drug_interaction('Pramipexole', 'Zolpidem').
drug_interaction('Indomethacin', 'Ketorolac').
drug_interaction('Indomethacin', 'Lidocaine').
drug_interaction('Indomethacin', 'Megestrol acetate').
drug_interaction('Indomethacin', 'Mesalazine').
drug_interaction('Indomethacin', 'Moxifloxacin').
drug_interaction('Indomethacin', 'Omeprazole').
drug_interaction('Indomethacin', 'Progesterone').
drug_interaction('Indomethacin', 'Pyrimethamine').
drug_interaction('Indomethacin', 'Secobarbital').
drug_interaction('Indomethacin', 'Sorafenib').
drug_interaction('Indomethacin', 'Tenoxicam').
drug_interaction('Indomethacin', 'Timolol').
drug_interaction('Indomethacin', 'Triflupromazine').
drug_interaction('Indomethacin', 'Trimethoprim').
drug_interaction('Indomethacin', 'Zoledronic acid').
drug_interaction('Interferon alfacon-1', 'Theophylline').
drug_interaction('Glucagon recombinant', 'Indomethacin').
drug_interaction('Glucagon recombinant', 'Procyclidine').
drug_interaction('Adapalene', 'Amikacin').
drug_interaction('Adapalene', 'Betamethasone').
drug_interaction('Adapalene', 'Chlorotrianisene').
drug_interaction('Adapalene', 'Desmopressin').
drug_interaction('Adapalene', 'Desogestrel').
drug_interaction('Adapalene', 'Diflorasone').
drug_interaction('Adapalene', 'Esmolol').
drug_interaction('Adapalene', 'Flunisolide').
drug_interaction('Adapalene', 'Indomethacin').
drug_interaction('Adapalene', 'Ketorolac').
drug_interaction('Adapalene', 'Mesalazine').
drug_interaction('Adapalene', 'Moxifloxacin').
drug_interaction('Adapalene', 'Tenoxicam').
drug_interaction('Adapalene', 'Timolol').
drug_interaction('Adapalene', 'Vitamin A').
drug_interaction('Adapalene', 'Zoledronic acid').
drug_interaction('Pyrimethamine', 'Temazepam').
drug_interaction('Pyrimethamine', 'Tenoxicam').
drug_interaction('Pyrimethamine', 'Theophylline').
drug_interaction('Pyrimethamine', 'Thiethylperazine').
drug_interaction('Pyrimethamine', 'Triflupromazine').
drug_interaction('Pyrimethamine', 'Trimethoprim').
drug_interaction('Pyrimethamine', 'Zolpidem').
drug_interaction('Triflupromazine', 'Trimethoprim').
drug_interaction('Triflupromazine', 'Zolpidem').
drug_interaction('Norepinephrine', 'Timolol').
drug_interaction('Desmopressin', 'Fluvoxamine').
drug_interaction('Desmopressin', 'Hydromorphone').
drug_interaction('Desmopressin', 'Indomethacin').
drug_interaction('Desmopressin', 'Ketorolac').
drug_interaction('Desmopressin', 'Mesalazine').
drug_interaction('Desmopressin', 'Tenoxicam').
drug_interaction('Megestrol acetate', 'Progesterone').
drug_interaction('Megestrol acetate', 'Sorafenib').
drug_interaction('Megestrol acetate', 'Timolol').
drug_interaction('Bleomycin', 'Filgrastim').
drug_interaction('Desogestrel', 'Secobarbital').
drug_interaction('Gramicidin D', 'Indomethacin').
drug_interaction('Gramicidin D', 'Progesterone').
drug_interaction('Gramicidin D', 'Sorafenib').
drug_interaction('Gramicidin D', 'Timolol').
drug_interaction('Benzatropine', 'Clozapine').
drug_interaction('Benzatropine', 'Ethopropazine').
drug_interaction('Benzatropine', 'Fluvoxamine').
drug_interaction('Benzatropine', 'Glucagon recombinant').
drug_interaction('Benzatropine', 'Hydromorphone').
drug_interaction('Benzatropine', 'Nabilone').
drug_interaction('Benzatropine', 'Omeprazole').
drug_interaction('Benzatropine', 'Procyclidine').
drug_interaction('Benzatropine', 'Promazine').
drug_interaction('Benzatropine', 'Ropinirole').
drug_interaction('Amikacin', 'Dicloxacillin').
drug_interaction('Amikacin', 'Indomethacin').
drug_interaction('Amikacin', 'Ketorolac').
drug_interaction('Amikacin', 'Mesalazine').
drug_interaction('Amikacin', 'Succinylcholine').
drug_interaction('Amikacin', 'Tenoxicam').
drug_interaction('Amikacin', 'Zoledronic acid').
drug_interaction('Clozapine', 'Dexrazoxane').
drug_interaction('Clozapine', 'Esmolol').
drug_interaction('Clozapine', 'Fluvoxamine').
drug_interaction('Clozapine', 'Gramicidin D').
drug_interaction('Clozapine', 'Hydromorphone').
drug_interaction('Clozapine', 'Ibritumomab tiuxetan').
drug_interaction('Clozapine', 'Indomethacin').
drug_interaction('Clozapine', 'Interferon alfacon-1').
drug_interaction('Clozapine', 'Lidocaine').
drug_interaction('Clozapine', 'Megestrol acetate').
drug_interaction('Clozapine', 'Moxifloxacin').
drug_interaction('Clozapine', 'Nabilone').
drug_interaction('Clozapine', 'Nitrofural').
drug_interaction('Clozapine', 'Nitroprusside').
drug_interaction('Clozapine', 'Octreotide').
drug_interaction('Clozapine', 'Omeprazole').
drug_interaction('Clozapine', 'Peginterferon alfa-2a').
drug_interaction('Clozapine', 'Pramipexole').
drug_interaction('Clozapine', 'Progesterone').
drug_interaction('Clozapine', 'Promazine').
drug_interaction('Clozapine', 'Pyrimethamine').
drug_interaction('Clozapine', 'Ropinirole').
drug_interaction('Clozapine', 'Secobarbital').
drug_interaction('Clozapine', 'Sorafenib').
drug_interaction('Clozapine', 'Temazepam').
drug_interaction('Clozapine', 'Theophylline').
drug_interaction('Clozapine', 'Timolol').
drug_interaction('Clozapine', 'Tositumomab').
drug_interaction('Clozapine', 'Triflupromazine').
drug_interaction('Clozapine', 'Trimethoprim').
drug_interaction('Clozapine', 'Vindesine').
drug_interaction('Clozapine', 'Zolpidem').
drug_interaction('Nitrofural', 'Promazine').
drug_interaction('Nitrofural', 'Ropinirole').
drug_interaction('Alprazolam', 'Cetirizine').
drug_interaction('Alprazolam', 'Chlorzoxazone').
drug_interaction('Alprazolam', 'Clozapine').
drug_interaction('Alprazolam', 'Fluvoxamine').
drug_interaction('Alprazolam', 'Hydromorphone').
drug_interaction('Alprazolam', 'Lidocaine').
drug_interaction('Alprazolam', 'Nabilone').
drug_interaction('Alprazolam', 'Omeprazole').
drug_interaction('Alprazolam', 'Pramipexole').
drug_interaction('Alprazolam', 'Promazine').
drug_interaction('Alprazolam', 'Pyrimethamine').
drug_interaction('Alprazolam', 'Ropinirole').
drug_interaction('Alprazolam', 'Secobarbital').
drug_interaction('Alprazolam', 'Sorafenib').
drug_interaction('Alprazolam', 'Temazepam').
drug_interaction('Alprazolam', 'Theophylline').
drug_interaction('Alprazolam', 'Triflupromazine').
drug_interaction('Alprazolam', 'Trimethoprim').
drug_interaction('Alprazolam', 'Zolpidem').
drug_interaction('Flunisolide', 'Fluvoxamine').
drug_interaction('Flunisolide', 'Indomethacin').
drug_interaction('Flunisolide', 'Ketorolac').
drug_interaction('Flunisolide', 'Mesalazine').
drug_interaction('Flunisolide', 'Moxifloxacin').
drug_interaction('Flunisolide', 'Tenoxicam').
drug_interaction('Thiethylperazine', 'Timolol').
drug_interaction('Thiethylperazine', 'Trimethoprim').
drug_interaction('Ketorolac', 'Mesalazine').
drug_interaction('Ketorolac', 'Moxifloxacin').
drug_interaction('Ketorolac', 'Tenoxicam').
drug_interaction('Ketorolac', 'Timolol').
drug_interaction('Ketorolac', 'Zoledronic acid').
drug_interaction('Abciximab', 'Adapalene').
drug_interaction('Abciximab', 'Chlorotrianisene').
drug_interaction('Abciximab', 'Desogestrel').
drug_interaction('Abciximab', 'Ibritumomab tiuxetan').
drug_interaction('Abciximab', 'Indomethacin').
drug_interaction('Abciximab', 'Ketorolac').
drug_interaction('Abciximab', 'Megestrol acetate').
drug_interaction('Abciximab', 'Mesalazine').
drug_interaction('Abciximab', 'Progesterone').
drug_interaction('Abciximab', 'Tenoxicam').
drug_interaction('Abciximab', 'Tositumomab').
drug_interaction('Esmolol', 'Carbachol').
drug_interaction('Timolol', 'Carbachol').
drug_interaction('Indomethacin', 'Esmolol').
drug_interaction('Ketorolac', 'Esmolol').
drug_interaction('Lidocaine', 'Esmolol').
drug_interaction('Mesalazine', 'Esmolol').
drug_interaction('Nabilone', 'Esmolol').
drug_interaction('Nitroprusside', 'Esmolol').
drug_interaction('Norepinephrine', 'Esmolol').
drug_interaction('Octreotide', 'Esmolol').
drug_interaction('Pramipexole', 'Esmolol').
drug_interaction('Promazine', 'Esmolol').
drug_interaction('Ropinirole', 'Esmolol').
drug_interaction('Secobarbital', 'Esmolol').
drug_interaction('Tenoxicam', 'Esmolol').
drug_interaction('Theophylline', 'Esmolol').
drug_interaction('Thiethylperazine', 'Esmolol').
drug_interaction('Timolol', 'Esmolol').
drug_interaction('Triflupromazine', 'Esmolol').
drug_interaction('Clozapine', 'Chlorzoxazone').
drug_interaction('Fluvoxamine', 'Chlorzoxazone').
drug_interaction('Hydromorphone', 'Chlorzoxazone').
drug_interaction('Lidocaine', 'Chlorzoxazone').
drug_interaction('Nabilone', 'Chlorzoxazone').
drug_interaction('Pramipexole', 'Chlorzoxazone').
drug_interaction('Promazine', 'Chlorzoxazone').
drug_interaction('Ropinirole', 'Chlorzoxazone').
drug_interaction('Secobarbital', 'Chlorzoxazone').
drug_interaction('Temazepam', 'Chlorzoxazone').
drug_interaction('Theophylline', 'Chlorzoxazone').
drug_interaction('Triflupromazine', 'Chlorzoxazone').
drug_interaction('Zolpidem', 'Chlorzoxazone').
drug_interaction('Lidocaine', 'Hydromorphone').
drug_interaction('Nabilone', 'Hydromorphone').
drug_interaction('Omeprazole', 'Hydromorphone').
drug_interaction('Pramipexole', 'Hydromorphone').
drug_interaction('Procyclidine', 'Hydromorphone').
drug_interaction('Promazine', 'Hydromorphone').
drug_interaction('Pyrimethamine', 'Hydromorphone').
drug_interaction('Ropinirole', 'Hydromorphone').
drug_interaction('Secobarbital', 'Hydromorphone').
drug_interaction('Sorafenib', 'Hydromorphone').
drug_interaction('Succinylcholine', 'Hydromorphone').
drug_interaction('Temazepam', 'Hydromorphone').
drug_interaction('Thiethylperazine', 'Hydromorphone').
drug_interaction('Triflupromazine', 'Hydromorphone').
drug_interaction('Trimethoprim', 'Hydromorphone').
drug_interaction('Zolpidem', 'Hydromorphone').
drug_interaction('Zolpidem', 'Trimethoprim').
drug_interaction('Pramipexole', 'Nitroprusside').
drug_interaction('Ropinirole', 'Nitroprusside').
drug_interaction('Secobarbital', 'Nitroprusside').
drug_interaction('Timolol', 'Nitroprusside').
drug_interaction('Sorafenib', 'Secobarbital').
drug_interaction('Temazepam', 'Secobarbital').
drug_interaction('Tenoxicam', 'Secobarbital').
drug_interaction('Theophylline', 'Secobarbital').
drug_interaction('Timolol', 'Secobarbital').
drug_interaction('Triflupromazine', 'Secobarbital').
drug_interaction('Trimethoprim', 'Secobarbital').
drug_interaction('Zolpidem', 'Secobarbital').
drug_interaction('Secobarbital', 'Ropinirole').
drug_interaction('Temazepam', 'Ropinirole').
drug_interaction('Theophylline', 'Ropinirole').
drug_interaction('Timolol', 'Ropinirole').
drug_interaction('Triflupromazine', 'Ropinirole').
drug_interaction('Zolpidem', 'Ropinirole').
drug_interaction('Theophylline', 'Peginterferon alfa-2a').
drug_interaction('Triflupromazine', 'Timolol').
drug_interaction('Trimethoprim', 'Timolol').
drug_interaction('Nitroprusside', 'Nabilone').
drug_interaction('Norepinephrine', 'Nabilone').
drug_interaction('Pramipexole', 'Nabilone').
drug_interaction('Procyclidine', 'Nabilone').
drug_interaction('Promazine', 'Nabilone').
drug_interaction('Ropinirole', 'Nabilone').
drug_interaction('Secobarbital', 'Nabilone').
drug_interaction('Temazepam', 'Nabilone').
drug_interaction('Timolol', 'Nabilone').
drug_interaction('Triflupromazine', 'Nabilone').
drug_interaction('Zolpidem', 'Nabilone').
drug_interaction('Promazine', 'Octreotide').
drug_interaction('Timolol', 'Octreotide').
drug_interaction('Chlorzoxazone', 'Cetirizine').
drug_interaction('Clozapine', 'Cetirizine').
drug_interaction('Fluvoxamine', 'Cetirizine').
drug_interaction('Hydromorphone', 'Cetirizine').
drug_interaction('Lidocaine', 'Cetirizine').
drug_interaction('Nabilone', 'Cetirizine').
drug_interaction('Pramipexole', 'Cetirizine').
drug_interaction('Promazine', 'Cetirizine').
drug_interaction('Ropinirole', 'Cetirizine').
drug_interaction('Secobarbital', 'Cetirizine').
drug_interaction('Temazepam', 'Cetirizine').
drug_interaction('Triflupromazine', 'Cetirizine').
drug_interaction('Zolpidem', 'Cetirizine').
drug_interaction('Diflorasone', 'Calcitriol').
drug_interaction('Flunisolide', 'Calcitriol').
drug_interaction('Fluvoxamine', 'Calcitriol').
drug_interaction('Menadione', 'Lidocaine').
drug_interaction('Nabilone', 'Lidocaine').
drug_interaction('Omeprazole', 'Lidocaine').
drug_interaction('Pramipexole', 'Lidocaine').
drug_interaction('Progesterone', 'Lidocaine').
drug_interaction('Promazine', 'Lidocaine').
drug_interaction('Pyrimethamine', 'Lidocaine').
drug_interaction('Ropinirole', 'Lidocaine').
drug_interaction('Secobarbital', 'Lidocaine').
drug_interaction('Sorafenib', 'Lidocaine').
drug_interaction('Temazepam', 'Lidocaine').
drug_interaction('Theophylline', 'Lidocaine').
drug_interaction('Timolol', 'Lidocaine').
drug_interaction('Triflupromazine', 'Lidocaine').
drug_interaction('Trimethoprim', 'Lidocaine').
drug_interaction('Zolpidem', 'Lidocaine').
drug_interaction('Indomethacin', 'Diflorasone').
drug_interaction('Ketorolac', 'Diflorasone').
drug_interaction('Mesalazine', 'Diflorasone').
drug_interaction('Moxifloxacin', 'Diflorasone').
drug_interaction('Tenoxicam', 'Diflorasone').
drug_interaction('Amikacin', 'Acetyldigitoxin').
drug_interaction('Bleomycin', 'Acetyldigitoxin').
drug_interaction('Calcitriol', 'Acetyldigitoxin').
drug_interaction('Chlorambucil', 'Acetyldigitoxin').
drug_interaction('Chlorotrianisene', 'Acetyldigitoxin').
drug_interaction('Dexrazoxane', 'Acetyldigitoxin').
drug_interaction('Esmolol', 'Acetyldigitoxin').
drug_interaction('Megestrol acetate', 'Acetyldigitoxin').
drug_interaction('Mesalazine', 'Acetyldigitoxin').
drug_interaction('Moxifloxacin', 'Acetyldigitoxin').
drug_interaction('Octreotide', 'Acetyldigitoxin').
drug_interaction('Sorafenib', 'Acetyldigitoxin').
drug_interaction('Succinylcholine', 'Acetyldigitoxin').
drug_interaction('Timolol', 'Acetyldigitoxin').
drug_interaction('Tositumomab', 'Acetyldigitoxin').
drug_interaction('Verteporfin', 'Acetyldigitoxin').
drug_interaction('Vindesine', 'Acetyldigitoxin').
drug_interaction('Vitamin A', 'Acetyldigitoxin').
drug_interaction('Calcitriol', 'Betamethasone').
drug_interaction('Chlorotrianisene', 'Betamethasone').
drug_interaction('Fluvoxamine', 'Betamethasone').
drug_interaction('Gramicidin D', 'Betamethasone').
drug_interaction('Indomethacin', 'Betamethasone').
drug_interaction('Ketorolac', 'Betamethasone').
drug_interaction('Lidocaine', 'Betamethasone').
drug_interaction('Megestrol acetate', 'Betamethasone').
drug_interaction('Mesalazine', 'Betamethasone').
drug_interaction('Moxifloxacin', 'Betamethasone').
drug_interaction('Omeprazole', 'Betamethasone').
drug_interaction('Progesterone', 'Betamethasone').
drug_interaction('Sorafenib', 'Betamethasone').
drug_interaction('Tenoxicam', 'Betamethasone').
drug_interaction('Triflupromazine', 'Betamethasone').
drug_interaction('Trimethoprim', 'Betamethasone').
drug_interaction('Ropinirole', 'Menadione').
drug_interaction('Theophylline', 'Menadione').
drug_interaction('Pyrimethamine', 'Promazine').
drug_interaction('Ropinirole', 'Promazine').
drug_interaction('Secobarbital', 'Promazine').
drug_interaction('Sorafenib', 'Promazine').
drug_interaction('Temazepam', 'Promazine').
drug_interaction('Theophylline', 'Promazine').
drug_interaction('Timolol', 'Promazine').
drug_interaction('Triflupromazine', 'Promazine').
drug_interaction('Trimethoprim', 'Promazine').
drug_interaction('Zolpidem', 'Promazine').
drug_interaction('Timolol', 'Theophylline').
drug_interaction('Trimethoprim', 'Theophylline').
drug_interaction('Zolpidem', 'Theophylline').
drug_interaction('Clozapine', 'Alfuzosin').
drug_interaction('Dipivefrin', 'Alfuzosin').
drug_interaction('Esmolol', 'Alfuzosin').
drug_interaction('Fluvoxamine', 'Alfuzosin').
drug_interaction('Moxifloxacin', 'Alfuzosin').
drug_interaction('Nitroprusside', 'Alfuzosin').
drug_interaction('Norepinephrine', 'Alfuzosin').
drug_interaction('Promazine', 'Alfuzosin').
drug_interaction('Timolol', 'Alfuzosin').
drug_interaction('Timolol', 'Tenoxicam').
drug_interaction('Trimethoprim', 'Tenoxicam').
drug_interaction('Zoledronic acid', 'Tenoxicam').
drug_interaction('Promazine', 'Progesterone').
drug_interaction('Pyrimethamine', 'Progesterone').
drug_interaction('Ropinirole', 'Progesterone').
drug_interaction('Secobarbital', 'Progesterone').
drug_interaction('Sorafenib', 'Progesterone').
drug_interaction('Theophylline', 'Progesterone').
drug_interaction('Timolol', 'Progesterone').
drug_interaction('Triflupromazine', 'Progesterone').
drug_interaction('Trimethoprim', 'Progesterone').
drug_interaction('Octreotide', 'Moxifloxacin').
drug_interaction('Promazine', 'Moxifloxacin').
drug_interaction('Sorafenib', 'Moxifloxacin').
drug_interaction('Tenoxicam', 'Moxifloxacin').
drug_interaction('Theophylline', 'Moxifloxacin').
drug_interaction('Trimethoprim', 'Moxifloxacin').
drug_interaction('Betamethasone', 'Aminohippuric acid').
drug_interaction('Clozapine', 'Aminohippuric acid').
drug_interaction('Indomethacin', 'Aminohippuric acid').
drug_interaction('Progesterone', 'Aminohippuric acid').
drug_interaction('Sorafenib', 'Aminohippuric acid').
drug_interaction('Timolol', 'Aminohippuric acid').
drug_interaction('Temazepam', 'Sorafenib').
drug_interaction('Tenoxicam', 'Sorafenib').
drug_interaction('Theophylline', 'Sorafenib').
drug_interaction('Timolol', 'Sorafenib').
drug_interaction('Triflupromazine', 'Sorafenib').
drug_interaction('Trimethoprim', 'Sorafenib').
drug_interaction('Zolpidem', 'Sorafenib').
drug_interaction('Clozapine', 'Chlorambucil').
drug_interaction('Diflorasone', 'Chlorotrianisene').
drug_interaction('Flunisolide', 'Chlorotrianisene').
drug_interaction('Ropinirole', 'Chlorotrianisene').
drug_interaction('Secobarbital', 'Chlorotrianisene').
drug_interaction('Theophylline', 'Chlorotrianisene').
drug_interaction('Theophylline', 'Temazepam').
drug_interaction('Triflupromazine', 'Temazepam').
drug_interaction('Trimethoprim', 'Temazepam').
drug_interaction('Zolpidem', 'Temazepam').
drug_interaction('Anakinra', 'Adalimumab').
drug_interaction('Theophylline', 'Adalimumab').
drug_interaction('Esmolol', 'Dipivefrin').
drug_interaction('Timolol', 'Dipivefrin').
drug_interaction('Hydromorphone', 'Fluvoxamine').
drug_interaction('Indomethacin', 'Fluvoxamine').
drug_interaction('Lidocaine', 'Fluvoxamine').
drug_interaction('Menadione', 'Fluvoxamine').
drug_interaction('Nabilone', 'Fluvoxamine').
drug_interaction('Nitrofural', 'Fluvoxamine').
drug_interaction('Octreotide', 'Fluvoxamine').
drug_interaction('Omeprazole', 'Fluvoxamine').
drug_interaction('Pramipexole', 'Fluvoxamine').
drug_interaction('Progesterone', 'Fluvoxamine').
drug_interaction('Promazine', 'Fluvoxamine').
drug_interaction('Ropinirole', 'Fluvoxamine').
drug_interaction('Secobarbital', 'Fluvoxamine').
drug_interaction('Sorafenib', 'Fluvoxamine').
drug_interaction('Temazepam', 'Fluvoxamine').
drug_interaction('Tenoxicam', 'Fluvoxamine').
drug_interaction('Theophylline', 'Fluvoxamine').
drug_interaction('Thiethylperazine', 'Fluvoxamine').
drug_interaction('Timolol', 'Fluvoxamine').
drug_interaction('Triflupromazine', 'Fluvoxamine').
drug_interaction('Trimethoprim', 'Fluvoxamine').
drug_interaction('Vindesine', 'Fluvoxamine').
drug_interaction('Zolpidem', 'Fluvoxamine').
drug_interaction('Progesterone', 'Omeprazole').
drug_interaction('Promazine', 'Omeprazole').
drug_interaction('Pyrimethamine', 'Omeprazole').
drug_interaction('Ropinirole', 'Omeprazole').
drug_interaction('Secobarbital', 'Omeprazole').
drug_interaction('Sorafenib', 'Omeprazole').
drug_interaction('Temazepam', 'Omeprazole').
drug_interaction('Tenoxicam', 'Omeprazole').
drug_interaction('Theophylline', 'Omeprazole').
drug_interaction('Timolol', 'Omeprazole').
drug_interaction('Trimethoprim', 'Omeprazole').
drug_interaction('Zoledronic acid', 'Omeprazole').
drug_interaction('Zolpidem', 'Omeprazole').
drug_interaction('Moxifloxacin', 'Mesalazine').
drug_interaction('Octreotide', 'Mesalazine').
drug_interaction('Omeprazole', 'Mesalazine').
drug_interaction('Tenoxicam', 'Mesalazine').
drug_interaction('Timolol', 'Mesalazine').
drug_interaction('Zoledronic acid', 'Mesalazine').
drug_interaction('Glucagon recombinant', 'Ethopropazine').
drug_interaction('Hydromorphone', 'Ethopropazine').
drug_interaction('Nabilone', 'Ethopropazine').
drug_interaction('Procyclidine', 'Ethopropazine').
drug_interaction('Promazine', 'Pramipexole').
drug_interaction('Ropinirole', 'Pramipexole').
drug_interaction('Secobarbital', 'Pramipexole').
drug_interaction('Temazepam', 'Pramipexole').
drug_interaction('Timolol', 'Pramipexole').
drug_interaction('Triflupromazine', 'Pramipexole').
drug_interaction('Zolpidem', 'Pramipexole').
drug_interaction('Ketorolac', 'Indomethacin').
drug_interaction('Lidocaine', 'Indomethacin').
drug_interaction('Megestrol acetate', 'Indomethacin').
drug_interaction('Mesalazine', 'Indomethacin').
drug_interaction('Moxifloxacin', 'Indomethacin').
drug_interaction('Omeprazole', 'Indomethacin').
drug_interaction('Progesterone', 'Indomethacin').
drug_interaction('Pyrimethamine', 'Indomethacin').
drug_interaction('Secobarbital', 'Indomethacin').
drug_interaction('Sorafenib', 'Indomethacin').
drug_interaction('Tenoxicam', 'Indomethacin').
drug_interaction('Timolol', 'Indomethacin').
drug_interaction('Triflupromazine', 'Indomethacin').
drug_interaction('Trimethoprim', 'Indomethacin').
drug_interaction('Zoledronic acid', 'Indomethacin').
drug_interaction('Theophylline', 'Interferon alfacon-1').
drug_interaction('Indomethacin', 'Glucagon recombinant').
drug_interaction('Procyclidine', 'Glucagon recombinant').
drug_interaction('Amikacin', 'Adapalene').
drug_interaction('Betamethasone', 'Adapalene').
drug_interaction('Chlorotrianisene', 'Adapalene').
drug_interaction('Desmopressin', 'Adapalene').
drug_interaction('Desogestrel', 'Adapalene').
drug_interaction('Diflorasone', 'Adapalene').
drug_interaction('Esmolol', 'Adapalene').
drug_interaction('Flunisolide', 'Adapalene').
drug_interaction('Indomethacin', 'Adapalene').
drug_interaction('Ketorolac', 'Adapalene').
drug_interaction('Mesalazine', 'Adapalene').
drug_interaction('Moxifloxacin', 'Adapalene').
drug_interaction('Tenoxicam', 'Adapalene').
drug_interaction('Timolol', 'Adapalene').
drug_interaction('Vitamin A', 'Adapalene').
drug_interaction('Zoledronic acid', 'Adapalene').
drug_interaction('Temazepam', 'Pyrimethamine').
drug_interaction('Tenoxicam', 'Pyrimethamine').
drug_interaction('Theophylline', 'Pyrimethamine').
drug_interaction('Thiethylperazine', 'Pyrimethamine').
drug_interaction('Triflupromazine', 'Pyrimethamine').
drug_interaction('Trimethoprim', 'Pyrimethamine').
drug_interaction('Zolpidem', 'Pyrimethamine').
drug_interaction('Trimethoprim', 'Triflupromazine').
drug_interaction('Zolpidem', 'Triflupromazine').
drug_interaction('Timolol', 'Norepinephrine').
drug_interaction('Fluvoxamine', 'Desmopressin').
drug_interaction('Hydromorphone', 'Desmopressin').
drug_interaction('Indomethacin', 'Desmopressin').
drug_interaction('Ketorolac', 'Desmopressin').
drug_interaction('Mesalazine', 'Desmopressin').
drug_interaction('Tenoxicam', 'Desmopressin').
drug_interaction('Progesterone', 'Megestrol acetate').
drug_interaction('Sorafenib', 'Megestrol acetate').
drug_interaction('Timolol', 'Megestrol acetate').
drug_interaction('Filgrastim', 'Bleomycin').
drug_interaction('Secobarbital', 'Desogestrel').
drug_interaction('Indomethacin', 'Gramicidin D').
drug_interaction('Progesterone', 'Gramicidin D').
drug_interaction('Sorafenib', 'Gramicidin D').
drug_interaction('Timolol', 'Gramicidin D').
drug_interaction('Clozapine', 'Benzatropine').
drug_interaction('Ethopropazine', 'Benzatropine').
drug_interaction('Fluvoxamine', 'Benzatropine').
drug_interaction('Glucagon recombinant', 'Benzatropine').
drug_interaction('Hydromorphone', 'Benzatropine').
drug_interaction('Nabilone', 'Benzatropine').
drug_interaction('Omeprazole', 'Benzatropine').
drug_interaction('Procyclidine', 'Benzatropine').
drug_interaction('Promazine', 'Benzatropine').
drug_interaction('Ropinirole', 'Benzatropine').
drug_interaction('Dicloxacillin', 'Amikacin').
drug_interaction('Indomethacin', 'Amikacin').
drug_interaction('Ketorolac', 'Amikacin').
drug_interaction('Mesalazine', 'Amikacin').
drug_interaction('Succinylcholine', 'Amikacin').
drug_interaction('Tenoxicam', 'Amikacin').
drug_interaction('Zoledronic acid', 'Amikacin').
drug_interaction('Dexrazoxane', 'Clozapine').
drug_interaction('Esmolol', 'Clozapine').
drug_interaction('Fluvoxamine', 'Clozapine').
drug_interaction('Gramicidin D', 'Clozapine').
drug_interaction('Hydromorphone', 'Clozapine').
drug_interaction('Ibritumomab tiuxetan', 'Clozapine').
drug_interaction('Indomethacin', 'Clozapine').
drug_interaction('Interferon alfacon-1', 'Clozapine').
drug_interaction('Lidocaine', 'Clozapine').
drug_interaction('Megestrol acetate', 'Clozapine').
drug_interaction('Moxifloxacin', 'Clozapine').
drug_interaction('Nabilone', 'Clozapine').
drug_interaction('Nitrofural', 'Clozapine').
drug_interaction('Nitroprusside', 'Clozapine').
drug_interaction('Octreotide', 'Clozapine').
drug_interaction('Omeprazole', 'Clozapine').
drug_interaction('Peginterferon alfa-2a', 'Clozapine').
drug_interaction('Pramipexole', 'Clozapine').
drug_interaction('Progesterone', 'Clozapine').
drug_interaction('Promazine', 'Clozapine').
drug_interaction('Pyrimethamine', 'Clozapine').
drug_interaction('Ropinirole', 'Clozapine').
drug_interaction('Secobarbital', 'Clozapine').
drug_interaction('Sorafenib', 'Clozapine').
drug_interaction('Temazepam', 'Clozapine').
drug_interaction('Theophylline', 'Clozapine').
drug_interaction('Timolol', 'Clozapine').
drug_interaction('Tositumomab', 'Clozapine').
drug_interaction('Triflupromazine', 'Clozapine').
drug_interaction('Trimethoprim', 'Clozapine').
drug_interaction('Vindesine', 'Clozapine').
drug_interaction('Zolpidem', 'Clozapine').
drug_interaction('Promazine', 'Nitrofural').
drug_interaction('Ropinirole', 'Nitrofural').
drug_interaction('Cetirizine', 'Alprazolam').
drug_interaction('Chlorzoxazone', 'Alprazolam').
drug_interaction('Clozapine', 'Alprazolam').
drug_interaction('Fluvoxamine', 'Alprazolam').
drug_interaction('Hydromorphone', 'Alprazolam').
drug_interaction('Lidocaine', 'Alprazolam').
drug_interaction('Nabilone', 'Alprazolam').
drug_interaction('Omeprazole', 'Alprazolam').
drug_interaction('Pramipexole', 'Alprazolam').
drug_interaction('Promazine', 'Alprazolam').
drug_interaction('Pyrimethamine', 'Alprazolam').
drug_interaction('Ropinirole', 'Alprazolam').
drug_interaction('Secobarbital', 'Alprazolam').
drug_interaction('Sorafenib', 'Alprazolam').
drug_interaction('Temazepam', 'Alprazolam').
drug_interaction('Theophylline', 'Alprazolam').
drug_interaction('Triflupromazine', 'Alprazolam').
drug_interaction('Trimethoprim', 'Alprazolam').
drug_interaction('Zolpidem', 'Alprazolam').
drug_interaction('Fluvoxamine', 'Flunisolide').
drug_interaction('Indomethacin', 'Flunisolide').
drug_interaction('Ketorolac', 'Flunisolide').
drug_interaction('Mesalazine', 'Flunisolide').
drug_interaction('Moxifloxacin', 'Flunisolide').
drug_interaction('Tenoxicam', 'Flunisolide').
drug_interaction('Timolol', 'Thiethylperazine').
drug_interaction('Trimethoprim', 'Thiethylperazine').
drug_interaction('Mesalazine', 'Ketorolac').
drug_interaction('Moxifloxacin', 'Ketorolac').
drug_interaction('Tenoxicam', 'Ketorolac').
drug_interaction('Timolol', 'Ketorolac').
drug_interaction('Zoledronic acid', 'Ketorolac').
drug_interaction('Adapalene', 'Abciximab').
drug_interaction('Chlorotrianisene', 'Abciximab').
drug_interaction('Desogestrel', 'Abciximab').
drug_interaction('Ibritumomab tiuxetan', 'Abciximab').
drug_interaction('Indomethacin', 'Abciximab').
drug_interaction('Ketorolac', 'Abciximab').
drug_interaction('Megestrol acetate', 'Abciximab').
drug_interaction('Mesalazine', 'Abciximab').
drug_interaction('Progesterone', 'Abciximab').
drug_interaction('Tenoxicam', 'Abciximab').
drug_interaction('Tositumomab', 'Abciximab').

