
drug_interaction('Argatroban', 'Doxycycline').
drug_interaction('Argatroban', 'Indinavir').
drug_interaction('Argatroban', 'Milrinone').
drug_interaction('Argatroban', 'Pethidine').
drug_interaction('Argatroban', 'Sildenafil').
drug_interaction('Argatroban', 'Tenecteplase').
drug_interaction('Argatroban', 'Tositumomab').
drug_interaction('Argatroban', 'Treprostinil').
drug_interaction('Chlorzoxazone', 'Cholecalciferol').
drug_interaction('Chlorzoxazone', 'Cimetidine').
drug_interaction('Chlorzoxazone', 'Dexbrompheniramine').
drug_interaction('Chlorzoxazone', 'Doxycycline').
drug_interaction('Chlorzoxazone', 'Ethchlorvynol').
drug_interaction('Chlorzoxazone', 'Hydromorphone').
drug_interaction('Chlorzoxazone', 'Indinavir').
drug_interaction('Chlorzoxazone', 'Loratadine').
drug_interaction('Chlorzoxazone', 'Loxapine').
drug_interaction('Chlorzoxazone', 'Methohexital').
drug_interaction('Chlorzoxazone', 'Pethidine').
drug_interaction('Chlorzoxazone', 'Pregabalin').
drug_interaction('Chlorzoxazone', 'Ropinirole').
drug_interaction('Chlorzoxazone', 'Secobarbital').
drug_interaction('Chlorzoxazone', 'Sildenafil').
drug_interaction('Chlorzoxazone', 'Tramadol').
drug_interaction('Palonosetron', 'Pethidine').
drug_interaction('Palonosetron', 'Ropinirole').
drug_interaction('Palonosetron', 'Sildenafil').
drug_interaction('Palonosetron', 'Tramadol').
drug_interaction('Palonosetron', 'Zolmitriptan').
drug_interaction('Amitriptyline', 'Amphetamine').
drug_interaction('Amitriptyline', 'Argatroban').
drug_interaction('Amitriptyline', 'Buspirone').
drug_interaction('Amitriptyline', 'Chlordiazepoxide').
drug_interaction('Amitriptyline', 'Chlorpromazine').
drug_interaction('Amitriptyline', 'Chlorzoxazone').
drug_interaction('Amitriptyline', 'Cholecalciferol').
drug_interaction('Amitriptyline', 'Cimetidine').
drug_interaction('Amitriptyline', 'Dexbrompheniramine').
drug_interaction('Amitriptyline', 'Doxycycline').
drug_interaction('Amitriptyline', 'Ethchlorvynol').
drug_interaction('Amitriptyline', 'Hydromorphone').
drug_interaction('Amitriptyline', 'Indinavir').
drug_interaction('Amitriptyline', 'Lenalidomide').
drug_interaction('Amitriptyline', 'Liothyronine').
drug_interaction('Amitriptyline', 'Loratadine').
drug_interaction('Amitriptyline', 'Loxapine').
drug_interaction('Amitriptyline', 'Methohexital').
drug_interaction('Amitriptyline', 'Palonosetron').
drug_interaction('Amitriptyline', 'Pethidine').
drug_interaction('Amitriptyline', 'Pregabalin').
drug_interaction('Amitriptyline', 'Ramipril').
drug_interaction('Amitriptyline', 'Ropinirole').
drug_interaction('Amitriptyline', 'Secobarbital').
drug_interaction('Amitriptyline', 'Sildenafil').
drug_interaction('Amitriptyline', 'Streptozocin').
drug_interaction('Amitriptyline', 'Sulfadiazine').
drug_interaction('Amitriptyline', 'Tramadol').
drug_interaction('Amitriptyline', 'Valsartan').
drug_interaction('Amitriptyline', 'Zolmitriptan').
drug_interaction('Oxiconazole', 'Pregabalin').
drug_interaction('Oxiconazole', 'Sucralfate').
drug_interaction('Ergocalciferol', 'Indinavir').
drug_interaction('Ergocalciferol', 'Sildenafil').
drug_interaction('Ergocalciferol', 'Sucralfate').
drug_interaction('Chlordiazepoxide', 'Chlorpromazine').
drug_interaction('Chlordiazepoxide', 'Chlorzoxazone').
drug_interaction('Chlordiazepoxide', 'Cholecalciferol').
drug_interaction('Chlordiazepoxide', 'Cimetidine').
drug_interaction('Chlordiazepoxide', 'Dexbrompheniramine').
drug_interaction('Chlordiazepoxide', 'Doxycycline').
drug_interaction('Chlordiazepoxide', 'Ethchlorvynol').
drug_interaction('Chlordiazepoxide', 'Hydromorphone').
drug_interaction('Chlordiazepoxide', 'Indinavir').
drug_interaction('Chlordiazepoxide', 'Loratadine').
drug_interaction('Chlordiazepoxide', 'Loxapine').
drug_interaction('Chlordiazepoxide', 'Methohexital').
drug_interaction('Chlordiazepoxide', 'Pethidine').
drug_interaction('Chlordiazepoxide', 'Pregabalin').
drug_interaction('Chlordiazepoxide', 'Ropinirole').
drug_interaction('Chlordiazepoxide', 'Secobarbital').
drug_interaction('Chlordiazepoxide', 'Sildenafil').
drug_interaction('Chlordiazepoxide', 'Tramadol').
drug_interaction('Tramadol', 'Zolmitriptan').
drug_interaction('Muromonab', 'Natalizumab').
drug_interaction('Calcium Acetate', 'Cholecalciferol').
drug_interaction('Calcium Acetate', 'Doxycycline').
drug_interaction('Calcium Acetate', 'Ergocalciferol').
drug_interaction('Calcium Acetate', 'Liothyronine').
drug_interaction('Calcium Acetate', 'Nimodipine').
drug_interaction('Calcium Acetate', 'Pregabalin').
drug_interaction('Ropinirole', 'Secobarbital').
drug_interaction('Ropinirole', 'Sildenafil').
drug_interaction('Ropinirole', 'Tramadol').
drug_interaction('Ropinirole', 'Valsartan').
drug_interaction('Ropinirole', 'Zolmitriptan').
drug_interaction('Allopurinol', 'Ramipril').
drug_interaction('Epirubicin', 'Metocurine Iodide').
drug_interaction('Epirubicin', 'Natalizumab').
drug_interaction('Epirubicin', 'Succinylcholine').
drug_interaction('Chlorpromazine', 'Chlorzoxazone').
drug_interaction('Chlorpromazine', 'Cholecalciferol').
drug_interaction('Chlorpromazine', 'Cimetidine').
drug_interaction('Chlorpromazine', 'Dexbrompheniramine').
drug_interaction('Chlorpromazine', 'Doxycycline').
drug_interaction('Chlorpromazine', 'Esmolol').
drug_interaction('Chlorpromazine', 'Ethchlorvynol').
drug_interaction('Chlorpromazine', 'Hydromorphone').
drug_interaction('Chlorpromazine', 'Indinavir').
drug_interaction('Chlorpromazine', 'Lenalidomide').
drug_interaction('Chlorpromazine', 'Liothyronine').
drug_interaction('Chlorpromazine', 'Loratadine').
drug_interaction('Chlorpromazine', 'Loxapine').
drug_interaction('Chlorpromazine', 'Methohexital').
drug_interaction('Chlorpromazine', 'Nimodipine').
drug_interaction('Chlorpromazine', 'Palonosetron').
drug_interaction('Chlorpromazine', 'Pethidine').
drug_interaction('Chlorpromazine', 'Pregabalin').
drug_interaction('Chlorpromazine', 'Ramipril').
drug_interaction('Chlorpromazine', 'Ropinirole').
drug_interaction('Chlorpromazine', 'Secobarbital').
drug_interaction('Chlorpromazine', 'Sildenafil').
drug_interaction('Chlorpromazine', 'Streptozocin').
drug_interaction('Chlorpromazine', 'Tramadol').
drug_interaction('Chlorpromazine', 'Treprostinil').
drug_interaction('Chlorpromazine', 'Valsartan').
drug_interaction('Chlorpromazine', 'Zolmitriptan').
drug_interaction('Acitretin', 'Doxycycline').
drug_interaction('L-Phenylalanine', 'Natalizumab').
drug_interaction('Doxycycline', 'Ergocalciferol').
drug_interaction('Doxycycline', 'Hydromorphone').
drug_interaction('Doxycycline', 'Indinavir').
drug_interaction('Doxycycline', 'Loratadine').
drug_interaction('Doxycycline', 'Methohexital').
drug_interaction('Doxycycline', 'Metocurine Iodide').
drug_interaction('Doxycycline', 'Nimodipine').
drug_interaction('Doxycycline', 'Palonosetron').
drug_interaction('Doxycycline', 'Pethidine').
drug_interaction('Doxycycline', 'Ropinirole').
drug_interaction('Doxycycline', 'Secobarbital').
drug_interaction('Doxycycline', 'Sildenafil').
drug_interaction('Doxycycline', 'Succinylcholine').
drug_interaction('Doxycycline', 'Sucralfate').
drug_interaction('Doxycycline', 'Sulfadiazine').
drug_interaction('Doxycycline', 'Teniposide').
drug_interaction('Doxycycline', 'Tramadol').
drug_interaction('Methohexital', 'Nimodipine').
drug_interaction('Methohexital', 'Pethidine').
drug_interaction('Methohexital', 'Pregabalin').
drug_interaction('Methohexital', 'Pyridoxine').
drug_interaction('Methohexital', 'Ramipril').
drug_interaction('Methohexital', 'Ropinirole').
drug_interaction('Methohexital', 'Secobarbital').
drug_interaction('Methohexital', 'Teniposide').
drug_interaction('Methohexital', 'Tramadol').
drug_interaction('Methohexital', 'Valsartan').
drug_interaction('Carmustine', 'Cimetidine').
drug_interaction('Carmustine', 'Natalizumab').
drug_interaction('Carmustine', 'Ropinirole').
drug_interaction('Nimodipine', 'Oxiconazole').
drug_interaction('Nimodipine', 'Ramipril').
drug_interaction('Nimodipine', 'Ropinirole').
drug_interaction('Nimodipine', 'Secobarbital').
drug_interaction('Nimodipine', 'Sildenafil').
drug_interaction('Nimodipine', 'Treprostinil').
drug_interaction('Nimodipine', 'Valsartan').
drug_interaction('Natalizumab', 'Streptozocin').
drug_interaction('Natalizumab', 'Teniposide').
drug_interaction('Natalizumab', 'Tositumomab').
drug_interaction('Alpha-1-proteinase inhibitor', 'Alprazolam').
drug_interaction('Alpha-1-proteinase inhibitor', 'Amitriptyline').
drug_interaction('Alpha-1-proteinase inhibitor', 'Pethidine').
drug_interaction('Alpha-1-proteinase inhibitor', 'Sildenafil').
drug_interaction('Acetaminophen', 'Amitriptyline').
drug_interaction('Acetaminophen', 'Buspirone').
drug_interaction('Acetaminophen', 'Chlorpromazine').
drug_interaction('Acetaminophen', 'Cholecalciferol').
drug_interaction('Acetaminophen', 'Cimetidine').
drug_interaction('Acetaminophen', 'Doxycycline').
drug_interaction('Acetaminophen', 'Indinavir').
drug_interaction('Acetaminophen', 'Lenalidomide').
drug_interaction('Acetaminophen', 'Liothyronine').
drug_interaction('Acetaminophen', 'Loratadine').
drug_interaction('Acetaminophen', 'Methohexital').
drug_interaction('Acetaminophen', 'Ropinirole').
drug_interaction('Acetaminophen', 'Secobarbital').
drug_interaction('Acetaminophen', 'Sildenafil').
drug_interaction('Acetaminophen', 'Streptozocin').
drug_interaction('Acetaminophen', 'Sulfadiazine').
drug_interaction('Acetaminophen', 'Valsartan').
drug_interaction('Lenalidomide', 'Liothyronine').
drug_interaction('Lenalidomide', 'Loratadine').
drug_interaction('Lenalidomide', 'Natalizumab').
drug_interaction('Lenalidomide', 'Streptozocin').
drug_interaction('Indinavir', 'Lenalidomide').
drug_interaction('Indinavir', 'Liothyronine').
drug_interaction('Indinavir', 'Loratadine').
drug_interaction('Indinavir', 'Miglitol').
drug_interaction('Indinavir', 'Miglustat').
drug_interaction('Indinavir', 'Nimodipine').
drug_interaction('Indinavir', 'Oxiconazole').
drug_interaction('Indinavir', 'Palonosetron').
drug_interaction('Indinavir', 'Pethidine').
drug_interaction('Indinavir', 'Ropinirole').
drug_interaction('Indinavir', 'Sildenafil').
drug_interaction('Indinavir', 'Streptozocin').
drug_interaction('Indinavir', 'Sulfadiazine').
drug_interaction('Indinavir', 'Teniposide').
drug_interaction('Indinavir', 'Tramadol').
drug_interaction('Indinavir', 'Treprostinil').
drug_interaction('Indinavir', 'Valsartan').
drug_interaction('Streptozocin', 'Succinylcholine').
drug_interaction('Dexbrompheniramine', 'Ethchlorvynol').
drug_interaction('Dexbrompheniramine', 'Hydromorphone').
drug_interaction('Dexbrompheniramine', 'Loratadine').
drug_interaction('Dexbrompheniramine', 'Loxapine').
drug_interaction('Dexbrompheniramine', 'Methohexital').
drug_interaction('Dexbrompheniramine', 'Pethidine').
drug_interaction('Dexbrompheniramine', 'Pregabalin').
drug_interaction('Dexbrompheniramine', 'Ropinirole').
drug_interaction('Dexbrompheniramine', 'Secobarbital').
drug_interaction('Dexbrompheniramine', 'Tramadol').
drug_interaction('Loratadine', 'Loxapine').
drug_interaction('Loratadine', 'Methohexital').
drug_interaction('Loratadine', 'Pethidine').
drug_interaction('Loratadine', 'Pregabalin').
drug_interaction('Loratadine', 'Ropinirole').
drug_interaction('Loratadine', 'Secobarbital').
drug_interaction('Loratadine', 'Sildenafil').
drug_interaction('Loratadine', 'Sulfadiazine').
drug_interaction('Loratadine', 'Tramadol').
drug_interaction('Loratadine', 'Valsartan').
drug_interaction('Loxapine', 'Methohexital').
drug_interaction('Loxapine', 'Pethidine').
drug_interaction('Loxapine', 'Pregabalin').
drug_interaction('Loxapine', 'Ropinirole').
drug_interaction('Loxapine', 'Secobarbital').
drug_interaction('Loxapine', 'Tramadol').
drug_interaction('Loxapine', 'Zolmitriptan').
drug_interaction('Anti-thymocyte Globulin (Rabbit)', 'Natalizumab').
drug_interaction('Ethchlorvynol', 'Hydromorphone').
drug_interaction('Ethchlorvynol', 'Loratadine').
drug_interaction('Ethchlorvynol', 'Loxapine').
drug_interaction('Ethchlorvynol', 'Methohexital').
drug_interaction('Ethchlorvynol', 'Pethidine').
drug_interaction('Ethchlorvynol', 'Pregabalin').
drug_interaction('Ethchlorvynol', 'Ropinirole').
drug_interaction('Ethchlorvynol', 'Secobarbital').
drug_interaction('Ethchlorvynol', 'Tramadol').
drug_interaction('Alprazolam', 'Amitriptyline').
drug_interaction('Alprazolam', 'Argatroban').
drug_interaction('Alprazolam', 'Buspirone').
drug_interaction('Alprazolam', 'Chlordiazepoxide').
drug_interaction('Alprazolam', 'Chlorpromazine').
drug_interaction('Alprazolam', 'Chlorzoxazone').
drug_interaction('Alprazolam', 'Cholecalciferol').
drug_interaction('Alprazolam', 'Dexbrompheniramine').
drug_interaction('Alprazolam', 'Doxycycline').
drug_interaction('Alprazolam', 'Ethchlorvynol').
drug_interaction('Alprazolam', 'Hydromorphone').
drug_interaction('Alprazolam', 'Indinavir').
drug_interaction('Alprazolam', 'Loratadine').
drug_interaction('Alprazolam', 'Loxapine').
drug_interaction('Alprazolam', 'Methohexital').
drug_interaction('Alprazolam', 'Nimodipine').
drug_interaction('Alprazolam', 'Pethidine').
drug_interaction('Alprazolam', 'Pregabalin').
drug_interaction('Alprazolam', 'Ramipril').
drug_interaction('Alprazolam', 'Ropinirole').
drug_interaction('Alprazolam', 'Secobarbital').
drug_interaction('Alprazolam', 'Sildenafil').
drug_interaction('Alprazolam', 'Sulfadiazine').
drug_interaction('Alprazolam', 'Tramadol').
drug_interaction('Alprazolam', 'Valsartan').
drug_interaction('Ramipril', 'Ropinirole').
drug_interaction('Ramipril', 'Secobarbital').
drug_interaction('Ramipril', 'Sildenafil').
drug_interaction('Ramipril', 'Treprostinil').
drug_interaction('Ramipril', 'Valsartan').
drug_interaction('Sildenafil', 'Sulfadiazine').
drug_interaction('Sildenafil', 'Teniposide').
drug_interaction('Sildenafil', 'Tramadol').
drug_interaction('Sildenafil', 'Treprostinil').
drug_interaction('Sildenafil', 'Valsartan').
drug_interaction('Succinylcholine', 'Tramadol').
drug_interaction('Secobarbital', 'Sildenafil').
drug_interaction('Secobarbital', 'Sulfadiazine').
drug_interaction('Secobarbital', 'Teniposide').
drug_interaction('Secobarbital', 'Tramadol').
drug_interaction('Secobarbital', 'Treprostinil').
drug_interaction('Secobarbital', 'Valsartan').
drug_interaction('Milrinone', 'Tenecteplase').
drug_interaction('Milrinone', 'Tositumomab').
drug_interaction('Milrinone', 'Treprostinil').
drug_interaction('Alemtuzumab', 'Natalizumab').
drug_interaction('Treprostinil', 'Valsartan').
drug_interaction('Esmolol', 'Methohexital').
drug_interaction('Esmolol', 'Nimodipine').
drug_interaction('Esmolol', 'Ramipril').
drug_interaction('Esmolol', 'Ropinirole').
drug_interaction('Esmolol', 'Secobarbital').
drug_interaction('Esmolol', 'Valsartan').
drug_interaction('Hydromorphone', 'Indinavir').
drug_interaction('Hydromorphone', 'Loratadine').
drug_interaction('Hydromorphone', 'Loxapine').
drug_interaction('Hydromorphone', 'Methohexital').
drug_interaction('Hydromorphone', 'Pethidine').
drug_interaction('Hydromorphone', 'Pregabalin').
drug_interaction('Hydromorphone', 'Ropinirole').
drug_interaction('Hydromorphone', 'Secobarbital').
drug_interaction('Hydromorphone', 'Sildenafil').
drug_interaction('Hydromorphone', 'Succinylcholine').
drug_interaction('Hydromorphone', 'Sulfadiazine').
drug_interaction('Hydromorphone', 'Tramadol').
drug_interaction('Hydromorphone', 'Valsartan').
drug_interaction('Cimetidine', 'Epirubicin').
drug_interaction('Cimetidine', 'Hydromorphone').
drug_interaction('Cimetidine', 'Indinavir').
drug_interaction('Cimetidine', 'Lenalidomide').
drug_interaction('Cimetidine', 'Liothyronine').
drug_interaction('Cimetidine', 'Loratadine').
drug_interaction('Cimetidine', 'Nimodipine').
drug_interaction('Cimetidine', 'Oxiconazole').
drug_interaction('Cimetidine', 'Palonosetron').
drug_interaction('Cimetidine', 'Pethidine').
drug_interaction('Cimetidine', 'Pregabalin').
drug_interaction('Cimetidine', 'Sildenafil').
drug_interaction('Cimetidine', 'Streptozocin').
drug_interaction('Cimetidine', 'Teniposide').
drug_interaction('Cimetidine', 'Tramadol').
drug_interaction('Cimetidine', 'Zolmitriptan').
drug_interaction('Pregabalin', 'Ramipril').
drug_interaction('Pregabalin', 'Ropinirole').
drug_interaction('Pregabalin', 'Secobarbital').
drug_interaction('Pregabalin', 'Tramadol').
drug_interaction('Pethidine', 'Pregabalin').
drug_interaction('Pethidine', 'Ramipril').
drug_interaction('Pethidine', 'Ropinirole').
drug_interaction('Pethidine', 'Secobarbital').
drug_interaction('Pethidine', 'Sildenafil').
drug_interaction('Pethidine', 'Succinylcholine').
drug_interaction('Pethidine', 'Tramadol').
drug_interaction('Pethidine', 'Zolmitriptan').
drug_interaction('Dicloxacillin', 'Doxycycline').
drug_interaction('Dicloxacillin', 'Epirubicin').
drug_interaction('Dicloxacillin', 'Nimodipine').
drug_interaction('Dicloxacillin', 'Streptozocin').
drug_interaction('Cladribine', 'Natalizumab').
drug_interaction('Pyridoxine', 'Secobarbital').
drug_interaction('Sulfadiazine', 'Treprostinil').
drug_interaction('Sulfadiazine', 'Valsartan').
drug_interaction('Miglustat', 'Sulfadiazine').
drug_interaction('Botulinum Toxin Type B', 'Epirubicin').
drug_interaction('Botulinum Toxin Type B', 'Metocurine Iodide').
drug_interaction('Botulinum Toxin Type B', 'Streptozocin').
drug_interaction('Botulinum Toxin Type B', 'Succinylcholine').
drug_interaction('Metocurine Iodide', 'Streptozocin').
drug_interaction('Tenecteplase', 'Treprostinil').
drug_interaction('Cholecalciferol', 'Doxycycline').
drug_interaction('Cholecalciferol', 'Ergocalciferol').
drug_interaction('Cholecalciferol', 'Hydromorphone').
drug_interaction('Cholecalciferol', 'Indinavir').
drug_interaction('Cholecalciferol', 'Loratadine').
drug_interaction('Cholecalciferol', 'Oxiconazole').
drug_interaction('Cholecalciferol', 'Palonosetron').
drug_interaction('Cholecalciferol', 'Pethidine').
drug_interaction('Cholecalciferol', 'Sildenafil').
drug_interaction('Cholecalciferol', 'Sucralfate').
drug_interaction('Cholecalciferol', 'Sulfadiazine').
drug_interaction('Cholecalciferol', 'Teniposide').
drug_interaction('Cholecalciferol', 'Tramadol').
drug_interaction('Cholecalciferol', 'Treprostinil').
drug_interaction('Cholecalciferol', 'Valsartan').
drug_interaction('Sapropterin', 'Sildenafil').
drug_interaction('Efalizumab', 'Natalizumab').
drug_interaction('Gemtuzumab ozogamicin', 'Natalizumab').
drug_interaction('Amphetamine', 'Chlorpromazine').
drug_interaction('Amphetamine', 'Cholecalciferol').
drug_interaction('Amphetamine', 'Cimetidine').
drug_interaction('Amphetamine', 'Dexbrompheniramine').
drug_interaction('Amphetamine', 'Hydromorphone').
drug_interaction('Amphetamine', 'Indinavir').
drug_interaction('Amphetamine', 'Loratadine').
drug_interaction('Amphetamine', 'Loxapine').
drug_interaction('Amphetamine', 'Pethidine').
drug_interaction('Amphetamine', 'Ropinirole').
drug_interaction('Amphetamine', 'Tramadol').
drug_interaction('Amphetamine', 'Vitamin C').
drug_interaction('Alclometasone', 'Doxycycline').
drug_interaction('Alclometasone', 'Indinavir').
drug_interaction('Alclometasone', 'Sildenafil').
drug_interaction('Buspirone', 'Chlordiazepoxide').
drug_interaction('Buspirone', 'Chlorpromazine').
drug_interaction('Buspirone', 'Chlorzoxazone').
drug_interaction('Buspirone', 'Cholecalciferol').
drug_interaction('Buspirone', 'Cimetidine').
drug_interaction('Buspirone', 'Dexbrompheniramine').
drug_interaction('Buspirone', 'Doxycycline').
drug_interaction('Buspirone', 'Ethchlorvynol').
drug_interaction('Buspirone', 'Hydromorphone').
drug_interaction('Buspirone', 'Indinavir').
drug_interaction('Buspirone', 'Lenalidomide').
drug_interaction('Buspirone', 'Loratadine').
drug_interaction('Buspirone', 'Loxapine').
drug_interaction('Buspirone', 'Methohexital').
drug_interaction('Buspirone', 'Oxiconazole').
drug_interaction('Buspirone', 'Palonosetron').
drug_interaction('Buspirone', 'Pethidine').
drug_interaction('Buspirone', 'Pregabalin').
drug_interaction('Buspirone', 'Ropinirole').
drug_interaction('Buspirone', 'Secobarbital').
drug_interaction('Buspirone', 'Sildenafil').
drug_interaction('Buspirone', 'Tramadol').
drug_interaction('Buspirone', 'Zolmitriptan').
drug_interaction('Capreomycin', 'Epirubicin').
drug_interaction('Capreomycin', 'Metocurine Iodide').
drug_interaction('Capreomycin', 'Streptozocin').
drug_interaction('Capreomycin', 'Succinylcholine').
drug_interaction('Miglitol', 'Sulfadiazine').
drug_interaction('Doxycycline', 'Argatroban').
drug_interaction('Indinavir', 'Argatroban').
drug_interaction('Milrinone', 'Argatroban').
drug_interaction('Pethidine', 'Argatroban').
drug_interaction('Sildenafil', 'Argatroban').
drug_interaction('Tenecteplase', 'Argatroban').
drug_interaction('Tositumomab', 'Argatroban').
drug_interaction('Treprostinil', 'Argatroban').
drug_interaction('Cholecalciferol', 'Chlorzoxazone').
drug_interaction('Cimetidine', 'Chlorzoxazone').
drug_interaction('Dexbrompheniramine', 'Chlorzoxazone').
drug_interaction('Doxycycline', 'Chlorzoxazone').
drug_interaction('Ethchlorvynol', 'Chlorzoxazone').
drug_interaction('Hydromorphone', 'Chlorzoxazone').
drug_interaction('Indinavir', 'Chlorzoxazone').
drug_interaction('Loratadine', 'Chlorzoxazone').
drug_interaction('Loxapine', 'Chlorzoxazone').
drug_interaction('Methohexital', 'Chlorzoxazone').
drug_interaction('Pethidine', 'Chlorzoxazone').
drug_interaction('Pregabalin', 'Chlorzoxazone').
drug_interaction('Ropinirole', 'Chlorzoxazone').
drug_interaction('Secobarbital', 'Chlorzoxazone').
drug_interaction('Sildenafil', 'Chlorzoxazone').
drug_interaction('Tramadol', 'Chlorzoxazone').
drug_interaction('Pethidine', 'Palonosetron').
drug_interaction('Ropinirole', 'Palonosetron').
drug_interaction('Sildenafil', 'Palonosetron').
drug_interaction('Tramadol', 'Palonosetron').
drug_interaction('Zolmitriptan', 'Palonosetron').
drug_interaction('Amphetamine', 'Amitriptyline').
drug_interaction('Argatroban', 'Amitriptyline').
drug_interaction('Buspirone', 'Amitriptyline').
drug_interaction('Chlordiazepoxide', 'Amitriptyline').
drug_interaction('Chlorpromazine', 'Amitriptyline').
drug_interaction('Chlorzoxazone', 'Amitriptyline').
drug_interaction('Cholecalciferol', 'Amitriptyline').
drug_interaction('Cimetidine', 'Amitriptyline').
drug_interaction('Dexbrompheniramine', 'Amitriptyline').
drug_interaction('Doxycycline', 'Amitriptyline').
drug_interaction('Ethchlorvynol', 'Amitriptyline').
drug_interaction('Hydromorphone', 'Amitriptyline').
drug_interaction('Indinavir', 'Amitriptyline').
drug_interaction('Lenalidomide', 'Amitriptyline').
drug_interaction('Liothyronine', 'Amitriptyline').
drug_interaction('Loratadine', 'Amitriptyline').
drug_interaction('Loxapine', 'Amitriptyline').
drug_interaction('Methohexital', 'Amitriptyline').
drug_interaction('Palonosetron', 'Amitriptyline').
drug_interaction('Pethidine', 'Amitriptyline').
drug_interaction('Pregabalin', 'Amitriptyline').
drug_interaction('Ramipril', 'Amitriptyline').
drug_interaction('Ropinirole', 'Amitriptyline').
drug_interaction('Secobarbital', 'Amitriptyline').
drug_interaction('Sildenafil', 'Amitriptyline').
drug_interaction('Streptozocin', 'Amitriptyline').
drug_interaction('Sulfadiazine', 'Amitriptyline').
drug_interaction('Tramadol', 'Amitriptyline').
drug_interaction('Valsartan', 'Amitriptyline').
drug_interaction('Zolmitriptan', 'Amitriptyline').
drug_interaction('Pregabalin', 'Oxiconazole').
drug_interaction('Sucralfate', 'Oxiconazole').
drug_interaction('Indinavir', 'Ergocalciferol').
drug_interaction('Sildenafil', 'Ergocalciferol').
drug_interaction('Sucralfate', 'Ergocalciferol').
drug_interaction('Chlorpromazine', 'Chlordiazepoxide').
drug_interaction('Chlorzoxazone', 'Chlordiazepoxide').
drug_interaction('Cholecalciferol', 'Chlordiazepoxide').
drug_interaction('Cimetidine', 'Chlordiazepoxide').
drug_interaction('Dexbrompheniramine', 'Chlordiazepoxide').
drug_interaction('Doxycycline', 'Chlordiazepoxide').
drug_interaction('Ethchlorvynol', 'Chlordiazepoxide').
drug_interaction('Hydromorphone', 'Chlordiazepoxide').
drug_interaction('Indinavir', 'Chlordiazepoxide').
drug_interaction('Loratadine', 'Chlordiazepoxide').
drug_interaction('Loxapine', 'Chlordiazepoxide').
drug_interaction('Methohexital', 'Chlordiazepoxide').
drug_interaction('Pethidine', 'Chlordiazepoxide').
drug_interaction('Pregabalin', 'Chlordiazepoxide').
drug_interaction('Ropinirole', 'Chlordiazepoxide').
drug_interaction('Secobarbital', 'Chlordiazepoxide').
drug_interaction('Sildenafil', 'Chlordiazepoxide').
drug_interaction('Tramadol', 'Chlordiazepoxide').
drug_interaction('Zolmitriptan', 'Tramadol').
drug_interaction('Natalizumab', 'Muromonab').
drug_interaction('Cholecalciferol', 'Calcium Acetate').
drug_interaction('Doxycycline', 'Calcium Acetate').
drug_interaction('Ergocalciferol', 'Calcium Acetate').
drug_interaction('Liothyronine', 'Calcium Acetate').
drug_interaction('Nimodipine', 'Calcium Acetate').
drug_interaction('Pregabalin', 'Calcium Acetate').
drug_interaction('Secobarbital', 'Ropinirole').
drug_interaction('Sildenafil', 'Ropinirole').
drug_interaction('Tramadol', 'Ropinirole').
drug_interaction('Valsartan', 'Ropinirole').
drug_interaction('Zolmitriptan', 'Ropinirole').
drug_interaction('Ramipril', 'Allopurinol').
drug_interaction('Metocurine Iodide', 'Epirubicin').
drug_interaction('Natalizumab', 'Epirubicin').
drug_interaction('Succinylcholine', 'Epirubicin').
drug_interaction('Chlorzoxazone', 'Chlorpromazine').
drug_interaction('Cholecalciferol', 'Chlorpromazine').
drug_interaction('Cimetidine', 'Chlorpromazine').
drug_interaction('Dexbrompheniramine', 'Chlorpromazine').
drug_interaction('Doxycycline', 'Chlorpromazine').
drug_interaction('Esmolol', 'Chlorpromazine').
drug_interaction('Ethchlorvynol', 'Chlorpromazine').
drug_interaction('Hydromorphone', 'Chlorpromazine').
drug_interaction('Indinavir', 'Chlorpromazine').
drug_interaction('Lenalidomide', 'Chlorpromazine').
drug_interaction('Liothyronine', 'Chlorpromazine').
drug_interaction('Loratadine', 'Chlorpromazine').
drug_interaction('Loxapine', 'Chlorpromazine').
drug_interaction('Methohexital', 'Chlorpromazine').
drug_interaction('Nimodipine', 'Chlorpromazine').
drug_interaction('Palonosetron', 'Chlorpromazine').
drug_interaction('Pethidine', 'Chlorpromazine').
drug_interaction('Pregabalin', 'Chlorpromazine').
drug_interaction('Ramipril', 'Chlorpromazine').
drug_interaction('Ropinirole', 'Chlorpromazine').
drug_interaction('Secobarbital', 'Chlorpromazine').
drug_interaction('Sildenafil', 'Chlorpromazine').
drug_interaction('Streptozocin', 'Chlorpromazine').
drug_interaction('Tramadol', 'Chlorpromazine').
drug_interaction('Treprostinil', 'Chlorpromazine').
drug_interaction('Valsartan', 'Chlorpromazine').
drug_interaction('Zolmitriptan', 'Chlorpromazine').
drug_interaction('Doxycycline', 'Acitretin').
drug_interaction('Natalizumab', 'L-Phenylalanine').
drug_interaction('Ergocalciferol', 'Doxycycline').
drug_interaction('Hydromorphone', 'Doxycycline').
drug_interaction('Indinavir', 'Doxycycline').
drug_interaction('Loratadine', 'Doxycycline').
drug_interaction('Methohexital', 'Doxycycline').
drug_interaction('Metocurine Iodide', 'Doxycycline').
drug_interaction('Nimodipine', 'Doxycycline').
drug_interaction('Palonosetron', 'Doxycycline').
drug_interaction('Pethidine', 'Doxycycline').
drug_interaction('Ropinirole', 'Doxycycline').
drug_interaction('Secobarbital', 'Doxycycline').
drug_interaction('Sildenafil', 'Doxycycline').
drug_interaction('Succinylcholine', 'Doxycycline').
drug_interaction('Sucralfate', 'Doxycycline').
drug_interaction('Sulfadiazine', 'Doxycycline').
drug_interaction('Teniposide', 'Doxycycline').
drug_interaction('Tramadol', 'Doxycycline').
drug_interaction('Nimodipine', 'Methohexital').
drug_interaction('Pethidine', 'Methohexital').
drug_interaction('Pregabalin', 'Methohexital').
drug_interaction('Pyridoxine', 'Methohexital').
drug_interaction('Ramipril', 'Methohexital').
drug_interaction('Ropinirole', 'Methohexital').
drug_interaction('Secobarbital', 'Methohexital').
drug_interaction('Teniposide', 'Methohexital').
drug_interaction('Tramadol', 'Methohexital').
drug_interaction('Valsartan', 'Methohexital').
drug_interaction('Cimetidine', 'Carmustine').
drug_interaction('Natalizumab', 'Carmustine').
drug_interaction('Ropinirole', 'Carmustine').
drug_interaction('Oxiconazole', 'Nimodipine').
drug_interaction('Ramipril', 'Nimodipine').
drug_interaction('Ropinirole', 'Nimodipine').
drug_interaction('Secobarbital', 'Nimodipine').
drug_interaction('Sildenafil', 'Nimodipine').
drug_interaction('Treprostinil', 'Nimodipine').
drug_interaction('Valsartan', 'Nimodipine').
drug_interaction('Streptozocin', 'Natalizumab').
drug_interaction('Teniposide', 'Natalizumab').
drug_interaction('Tositumomab', 'Natalizumab').
drug_interaction('Alprazolam', 'Alpha-1-proteinase inhibitor').
drug_interaction('Amitriptyline', 'Alpha-1-proteinase inhibitor').
drug_interaction('Pethidine', 'Alpha-1-proteinase inhibitor').
drug_interaction('Sildenafil', 'Alpha-1-proteinase inhibitor').
drug_interaction('Amitriptyline', 'Acetaminophen').
drug_interaction('Buspirone', 'Acetaminophen').
drug_interaction('Chlorpromazine', 'Acetaminophen').
drug_interaction('Cholecalciferol', 'Acetaminophen').
drug_interaction('Cimetidine', 'Acetaminophen').
drug_interaction('Doxycycline', 'Acetaminophen').
drug_interaction('Indinavir', 'Acetaminophen').
drug_interaction('Lenalidomide', 'Acetaminophen').
drug_interaction('Liothyronine', 'Acetaminophen').
drug_interaction('Loratadine', 'Acetaminophen').
drug_interaction('Methohexital', 'Acetaminophen').
drug_interaction('Ropinirole', 'Acetaminophen').
drug_interaction('Secobarbital', 'Acetaminophen').
drug_interaction('Sildenafil', 'Acetaminophen').
drug_interaction('Streptozocin', 'Acetaminophen').
drug_interaction('Sulfadiazine', 'Acetaminophen').
drug_interaction('Valsartan', 'Acetaminophen').
drug_interaction('Liothyronine', 'Lenalidomide').
drug_interaction('Loratadine', 'Lenalidomide').
drug_interaction('Natalizumab', 'Lenalidomide').
drug_interaction('Streptozocin', 'Lenalidomide').
drug_interaction('Lenalidomide', 'Indinavir').
drug_interaction('Liothyronine', 'Indinavir').
drug_interaction('Loratadine', 'Indinavir').
drug_interaction('Miglitol', 'Indinavir').
drug_interaction('Miglustat', 'Indinavir').
drug_interaction('Nimodipine', 'Indinavir').
drug_interaction('Oxiconazole', 'Indinavir').
drug_interaction('Palonosetron', 'Indinavir').
drug_interaction('Pethidine', 'Indinavir').
drug_interaction('Ropinirole', 'Indinavir').
drug_interaction('Sildenafil', 'Indinavir').
drug_interaction('Streptozocin', 'Indinavir').
drug_interaction('Sulfadiazine', 'Indinavir').
drug_interaction('Teniposide', 'Indinavir').
drug_interaction('Tramadol', 'Indinavir').
drug_interaction('Treprostinil', 'Indinavir').
drug_interaction('Valsartan', 'Indinavir').
drug_interaction('Succinylcholine', 'Streptozocin').
drug_interaction('Ethchlorvynol', 'Dexbrompheniramine').
drug_interaction('Hydromorphone', 'Dexbrompheniramine').
drug_interaction('Loratadine', 'Dexbrompheniramine').
drug_interaction('Loxapine', 'Dexbrompheniramine').
drug_interaction('Methohexital', 'Dexbrompheniramine').
drug_interaction('Pethidine', 'Dexbrompheniramine').
drug_interaction('Pregabalin', 'Dexbrompheniramine').
drug_interaction('Ropinirole', 'Dexbrompheniramine').
drug_interaction('Secobarbital', 'Dexbrompheniramine').
drug_interaction('Tramadol', 'Dexbrompheniramine').
drug_interaction('Loxapine', 'Loratadine').
drug_interaction('Methohexital', 'Loratadine').
drug_interaction('Pethidine', 'Loratadine').
drug_interaction('Pregabalin', 'Loratadine').
drug_interaction('Ropinirole', 'Loratadine').
drug_interaction('Secobarbital', 'Loratadine').
drug_interaction('Sildenafil', 'Loratadine').
drug_interaction('Sulfadiazine', 'Loratadine').
drug_interaction('Tramadol', 'Loratadine').
drug_interaction('Valsartan', 'Loratadine').
drug_interaction('Methohexital', 'Loxapine').
drug_interaction('Pethidine', 'Loxapine').
drug_interaction('Pregabalin', 'Loxapine').
drug_interaction('Ropinirole', 'Loxapine').
drug_interaction('Secobarbital', 'Loxapine').
drug_interaction('Tramadol', 'Loxapine').
drug_interaction('Zolmitriptan', 'Loxapine').
drug_interaction('Natalizumab', 'Anti-thymocyte Globulin (Rabbit)').
drug_interaction('Hydromorphone', 'Ethchlorvynol').
drug_interaction('Loratadine', 'Ethchlorvynol').
drug_interaction('Loxapine', 'Ethchlorvynol').
drug_interaction('Methohexital', 'Ethchlorvynol').
drug_interaction('Pethidine', 'Ethchlorvynol').
drug_interaction('Pregabalin', 'Ethchlorvynol').
drug_interaction('Ropinirole', 'Ethchlorvynol').
drug_interaction('Secobarbital', 'Ethchlorvynol').
drug_interaction('Tramadol', 'Ethchlorvynol').
drug_interaction('Amitriptyline', 'Alprazolam').
drug_interaction('Argatroban', 'Alprazolam').
drug_interaction('Buspirone', 'Alprazolam').
drug_interaction('Chlordiazepoxide', 'Alprazolam').
drug_interaction('Chlorpromazine', 'Alprazolam').
drug_interaction('Chlorzoxazone', 'Alprazolam').
drug_interaction('Cholecalciferol', 'Alprazolam').
drug_interaction('Dexbrompheniramine', 'Alprazolam').
drug_interaction('Doxycycline', 'Alprazolam').
drug_interaction('Ethchlorvynol', 'Alprazolam').
drug_interaction('Hydromorphone', 'Alprazolam').
drug_interaction('Indinavir', 'Alprazolam').
drug_interaction('Loratadine', 'Alprazolam').
drug_interaction('Loxapine', 'Alprazolam').
drug_interaction('Methohexital', 'Alprazolam').
drug_interaction('Nimodipine', 'Alprazolam').
drug_interaction('Pethidine', 'Alprazolam').
drug_interaction('Pregabalin', 'Alprazolam').
drug_interaction('Ramipril', 'Alprazolam').
drug_interaction('Ropinirole', 'Alprazolam').
drug_interaction('Secobarbital', 'Alprazolam').
drug_interaction('Sildenafil', 'Alprazolam').
drug_interaction('Sulfadiazine', 'Alprazolam').
drug_interaction('Tramadol', 'Alprazolam').
drug_interaction('Valsartan', 'Alprazolam').
drug_interaction('Ropinirole', 'Ramipril').
drug_interaction('Secobarbital', 'Ramipril').
drug_interaction('Sildenafil', 'Ramipril').
drug_interaction('Treprostinil', 'Ramipril').
drug_interaction('Valsartan', 'Ramipril').
drug_interaction('Sulfadiazine', 'Sildenafil').
drug_interaction('Teniposide', 'Sildenafil').
drug_interaction('Tramadol', 'Sildenafil').
drug_interaction('Treprostinil', 'Sildenafil').
drug_interaction('Valsartan', 'Sildenafil').
drug_interaction('Tramadol', 'Succinylcholine').
drug_interaction('Sildenafil', 'Secobarbital').
drug_interaction('Sulfadiazine', 'Secobarbital').
drug_interaction('Teniposide', 'Secobarbital').
drug_interaction('Tramadol', 'Secobarbital').
drug_interaction('Treprostinil', 'Secobarbital').
drug_interaction('Valsartan', 'Secobarbital').
drug_interaction('Tenecteplase', 'Milrinone').
drug_interaction('Tositumomab', 'Milrinone').
drug_interaction('Treprostinil', 'Milrinone').
drug_interaction('Natalizumab', 'Alemtuzumab').
drug_interaction('Valsartan', 'Treprostinil').
drug_interaction('Methohexital', 'Esmolol').
drug_interaction('Nimodipine', 'Esmolol').
drug_interaction('Ramipril', 'Esmolol').
drug_interaction('Ropinirole', 'Esmolol').
drug_interaction('Secobarbital', 'Esmolol').
drug_interaction('Valsartan', 'Esmolol').
drug_interaction('Indinavir', 'Hydromorphone').
drug_interaction('Loratadine', 'Hydromorphone').
drug_interaction('Loxapine', 'Hydromorphone').
drug_interaction('Methohexital', 'Hydromorphone').
drug_interaction('Pethidine', 'Hydromorphone').
drug_interaction('Pregabalin', 'Hydromorphone').
drug_interaction('Ropinirole', 'Hydromorphone').
drug_interaction('Secobarbital', 'Hydromorphone').
drug_interaction('Sildenafil', 'Hydromorphone').
drug_interaction('Succinylcholine', 'Hydromorphone').
drug_interaction('Sulfadiazine', 'Hydromorphone').
drug_interaction('Tramadol', 'Hydromorphone').
drug_interaction('Valsartan', 'Hydromorphone').
drug_interaction('Epirubicin', 'Cimetidine').
drug_interaction('Hydromorphone', 'Cimetidine').
drug_interaction('Indinavir', 'Cimetidine').
drug_interaction('Lenalidomide', 'Cimetidine').
drug_interaction('Liothyronine', 'Cimetidine').
drug_interaction('Loratadine', 'Cimetidine').
drug_interaction('Nimodipine', 'Cimetidine').
drug_interaction('Oxiconazole', 'Cimetidine').
drug_interaction('Palonosetron', 'Cimetidine').
drug_interaction('Pethidine', 'Cimetidine').
drug_interaction('Pregabalin', 'Cimetidine').
drug_interaction('Sildenafil', 'Cimetidine').
drug_interaction('Streptozocin', 'Cimetidine').
drug_interaction('Teniposide', 'Cimetidine').
drug_interaction('Tramadol', 'Cimetidine').
drug_interaction('Zolmitriptan', 'Cimetidine').
drug_interaction('Ramipril', 'Pregabalin').
drug_interaction('Ropinirole', 'Pregabalin').
drug_interaction('Secobarbital', 'Pregabalin').
drug_interaction('Tramadol', 'Pregabalin').
drug_interaction('Pregabalin', 'Pethidine').
drug_interaction('Ramipril', 'Pethidine').
drug_interaction('Ropinirole', 'Pethidine').
drug_interaction('Secobarbital', 'Pethidine').
drug_interaction('Sildenafil', 'Pethidine').
drug_interaction('Succinylcholine', 'Pethidine').
drug_interaction('Tramadol', 'Pethidine').
drug_interaction('Zolmitriptan', 'Pethidine').
drug_interaction('Doxycycline', 'Dicloxacillin').
drug_interaction('Epirubicin', 'Dicloxacillin').
drug_interaction('Nimodipine', 'Dicloxacillin').
drug_interaction('Streptozocin', 'Dicloxacillin').
drug_interaction('Natalizumab', 'Cladribine').
drug_interaction('Secobarbital', 'Pyridoxine').
drug_interaction('Treprostinil', 'Sulfadiazine').
drug_interaction('Valsartan', 'Sulfadiazine').
drug_interaction('Sulfadiazine', 'Miglustat').
drug_interaction('Epirubicin', 'Botulinum Toxin Type B').
drug_interaction('Metocurine Iodide', 'Botulinum Toxin Type B').
drug_interaction('Streptozocin', 'Botulinum Toxin Type B').
drug_interaction('Succinylcholine', 'Botulinum Toxin Type B').
drug_interaction('Streptozocin', 'Metocurine Iodide').
drug_interaction('Treprostinil', 'Tenecteplase').
drug_interaction('Doxycycline', 'Cholecalciferol').
drug_interaction('Ergocalciferol', 'Cholecalciferol').
drug_interaction('Hydromorphone', 'Cholecalciferol').
drug_interaction('Indinavir', 'Cholecalciferol').
drug_interaction('Loratadine', 'Cholecalciferol').
drug_interaction('Oxiconazole', 'Cholecalciferol').
drug_interaction('Palonosetron', 'Cholecalciferol').
drug_interaction('Pethidine', 'Cholecalciferol').
drug_interaction('Sildenafil', 'Cholecalciferol').
drug_interaction('Sucralfate', 'Cholecalciferol').
drug_interaction('Sulfadiazine', 'Cholecalciferol').
drug_interaction('Teniposide', 'Cholecalciferol').
drug_interaction('Tramadol', 'Cholecalciferol').
drug_interaction('Treprostinil', 'Cholecalciferol').
drug_interaction('Valsartan', 'Cholecalciferol').
drug_interaction('Sildenafil', 'Sapropterin').
drug_interaction('Natalizumab', 'Efalizumab').
drug_interaction('Natalizumab', 'Gemtuzumab ozogamicin').
drug_interaction('Chlorpromazine', 'Amphetamine').
drug_interaction('Cholecalciferol', 'Amphetamine').
drug_interaction('Cimetidine', 'Amphetamine').
drug_interaction('Dexbrompheniramine', 'Amphetamine').
drug_interaction('Hydromorphone', 'Amphetamine').
drug_interaction('Indinavir', 'Amphetamine').
drug_interaction('Loratadine', 'Amphetamine').
drug_interaction('Loxapine', 'Amphetamine').
drug_interaction('Pethidine', 'Amphetamine').
drug_interaction('Ropinirole', 'Amphetamine').
drug_interaction('Tramadol', 'Amphetamine').
drug_interaction('Vitamin C', 'Amphetamine').
drug_interaction('Doxycycline', 'Alclometasone').
drug_interaction('Indinavir', 'Alclometasone').
drug_interaction('Sildenafil', 'Alclometasone').
drug_interaction('Chlordiazepoxide', 'Buspirone').
drug_interaction('Chlorpromazine', 'Buspirone').
drug_interaction('Chlorzoxazone', 'Buspirone').
drug_interaction('Cholecalciferol', 'Buspirone').
drug_interaction('Cimetidine', 'Buspirone').
drug_interaction('Dexbrompheniramine', 'Buspirone').
drug_interaction('Doxycycline', 'Buspirone').
drug_interaction('Ethchlorvynol', 'Buspirone').
drug_interaction('Hydromorphone', 'Buspirone').
drug_interaction('Indinavir', 'Buspirone').
drug_interaction('Lenalidomide', 'Buspirone').
drug_interaction('Loratadine', 'Buspirone').
drug_interaction('Loxapine', 'Buspirone').
drug_interaction('Methohexital', 'Buspirone').
drug_interaction('Oxiconazole', 'Buspirone').
drug_interaction('Palonosetron', 'Buspirone').
drug_interaction('Pethidine', 'Buspirone').
drug_interaction('Pregabalin', 'Buspirone').
drug_interaction('Ropinirole', 'Buspirone').
drug_interaction('Secobarbital', 'Buspirone').
drug_interaction('Sildenafil', 'Buspirone').
drug_interaction('Tramadol', 'Buspirone').
drug_interaction('Zolmitriptan', 'Buspirone').
drug_interaction('Epirubicin', 'Capreomycin').
drug_interaction('Metocurine Iodide', 'Capreomycin').
drug_interaction('Streptozocin', 'Capreomycin').
drug_interaction('Succinylcholine', 'Capreomycin').
drug_interaction('Sulfadiazine', 'Miglitol').

