
drug_interaction('Methadone', 'Mexiletine').
drug_interaction('Methadone', 'Oxyphenonium').
drug_interaction('Methadone', 'Oxytocin').
drug_interaction('Methadone', 'Palonosetron').
drug_interaction('Methadone', 'Pethidine').
drug_interaction('Methadone', 'Promazine').
drug_interaction('Methadone', 'Ritonavir').
drug_interaction('Methadone', 'Rosiglitazone').
drug_interaction('Methadone', 'Tolcapone').
drug_interaction('Methadone', 'Torasemide').
drug_interaction('Methadone', 'Trihexyphenidyl').
drug_interaction('Methadone', 'Vinorelbine').
drug_interaction('Methadone', 'Zidovudine').
drug_interaction('Methadone', 'Ziprasidone').
drug_interaction('Methadone', 'Zolpidem').
drug_interaction('Brimonidine', 'Chlordiazepoxide').
drug_interaction('Brimonidine', 'Chlorpromazine').
drug_interaction('Brimonidine', 'Cyproheptadine').
drug_interaction('Brimonidine', 'Digoxin').
drug_interaction('Brimonidine', 'Entacapone').
drug_interaction('Brimonidine', 'Ethchlorvynol').
drug_interaction('Brimonidine', 'Etomidate').
drug_interaction('Brimonidine', 'Haloperidol').
drug_interaction('Brimonidine', 'Hyaluronidase').
drug_interaction('Brimonidine', 'Imipramine').
drug_interaction('Brimonidine', 'Methadone').
drug_interaction('Brimonidine', 'Olmesartan').
drug_interaction('Brimonidine', 'Pethidine').
drug_interaction('Brimonidine', 'Promazine').
drug_interaction('Brimonidine', 'Ramipril').
drug_interaction('Brimonidine', 'Rituximab').
drug_interaction('Brimonidine', 'Tolcapone').
drug_interaction('Brimonidine', 'Torasemide').
drug_interaction('Brimonidine', 'Ziprasidone').
drug_interaction('Brimonidine', 'Zolpidem').
drug_interaction('Goserelin', 'Haloperidol').
drug_interaction('Goserelin', 'Imipramine').
drug_interaction('Goserelin', 'Insulin Glargine').
drug_interaction('Goserelin', 'Methadone').
drug_interaction('Goserelin', 'Miglitol').
drug_interaction('Goserelin', 'Oxytocin').
drug_interaction('Goserelin', 'Promazine').
drug_interaction('Goserelin', 'Ritonavir').
drug_interaction('Goserelin', 'Rosiglitazone').
drug_interaction('Goserelin', 'Ziprasidone').
drug_interaction('Ibritumomab tiuxetan', 'Natalizumab').
drug_interaction('Ibritumomab tiuxetan', 'Pimecrolimus').
drug_interaction('Calcium Gluceptate', 'Digoxin').
drug_interaction('Calcium Gluceptate', 'Enoxacin').
drug_interaction('Calcium Gluceptate', 'Levothyroxine').
drug_interaction('Abciximab', 'Aminosalicylic Acid').
drug_interaction('Abciximab', 'Anistreplase').
drug_interaction('Abciximab', 'Diethylstilbestrol').
drug_interaction('Abciximab', 'Etonogestrel').
drug_interaction('Abciximab', 'Ibritumomab tiuxetan').
drug_interaction('Abciximab', 'Megestrol acetate').
drug_interaction('Abciximab', 'Pimecrolimus').
drug_interaction('Abciximab', 'Rosiglitazone').
drug_interaction('Abciximab', 'Vitamin E').
drug_interaction('Bethanidine', 'Brimonidine').
drug_interaction('Bethanidine', 'Imipramine').
drug_interaction('Bethanidine', 'Olmesartan').
drug_interaction('Bethanidine', 'Ramipril').
drug_interaction('Bethanidine', 'Rituximab').
drug_interaction('Bethanidine', 'Torasemide').
drug_interaction('Flucloxacillin', 'Piperacillin').
drug_interaction('Flucloxacillin', 'Streptozocin').
drug_interaction('Flucloxacillin', 'Valrubicin').
drug_interaction('Mexiletine', 'Palonosetron').
drug_interaction('Mexiletine', 'Promazine').
drug_interaction('Mexiletine', 'Ritonavir').
drug_interaction('Mexiletine', 'Ziprasidone').
drug_interaction('Mexiletine', 'Zolpidem').
drug_interaction('Piperacillin', 'Streptozocin').
drug_interaction('Piperacillin', 'Valrubicin').
drug_interaction('Streptozocin', 'Torasemide').
drug_interaction('Streptozocin', 'Zidovudine').
drug_interaction('Oxytocin', 'Promazine').
drug_interaction('Oxytocin', 'Ziprasidone').
drug_interaction('Zidovudine', 'Ziprasidone').
drug_interaction('Etonogestrel', 'Insulin Glargine').
drug_interaction('Etonogestrel', 'Miglitol').
drug_interaction('Etonogestrel', 'Ritonavir').
drug_interaction('Etonogestrel', 'Rosiglitazone').
drug_interaction('Etonogestrel', 'Ziprasidone').
drug_interaction('Amsacrine', 'Betamethasone').
drug_interaction('Amsacrine', 'Bevacizumab').
drug_interaction('Amsacrine', 'Caffeine').
drug_interaction('Amsacrine', 'Chlorpromazine').
drug_interaction('Amsacrine', 'Darifenacin').
drug_interaction('Amsacrine', 'Diethylstilbestrol').
drug_interaction('Amsacrine', 'Digoxin').
drug_interaction('Amsacrine', 'Haloperidol').
drug_interaction('Amsacrine', 'Imipramine').
drug_interaction('Amsacrine', 'Methadone').
drug_interaction('Amsacrine', 'Natalizumab').
drug_interaction('Amsacrine', 'Pimecrolimus').
drug_interaction('Amsacrine', 'Promazine').
drug_interaction('Amsacrine', 'Ritonavir').
drug_interaction('Amsacrine', 'Zidovudine').
drug_interaction('Amsacrine', 'Ziprasidone').
drug_interaction('Phenoxymethylpenicillin', 'Streptozocin').
drug_interaction('Phenoxymethylpenicillin', 'Valrubicin').
drug_interaction('Gemtuzumab ozogamicin', 'Natalizumab').
drug_interaction('Gemtuzumab ozogamicin', 'Pimecrolimus').
drug_interaction('Aminosalicylic Acid', 'Anistreplase').
drug_interaction('Aminosalicylic Acid', 'Betamethasone').
drug_interaction('Aminosalicylic Acid', 'Hyaluronidase').
drug_interaction('Aminosalicylic Acid', 'Insulin Glargine').
drug_interaction('Aminosalicylic Acid', 'Miglitol').
drug_interaction('Aminosalicylic Acid', 'Ramipril').
drug_interaction('Aminosalicylic Acid', 'Rosiglitazone').
drug_interaction('Aminosalicylic Acid', 'Torasemide').
drug_interaction('Cyproheptadine', 'Entacapone').
drug_interaction('Cyproheptadine', 'Ethchlorvynol').
drug_interaction('Cyproheptadine', 'Etomidate').
drug_interaction('Cyproheptadine', 'Haloperidol').
drug_interaction('Cyproheptadine', 'Hyaluronidase').
drug_interaction('Cyproheptadine', 'Imipramine').
drug_interaction('Cyproheptadine', 'Methadone').
drug_interaction('Cyproheptadine', 'Pethidine').
drug_interaction('Cyproheptadine', 'Promazine').
drug_interaction('Cyproheptadine', 'Tolcapone').
drug_interaction('Cyproheptadine', 'Ziprasidone').
drug_interaction('Cyproheptadine', 'Zolpidem').
drug_interaction('Ziprasidone', 'Zolpidem').
drug_interaction('Digoxin', 'Enoxacin').
drug_interaction('Digoxin', 'Floxuridine').
drug_interaction('Digoxin', 'Flutamide').
drug_interaction('Digoxin', 'Gemtuzumab ozogamicin').
drug_interaction('Digoxin', 'Goserelin').
drug_interaction('Digoxin', 'Haloperidol').
drug_interaction('Digoxin', 'Imipramine').
drug_interaction('Digoxin', 'Levothyroxine').
drug_interaction('Digoxin', 'Megestrol acetate').
drug_interaction('Digoxin', 'Methadone').
drug_interaction('Digoxin', 'Pimecrolimus').
drug_interaction('Digoxin', 'Ramipril').
drug_interaction('Digoxin', 'Ritonavir').
drug_interaction('Digoxin', 'Rituximab').
drug_interaction('Digoxin', 'Streptozocin').
drug_interaction('Digoxin', 'Teniposide').
drug_interaction('Digoxin', 'Tioguanine').
drug_interaction('Digoxin', 'Torasemide').
drug_interaction('Digoxin', 'Valrubicin').
drug_interaction('Digoxin', 'Vinorelbine').
drug_interaction('Digoxin', 'Zidovudine').
drug_interaction('Digoxin', 'Ziprasidone').
drug_interaction('Levothyroxine', 'Ritonavir').
drug_interaction('Levothyroxine', 'Zidovudine').
drug_interaction('Levothyroxine', 'Ziprasidone').
drug_interaction('Teniposide', 'Ziprasidone').
drug_interaction('Miglitol', 'Ritonavir').
drug_interaction('Miglitol', 'Torasemide').
drug_interaction('Miglitol', 'Ziprasidone').
drug_interaction('Imipramine', 'Isoetarine').
drug_interaction('Imipramine', 'Levothyroxine').
drug_interaction('Imipramine', 'Megestrol acetate').
drug_interaction('Imipramine', 'Methadone').
drug_interaction('Imipramine', 'Mexiletine').
drug_interaction('Imipramine', 'Olmesartan').
drug_interaction('Imipramine', 'Palonosetron').
drug_interaction('Imipramine', 'Pethidine').
drug_interaction('Imipramine', 'Promazine').
drug_interaction('Imipramine', 'Ramipril').
drug_interaction('Imipramine', 'Ritonavir').
drug_interaction('Imipramine', 'Streptozocin').
drug_interaction('Imipramine', 'Tolcapone').
drug_interaction('Imipramine', 'Torasemide').
drug_interaction('Imipramine', 'Vinorelbine').
drug_interaction('Imipramine', 'Zidovudine').
drug_interaction('Imipramine', 'Ziprasidone').
drug_interaction('Imipramine', 'Zolpidem').
drug_interaction('Rosiglitazone', 'Torasemide').
drug_interaction('Rosiglitazone', 'Zidovudine').
drug_interaction('Rosiglitazone', 'Ziprasidone').
drug_interaction('Olmesartan', 'Pimecrolimus').
drug_interaction('Olmesartan', 'Ramipril').
drug_interaction('Olmesartan', 'Rituximab').
drug_interaction('Olmesartan', 'Tolcapone').
drug_interaction('Olmesartan', 'Torasemide').
drug_interaction('Etomidate', 'Haloperidol').
drug_interaction('Etomidate', 'Imipramine').
drug_interaction('Etomidate', 'Methadone').
drug_interaction('Etomidate', 'Pethidine').
drug_interaction('Etomidate', 'Promazine').
drug_interaction('Etomidate', 'Tolcapone').
drug_interaction('Etomidate', 'Ziprasidone').
drug_interaction('Etomidate', 'Zolpidem').
drug_interaction('Enoxacin', 'Insulin Glargine').
drug_interaction('Enoxacin', 'Miglitol').
drug_interaction('Enoxacin', 'Pimecrolimus').
drug_interaction('Enoxacin', 'Rosiglitazone').
drug_interaction('Insulin Glargine', 'Megestrol acetate').
drug_interaction('Insulin Glargine', 'Miglitol').
drug_interaction('Insulin Glargine', 'Ritonavir').
drug_interaction('Insulin Glargine', 'Rosiglitazone').
drug_interaction('Insulin Glargine', 'Torasemide').
drug_interaction('Insulin Glargine', 'Ziprasidone').
drug_interaction('Pimecrolimus', 'Ramipril').
drug_interaction('Pimecrolimus', 'Ritonavir').
drug_interaction('Pimecrolimus', 'Rituximab').
drug_interaction('Pimecrolimus', 'Streptozocin').
drug_interaction('Pimecrolimus', 'Teniposide').
drug_interaction('Pimecrolimus', 'Tioguanine').
drug_interaction('Pimecrolimus', 'Torasemide').
drug_interaction('Pimecrolimus', 'Valrubicin').
drug_interaction('Pimecrolimus', 'Vinorelbine').
drug_interaction('Pimecrolimus', 'Ziprasidone').
drug_interaction('Natalizumab', 'Pimecrolimus').
drug_interaction('Natalizumab', 'Rituximab').
drug_interaction('Natalizumab', 'Streptozocin').
drug_interaction('Natalizumab', 'Teniposide').
drug_interaction('Natalizumab', 'Tioguanine').
drug_interaction('Natalizumab', 'Vinorelbine').
drug_interaction('Diethylstilbestrol', 'Digoxin').
drug_interaction('Diethylstilbestrol', 'Entacapone').
drug_interaction('Diethylstilbestrol', 'Haloperidol').
drug_interaction('Diethylstilbestrol', 'Hyaluronidase').
drug_interaction('Diethylstilbestrol', 'Imipramine').
drug_interaction('Diethylstilbestrol', 'Levothyroxine').
drug_interaction('Diethylstilbestrol', 'Megestrol acetate').
drug_interaction('Diethylstilbestrol', 'Methadone').
drug_interaction('Diethylstilbestrol', 'Ramipril').
drug_interaction('Diethylstilbestrol', 'Ritonavir').
drug_interaction('Diethylstilbestrol', 'Streptozocin').
drug_interaction('Diethylstilbestrol', 'Tolcapone').
drug_interaction('Diethylstilbestrol', 'Vinorelbine').
drug_interaction('Diethylstilbestrol', 'Vitamin C').
drug_interaction('Oxiconazole', 'Zolpidem').
drug_interaction('Ramipril', 'Rituximab').
drug_interaction('Ramipril', 'Tolcapone').
drug_interaction('Ramipril', 'Torasemide').
drug_interaction('Ramipril', 'Zidovudine').
drug_interaction('Palonosetron', 'Pethidine').
drug_interaction('Palonosetron', 'Promazine').
drug_interaction('Palonosetron', 'Ritonavir').
drug_interaction('Palonosetron', 'Ziprasidone').
drug_interaction('Acetohexamide', 'Betamethasone').
drug_interaction('Acetohexamide', 'Chloramphenicol').
drug_interaction('Acetohexamide', 'Etonogestrel').
drug_interaction('Acetohexamide', 'Goserelin').
drug_interaction('Acetohexamide', 'Insulin Glargine').
drug_interaction('Acetohexamide', 'Megestrol acetate').
drug_interaction('Acetohexamide', 'Ritonavir').
drug_interaction('Acetohexamide', 'Rosiglitazone').
drug_interaction('Acetohexamide', 'Torasemide').
drug_interaction('Acetohexamide', 'Ziprasidone').
drug_interaction('Caffeine', 'Chlorpromazine').
drug_interaction('Caffeine', 'Darifenacin').
drug_interaction('Caffeine', 'Diethylstilbestrol').
drug_interaction('Caffeine', 'Digoxin').
drug_interaction('Caffeine', 'Floxuridine').
drug_interaction('Caffeine', 'Flutamide').
drug_interaction('Caffeine', 'Haloperidol').
drug_interaction('Caffeine', 'Imipramine').
drug_interaction('Caffeine', 'Levothyroxine').
drug_interaction('Caffeine', 'Megestrol acetate').
drug_interaction('Caffeine', 'Methadone').
drug_interaction('Caffeine', 'Mexiletine').
drug_interaction('Caffeine', 'Palonosetron').
drug_interaction('Caffeine', 'Promazine').
drug_interaction('Caffeine', 'Ritonavir').
drug_interaction('Caffeine', 'Rosiglitazone').
drug_interaction('Caffeine', 'Streptozocin').
drug_interaction('Caffeine', 'Vinorelbine').
drug_interaction('Caffeine', 'Zidovudine').
drug_interaction('Caffeine', 'Ziprasidone').
drug_interaction('Caffeine', 'Zolpidem').
drug_interaction('Infliximab', 'Natalizumab').
drug_interaction('Infliximab', 'Pimecrolimus').
drug_interaction('Infliximab', 'Rituximab').
drug_interaction('Darifenacin', 'Haloperidol').
drug_interaction('Darifenacin', 'Hyoscyamine').
drug_interaction('Darifenacin', 'Imipramine').
drug_interaction('Darifenacin', 'Methadone').
drug_interaction('Darifenacin', 'Mexiletine').
drug_interaction('Darifenacin', 'Oxyphenonium').
drug_interaction('Darifenacin', 'Palonosetron').
drug_interaction('Darifenacin', 'Pethidine').
drug_interaction('Darifenacin', 'Promazine').
drug_interaction('Darifenacin', 'Ritonavir').
drug_interaction('Darifenacin', 'Trihexyphenidyl').
drug_interaction('Darifenacin', 'Vinorelbine').
drug_interaction('Darifenacin', 'Ziprasidone').
drug_interaction('Darifenacin', 'Zolpidem').
drug_interaction('Anidulafungin', 'Zolpidem').
drug_interaction('Betamethasone', 'Caffeine').
drug_interaction('Betamethasone', 'Chlorpromazine').
drug_interaction('Betamethasone', 'Diethylstilbestrol').
drug_interaction('Betamethasone', 'Digoxin').
drug_interaction('Betamethasone', 'Enoxacin').
drug_interaction('Betamethasone', 'Haloperidol').
drug_interaction('Betamethasone', 'Hyaluronidase').
drug_interaction('Betamethasone', 'Imipramine').
drug_interaction('Betamethasone', 'Insulin Glargine').
drug_interaction('Betamethasone', 'Levothyroxine').
drug_interaction('Betamethasone', 'Megestrol acetate').
drug_interaction('Betamethasone', 'Methadone').
drug_interaction('Betamethasone', 'Miglitol').
drug_interaction('Betamethasone', 'Natalizumab').
drug_interaction('Betamethasone', 'Pimecrolimus').
drug_interaction('Betamethasone', 'Ritonavir').
drug_interaction('Betamethasone', 'Rosiglitazone').
drug_interaction('Betamethasone', 'Streptozocin').
drug_interaction('Betamethasone', 'Torasemide').
drug_interaction('Betamethasone', 'Vinorelbine').
drug_interaction('Adalimumab', 'Infliximab').
drug_interaction('Adalimumab', 'Natalizumab').
drug_interaction('Adalimumab', 'Pimecrolimus').
drug_interaction('Adalimumab', 'Rituximab').
drug_interaction('Flutamide', 'Mexiletine').
drug_interaction('Flutamide', 'Ritonavir').
drug_interaction('Flutamide', 'Ziprasidone').
drug_interaction('Chlorpromazine', 'Cyproheptadine').
drug_interaction('Chlorpromazine', 'Darifenacin').
drug_interaction('Chlorpromazine', 'Diethylstilbestrol').
drug_interaction('Chlorpromazine', 'Digoxin').
drug_interaction('Chlorpromazine', 'Entacapone').
drug_interaction('Chlorpromazine', 'Ethchlorvynol').
drug_interaction('Chlorpromazine', 'Etomidate').
drug_interaction('Chlorpromazine', 'Goserelin').
drug_interaction('Chlorpromazine', 'Haloperidol').
drug_interaction('Chlorpromazine', 'Imipramine').
drug_interaction('Chlorpromazine', 'Levothyroxine').
drug_interaction('Chlorpromazine', 'Megestrol acetate').
drug_interaction('Chlorpromazine', 'Methadone').
drug_interaction('Chlorpromazine', 'Mexiletine').
drug_interaction('Chlorpromazine', 'Olmesartan').
drug_interaction('Chlorpromazine', 'Oxytocin').
drug_interaction('Chlorpromazine', 'Palonosetron').
drug_interaction('Chlorpromazine', 'Pethidine').
drug_interaction('Chlorpromazine', 'Promazine').
drug_interaction('Chlorpromazine', 'Ramipril').
drug_interaction('Chlorpromazine', 'Ritonavir').
drug_interaction('Chlorpromazine', 'Streptozocin').
drug_interaction('Chlorpromazine', 'Tolcapone').
drug_interaction('Chlorpromazine', 'Torasemide').
drug_interaction('Chlorpromazine', 'Vinorelbine').
drug_interaction('Chlorpromazine', 'Zidovudine').
drug_interaction('Chlorpromazine', 'Ziprasidone').
drug_interaction('Chlorpromazine', 'Zolpidem').
drug_interaction('Isoetarine', 'Torasemide').
drug_interaction('Haloperidol', 'Imipramine').
drug_interaction('Haloperidol', 'Levothyroxine').
drug_interaction('Haloperidol', 'Megestrol acetate').
drug_interaction('Haloperidol', 'Methadone').
drug_interaction('Haloperidol', 'Mexiletine').
drug_interaction('Haloperidol', 'Oxytocin').
drug_interaction('Haloperidol', 'Palonosetron').
drug_interaction('Haloperidol', 'Pethidine').
drug_interaction('Haloperidol', 'Pimecrolimus').
drug_interaction('Haloperidol', 'Promazine').
drug_interaction('Haloperidol', 'Ritonavir').
drug_interaction('Haloperidol', 'Streptozocin').
drug_interaction('Haloperidol', 'Tolcapone').
drug_interaction('Haloperidol', 'Vinorelbine').
drug_interaction('Haloperidol', 'Zidovudine').
drug_interaction('Haloperidol', 'Ziprasidone').
drug_interaction('Haloperidol', 'Zolpidem').
drug_interaction('Promazine', 'Ritonavir').
drug_interaction('Promazine', 'Tolcapone').
drug_interaction('Promazine', 'Vinorelbine').
drug_interaction('Promazine', 'Ziprasidone').
drug_interaction('Promazine', 'Zolpidem').
drug_interaction('Ethchlorvynol', 'Etomidate').
drug_interaction('Ethchlorvynol', 'Haloperidol').
drug_interaction('Ethchlorvynol', 'Imipramine').
drug_interaction('Ethchlorvynol', 'Methadone').
drug_interaction('Ethchlorvynol', 'Pethidine').
drug_interaction('Ethchlorvynol', 'Promazine').
drug_interaction('Ethchlorvynol', 'Tolcapone').
drug_interaction('Ethchlorvynol', 'Ziprasidone').
drug_interaction('Ethchlorvynol', 'Zolpidem').
drug_interaction('Torasemide', 'Valrubicin').
drug_interaction('Muromonab', 'Natalizumab').
drug_interaction('Muromonab', 'Pimecrolimus').
drug_interaction('Bevacizumab', 'Diethylstilbestrol').
drug_interaction('Bevacizumab', 'Digoxin').
drug_interaction('Bevacizumab', 'Enoxacin').
drug_interaction('Bevacizumab', 'Floxuridine').
drug_interaction('Bevacizumab', 'Flutamide').
drug_interaction('Bevacizumab', 'Gemtuzumab ozogamicin').
drug_interaction('Bevacizumab', 'Goserelin').
drug_interaction('Bevacizumab', 'Megestrol acetate').
drug_interaction('Bevacizumab', 'Rituximab').
drug_interaction('Bevacizumab', 'Streptozocin').
drug_interaction('Bevacizumab', 'Teniposide').
drug_interaction('Bevacizumab', 'Tioguanine').
drug_interaction('Bevacizumab', 'Valrubicin').
drug_interaction('Bevacizumab', 'Vinorelbine').
drug_interaction('Ritonavir', 'Rosiglitazone').
drug_interaction('Ritonavir', 'Streptozocin').
drug_interaction('Ritonavir', 'Teniposide').
drug_interaction('Ritonavir', 'Torasemide').
drug_interaction('Ritonavir', 'Vinorelbine').
drug_interaction('Ritonavir', 'Zidovudine').
drug_interaction('Ritonavir', 'Ziprasidone').
drug_interaction('Ritonavir', 'Zolpidem').
drug_interaction('Pethidine', 'Promazine').
drug_interaction('Pethidine', 'Ramipril').
drug_interaction('Pethidine', 'Ritonavir').
drug_interaction('Pethidine', 'Tolcapone').
drug_interaction('Pethidine', 'Torasemide').
drug_interaction('Pethidine', 'Trihexyphenidyl').
drug_interaction('Pethidine', 'Ziprasidone').
drug_interaction('Pethidine', 'Zolpidem').
drug_interaction('Rituximab', 'Torasemide').
drug_interaction('Tolcapone', 'Torasemide').
drug_interaction('Tolcapone', 'Ziprasidone').
drug_interaction('Tolcapone', 'Zolpidem').
drug_interaction('Chlordiazepoxide', 'Chlorpromazine').
drug_interaction('Chlordiazepoxide', 'Cyproheptadine').
drug_interaction('Chlordiazepoxide', 'Darifenacin').
drug_interaction('Chlordiazepoxide', 'Entacapone').
drug_interaction('Chlordiazepoxide', 'Ethchlorvynol').
drug_interaction('Chlordiazepoxide', 'Etomidate').
drug_interaction('Chlordiazepoxide', 'Haloperidol').
drug_interaction('Chlordiazepoxide', 'Hyaluronidase').
drug_interaction('Chlordiazepoxide', 'Imipramine').
drug_interaction('Chlordiazepoxide', 'Methadone').
drug_interaction('Chlordiazepoxide', 'Pethidine').
drug_interaction('Chlordiazepoxide', 'Promazine').
drug_interaction('Chlordiazepoxide', 'Ritonavir').
drug_interaction('Chlordiazepoxide', 'Tolcapone').
drug_interaction('Chlordiazepoxide', 'Ziprasidone').
drug_interaction('Chlordiazepoxide', 'Zolpidem').
drug_interaction('Chloramphenicol', 'Flutamide').
drug_interaction('Chloramphenicol', 'Haloperidol').
drug_interaction('Chloramphenicol', 'Imipramine').
drug_interaction('Chloramphenicol', 'Methadone').
drug_interaction('Chloramphenicol', 'Oxiconazole').
drug_interaction('Chloramphenicol', 'Pethidine').
drug_interaction('Chloramphenicol', 'Promazine').
drug_interaction('Chloramphenicol', 'Teniposide').
drug_interaction('Chloramphenicol', 'Zidovudine').
drug_interaction('Chloramphenicol', 'Zolpidem').
drug_interaction('Oxyphenonium', 'Pethidine').
drug_interaction('Oxyphenonium', 'Trihexyphenidyl').
drug_interaction('Floxuridine', 'Haloperidol').
drug_interaction('Floxuridine', 'Methadone').
drug_interaction('Floxuridine', 'Natalizumab').
drug_interaction('Floxuridine', 'Pimecrolimus').
drug_interaction('Floxuridine', 'Promazine').
drug_interaction('Floxuridine', 'Rosiglitazone').
drug_interaction('Floxuridine', 'Torasemide').
drug_interaction('Floxuridine', 'Zidovudine').
drug_interaction('Floxuridine', 'Zolpidem').
drug_interaction('Vinorelbine', 'Zidovudine').
drug_interaction('Vinorelbine', 'Ziprasidone').
drug_interaction('Hyoscyamine', 'Methadone').
drug_interaction('Hyoscyamine', 'Oxyphenonium').
drug_interaction('Hyoscyamine', 'Pethidine').
drug_interaction('Hyoscyamine', 'Trihexyphenidyl').
drug_interaction('Megestrol acetate', 'Miglitol').
drug_interaction('Megestrol acetate', 'Ritonavir').
drug_interaction('Megestrol acetate', 'Rosiglitazone').
drug_interaction('Megestrol acetate', 'Zidovudine').
drug_interaction('Aldesleukin', 'Betamethasone').
drug_interaction('Aldesleukin', 'Bevacizumab').
drug_interaction('Aldesleukin', 'Brimonidine').
drug_interaction('Aldesleukin', 'Chlorpromazine').
drug_interaction('Aldesleukin', 'Digoxin').
drug_interaction('Aldesleukin', 'Imipramine').
drug_interaction('Aldesleukin', 'Olmesartan').
drug_interaction('Aldesleukin', 'Ramipril').
drug_interaction('Aldesleukin', 'Tolcapone').
drug_interaction('Aldesleukin', 'Torasemide').
drug_interaction('Entacapone', 'Ethchlorvynol').
drug_interaction('Entacapone', 'Etomidate').
drug_interaction('Entacapone', 'Haloperidol').
drug_interaction('Entacapone', 'Imipramine').
drug_interaction('Entacapone', 'Methadone').
drug_interaction('Entacapone', 'Pethidine').
drug_interaction('Entacapone', 'Promazine').
drug_interaction('Entacapone', 'Tolcapone').
drug_interaction('Entacapone', 'Ziprasidone').
drug_interaction('Entacapone', 'Zolpidem').
drug_interaction('Azithromycin', 'Betamethasone').
drug_interaction('Azithromycin', 'Caffeine').
drug_interaction('Azithromycin', 'Chlorpromazine').
drug_interaction('Azithromycin', 'Diethylstilbestrol').
drug_interaction('Azithromycin', 'Digoxin').
drug_interaction('Azithromycin', 'Flutamide').
drug_interaction('Azithromycin', 'Goserelin').
drug_interaction('Azithromycin', 'Haloperidol').
drug_interaction('Azithromycin', 'Imipramine').
drug_interaction('Azithromycin', 'Methadone').
drug_interaction('Azithromycin', 'Mexiletine').
drug_interaction('Azithromycin', 'Oxytocin').
drug_interaction('Azithromycin', 'Palonosetron').
drug_interaction('Azithromycin', 'Promazine').
drug_interaction('Azithromycin', 'Ritonavir').
drug_interaction('Azithromycin', 'Zidovudine').
drug_interaction('Azithromycin', 'Ziprasidone').
drug_interaction('Azithromycin', 'Zolpidem').
drug_interaction('Mexiletine', 'Methadone').
drug_interaction('Oxyphenonium', 'Methadone').
drug_interaction('Oxytocin', 'Methadone').
drug_interaction('Palonosetron', 'Methadone').
drug_interaction('Pethidine', 'Methadone').
drug_interaction('Promazine', 'Methadone').
drug_interaction('Ritonavir', 'Methadone').
drug_interaction('Rosiglitazone', 'Methadone').
drug_interaction('Tolcapone', 'Methadone').
drug_interaction('Torasemide', 'Methadone').
drug_interaction('Trihexyphenidyl', 'Methadone').
drug_interaction('Vinorelbine', 'Methadone').
drug_interaction('Zidovudine', 'Methadone').
drug_interaction('Ziprasidone', 'Methadone').
drug_interaction('Zolpidem', 'Methadone').
drug_interaction('Chlordiazepoxide', 'Brimonidine').
drug_interaction('Chlorpromazine', 'Brimonidine').
drug_interaction('Cyproheptadine', 'Brimonidine').
drug_interaction('Digoxin', 'Brimonidine').
drug_interaction('Entacapone', 'Brimonidine').
drug_interaction('Ethchlorvynol', 'Brimonidine').
drug_interaction('Etomidate', 'Brimonidine').
drug_interaction('Haloperidol', 'Brimonidine').
drug_interaction('Hyaluronidase', 'Brimonidine').
drug_interaction('Imipramine', 'Brimonidine').
drug_interaction('Methadone', 'Brimonidine').
drug_interaction('Olmesartan', 'Brimonidine').
drug_interaction('Pethidine', 'Brimonidine').
drug_interaction('Promazine', 'Brimonidine').
drug_interaction('Ramipril', 'Brimonidine').
drug_interaction('Rituximab', 'Brimonidine').
drug_interaction('Tolcapone', 'Brimonidine').
drug_interaction('Torasemide', 'Brimonidine').
drug_interaction('Ziprasidone', 'Brimonidine').
drug_interaction('Zolpidem', 'Brimonidine').
drug_interaction('Haloperidol', 'Goserelin').
drug_interaction('Imipramine', 'Goserelin').
drug_interaction('Insulin Glargine', 'Goserelin').
drug_interaction('Methadone', 'Goserelin').
drug_interaction('Miglitol', 'Goserelin').
drug_interaction('Oxytocin', 'Goserelin').
drug_interaction('Promazine', 'Goserelin').
drug_interaction('Ritonavir', 'Goserelin').
drug_interaction('Rosiglitazone', 'Goserelin').
drug_interaction('Ziprasidone', 'Goserelin').
drug_interaction('Natalizumab', 'Ibritumomab tiuxetan').
drug_interaction('Pimecrolimus', 'Ibritumomab tiuxetan').
drug_interaction('Digoxin', 'Calcium Gluceptate').
drug_interaction('Enoxacin', 'Calcium Gluceptate').
drug_interaction('Levothyroxine', 'Calcium Gluceptate').
drug_interaction('Aminosalicylic Acid', 'Abciximab').
drug_interaction('Anistreplase', 'Abciximab').
drug_interaction('Diethylstilbestrol', 'Abciximab').
drug_interaction('Etonogestrel', 'Abciximab').
drug_interaction('Ibritumomab tiuxetan', 'Abciximab').
drug_interaction('Megestrol acetate', 'Abciximab').
drug_interaction('Pimecrolimus', 'Abciximab').
drug_interaction('Rosiglitazone', 'Abciximab').
drug_interaction('Vitamin E', 'Abciximab').
drug_interaction('Brimonidine', 'Bethanidine').
drug_interaction('Imipramine', 'Bethanidine').
drug_interaction('Olmesartan', 'Bethanidine').
drug_interaction('Ramipril', 'Bethanidine').
drug_interaction('Rituximab', 'Bethanidine').
drug_interaction('Torasemide', 'Bethanidine').
drug_interaction('Piperacillin', 'Flucloxacillin').
drug_interaction('Streptozocin', 'Flucloxacillin').
drug_interaction('Valrubicin', 'Flucloxacillin').
drug_interaction('Palonosetron', 'Mexiletine').
drug_interaction('Promazine', 'Mexiletine').
drug_interaction('Ritonavir', 'Mexiletine').
drug_interaction('Ziprasidone', 'Mexiletine').
drug_interaction('Zolpidem', 'Mexiletine').
drug_interaction('Streptozocin', 'Piperacillin').
drug_interaction('Valrubicin', 'Piperacillin').
drug_interaction('Torasemide', 'Streptozocin').
drug_interaction('Zidovudine', 'Streptozocin').
drug_interaction('Promazine', 'Oxytocin').
drug_interaction('Ziprasidone', 'Oxytocin').
drug_interaction('Ziprasidone', 'Zidovudine').
drug_interaction('Insulin Glargine', 'Etonogestrel').
drug_interaction('Miglitol', 'Etonogestrel').
drug_interaction('Ritonavir', 'Etonogestrel').
drug_interaction('Rosiglitazone', 'Etonogestrel').
drug_interaction('Ziprasidone', 'Etonogestrel').
drug_interaction('Betamethasone', 'Amsacrine').
drug_interaction('Bevacizumab', 'Amsacrine').
drug_interaction('Caffeine', 'Amsacrine').
drug_interaction('Chlorpromazine', 'Amsacrine').
drug_interaction('Darifenacin', 'Amsacrine').
drug_interaction('Diethylstilbestrol', 'Amsacrine').
drug_interaction('Digoxin', 'Amsacrine').
drug_interaction('Haloperidol', 'Amsacrine').
drug_interaction('Imipramine', 'Amsacrine').
drug_interaction('Methadone', 'Amsacrine').
drug_interaction('Natalizumab', 'Amsacrine').
drug_interaction('Pimecrolimus', 'Amsacrine').
drug_interaction('Promazine', 'Amsacrine').
drug_interaction('Ritonavir', 'Amsacrine').
drug_interaction('Zidovudine', 'Amsacrine').
drug_interaction('Ziprasidone', 'Amsacrine').
drug_interaction('Streptozocin', 'Phenoxymethylpenicillin').
drug_interaction('Valrubicin', 'Phenoxymethylpenicillin').
drug_interaction('Natalizumab', 'Gemtuzumab ozogamicin').
drug_interaction('Pimecrolimus', 'Gemtuzumab ozogamicin').
drug_interaction('Anistreplase', 'Aminosalicylic Acid').
drug_interaction('Betamethasone', 'Aminosalicylic Acid').
drug_interaction('Hyaluronidase', 'Aminosalicylic Acid').
drug_interaction('Insulin Glargine', 'Aminosalicylic Acid').
drug_interaction('Miglitol', 'Aminosalicylic Acid').
drug_interaction('Ramipril', 'Aminosalicylic Acid').
drug_interaction('Rosiglitazone', 'Aminosalicylic Acid').
drug_interaction('Torasemide', 'Aminosalicylic Acid').
drug_interaction('Entacapone', 'Cyproheptadine').
drug_interaction('Ethchlorvynol', 'Cyproheptadine').
drug_interaction('Etomidate', 'Cyproheptadine').
drug_interaction('Haloperidol', 'Cyproheptadine').
drug_interaction('Hyaluronidase', 'Cyproheptadine').
drug_interaction('Imipramine', 'Cyproheptadine').
drug_interaction('Methadone', 'Cyproheptadine').
drug_interaction('Pethidine', 'Cyproheptadine').
drug_interaction('Promazine', 'Cyproheptadine').
drug_interaction('Tolcapone', 'Cyproheptadine').
drug_interaction('Ziprasidone', 'Cyproheptadine').
drug_interaction('Zolpidem', 'Cyproheptadine').
drug_interaction('Zolpidem', 'Ziprasidone').
drug_interaction('Enoxacin', 'Digoxin').
drug_interaction('Floxuridine', 'Digoxin').
drug_interaction('Flutamide', 'Digoxin').
drug_interaction('Gemtuzumab ozogamicin', 'Digoxin').
drug_interaction('Goserelin', 'Digoxin').
drug_interaction('Haloperidol', 'Digoxin').
drug_interaction('Imipramine', 'Digoxin').
drug_interaction('Levothyroxine', 'Digoxin').
drug_interaction('Megestrol acetate', 'Digoxin').
drug_interaction('Methadone', 'Digoxin').
drug_interaction('Pimecrolimus', 'Digoxin').
drug_interaction('Ramipril', 'Digoxin').
drug_interaction('Ritonavir', 'Digoxin').
drug_interaction('Rituximab', 'Digoxin').
drug_interaction('Streptozocin', 'Digoxin').
drug_interaction('Teniposide', 'Digoxin').
drug_interaction('Tioguanine', 'Digoxin').
drug_interaction('Torasemide', 'Digoxin').
drug_interaction('Valrubicin', 'Digoxin').
drug_interaction('Vinorelbine', 'Digoxin').
drug_interaction('Zidovudine', 'Digoxin').
drug_interaction('Ziprasidone', 'Digoxin').
drug_interaction('Ritonavir', 'Levothyroxine').
drug_interaction('Zidovudine', 'Levothyroxine').
drug_interaction('Ziprasidone', 'Levothyroxine').
drug_interaction('Ziprasidone', 'Teniposide').
drug_interaction('Ritonavir', 'Miglitol').
drug_interaction('Torasemide', 'Miglitol').
drug_interaction('Ziprasidone', 'Miglitol').
drug_interaction('Isoetarine', 'Imipramine').
drug_interaction('Levothyroxine', 'Imipramine').
drug_interaction('Megestrol acetate', 'Imipramine').
drug_interaction('Methadone', 'Imipramine').
drug_interaction('Mexiletine', 'Imipramine').
drug_interaction('Olmesartan', 'Imipramine').
drug_interaction('Palonosetron', 'Imipramine').
drug_interaction('Pethidine', 'Imipramine').
drug_interaction('Promazine', 'Imipramine').
drug_interaction('Ramipril', 'Imipramine').
drug_interaction('Ritonavir', 'Imipramine').
drug_interaction('Streptozocin', 'Imipramine').
drug_interaction('Tolcapone', 'Imipramine').
drug_interaction('Torasemide', 'Imipramine').
drug_interaction('Vinorelbine', 'Imipramine').
drug_interaction('Zidovudine', 'Imipramine').
drug_interaction('Ziprasidone', 'Imipramine').
drug_interaction('Zolpidem', 'Imipramine').
drug_interaction('Torasemide', 'Rosiglitazone').
drug_interaction('Zidovudine', 'Rosiglitazone').
drug_interaction('Ziprasidone', 'Rosiglitazone').
drug_interaction('Pimecrolimus', 'Olmesartan').
drug_interaction('Ramipril', 'Olmesartan').
drug_interaction('Rituximab', 'Olmesartan').
drug_interaction('Tolcapone', 'Olmesartan').
drug_interaction('Torasemide', 'Olmesartan').
drug_interaction('Haloperidol', 'Etomidate').
drug_interaction('Imipramine', 'Etomidate').
drug_interaction('Methadone', 'Etomidate').
drug_interaction('Pethidine', 'Etomidate').
drug_interaction('Promazine', 'Etomidate').
drug_interaction('Tolcapone', 'Etomidate').
drug_interaction('Ziprasidone', 'Etomidate').
drug_interaction('Zolpidem', 'Etomidate').
drug_interaction('Insulin Glargine', 'Enoxacin').
drug_interaction('Miglitol', 'Enoxacin').
drug_interaction('Pimecrolimus', 'Enoxacin').
drug_interaction('Rosiglitazone', 'Enoxacin').
drug_interaction('Megestrol acetate', 'Insulin Glargine').
drug_interaction('Miglitol', 'Insulin Glargine').
drug_interaction('Ritonavir', 'Insulin Glargine').
drug_interaction('Rosiglitazone', 'Insulin Glargine').
drug_interaction('Torasemide', 'Insulin Glargine').
drug_interaction('Ziprasidone', 'Insulin Glargine').
drug_interaction('Ramipril', 'Pimecrolimus').
drug_interaction('Ritonavir', 'Pimecrolimus').
drug_interaction('Rituximab', 'Pimecrolimus').
drug_interaction('Streptozocin', 'Pimecrolimus').
drug_interaction('Teniposide', 'Pimecrolimus').
drug_interaction('Tioguanine', 'Pimecrolimus').
drug_interaction('Torasemide', 'Pimecrolimus').
drug_interaction('Valrubicin', 'Pimecrolimus').
drug_interaction('Vinorelbine', 'Pimecrolimus').
drug_interaction('Ziprasidone', 'Pimecrolimus').
drug_interaction('Pimecrolimus', 'Natalizumab').
drug_interaction('Rituximab', 'Natalizumab').
drug_interaction('Streptozocin', 'Natalizumab').
drug_interaction('Teniposide', 'Natalizumab').
drug_interaction('Tioguanine', 'Natalizumab').
drug_interaction('Vinorelbine', 'Natalizumab').
drug_interaction('Digoxin', 'Diethylstilbestrol').
drug_interaction('Entacapone', 'Diethylstilbestrol').
drug_interaction('Haloperidol', 'Diethylstilbestrol').
drug_interaction('Hyaluronidase', 'Diethylstilbestrol').
drug_interaction('Imipramine', 'Diethylstilbestrol').
drug_interaction('Levothyroxine', 'Diethylstilbestrol').
drug_interaction('Megestrol acetate', 'Diethylstilbestrol').
drug_interaction('Methadone', 'Diethylstilbestrol').
drug_interaction('Ramipril', 'Diethylstilbestrol').
drug_interaction('Ritonavir', 'Diethylstilbestrol').
drug_interaction('Streptozocin', 'Diethylstilbestrol').
drug_interaction('Tolcapone', 'Diethylstilbestrol').
drug_interaction('Vinorelbine', 'Diethylstilbestrol').
drug_interaction('Vitamin C', 'Diethylstilbestrol').
drug_interaction('Zolpidem', 'Oxiconazole').
drug_interaction('Rituximab', 'Ramipril').
drug_interaction('Tolcapone', 'Ramipril').
drug_interaction('Torasemide', 'Ramipril').
drug_interaction('Zidovudine', 'Ramipril').
drug_interaction('Pethidine', 'Palonosetron').
drug_interaction('Promazine', 'Palonosetron').
drug_interaction('Ritonavir', 'Palonosetron').
drug_interaction('Ziprasidone', 'Palonosetron').
drug_interaction('Betamethasone', 'Acetohexamide').
drug_interaction('Chloramphenicol', 'Acetohexamide').
drug_interaction('Etonogestrel', 'Acetohexamide').
drug_interaction('Goserelin', 'Acetohexamide').
drug_interaction('Insulin Glargine', 'Acetohexamide').
drug_interaction('Megestrol acetate', 'Acetohexamide').
drug_interaction('Ritonavir', 'Acetohexamide').
drug_interaction('Rosiglitazone', 'Acetohexamide').
drug_interaction('Torasemide', 'Acetohexamide').
drug_interaction('Ziprasidone', 'Acetohexamide').
drug_interaction('Chlorpromazine', 'Caffeine').
drug_interaction('Darifenacin', 'Caffeine').
drug_interaction('Diethylstilbestrol', 'Caffeine').
drug_interaction('Digoxin', 'Caffeine').
drug_interaction('Floxuridine', 'Caffeine').
drug_interaction('Flutamide', 'Caffeine').
drug_interaction('Haloperidol', 'Caffeine').
drug_interaction('Imipramine', 'Caffeine').
drug_interaction('Levothyroxine', 'Caffeine').
drug_interaction('Megestrol acetate', 'Caffeine').
drug_interaction('Methadone', 'Caffeine').
drug_interaction('Mexiletine', 'Caffeine').
drug_interaction('Palonosetron', 'Caffeine').
drug_interaction('Promazine', 'Caffeine').
drug_interaction('Ritonavir', 'Caffeine').
drug_interaction('Rosiglitazone', 'Caffeine').
drug_interaction('Streptozocin', 'Caffeine').
drug_interaction('Vinorelbine', 'Caffeine').
drug_interaction('Zidovudine', 'Caffeine').
drug_interaction('Ziprasidone', 'Caffeine').
drug_interaction('Zolpidem', 'Caffeine').
drug_interaction('Natalizumab', 'Infliximab').
drug_interaction('Pimecrolimus', 'Infliximab').
drug_interaction('Rituximab', 'Infliximab').
drug_interaction('Haloperidol', 'Darifenacin').
drug_interaction('Hyoscyamine', 'Darifenacin').
drug_interaction('Imipramine', 'Darifenacin').
drug_interaction('Methadone', 'Darifenacin').
drug_interaction('Mexiletine', 'Darifenacin').
drug_interaction('Oxyphenonium', 'Darifenacin').
drug_interaction('Palonosetron', 'Darifenacin').
drug_interaction('Pethidine', 'Darifenacin').
drug_interaction('Promazine', 'Darifenacin').
drug_interaction('Ritonavir', 'Darifenacin').
drug_interaction('Trihexyphenidyl', 'Darifenacin').
drug_interaction('Vinorelbine', 'Darifenacin').
drug_interaction('Ziprasidone', 'Darifenacin').
drug_interaction('Zolpidem', 'Darifenacin').
drug_interaction('Zolpidem', 'Anidulafungin').
drug_interaction('Caffeine', 'Betamethasone').
drug_interaction('Chlorpromazine', 'Betamethasone').
drug_interaction('Diethylstilbestrol', 'Betamethasone').
drug_interaction('Digoxin', 'Betamethasone').
drug_interaction('Enoxacin', 'Betamethasone').
drug_interaction('Haloperidol', 'Betamethasone').
drug_interaction('Hyaluronidase', 'Betamethasone').
drug_interaction('Imipramine', 'Betamethasone').
drug_interaction('Insulin Glargine', 'Betamethasone').
drug_interaction('Levothyroxine', 'Betamethasone').
drug_interaction('Megestrol acetate', 'Betamethasone').
drug_interaction('Methadone', 'Betamethasone').
drug_interaction('Miglitol', 'Betamethasone').
drug_interaction('Natalizumab', 'Betamethasone').
drug_interaction('Pimecrolimus', 'Betamethasone').
drug_interaction('Ritonavir', 'Betamethasone').
drug_interaction('Rosiglitazone', 'Betamethasone').
drug_interaction('Streptozocin', 'Betamethasone').
drug_interaction('Torasemide', 'Betamethasone').
drug_interaction('Vinorelbine', 'Betamethasone').
drug_interaction('Infliximab', 'Adalimumab').
drug_interaction('Natalizumab', 'Adalimumab').
drug_interaction('Pimecrolimus', 'Adalimumab').
drug_interaction('Rituximab', 'Adalimumab').
drug_interaction('Mexiletine', 'Flutamide').
drug_interaction('Ritonavir', 'Flutamide').
drug_interaction('Ziprasidone', 'Flutamide').
drug_interaction('Cyproheptadine', 'Chlorpromazine').
drug_interaction('Darifenacin', 'Chlorpromazine').
drug_interaction('Diethylstilbestrol', 'Chlorpromazine').
drug_interaction('Digoxin', 'Chlorpromazine').
drug_interaction('Entacapone', 'Chlorpromazine').
drug_interaction('Ethchlorvynol', 'Chlorpromazine').
drug_interaction('Etomidate', 'Chlorpromazine').
drug_interaction('Goserelin', 'Chlorpromazine').
drug_interaction('Haloperidol', 'Chlorpromazine').
drug_interaction('Imipramine', 'Chlorpromazine').
drug_interaction('Levothyroxine', 'Chlorpromazine').
drug_interaction('Megestrol acetate', 'Chlorpromazine').
drug_interaction('Methadone', 'Chlorpromazine').
drug_interaction('Mexiletine', 'Chlorpromazine').
drug_interaction('Olmesartan', 'Chlorpromazine').
drug_interaction('Oxytocin', 'Chlorpromazine').
drug_interaction('Palonosetron', 'Chlorpromazine').
drug_interaction('Pethidine', 'Chlorpromazine').
drug_interaction('Promazine', 'Chlorpromazine').
drug_interaction('Ramipril', 'Chlorpromazine').
drug_interaction('Ritonavir', 'Chlorpromazine').
drug_interaction('Streptozocin', 'Chlorpromazine').
drug_interaction('Tolcapone', 'Chlorpromazine').
drug_interaction('Torasemide', 'Chlorpromazine').
drug_interaction('Vinorelbine', 'Chlorpromazine').
drug_interaction('Zidovudine', 'Chlorpromazine').
drug_interaction('Ziprasidone', 'Chlorpromazine').
drug_interaction('Zolpidem', 'Chlorpromazine').
drug_interaction('Torasemide', 'Isoetarine').
drug_interaction('Imipramine', 'Haloperidol').
drug_interaction('Levothyroxine', 'Haloperidol').
drug_interaction('Megestrol acetate', 'Haloperidol').
drug_interaction('Methadone', 'Haloperidol').
drug_interaction('Mexiletine', 'Haloperidol').
drug_interaction('Oxytocin', 'Haloperidol').
drug_interaction('Palonosetron', 'Haloperidol').
drug_interaction('Pethidine', 'Haloperidol').
drug_interaction('Pimecrolimus', 'Haloperidol').
drug_interaction('Promazine', 'Haloperidol').
drug_interaction('Ritonavir', 'Haloperidol').
drug_interaction('Streptozocin', 'Haloperidol').
drug_interaction('Tolcapone', 'Haloperidol').
drug_interaction('Vinorelbine', 'Haloperidol').
drug_interaction('Zidovudine', 'Haloperidol').
drug_interaction('Ziprasidone', 'Haloperidol').
drug_interaction('Zolpidem', 'Haloperidol').
drug_interaction('Ritonavir', 'Promazine').
drug_interaction('Tolcapone', 'Promazine').
drug_interaction('Vinorelbine', 'Promazine').
drug_interaction('Ziprasidone', 'Promazine').
drug_interaction('Zolpidem', 'Promazine').
drug_interaction('Etomidate', 'Ethchlorvynol').
drug_interaction('Haloperidol', 'Ethchlorvynol').
drug_interaction('Imipramine', 'Ethchlorvynol').
drug_interaction('Methadone', 'Ethchlorvynol').
drug_interaction('Pethidine', 'Ethchlorvynol').
drug_interaction('Promazine', 'Ethchlorvynol').
drug_interaction('Tolcapone', 'Ethchlorvynol').
drug_interaction('Ziprasidone', 'Ethchlorvynol').
drug_interaction('Zolpidem', 'Ethchlorvynol').
drug_interaction('Valrubicin', 'Torasemide').
drug_interaction('Natalizumab', 'Muromonab').
drug_interaction('Pimecrolimus', 'Muromonab').
drug_interaction('Diethylstilbestrol', 'Bevacizumab').
drug_interaction('Digoxin', 'Bevacizumab').
drug_interaction('Enoxacin', 'Bevacizumab').
drug_interaction('Floxuridine', 'Bevacizumab').
drug_interaction('Flutamide', 'Bevacizumab').
drug_interaction('Gemtuzumab ozogamicin', 'Bevacizumab').
drug_interaction('Goserelin', 'Bevacizumab').
drug_interaction('Megestrol acetate', 'Bevacizumab').
drug_interaction('Rituximab', 'Bevacizumab').
drug_interaction('Streptozocin', 'Bevacizumab').
drug_interaction('Teniposide', 'Bevacizumab').
drug_interaction('Tioguanine', 'Bevacizumab').
drug_interaction('Valrubicin', 'Bevacizumab').
drug_interaction('Vinorelbine', 'Bevacizumab').
drug_interaction('Rosiglitazone', 'Ritonavir').
drug_interaction('Streptozocin', 'Ritonavir').
drug_interaction('Teniposide', 'Ritonavir').
drug_interaction('Torasemide', 'Ritonavir').
drug_interaction('Vinorelbine', 'Ritonavir').
drug_interaction('Zidovudine', 'Ritonavir').
drug_interaction('Ziprasidone', 'Ritonavir').
drug_interaction('Zolpidem', 'Ritonavir').
drug_interaction('Promazine', 'Pethidine').
drug_interaction('Ramipril', 'Pethidine').
drug_interaction('Ritonavir', 'Pethidine').
drug_interaction('Tolcapone', 'Pethidine').
drug_interaction('Torasemide', 'Pethidine').
drug_interaction('Trihexyphenidyl', 'Pethidine').
drug_interaction('Ziprasidone', 'Pethidine').
drug_interaction('Zolpidem', 'Pethidine').
drug_interaction('Torasemide', 'Rituximab').
drug_interaction('Torasemide', 'Tolcapone').
drug_interaction('Ziprasidone', 'Tolcapone').
drug_interaction('Zolpidem', 'Tolcapone').
drug_interaction('Chlorpromazine', 'Chlordiazepoxide').
drug_interaction('Cyproheptadine', 'Chlordiazepoxide').
drug_interaction('Darifenacin', 'Chlordiazepoxide').
drug_interaction('Entacapone', 'Chlordiazepoxide').
drug_interaction('Ethchlorvynol', 'Chlordiazepoxide').
drug_interaction('Etomidate', 'Chlordiazepoxide').
drug_interaction('Haloperidol', 'Chlordiazepoxide').
drug_interaction('Hyaluronidase', 'Chlordiazepoxide').
drug_interaction('Imipramine', 'Chlordiazepoxide').
drug_interaction('Methadone', 'Chlordiazepoxide').
drug_interaction('Pethidine', 'Chlordiazepoxide').
drug_interaction('Promazine', 'Chlordiazepoxide').
drug_interaction('Ritonavir', 'Chlordiazepoxide').
drug_interaction('Tolcapone', 'Chlordiazepoxide').
drug_interaction('Ziprasidone', 'Chlordiazepoxide').
drug_interaction('Zolpidem', 'Chlordiazepoxide').
drug_interaction('Flutamide', 'Chloramphenicol').
drug_interaction('Haloperidol', 'Chloramphenicol').
drug_interaction('Imipramine', 'Chloramphenicol').
drug_interaction('Methadone', 'Chloramphenicol').
drug_interaction('Oxiconazole', 'Chloramphenicol').
drug_interaction('Pethidine', 'Chloramphenicol').
drug_interaction('Promazine', 'Chloramphenicol').
drug_interaction('Teniposide', 'Chloramphenicol').
drug_interaction('Zidovudine', 'Chloramphenicol').
drug_interaction('Zolpidem', 'Chloramphenicol').
drug_interaction('Pethidine', 'Oxyphenonium').
drug_interaction('Trihexyphenidyl', 'Oxyphenonium').
drug_interaction('Haloperidol', 'Floxuridine').
drug_interaction('Methadone', 'Floxuridine').
drug_interaction('Natalizumab', 'Floxuridine').
drug_interaction('Pimecrolimus', 'Floxuridine').
drug_interaction('Promazine', 'Floxuridine').
drug_interaction('Rosiglitazone', 'Floxuridine').
drug_interaction('Torasemide', 'Floxuridine').
drug_interaction('Zidovudine', 'Floxuridine').
drug_interaction('Zolpidem', 'Floxuridine').
drug_interaction('Zidovudine', 'Vinorelbine').
drug_interaction('Ziprasidone', 'Vinorelbine').
drug_interaction('Methadone', 'Hyoscyamine').
drug_interaction('Oxyphenonium', 'Hyoscyamine').
drug_interaction('Pethidine', 'Hyoscyamine').
drug_interaction('Trihexyphenidyl', 'Hyoscyamine').
drug_interaction('Miglitol', 'Megestrol acetate').
drug_interaction('Ritonavir', 'Megestrol acetate').
drug_interaction('Rosiglitazone', 'Megestrol acetate').
drug_interaction('Zidovudine', 'Megestrol acetate').
drug_interaction('Betamethasone', 'Aldesleukin').
drug_interaction('Bevacizumab', 'Aldesleukin').
drug_interaction('Brimonidine', 'Aldesleukin').
drug_interaction('Chlorpromazine', 'Aldesleukin').
drug_interaction('Digoxin', 'Aldesleukin').
drug_interaction('Imipramine', 'Aldesleukin').
drug_interaction('Olmesartan', 'Aldesleukin').
drug_interaction('Ramipril', 'Aldesleukin').
drug_interaction('Tolcapone', 'Aldesleukin').
drug_interaction('Torasemide', 'Aldesleukin').
drug_interaction('Ethchlorvynol', 'Entacapone').
drug_interaction('Etomidate', 'Entacapone').
drug_interaction('Haloperidol', 'Entacapone').
drug_interaction('Imipramine', 'Entacapone').
drug_interaction('Methadone', 'Entacapone').
drug_interaction('Pethidine', 'Entacapone').
drug_interaction('Promazine', 'Entacapone').
drug_interaction('Tolcapone', 'Entacapone').
drug_interaction('Ziprasidone', 'Entacapone').
drug_interaction('Zolpidem', 'Entacapone').
drug_interaction('Betamethasone', 'Azithromycin').
drug_interaction('Caffeine', 'Azithromycin').
drug_interaction('Chlorpromazine', 'Azithromycin').
drug_interaction('Diethylstilbestrol', 'Azithromycin').
drug_interaction('Digoxin', 'Azithromycin').
drug_interaction('Flutamide', 'Azithromycin').
drug_interaction('Goserelin', 'Azithromycin').
drug_interaction('Haloperidol', 'Azithromycin').
drug_interaction('Imipramine', 'Azithromycin').
drug_interaction('Methadone', 'Azithromycin').
drug_interaction('Mexiletine', 'Azithromycin').
drug_interaction('Oxytocin', 'Azithromycin').
drug_interaction('Palonosetron', 'Azithromycin').
drug_interaction('Promazine', 'Azithromycin').
drug_interaction('Ritonavir', 'Azithromycin').
drug_interaction('Zidovudine', 'Azithromycin').
drug_interaction('Ziprasidone', 'Azithromycin').
drug_interaction('Zolpidem', 'Azithromycin').

