
drug_interaction('Nicotine', 'Sorafenib').
drug_interaction('Nicotine', 'Sulfadiazine').
drug_interaction('Nicotine', 'Sulfisoxazole').
drug_interaction('Nicotine', 'Ticlopidine').
drug_interaction('Nicotine', 'Valsartan').
drug_interaction('Nicotine', 'Venlafaxine').
drug_interaction('Bethanidine', 'Chlorthalidone').
drug_interaction('Bethanidine', 'Minoxidil').
drug_interaction('Bethanidine', 'Nimodipine').
drug_interaction('Bethanidine', 'Prazosin').
drug_interaction('Bethanidine', 'Reserpine').
drug_interaction('Bethanidine', 'Travoprost').
drug_interaction('Bethanidine', 'Valsartan').
drug_interaction('Bethanidine', 'Venlafaxine').
drug_interaction('Flutamide', 'Fluvoxamine').
drug_interaction('Flutamide', 'Sulfisoxazole').
drug_interaction('Flutamide', 'Ticlopidine').
drug_interaction('Flutamide', 'Venlafaxine').
drug_interaction('Venlafaxine', 'Zolpidem').
drug_interaction('Betamethasone', 'Chlorotrianisene').
drug_interaction('Betamethasone', 'Chlorthalidone').
drug_interaction('Betamethasone', 'Dronabinol').
drug_interaction('Betamethasone', 'Erythromycin').
drug_interaction('Betamethasone', 'Fluoxetine').
drug_interaction('Betamethasone', 'Fluvoxamine').
drug_interaction('Betamethasone', 'Grepafloxacin').
drug_interaction('Betamethasone', 'Hyaluronidase').
drug_interaction('Betamethasone', 'Liothyronine').
drug_interaction('Betamethasone', 'Miglitol').
drug_interaction('Betamethasone', 'Mitomycin').
drug_interaction('Betamethasone', 'Morphine').
drug_interaction('Betamethasone', 'Natalizumab').
drug_interaction('Betamethasone', 'Pefloxacin').
drug_interaction('Betamethasone', 'Prazosin').
drug_interaction('Betamethasone', 'Reserpine').
drug_interaction('Betamethasone', 'Sorafenib').
drug_interaction('Betamethasone', 'Venlafaxine').
drug_interaction('Natalizumab', 'Sorafenib').
drug_interaction('Fluvoxamine', 'Grepafloxacin').
drug_interaction('Fluvoxamine', 'L-Tryptophan').
drug_interaction('Fluvoxamine', 'Liothyronine').
drug_interaction('Fluvoxamine', 'Menadione').
drug_interaction('Fluvoxamine', 'Miglitol').
drug_interaction('Fluvoxamine', 'Morphine').
drug_interaction('Fluvoxamine', 'Nicotine').
drug_interaction('Fluvoxamine', 'Nimodipine').
drug_interaction('Fluvoxamine', 'Olanzapine').
drug_interaction('Fluvoxamine', 'Prazosin').
drug_interaction('Fluvoxamine', 'Pyrazinamide').
drug_interaction('Fluvoxamine', 'Raloxifene').
drug_interaction('Fluvoxamine', 'Remoxipride').
drug_interaction('Fluvoxamine', 'Reserpine').
drug_interaction('Fluvoxamine', 'Sorafenib').
drug_interaction('Fluvoxamine', 'Sulfadiazine').
drug_interaction('Fluvoxamine', 'Sulfisoxazole').
drug_interaction('Fluvoxamine', 'Temazepam').
drug_interaction('Fluvoxamine', 'Thiethylperazine').
drug_interaction('Fluvoxamine', 'Ticlopidine').
drug_interaction('Fluvoxamine', 'Tolcapone').
drug_interaction('Fluvoxamine', 'Tramadol').
drug_interaction('Fluvoxamine', 'Valsartan').
drug_interaction('Fluvoxamine', 'Venlafaxine').
drug_interaction('Fluvoxamine', 'Zolpidem').
drug_interaction('Famciclovir', 'Fluvoxamine').
drug_interaction('Famciclovir', 'Sulfisoxazole').
drug_interaction('Famciclovir', 'Ticlopidine').
drug_interaction('Famciclovir', 'Venlafaxine').
drug_interaction('Thiethylperazine', 'Tramadol').
drug_interaction('Grepafloxacin', 'Liothyronine').
drug_interaction('Grepafloxacin', 'Medrysone').
drug_interaction('Grepafloxacin', 'Miglitol').
drug_interaction('Grepafloxacin', 'Mitomycin').
drug_interaction('Grepafloxacin', 'Morphine').
drug_interaction('Grepafloxacin', 'Olanzapine').
drug_interaction('Grepafloxacin', 'Prazosin').
drug_interaction('Grepafloxacin', 'Reserpine').
drug_interaction('Grepafloxacin', 'Sorafenib').
drug_interaction('Grepafloxacin', 'Sulfadiazine').
drug_interaction('Grepafloxacin', 'Sulfisoxazole').
drug_interaction('Grepafloxacin', 'Ticlopidine').
drug_interaction('Grepafloxacin', 'Venlafaxine').
drug_interaction('Dicloxacillin', 'Dicoumarol').
drug_interaction('Dicloxacillin', 'Nimodipine').
drug_interaction('Sulfadiazine', 'Sulfisoxazole').
drug_interaction('Sulfadiazine', 'Temazepam').
drug_interaction('Sulfadiazine', 'Ticlopidine').
drug_interaction('Sulfadiazine', 'Valsartan').
drug_interaction('Sulfadiazine', 'Venlafaxine').
drug_interaction('Sulfadiazine', 'Zolpidem').
drug_interaction('Olanzapine', 'Prazosin').
drug_interaction('Olanzapine', 'Remoxipride').
drug_interaction('Olanzapine', 'Reserpine').
drug_interaction('Olanzapine', 'Sorafenib').
drug_interaction('Olanzapine', 'Sulfisoxazole').
drug_interaction('Olanzapine', 'Temazepam').
drug_interaction('Olanzapine', 'Thiethylperazine').
drug_interaction('Olanzapine', 'Ticlopidine').
drug_interaction('Olanzapine', 'Tolcapone').
drug_interaction('Olanzapine', 'Tramadol').
drug_interaction('Olanzapine', 'Venlafaxine').
drug_interaction('Olanzapine', 'Zolpidem').
drug_interaction('Bortezomib', 'Cevimeline').
drug_interaction('Bortezomib', 'Chlorthalidone').
drug_interaction('Bortezomib', 'Dapsone').
drug_interaction('Bortezomib', 'Dofetilide').
drug_interaction('Bortezomib', 'Dronabinol').
drug_interaction('Bortezomib', 'Ergocalciferol').
drug_interaction('Bortezomib', 'Erythromycin').
drug_interaction('Bortezomib', 'Famciclovir').
drug_interaction('Bortezomib', 'Fluoxetine').
drug_interaction('Bortezomib', 'Flutamide').
drug_interaction('Bortezomib', 'Fluvoxamine').
drug_interaction('Bortezomib', 'Grepafloxacin').
drug_interaction('Bortezomib', 'Menadione').
drug_interaction('Bortezomib', 'Minoxidil').
drug_interaction('Bortezomib', 'Morphine').
drug_interaction('Bortezomib', 'Nicotine').
drug_interaction('Bortezomib', 'Nimodipine').
drug_interaction('Bortezomib', 'Olanzapine').
drug_interaction('Bortezomib', 'Prazosin').
drug_interaction('Bortezomib', 'Pyrazinamide').
drug_interaction('Bortezomib', 'Raloxifene').
drug_interaction('Bortezomib', 'Reserpine').
drug_interaction('Bortezomib', 'Sorafenib').
drug_interaction('Bortezomib', 'Sulfadiazine').
drug_interaction('Bortezomib', 'Sulfisoxazole').
drug_interaction('Bortezomib', 'Temazepam').
drug_interaction('Bortezomib', 'Ticlopidine').
drug_interaction('Bortezomib', 'Tolcapone').
drug_interaction('Bortezomib', 'Tramadol').
drug_interaction('Bortezomib', 'Valsartan').
drug_interaction('Bortezomib', 'Venlafaxine').
drug_interaction('Bortezomib', 'Vitamin C').
drug_interaction('Bortezomib', 'Zolpidem').
drug_interaction('Reteplase', 'Ticlopidine').
drug_interaction('Amitriptyline', 'Baclofen').
drug_interaction('Amitriptyline', 'Betamethasone').
drug_interaction('Amitriptyline', 'Bethanidine').
drug_interaction('Amitriptyline', 'Bortezomib').
drug_interaction('Amitriptyline', 'Dexbrompheniramine').
drug_interaction('Amitriptyline', 'Dicoumarol').
drug_interaction('Amitriptyline', 'Dofetilide').
drug_interaction('Amitriptyline', 'Dronabinol').
drug_interaction('Amitriptyline', 'Erythromycin').
drug_interaction('Amitriptyline', 'Ethchlorvynol').
drug_interaction('Amitriptyline', 'Fluoxetine').
drug_interaction('Amitriptyline', 'Fluvoxamine').
drug_interaction('Amitriptyline', 'Grepafloxacin').
drug_interaction('Amitriptyline', 'Lepirudin').
drug_interaction('Amitriptyline', 'Liothyronine').
drug_interaction('Amitriptyline', 'Mitomycin').
drug_interaction('Amitriptyline', 'Morphine').
drug_interaction('Amitriptyline', 'Nicotine').
drug_interaction('Amitriptyline', 'Olanzapine').
drug_interaction('Amitriptyline', 'Prazosin').
drug_interaction('Amitriptyline', 'Remoxipride').
drug_interaction('Amitriptyline', 'Reserpine').
drug_interaction('Amitriptyline', 'Sorafenib').
drug_interaction('Amitriptyline', 'Sulfadiazine').
drug_interaction('Amitriptyline', 'Sulfisoxazole').
drug_interaction('Amitriptyline', 'Temazepam').
drug_interaction('Amitriptyline', 'Ticlopidine').
drug_interaction('Amitriptyline', 'Tolcapone').
drug_interaction('Amitriptyline', 'Tramadol').
drug_interaction('Amitriptyline', 'Valsartan').
drug_interaction('Amitriptyline', 'Venlafaxine').
drug_interaction('Amitriptyline', 'Zolpidem').
drug_interaction('Acetyldigitoxin', 'Altretamine').
drug_interaction('Acetyldigitoxin', 'Amikacin').
drug_interaction('Acetyldigitoxin', 'Asparaginase').
drug_interaction('Acetyldigitoxin', 'Bortezomib').
drug_interaction('Acetyldigitoxin', 'Calcium Gluceptate').
drug_interaction('Acetyldigitoxin', 'Chlorotrianisene').
drug_interaction('Acetyldigitoxin', 'Chlorthalidone').
drug_interaction('Acetyldigitoxin', 'Ergocalciferol').
drug_interaction('Acetyldigitoxin', 'Erythromycin').
drug_interaction('Acetyldigitoxin', 'Flutamide').
drug_interaction('Acetyldigitoxin', 'Grepafloxacin').
drug_interaction('Acetyldigitoxin', 'Mitomycin').
drug_interaction('Acetyldigitoxin', 'Pefloxacin').
drug_interaction('Acetyldigitoxin', 'Reserpine').
drug_interaction('Acetyldigitoxin', 'Sorafenib').
drug_interaction('Acetyldigitoxin', 'Succinylcholine').
drug_interaction('Acetyldigitoxin', 'Vitamin A').
drug_interaction('Ergocalciferol', 'Erythromycin').
drug_interaction('Ergocalciferol', 'Fluvoxamine').
drug_interaction('Ergocalciferol', 'Sulfisoxazole').
drug_interaction('Ergocalciferol', 'Ticlopidine').
drug_interaction('Ergocalciferol', 'Venlafaxine').
drug_interaction('Valsartan', 'Venlafaxine').
drug_interaction('Valsartan', 'Zolpidem').
drug_interaction('Chlorotrianisene', 'Dicoumarol').
drug_interaction('Chlorotrianisene', 'Hyaluronidase').
drug_interaction('Chlorotrianisene', 'Lepirudin').
drug_interaction('Chlorotrianisene', 'Liothyronine').
drug_interaction('Chlorotrianisene', 'Medrysone').
drug_interaction('Chlorotrianisene', 'Vitamin C').
drug_interaction('Hyaluronidase', 'Medrysone').
drug_interaction('Hyaluronidase', 'Temazepam').
drug_interaction('Lepirudin', 'Reteplase').
drug_interaction('Lepirudin', 'Ticlopidine').
drug_interaction('Nimodipine', 'Prazosin').
drug_interaction('Nimodipine', 'Reserpine').
drug_interaction('Nimodipine', 'Sulfisoxazole').
drug_interaction('Nimodipine', 'Ticlopidine').
drug_interaction('Nimodipine', 'Tolcapone').
drug_interaction('Nimodipine', 'Travoprost').
drug_interaction('Nimodipine', 'Valsartan').
drug_interaction('Nimodipine', 'Venlafaxine').
drug_interaction('Ethchlorvynol', 'Fluoxetine').
drug_interaction('Ethchlorvynol', 'Fluvoxamine').
drug_interaction('Ethchlorvynol', 'Morphine').
drug_interaction('Ethchlorvynol', 'Olanzapine').
drug_interaction('Ethchlorvynol', 'Remoxipride').
drug_interaction('Ethchlorvynol', 'Reserpine').
drug_interaction('Ethchlorvynol', 'Temazepam').
drug_interaction('Ethchlorvynol', 'Tolcapone').
drug_interaction('Ethchlorvynol', 'Tramadol').
drug_interaction('Ethchlorvynol', 'Venlafaxine').
drug_interaction('Ethchlorvynol', 'Zolpidem').
drug_interaction('Efalizumab', 'Natalizumab').
drug_interaction('Ticlopidine', 'Tramadol').
drug_interaction('Ticlopidine', 'Valsartan').
drug_interaction('Ticlopidine', 'Venlafaxine').
drug_interaction('Ticlopidine', 'Zolpidem').
drug_interaction('Tramadol', 'Trospium').
drug_interaction('Tramadol', 'Venlafaxine').
drug_interaction('Tramadol', 'Zolpidem').
drug_interaction('Dofetilide', 'Erythromycin').
drug_interaction('Dofetilide', 'Fluoxetine').
drug_interaction('Dofetilide', 'Fluvoxamine').
drug_interaction('Dofetilide', 'Olanzapine').
drug_interaction('Dofetilide', 'Sorafenib').
drug_interaction('Dofetilide', 'Sulfisoxazole').
drug_interaction('Dofetilide', 'Ticlopidine').
drug_interaction('Dofetilide', 'Venlafaxine').
drug_interaction('Amikacin', 'Ampicillin').
drug_interaction('Amikacin', 'Dicloxacillin').
drug_interaction('Amikacin', 'Phenoxymethylpenicillin').
drug_interaction('Amikacin', 'Succinylcholine').
drug_interaction('Mitomycin', 'Morphine').
drug_interaction('Mitomycin', 'Natalizumab').
drug_interaction('Mitomycin', 'Olanzapine').
drug_interaction('Mitomycin', 'Prazosin').
drug_interaction('Mitomycin', 'Reserpine').
drug_interaction('Mitomycin', 'Sorafenib').
drug_interaction('Mitomycin', 'Venlafaxine').
drug_interaction('Dexbrompheniramine', 'Dronabinol').
drug_interaction('Dexbrompheniramine', 'Ethchlorvynol').
drug_interaction('Dexbrompheniramine', 'Fluoxetine').
drug_interaction('Dexbrompheniramine', 'Fluvoxamine').
drug_interaction('Dexbrompheniramine', 'Hyaluronidase').
drug_interaction('Dexbrompheniramine', 'Morphine').
drug_interaction('Dexbrompheniramine', 'Olanzapine').
drug_interaction('Dexbrompheniramine', 'Remoxipride').
drug_interaction('Dexbrompheniramine', 'Reserpine').
drug_interaction('Dexbrompheniramine', 'Temazepam').
drug_interaction('Dexbrompheniramine', 'Tolcapone').
drug_interaction('Dexbrompheniramine', 'Tramadol').
drug_interaction('Dexbrompheniramine', 'Venlafaxine').
drug_interaction('Dexbrompheniramine', 'Zolpidem').
drug_interaction('Muromonab', 'Natalizumab').
drug_interaction('Reserpine', 'Sorafenib').
drug_interaction('Reserpine', 'Temazepam').
drug_interaction('Reserpine', 'Tolcapone').
drug_interaction('Reserpine', 'Tramadol').
drug_interaction('Reserpine', 'Travoprost').
drug_interaction('Reserpine', 'Valsartan').
drug_interaction('Reserpine', 'Venlafaxine').
drug_interaction('Reserpine', 'Zolpidem').
drug_interaction('Sulfisoxazole', 'Temazepam').
drug_interaction('Sulfisoxazole', 'Ticlopidine').
drug_interaction('Sulfisoxazole', 'Tramadol').
drug_interaction('Sulfisoxazole', 'Valsartan').
drug_interaction('Sulfisoxazole', 'Venlafaxine').
drug_interaction('Sulfisoxazole', 'Zolpidem').
drug_interaction('Succinylcholine', 'Tramadol').
drug_interaction('Remoxipride', 'Reserpine').
drug_interaction('Remoxipride', 'Temazepam').
drug_interaction('Remoxipride', 'Ticlopidine').
drug_interaction('Remoxipride', 'Tolcapone').
drug_interaction('Remoxipride', 'Tramadol').
drug_interaction('Remoxipride', 'Venlafaxine').
drug_interaction('Remoxipride', 'Zolpidem').
drug_interaction('Dronabinol', 'Erythromycin').
drug_interaction('Dronabinol', 'Ethchlorvynol').
drug_interaction('Dronabinol', 'Fluoxetine').
drug_interaction('Dronabinol', 'Fluvoxamine').
drug_interaction('Dronabinol', 'Grepafloxacin').
drug_interaction('Dronabinol', 'Morphine').
drug_interaction('Dronabinol', 'Nicotine').
drug_interaction('Dronabinol', 'Olanzapine').
drug_interaction('Dronabinol', 'Prazosin').
drug_interaction('Dronabinol', 'Remoxipride').
drug_interaction('Dronabinol', 'Reserpine').
drug_interaction('Dronabinol', 'Sorafenib').
drug_interaction('Dronabinol', 'Sulfadiazine').
drug_interaction('Dronabinol', 'Sulfisoxazole').
drug_interaction('Dronabinol', 'Temazepam').
drug_interaction('Dronabinol', 'Ticlopidine').
drug_interaction('Dronabinol', 'Tolcapone').
drug_interaction('Dronabinol', 'Tramadol').
drug_interaction('Dronabinol', 'Trospium').
drug_interaction('Dronabinol', 'Valsartan').
drug_interaction('Dronabinol', 'Venlafaxine').
drug_interaction('Dronabinol', 'Zolpidem').
drug_interaction('Erythromycin', 'Famciclovir').
drug_interaction('Erythromycin', 'Fluoxetine').
drug_interaction('Erythromycin', 'Flutamide').
drug_interaction('Erythromycin', 'Fluvoxamine').
drug_interaction('Erythromycin', 'Grepafloxacin').
drug_interaction('Erythromycin', 'Liothyronine').
drug_interaction('Erythromycin', 'Mitomycin').
drug_interaction('Erythromycin', 'Morphine').
drug_interaction('Erythromycin', 'Nicotine').
drug_interaction('Erythromycin', 'Nimodipine').
drug_interaction('Erythromycin', 'Olanzapine').
drug_interaction('Erythromycin', 'Prazosin').
drug_interaction('Erythromycin', 'Pyrazinamide').
drug_interaction('Erythromycin', 'Raloxifene').
drug_interaction('Erythromycin', 'Reserpine').
drug_interaction('Erythromycin', 'Sorafenib').
drug_interaction('Erythromycin', 'Sulfadiazine').
drug_interaction('Erythromycin', 'Sulfisoxazole').
drug_interaction('Erythromycin', 'Temazepam').
drug_interaction('Erythromycin', 'Ticlopidine').
drug_interaction('Erythromycin', 'Tramadol').
drug_interaction('Erythromycin', 'Venlafaxine').
drug_interaction('Erythromycin', 'Zolpidem').
drug_interaction('Pefloxacin', 'Sulfadiazine').
drug_interaction('Pefloxacin', 'Sulfisoxazole').
drug_interaction('Alfuzosin', 'Bethanidine').
drug_interaction('Alfuzosin', 'Bortezomib').
drug_interaction('Alfuzosin', 'Chlorthalidone').
drug_interaction('Alfuzosin', 'Dofetilide').
drug_interaction('Alfuzosin', 'Erythromycin').
drug_interaction('Alfuzosin', 'Fluoxetine').
drug_interaction('Alfuzosin', 'Fluvoxamine').
drug_interaction('Alfuzosin', 'Lepirudin').
drug_interaction('Alfuzosin', 'Minoxidil').
drug_interaction('Alfuzosin', 'Nimodipine').
drug_interaction('Alfuzosin', 'Prazosin').
drug_interaction('Alfuzosin', 'Reserpine').
drug_interaction('Alfuzosin', 'Sulfisoxazole').
drug_interaction('Alfuzosin', 'Ticlopidine').
drug_interaction('Alfuzosin', 'Travoprost').
drug_interaction('Alfuzosin', 'Valsartan').
drug_interaction('Alfuzosin', 'Venlafaxine').
drug_interaction('Altretamine', 'Amitriptyline').
drug_interaction('Altretamine', 'Natalizumab').
drug_interaction('Altretamine', 'Pyridoxine').
drug_interaction('Adalimumab', 'Natalizumab').
drug_interaction('Calcium Gluceptate', 'Chlorthalidone').
drug_interaction('Calcium Gluceptate', 'Ergocalciferol').
drug_interaction('Calcium Gluceptate', 'Grepafloxacin').
drug_interaction('Calcium Gluceptate', 'Liothyronine').
drug_interaction('Calcium Gluceptate', 'Nimodipine').
drug_interaction('Calcium Gluceptate', 'Pefloxacin').
drug_interaction('Sorafenib', 'Sulfadiazine').
drug_interaction('Sorafenib', 'Sulfisoxazole').
drug_interaction('Sorafenib', 'Temazepam').
drug_interaction('Sorafenib', 'Ticlopidine').
drug_interaction('Sorafenib', 'Tramadol').
drug_interaction('Sorafenib', 'Valsartan').
drug_interaction('Sorafenib', 'Venlafaxine').
drug_interaction('Sorafenib', 'Zolpidem').
drug_interaction('Cefotiam', 'Dicoumarol').
drug_interaction('Liothyronine', 'Morphine').
drug_interaction('Liothyronine', 'Olanzapine').
drug_interaction('Liothyronine', 'Prazosin').
drug_interaction('Liothyronine', 'Reserpine').
drug_interaction('Liothyronine', 'Sorafenib').
drug_interaction('Liothyronine', 'Venlafaxine').
drug_interaction('Travoprost', 'Valsartan').
drug_interaction('Miglitol', 'Olanzapine').
drug_interaction('Miglitol', 'Pefloxacin').
drug_interaction('Miglitol', 'Sulfadiazine').
drug_interaction('Miglitol', 'Sulfisoxazole').
drug_interaction('Miglitol', 'Venlafaxine').
drug_interaction('Pyrazinamide', 'Sulfisoxazole').
drug_interaction('Pyrazinamide', 'Ticlopidine').
drug_interaction('Pyrazinamide', 'Venlafaxine').
drug_interaction('Prazosin', 'Reserpine').
drug_interaction('Prazosin', 'Sorafenib').
drug_interaction('Prazosin', 'Tolcapone').
drug_interaction('Prazosin', 'Travoprost').
drug_interaction('Prazosin', 'Valsartan').
drug_interaction('Prazosin', 'Venlafaxine').
drug_interaction('Dapsone', 'Erythromycin').
drug_interaction('Dapsone', 'Fluoxetine').
drug_interaction('Dapsone', 'Flutamide').
drug_interaction('Dapsone', 'Fluvoxamine').
drug_interaction('Dapsone', 'Nicotine').
drug_interaction('Dapsone', 'Sorafenib').
drug_interaction('Dapsone', 'Sulfadiazine').
drug_interaction('Dapsone', 'Sulfisoxazole').
drug_interaction('Dapsone', 'Thiethylperazine').
drug_interaction('Dapsone', 'Ticlopidine').
drug_interaction('Dapsone', 'Valsartan').
drug_interaction('Dapsone', 'Venlafaxine').
drug_interaction('Medrysone', 'Pefloxacin').
drug_interaction('Temazepam', 'Ticlopidine').
drug_interaction('Temazepam', 'Tolcapone').
drug_interaction('Temazepam', 'Tramadol').
drug_interaction('Temazepam', 'Valsartan').
drug_interaction('Temazepam', 'Venlafaxine').
drug_interaction('Temazepam', 'Zolpidem').
drug_interaction('Dydrogesterone', 'Lepirudin').
drug_interaction('Cevimeline', 'Erythromycin').
drug_interaction('Cevimeline', 'Fluoxetine').
drug_interaction('Cevimeline', 'Fluvoxamine').
drug_interaction('Cevimeline', 'Sulfisoxazole').
drug_interaction('Cevimeline', 'Ticlopidine').
drug_interaction('Cevimeline', 'Venlafaxine').
drug_interaction('Ampicillin', 'Dicoumarol').
drug_interaction('Chlorthalidone', 'Dofetilide').
drug_interaction('Chlorthalidone', 'Ergocalciferol').
drug_interaction('Chlorthalidone', 'Fluoxetine').
drug_interaction('Chlorthalidone', 'Fluvoxamine').
drug_interaction('Chlorthalidone', 'Medrysone').
drug_interaction('Chlorthalidone', 'Miglitol').
drug_interaction('Chlorthalidone', 'Minoxidil').
drug_interaction('Chlorthalidone', 'Morphine').
drug_interaction('Chlorthalidone', 'Nimodipine').
drug_interaction('Chlorthalidone', 'Prazosin').
drug_interaction('Chlorthalidone', 'Reserpine').
drug_interaction('Chlorthalidone', 'Tolcapone').
drug_interaction('Chlorthalidone', 'Tramadol').
drug_interaction('Chlorthalidone', 'Travoprost').
drug_interaction('Chlorthalidone', 'Trospium').
drug_interaction('Chlorthalidone', 'Valsartan').
drug_interaction('Chlorthalidone', 'Venlafaxine').
drug_interaction('L-Tryptophan', 'Venlafaxine').
drug_interaction('Menadione', 'Nicotine').
drug_interaction('Menadione', 'Ticlopidine').
drug_interaction('Minoxidil', 'Morphine').
drug_interaction('Minoxidil', 'Nimodipine').
drug_interaction('Minoxidil', 'Prazosin').
drug_interaction('Minoxidil', 'Reserpine').
drug_interaction('Minoxidil', 'Tolcapone').
drug_interaction('Minoxidil', 'Travoprost').
drug_interaction('Minoxidil', 'Valsartan').
drug_interaction('Baclofen', 'Dexbrompheniramine').
drug_interaction('Baclofen', 'Dronabinol').
drug_interaction('Baclofen', 'Ethchlorvynol').
drug_interaction('Baclofen', 'Fluoxetine').
drug_interaction('Baclofen', 'Fluvoxamine').
drug_interaction('Baclofen', 'Morphine').
drug_interaction('Baclofen', 'Olanzapine').
drug_interaction('Baclofen', 'Remoxipride').
drug_interaction('Baclofen', 'Reserpine').
drug_interaction('Baclofen', 'Temazepam').
drug_interaction('Baclofen', 'Tolcapone').
drug_interaction('Baclofen', 'Tramadol').
drug_interaction('Baclofen', 'Venlafaxine').
drug_interaction('Baclofen', 'Zolpidem').
drug_interaction('Raloxifene', 'Sulfisoxazole').
drug_interaction('Raloxifene', 'Ticlopidine').
drug_interaction('Raloxifene', 'Venlafaxine').
drug_interaction('Morphine', 'Nimodipine').
drug_interaction('Morphine', 'Olanzapine').
drug_interaction('Morphine', 'Prazosin').
drug_interaction('Morphine', 'Remoxipride').
drug_interaction('Morphine', 'Reserpine').
drug_interaction('Morphine', 'Sorafenib').
drug_interaction('Morphine', 'Succinylcholine').
drug_interaction('Morphine', 'Sulfisoxazole').
drug_interaction('Morphine', 'Temazepam').
drug_interaction('Morphine', 'Thiethylperazine').
drug_interaction('Morphine', 'Ticlopidine').
drug_interaction('Morphine', 'Tolcapone').
drug_interaction('Morphine', 'Tramadol').
drug_interaction('Morphine', 'Trospium').
drug_interaction('Morphine', 'Valsartan').
drug_interaction('Morphine', 'Venlafaxine').
drug_interaction('Morphine', 'Zolpidem').
drug_interaction('Fluoxetine', 'Flutamide').
drug_interaction('Fluoxetine', 'Fluvoxamine').
drug_interaction('Fluoxetine', 'Grepafloxacin').
drug_interaction('Fluoxetine', 'L-Tryptophan').
drug_interaction('Fluoxetine', 'Liothyronine').
drug_interaction('Fluoxetine', 'Miglitol').
drug_interaction('Fluoxetine', 'Morphine').
drug_interaction('Fluoxetine', 'Nicotine').
drug_interaction('Fluoxetine', 'Nimodipine').
drug_interaction('Fluoxetine', 'Olanzapine').
drug_interaction('Fluoxetine', 'Prazosin').
drug_interaction('Fluoxetine', 'Remoxipride').
drug_interaction('Fluoxetine', 'Reserpine').
drug_interaction('Fluoxetine', 'Sorafenib').
drug_interaction('Fluoxetine', 'Sulfadiazine').
drug_interaction('Fluoxetine', 'Sulfisoxazole').
drug_interaction('Fluoxetine', 'Temazepam').
drug_interaction('Fluoxetine', 'Thiethylperazine').
drug_interaction('Fluoxetine', 'Ticlopidine').
drug_interaction('Fluoxetine', 'Tolcapone').
drug_interaction('Fluoxetine', 'Tramadol').
drug_interaction('Fluoxetine', 'Valsartan').
drug_interaction('Fluoxetine', 'Venlafaxine').
drug_interaction('Fluoxetine', 'Zolpidem').
drug_interaction('Dicoumarol', 'Dydrogesterone').
drug_interaction('Dicoumarol', 'Erythromycin').
drug_interaction('Dicoumarol', 'Fluoxetine').
drug_interaction('Dicoumarol', 'Fluvoxamine').
drug_interaction('Dicoumarol', 'Grepafloxacin').
drug_interaction('Dicoumarol', 'Lepirudin').
drug_interaction('Dicoumarol', 'Liothyronine').
drug_interaction('Dicoumarol', 'Pefloxacin').
drug_interaction('Dicoumarol', 'Phenoxymethylpenicillin').
drug_interaction('Dicoumarol', 'Reteplase').
drug_interaction('Dicoumarol', 'Sorafenib').
drug_interaction('Dicoumarol', 'Sulfadiazine').
drug_interaction('Dicoumarol', 'Sulfisoxazole').
drug_interaction('Dicoumarol', 'Ticlopidine').
drug_interaction('Dicoumarol', 'Tramadol').
drug_interaction('Dicoumarol', 'Valsartan').
drug_interaction('Dicoumarol', 'Venlafaxine').
drug_interaction('Tolcapone', 'Tramadol').
drug_interaction('Tolcapone', 'Valsartan').
drug_interaction('Tolcapone', 'Venlafaxine').
drug_interaction('Tolcapone', 'Zolpidem').
drug_interaction('Sorafenib', 'Nicotine').
drug_interaction('Sulfadiazine', 'Nicotine').
drug_interaction('Sulfisoxazole', 'Nicotine').
drug_interaction('Ticlopidine', 'Nicotine').
drug_interaction('Valsartan', 'Nicotine').
drug_interaction('Venlafaxine', 'Nicotine').
drug_interaction('Chlorthalidone', 'Bethanidine').
drug_interaction('Minoxidil', 'Bethanidine').
drug_interaction('Nimodipine', 'Bethanidine').
drug_interaction('Prazosin', 'Bethanidine').
drug_interaction('Reserpine', 'Bethanidine').
drug_interaction('Travoprost', 'Bethanidine').
drug_interaction('Valsartan', 'Bethanidine').
drug_interaction('Venlafaxine', 'Bethanidine').
drug_interaction('Fluvoxamine', 'Flutamide').
drug_interaction('Sulfisoxazole', 'Flutamide').
drug_interaction('Ticlopidine', 'Flutamide').
drug_interaction('Venlafaxine', 'Flutamide').
drug_interaction('Zolpidem', 'Venlafaxine').
drug_interaction('Chlorotrianisene', 'Betamethasone').
drug_interaction('Chlorthalidone', 'Betamethasone').
drug_interaction('Dronabinol', 'Betamethasone').
drug_interaction('Erythromycin', 'Betamethasone').
drug_interaction('Fluoxetine', 'Betamethasone').
drug_interaction('Fluvoxamine', 'Betamethasone').
drug_interaction('Grepafloxacin', 'Betamethasone').
drug_interaction('Hyaluronidase', 'Betamethasone').
drug_interaction('Liothyronine', 'Betamethasone').
drug_interaction('Miglitol', 'Betamethasone').
drug_interaction('Mitomycin', 'Betamethasone').
drug_interaction('Morphine', 'Betamethasone').
drug_interaction('Natalizumab', 'Betamethasone').
drug_interaction('Pefloxacin', 'Betamethasone').
drug_interaction('Prazosin', 'Betamethasone').
drug_interaction('Reserpine', 'Betamethasone').
drug_interaction('Sorafenib', 'Betamethasone').
drug_interaction('Venlafaxine', 'Betamethasone').
drug_interaction('Sorafenib', 'Natalizumab').
drug_interaction('Grepafloxacin', 'Fluvoxamine').
drug_interaction('L-Tryptophan', 'Fluvoxamine').
drug_interaction('Liothyronine', 'Fluvoxamine').
drug_interaction('Menadione', 'Fluvoxamine').
drug_interaction('Miglitol', 'Fluvoxamine').
drug_interaction('Morphine', 'Fluvoxamine').
drug_interaction('Nicotine', 'Fluvoxamine').
drug_interaction('Nimodipine', 'Fluvoxamine').
drug_interaction('Olanzapine', 'Fluvoxamine').
drug_interaction('Prazosin', 'Fluvoxamine').
drug_interaction('Pyrazinamide', 'Fluvoxamine').
drug_interaction('Raloxifene', 'Fluvoxamine').
drug_interaction('Remoxipride', 'Fluvoxamine').
drug_interaction('Reserpine', 'Fluvoxamine').
drug_interaction('Sorafenib', 'Fluvoxamine').
drug_interaction('Sulfadiazine', 'Fluvoxamine').
drug_interaction('Sulfisoxazole', 'Fluvoxamine').
drug_interaction('Temazepam', 'Fluvoxamine').
drug_interaction('Thiethylperazine', 'Fluvoxamine').
drug_interaction('Ticlopidine', 'Fluvoxamine').
drug_interaction('Tolcapone', 'Fluvoxamine').
drug_interaction('Tramadol', 'Fluvoxamine').
drug_interaction('Valsartan', 'Fluvoxamine').
drug_interaction('Venlafaxine', 'Fluvoxamine').
drug_interaction('Zolpidem', 'Fluvoxamine').
drug_interaction('Fluvoxamine', 'Famciclovir').
drug_interaction('Sulfisoxazole', 'Famciclovir').
drug_interaction('Ticlopidine', 'Famciclovir').
drug_interaction('Venlafaxine', 'Famciclovir').
drug_interaction('Tramadol', 'Thiethylperazine').
drug_interaction('Liothyronine', 'Grepafloxacin').
drug_interaction('Medrysone', 'Grepafloxacin').
drug_interaction('Miglitol', 'Grepafloxacin').
drug_interaction('Mitomycin', 'Grepafloxacin').
drug_interaction('Morphine', 'Grepafloxacin').
drug_interaction('Olanzapine', 'Grepafloxacin').
drug_interaction('Prazosin', 'Grepafloxacin').
drug_interaction('Reserpine', 'Grepafloxacin').
drug_interaction('Sorafenib', 'Grepafloxacin').
drug_interaction('Sulfadiazine', 'Grepafloxacin').
drug_interaction('Sulfisoxazole', 'Grepafloxacin').
drug_interaction('Ticlopidine', 'Grepafloxacin').
drug_interaction('Venlafaxine', 'Grepafloxacin').
drug_interaction('Dicoumarol', 'Dicloxacillin').
drug_interaction('Nimodipine', 'Dicloxacillin').
drug_interaction('Sulfisoxazole', 'Sulfadiazine').
drug_interaction('Temazepam', 'Sulfadiazine').
drug_interaction('Ticlopidine', 'Sulfadiazine').
drug_interaction('Valsartan', 'Sulfadiazine').
drug_interaction('Venlafaxine', 'Sulfadiazine').
drug_interaction('Zolpidem', 'Sulfadiazine').
drug_interaction('Prazosin', 'Olanzapine').
drug_interaction('Remoxipride', 'Olanzapine').
drug_interaction('Reserpine', 'Olanzapine').
drug_interaction('Sorafenib', 'Olanzapine').
drug_interaction('Sulfisoxazole', 'Olanzapine').
drug_interaction('Temazepam', 'Olanzapine').
drug_interaction('Thiethylperazine', 'Olanzapine').
drug_interaction('Ticlopidine', 'Olanzapine').
drug_interaction('Tolcapone', 'Olanzapine').
drug_interaction('Tramadol', 'Olanzapine').
drug_interaction('Venlafaxine', 'Olanzapine').
drug_interaction('Zolpidem', 'Olanzapine').
drug_interaction('Cevimeline', 'Bortezomib').
drug_interaction('Chlorthalidone', 'Bortezomib').
drug_interaction('Dapsone', 'Bortezomib').
drug_interaction('Dofetilide', 'Bortezomib').
drug_interaction('Dronabinol', 'Bortezomib').
drug_interaction('Ergocalciferol', 'Bortezomib').
drug_interaction('Erythromycin', 'Bortezomib').
drug_interaction('Famciclovir', 'Bortezomib').
drug_interaction('Fluoxetine', 'Bortezomib').
drug_interaction('Flutamide', 'Bortezomib').
drug_interaction('Fluvoxamine', 'Bortezomib').
drug_interaction('Grepafloxacin', 'Bortezomib').
drug_interaction('Menadione', 'Bortezomib').
drug_interaction('Minoxidil', 'Bortezomib').
drug_interaction('Morphine', 'Bortezomib').
drug_interaction('Nicotine', 'Bortezomib').
drug_interaction('Nimodipine', 'Bortezomib').
drug_interaction('Olanzapine', 'Bortezomib').
drug_interaction('Prazosin', 'Bortezomib').
drug_interaction('Pyrazinamide', 'Bortezomib').
drug_interaction('Raloxifene', 'Bortezomib').
drug_interaction('Reserpine', 'Bortezomib').
drug_interaction('Sorafenib', 'Bortezomib').
drug_interaction('Sulfadiazine', 'Bortezomib').
drug_interaction('Sulfisoxazole', 'Bortezomib').
drug_interaction('Temazepam', 'Bortezomib').
drug_interaction('Ticlopidine', 'Bortezomib').
drug_interaction('Tolcapone', 'Bortezomib').
drug_interaction('Tramadol', 'Bortezomib').
drug_interaction('Valsartan', 'Bortezomib').
drug_interaction('Venlafaxine', 'Bortezomib').
drug_interaction('Vitamin C', 'Bortezomib').
drug_interaction('Zolpidem', 'Bortezomib').
drug_interaction('Ticlopidine', 'Reteplase').
drug_interaction('Baclofen', 'Amitriptyline').
drug_interaction('Betamethasone', 'Amitriptyline').
drug_interaction('Bethanidine', 'Amitriptyline').
drug_interaction('Bortezomib', 'Amitriptyline').
drug_interaction('Dexbrompheniramine', 'Amitriptyline').
drug_interaction('Dicoumarol', 'Amitriptyline').
drug_interaction('Dofetilide', 'Amitriptyline').
drug_interaction('Dronabinol', 'Amitriptyline').
drug_interaction('Erythromycin', 'Amitriptyline').
drug_interaction('Ethchlorvynol', 'Amitriptyline').
drug_interaction('Fluoxetine', 'Amitriptyline').
drug_interaction('Fluvoxamine', 'Amitriptyline').
drug_interaction('Grepafloxacin', 'Amitriptyline').
drug_interaction('Lepirudin', 'Amitriptyline').
drug_interaction('Liothyronine', 'Amitriptyline').
drug_interaction('Mitomycin', 'Amitriptyline').
drug_interaction('Morphine', 'Amitriptyline').
drug_interaction('Nicotine', 'Amitriptyline').
drug_interaction('Olanzapine', 'Amitriptyline').
drug_interaction('Prazosin', 'Amitriptyline').
drug_interaction('Remoxipride', 'Amitriptyline').
drug_interaction('Reserpine', 'Amitriptyline').
drug_interaction('Sorafenib', 'Amitriptyline').
drug_interaction('Sulfadiazine', 'Amitriptyline').
drug_interaction('Sulfisoxazole', 'Amitriptyline').
drug_interaction('Temazepam', 'Amitriptyline').
drug_interaction('Ticlopidine', 'Amitriptyline').
drug_interaction('Tolcapone', 'Amitriptyline').
drug_interaction('Tramadol', 'Amitriptyline').
drug_interaction('Valsartan', 'Amitriptyline').
drug_interaction('Venlafaxine', 'Amitriptyline').
drug_interaction('Zolpidem', 'Amitriptyline').
drug_interaction('Altretamine', 'Acetyldigitoxin').
drug_interaction('Amikacin', 'Acetyldigitoxin').
drug_interaction('Asparaginase', 'Acetyldigitoxin').
drug_interaction('Bortezomib', 'Acetyldigitoxin').
drug_interaction('Calcium Gluceptate', 'Acetyldigitoxin').
drug_interaction('Chlorotrianisene', 'Acetyldigitoxin').
drug_interaction('Chlorthalidone', 'Acetyldigitoxin').
drug_interaction('Ergocalciferol', 'Acetyldigitoxin').
drug_interaction('Erythromycin', 'Acetyldigitoxin').
drug_interaction('Flutamide', 'Acetyldigitoxin').
drug_interaction('Grepafloxacin', 'Acetyldigitoxin').
drug_interaction('Mitomycin', 'Acetyldigitoxin').
drug_interaction('Pefloxacin', 'Acetyldigitoxin').
drug_interaction('Reserpine', 'Acetyldigitoxin').
drug_interaction('Sorafenib', 'Acetyldigitoxin').
drug_interaction('Succinylcholine', 'Acetyldigitoxin').
drug_interaction('Vitamin A', 'Acetyldigitoxin').
drug_interaction('Erythromycin', 'Ergocalciferol').
drug_interaction('Fluvoxamine', 'Ergocalciferol').
drug_interaction('Sulfisoxazole', 'Ergocalciferol').
drug_interaction('Ticlopidine', 'Ergocalciferol').
drug_interaction('Venlafaxine', 'Ergocalciferol').
drug_interaction('Venlafaxine', 'Valsartan').
drug_interaction('Zolpidem', 'Valsartan').
drug_interaction('Dicoumarol', 'Chlorotrianisene').
drug_interaction('Hyaluronidase', 'Chlorotrianisene').
drug_interaction('Lepirudin', 'Chlorotrianisene').
drug_interaction('Liothyronine', 'Chlorotrianisene').
drug_interaction('Medrysone', 'Chlorotrianisene').
drug_interaction('Vitamin C', 'Chlorotrianisene').
drug_interaction('Medrysone', 'Hyaluronidase').
drug_interaction('Temazepam', 'Hyaluronidase').
drug_interaction('Reteplase', 'Lepirudin').
drug_interaction('Ticlopidine', 'Lepirudin').
drug_interaction('Prazosin', 'Nimodipine').
drug_interaction('Reserpine', 'Nimodipine').
drug_interaction('Sulfisoxazole', 'Nimodipine').
drug_interaction('Ticlopidine', 'Nimodipine').
drug_interaction('Tolcapone', 'Nimodipine').
drug_interaction('Travoprost', 'Nimodipine').
drug_interaction('Valsartan', 'Nimodipine').
drug_interaction('Venlafaxine', 'Nimodipine').
drug_interaction('Fluoxetine', 'Ethchlorvynol').
drug_interaction('Fluvoxamine', 'Ethchlorvynol').
drug_interaction('Morphine', 'Ethchlorvynol').
drug_interaction('Olanzapine', 'Ethchlorvynol').
drug_interaction('Remoxipride', 'Ethchlorvynol').
drug_interaction('Reserpine', 'Ethchlorvynol').
drug_interaction('Temazepam', 'Ethchlorvynol').
drug_interaction('Tolcapone', 'Ethchlorvynol').
drug_interaction('Tramadol', 'Ethchlorvynol').
drug_interaction('Venlafaxine', 'Ethchlorvynol').
drug_interaction('Zolpidem', 'Ethchlorvynol').
drug_interaction('Natalizumab', 'Efalizumab').
drug_interaction('Tramadol', 'Ticlopidine').
drug_interaction('Valsartan', 'Ticlopidine').
drug_interaction('Venlafaxine', 'Ticlopidine').
drug_interaction('Zolpidem', 'Ticlopidine').
drug_interaction('Trospium', 'Tramadol').
drug_interaction('Venlafaxine', 'Tramadol').
drug_interaction('Zolpidem', 'Tramadol').
drug_interaction('Erythromycin', 'Dofetilide').
drug_interaction('Fluoxetine', 'Dofetilide').
drug_interaction('Fluvoxamine', 'Dofetilide').
drug_interaction('Olanzapine', 'Dofetilide').
drug_interaction('Sorafenib', 'Dofetilide').
drug_interaction('Sulfisoxazole', 'Dofetilide').
drug_interaction('Ticlopidine', 'Dofetilide').
drug_interaction('Venlafaxine', 'Dofetilide').
drug_interaction('Ampicillin', 'Amikacin').
drug_interaction('Dicloxacillin', 'Amikacin').
drug_interaction('Phenoxymethylpenicillin', 'Amikacin').
drug_interaction('Succinylcholine', 'Amikacin').
drug_interaction('Morphine', 'Mitomycin').
drug_interaction('Natalizumab', 'Mitomycin').
drug_interaction('Olanzapine', 'Mitomycin').
drug_interaction('Prazosin', 'Mitomycin').
drug_interaction('Reserpine', 'Mitomycin').
drug_interaction('Sorafenib', 'Mitomycin').
drug_interaction('Venlafaxine', 'Mitomycin').
drug_interaction('Dronabinol', 'Dexbrompheniramine').
drug_interaction('Ethchlorvynol', 'Dexbrompheniramine').
drug_interaction('Fluoxetine', 'Dexbrompheniramine').
drug_interaction('Fluvoxamine', 'Dexbrompheniramine').
drug_interaction('Hyaluronidase', 'Dexbrompheniramine').
drug_interaction('Morphine', 'Dexbrompheniramine').
drug_interaction('Olanzapine', 'Dexbrompheniramine').
drug_interaction('Remoxipride', 'Dexbrompheniramine').
drug_interaction('Reserpine', 'Dexbrompheniramine').
drug_interaction('Temazepam', 'Dexbrompheniramine').
drug_interaction('Tolcapone', 'Dexbrompheniramine').
drug_interaction('Tramadol', 'Dexbrompheniramine').
drug_interaction('Venlafaxine', 'Dexbrompheniramine').
drug_interaction('Zolpidem', 'Dexbrompheniramine').
drug_interaction('Natalizumab', 'Muromonab').
drug_interaction('Sorafenib', 'Reserpine').
drug_interaction('Temazepam', 'Reserpine').
drug_interaction('Tolcapone', 'Reserpine').
drug_interaction('Tramadol', 'Reserpine').
drug_interaction('Travoprost', 'Reserpine').
drug_interaction('Valsartan', 'Reserpine').
drug_interaction('Venlafaxine', 'Reserpine').
drug_interaction('Zolpidem', 'Reserpine').
drug_interaction('Temazepam', 'Sulfisoxazole').
drug_interaction('Ticlopidine', 'Sulfisoxazole').
drug_interaction('Tramadol', 'Sulfisoxazole').
drug_interaction('Valsartan', 'Sulfisoxazole').
drug_interaction('Venlafaxine', 'Sulfisoxazole').
drug_interaction('Zolpidem', 'Sulfisoxazole').
drug_interaction('Tramadol', 'Succinylcholine').
drug_interaction('Reserpine', 'Remoxipride').
drug_interaction('Temazepam', 'Remoxipride').
drug_interaction('Ticlopidine', 'Remoxipride').
drug_interaction('Tolcapone', 'Remoxipride').
drug_interaction('Tramadol', 'Remoxipride').
drug_interaction('Venlafaxine', 'Remoxipride').
drug_interaction('Zolpidem', 'Remoxipride').
drug_interaction('Erythromycin', 'Dronabinol').
drug_interaction('Ethchlorvynol', 'Dronabinol').
drug_interaction('Fluoxetine', 'Dronabinol').
drug_interaction('Fluvoxamine', 'Dronabinol').
drug_interaction('Grepafloxacin', 'Dronabinol').
drug_interaction('Morphine', 'Dronabinol').
drug_interaction('Nicotine', 'Dronabinol').
drug_interaction('Olanzapine', 'Dronabinol').
drug_interaction('Prazosin', 'Dronabinol').
drug_interaction('Remoxipride', 'Dronabinol').
drug_interaction('Reserpine', 'Dronabinol').
drug_interaction('Sorafenib', 'Dronabinol').
drug_interaction('Sulfadiazine', 'Dronabinol').
drug_interaction('Sulfisoxazole', 'Dronabinol').
drug_interaction('Temazepam', 'Dronabinol').
drug_interaction('Ticlopidine', 'Dronabinol').
drug_interaction('Tolcapone', 'Dronabinol').
drug_interaction('Tramadol', 'Dronabinol').
drug_interaction('Trospium', 'Dronabinol').
drug_interaction('Valsartan', 'Dronabinol').
drug_interaction('Venlafaxine', 'Dronabinol').
drug_interaction('Zolpidem', 'Dronabinol').
drug_interaction('Famciclovir', 'Erythromycin').
drug_interaction('Fluoxetine', 'Erythromycin').
drug_interaction('Flutamide', 'Erythromycin').
drug_interaction('Fluvoxamine', 'Erythromycin').
drug_interaction('Grepafloxacin', 'Erythromycin').
drug_interaction('Liothyronine', 'Erythromycin').
drug_interaction('Mitomycin', 'Erythromycin').
drug_interaction('Morphine', 'Erythromycin').
drug_interaction('Nicotine', 'Erythromycin').
drug_interaction('Nimodipine', 'Erythromycin').
drug_interaction('Olanzapine', 'Erythromycin').
drug_interaction('Prazosin', 'Erythromycin').
drug_interaction('Pyrazinamide', 'Erythromycin').
drug_interaction('Raloxifene', 'Erythromycin').
drug_interaction('Reserpine', 'Erythromycin').
drug_interaction('Sorafenib', 'Erythromycin').
drug_interaction('Sulfadiazine', 'Erythromycin').
drug_interaction('Sulfisoxazole', 'Erythromycin').
drug_interaction('Temazepam', 'Erythromycin').
drug_interaction('Ticlopidine', 'Erythromycin').
drug_interaction('Tramadol', 'Erythromycin').
drug_interaction('Venlafaxine', 'Erythromycin').
drug_interaction('Zolpidem', 'Erythromycin').
drug_interaction('Sulfadiazine', 'Pefloxacin').
drug_interaction('Sulfisoxazole', 'Pefloxacin').
drug_interaction('Bethanidine', 'Alfuzosin').
drug_interaction('Bortezomib', 'Alfuzosin').
drug_interaction('Chlorthalidone', 'Alfuzosin').
drug_interaction('Dofetilide', 'Alfuzosin').
drug_interaction('Erythromycin', 'Alfuzosin').
drug_interaction('Fluoxetine', 'Alfuzosin').
drug_interaction('Fluvoxamine', 'Alfuzosin').
drug_interaction('Lepirudin', 'Alfuzosin').
drug_interaction('Minoxidil', 'Alfuzosin').
drug_interaction('Nimodipine', 'Alfuzosin').
drug_interaction('Prazosin', 'Alfuzosin').
drug_interaction('Reserpine', 'Alfuzosin').
drug_interaction('Sulfisoxazole', 'Alfuzosin').
drug_interaction('Ticlopidine', 'Alfuzosin').
drug_interaction('Travoprost', 'Alfuzosin').
drug_interaction('Valsartan', 'Alfuzosin').
drug_interaction('Venlafaxine', 'Alfuzosin').
drug_interaction('Amitriptyline', 'Altretamine').
drug_interaction('Natalizumab', 'Altretamine').
drug_interaction('Pyridoxine', 'Altretamine').
drug_interaction('Natalizumab', 'Adalimumab').
drug_interaction('Chlorthalidone', 'Calcium Gluceptate').
drug_interaction('Ergocalciferol', 'Calcium Gluceptate').
drug_interaction('Grepafloxacin', 'Calcium Gluceptate').
drug_interaction('Liothyronine', 'Calcium Gluceptate').
drug_interaction('Nimodipine', 'Calcium Gluceptate').
drug_interaction('Pefloxacin', 'Calcium Gluceptate').
drug_interaction('Sulfadiazine', 'Sorafenib').
drug_interaction('Sulfisoxazole', 'Sorafenib').
drug_interaction('Temazepam', 'Sorafenib').
drug_interaction('Ticlopidine', 'Sorafenib').
drug_interaction('Tramadol', 'Sorafenib').
drug_interaction('Valsartan', 'Sorafenib').
drug_interaction('Venlafaxine', 'Sorafenib').
drug_interaction('Zolpidem', 'Sorafenib').
drug_interaction('Dicoumarol', 'Cefotiam').
drug_interaction('Morphine', 'Liothyronine').
drug_interaction('Olanzapine', 'Liothyronine').
drug_interaction('Prazosin', 'Liothyronine').
drug_interaction('Reserpine', 'Liothyronine').
drug_interaction('Sorafenib', 'Liothyronine').
drug_interaction('Venlafaxine', 'Liothyronine').
drug_interaction('Valsartan', 'Travoprost').
drug_interaction('Olanzapine', 'Miglitol').
drug_interaction('Pefloxacin', 'Miglitol').
drug_interaction('Sulfadiazine', 'Miglitol').
drug_interaction('Sulfisoxazole', 'Miglitol').
drug_interaction('Venlafaxine', 'Miglitol').
drug_interaction('Sulfisoxazole', 'Pyrazinamide').
drug_interaction('Ticlopidine', 'Pyrazinamide').
drug_interaction('Venlafaxine', 'Pyrazinamide').
drug_interaction('Reserpine', 'Prazosin').
drug_interaction('Sorafenib', 'Prazosin').
drug_interaction('Tolcapone', 'Prazosin').
drug_interaction('Travoprost', 'Prazosin').
drug_interaction('Valsartan', 'Prazosin').
drug_interaction('Venlafaxine', 'Prazosin').
drug_interaction('Erythromycin', 'Dapsone').
drug_interaction('Fluoxetine', 'Dapsone').
drug_interaction('Flutamide', 'Dapsone').
drug_interaction('Fluvoxamine', 'Dapsone').
drug_interaction('Nicotine', 'Dapsone').
drug_interaction('Sorafenib', 'Dapsone').
drug_interaction('Sulfadiazine', 'Dapsone').
drug_interaction('Sulfisoxazole', 'Dapsone').
drug_interaction('Thiethylperazine', 'Dapsone').
drug_interaction('Ticlopidine', 'Dapsone').
drug_interaction('Valsartan', 'Dapsone').
drug_interaction('Venlafaxine', 'Dapsone').
drug_interaction('Pefloxacin', 'Medrysone').
drug_interaction('Ticlopidine', 'Temazepam').
drug_interaction('Tolcapone', 'Temazepam').
drug_interaction('Tramadol', 'Temazepam').
drug_interaction('Valsartan', 'Temazepam').
drug_interaction('Venlafaxine', 'Temazepam').
drug_interaction('Zolpidem', 'Temazepam').
drug_interaction('Lepirudin', 'Dydrogesterone').
drug_interaction('Erythromycin', 'Cevimeline').
drug_interaction('Fluoxetine', 'Cevimeline').
drug_interaction('Fluvoxamine', 'Cevimeline').
drug_interaction('Sulfisoxazole', 'Cevimeline').
drug_interaction('Ticlopidine', 'Cevimeline').
drug_interaction('Venlafaxine', 'Cevimeline').
drug_interaction('Dicoumarol', 'Ampicillin').
drug_interaction('Dofetilide', 'Chlorthalidone').
drug_interaction('Ergocalciferol', 'Chlorthalidone').
drug_interaction('Fluoxetine', 'Chlorthalidone').
drug_interaction('Fluvoxamine', 'Chlorthalidone').
drug_interaction('Medrysone', 'Chlorthalidone').
drug_interaction('Miglitol', 'Chlorthalidone').
drug_interaction('Minoxidil', 'Chlorthalidone').
drug_interaction('Morphine', 'Chlorthalidone').
drug_interaction('Nimodipine', 'Chlorthalidone').
drug_interaction('Prazosin', 'Chlorthalidone').
drug_interaction('Reserpine', 'Chlorthalidone').
drug_interaction('Tolcapone', 'Chlorthalidone').
drug_interaction('Tramadol', 'Chlorthalidone').
drug_interaction('Travoprost', 'Chlorthalidone').
drug_interaction('Trospium', 'Chlorthalidone').
drug_interaction('Valsartan', 'Chlorthalidone').
drug_interaction('Venlafaxine', 'Chlorthalidone').
drug_interaction('Venlafaxine', 'L-Tryptophan').
drug_interaction('Nicotine', 'Menadione').
drug_interaction('Ticlopidine', 'Menadione').
drug_interaction('Morphine', 'Minoxidil').
drug_interaction('Nimodipine', 'Minoxidil').
drug_interaction('Prazosin', 'Minoxidil').
drug_interaction('Reserpine', 'Minoxidil').
drug_interaction('Tolcapone', 'Minoxidil').
drug_interaction('Travoprost', 'Minoxidil').
drug_interaction('Valsartan', 'Minoxidil').
drug_interaction('Dexbrompheniramine', 'Baclofen').
drug_interaction('Dronabinol', 'Baclofen').
drug_interaction('Ethchlorvynol', 'Baclofen').
drug_interaction('Fluoxetine', 'Baclofen').
drug_interaction('Fluvoxamine', 'Baclofen').
drug_interaction('Morphine', 'Baclofen').
drug_interaction('Olanzapine', 'Baclofen').
drug_interaction('Remoxipride', 'Baclofen').
drug_interaction('Reserpine', 'Baclofen').
drug_interaction('Temazepam', 'Baclofen').
drug_interaction('Tolcapone', 'Baclofen').
drug_interaction('Tramadol', 'Baclofen').
drug_interaction('Venlafaxine', 'Baclofen').
drug_interaction('Zolpidem', 'Baclofen').
drug_interaction('Sulfisoxazole', 'Raloxifene').
drug_interaction('Ticlopidine', 'Raloxifene').
drug_interaction('Venlafaxine', 'Raloxifene').
drug_interaction('Nimodipine', 'Morphine').
drug_interaction('Olanzapine', 'Morphine').
drug_interaction('Prazosin', 'Morphine').
drug_interaction('Remoxipride', 'Morphine').
drug_interaction('Reserpine', 'Morphine').
drug_interaction('Sorafenib', 'Morphine').
drug_interaction('Succinylcholine', 'Morphine').
drug_interaction('Sulfisoxazole', 'Morphine').
drug_interaction('Temazepam', 'Morphine').
drug_interaction('Thiethylperazine', 'Morphine').
drug_interaction('Ticlopidine', 'Morphine').
drug_interaction('Tolcapone', 'Morphine').
drug_interaction('Tramadol', 'Morphine').
drug_interaction('Trospium', 'Morphine').
drug_interaction('Valsartan', 'Morphine').
drug_interaction('Venlafaxine', 'Morphine').
drug_interaction('Zolpidem', 'Morphine').
drug_interaction('Flutamide', 'Fluoxetine').
drug_interaction('Fluvoxamine', 'Fluoxetine').
drug_interaction('Grepafloxacin', 'Fluoxetine').
drug_interaction('L-Tryptophan', 'Fluoxetine').
drug_interaction('Liothyronine', 'Fluoxetine').
drug_interaction('Miglitol', 'Fluoxetine').
drug_interaction('Morphine', 'Fluoxetine').
drug_interaction('Nicotine', 'Fluoxetine').
drug_interaction('Nimodipine', 'Fluoxetine').
drug_interaction('Olanzapine', 'Fluoxetine').
drug_interaction('Prazosin', 'Fluoxetine').
drug_interaction('Remoxipride', 'Fluoxetine').
drug_interaction('Reserpine', 'Fluoxetine').
drug_interaction('Sorafenib', 'Fluoxetine').
drug_interaction('Sulfadiazine', 'Fluoxetine').
drug_interaction('Sulfisoxazole', 'Fluoxetine').
drug_interaction('Temazepam', 'Fluoxetine').
drug_interaction('Thiethylperazine', 'Fluoxetine').
drug_interaction('Ticlopidine', 'Fluoxetine').
drug_interaction('Tolcapone', 'Fluoxetine').
drug_interaction('Tramadol', 'Fluoxetine').
drug_interaction('Valsartan', 'Fluoxetine').
drug_interaction('Venlafaxine', 'Fluoxetine').
drug_interaction('Zolpidem', 'Fluoxetine').
drug_interaction('Dydrogesterone', 'Dicoumarol').
drug_interaction('Erythromycin', 'Dicoumarol').
drug_interaction('Fluoxetine', 'Dicoumarol').
drug_interaction('Fluvoxamine', 'Dicoumarol').
drug_interaction('Grepafloxacin', 'Dicoumarol').
drug_interaction('Lepirudin', 'Dicoumarol').
drug_interaction('Liothyronine', 'Dicoumarol').
drug_interaction('Pefloxacin', 'Dicoumarol').
drug_interaction('Phenoxymethylpenicillin', 'Dicoumarol').
drug_interaction('Reteplase', 'Dicoumarol').
drug_interaction('Sorafenib', 'Dicoumarol').
drug_interaction('Sulfadiazine', 'Dicoumarol').
drug_interaction('Sulfisoxazole', 'Dicoumarol').
drug_interaction('Ticlopidine', 'Dicoumarol').
drug_interaction('Tramadol', 'Dicoumarol').
drug_interaction('Valsartan', 'Dicoumarol').
drug_interaction('Venlafaxine', 'Dicoumarol').
drug_interaction('Tramadol', 'Tolcapone').
drug_interaction('Valsartan', 'Tolcapone').
drug_interaction('Venlafaxine', 'Tolcapone').
drug_interaction('Zolpidem', 'Tolcapone').

