
drug_interaction('Valsartan', 'Venlafaxine').
drug_interaction('Amikacin', 'Ampicillin').
drug_interaction('Amikacin', 'Botulinum Toxin Type B').
drug_interaction('Amikacin', 'Indomethacin').
drug_interaction('Amikacin', 'Succinylcholine').
drug_interaction('Amikacin', 'Tenofovir').
drug_interaction('Amikacin', 'Tenoxicam').
drug_interaction('Trastuzumab', 'Trifluridine').
drug_interaction('Indomethacin', 'Lansoprazole').
drug_interaction('Indomethacin', 'Lovastatin').
drug_interaction('Indomethacin', 'Mefloquine').
drug_interaction('Indomethacin', 'Meprobamate').
drug_interaction('Indomethacin', 'Methyclothiazide').
drug_interaction('Indomethacin', 'Metoprolol').
drug_interaction('Indomethacin', 'Morphine').
drug_interaction('Indomethacin', 'Moxifloxacin').
drug_interaction('Indomethacin', 'Nelfinavir').
drug_interaction('Indomethacin', 'Phenytoin').
drug_interaction('Indomethacin', 'Ramipril').
drug_interaction('Indomethacin', 'Secobarbital').
drug_interaction('Indomethacin', 'Sotalol').
drug_interaction('Indomethacin', 'Tenofovir').
drug_interaction('Indomethacin', 'Tenoxicam').
drug_interaction('Indomethacin', 'Ticlopidine').
drug_interaction('Indomethacin', 'Topiramate').
drug_interaction('Indomethacin', 'Treprostinil').
drug_interaction('Indomethacin', 'Triflupromazine').
drug_interaction('Indomethacin', 'Valsartan').
drug_interaction('Indomethacin', 'Venlafaxine').
drug_interaction('Moxifloxacin', 'Nelfinavir').
drug_interaction('Moxifloxacin', 'Sotalol').
drug_interaction('Moxifloxacin', 'Sucralfate').
drug_interaction('Moxifloxacin', 'Tenoxicam').
drug_interaction('Moxifloxacin', 'Theophylline').
drug_interaction('Moxifloxacin', 'Trastuzumab').
drug_interaction('Moxifloxacin', 'Treprostinil').
drug_interaction('Moxifloxacin', 'Venlafaxine').
drug_interaction('Metoprolol', 'Morphine').
drug_interaction('Metoprolol', 'Nelfinavir').
drug_interaction('Metoprolol', 'Phenylpropanolamine').
drug_interaction('Metoprolol', 'Phenytoin').
drug_interaction('Metoprolol', 'Prochlorperazine').
drug_interaction('Metoprolol', 'Ramipril').
drug_interaction('Metoprolol', 'Rituximab').
drug_interaction('Metoprolol', 'Secobarbital').
drug_interaction('Metoprolol', 'Sotalol').
drug_interaction('Metoprolol', 'Tenoxicam').
drug_interaction('Metoprolol', 'Theophylline').
drug_interaction('Metoprolol', 'Thiethylperazine').
drug_interaction('Metoprolol', 'Ticlopidine').
drug_interaction('Metoprolol', 'Topiramate').
drug_interaction('Metoprolol', 'Treprostinil').
drug_interaction('Metoprolol', 'Triflupromazine').
drug_interaction('Metoprolol', 'Valsartan').
drug_interaction('Metoprolol', 'Venlafaxine').
drug_interaction('Metformin', 'Methyclothiazide').
drug_interaction('Metformin', 'Moxifloxacin').
drug_interaction('Metformin', 'Nelfinavir').
drug_interaction('Metformin', 'Topiramate').
drug_interaction('Metformin', 'Venlafaxine').
drug_interaction('Meprobamate', 'Metoprolol').
drug_interaction('Meprobamate', 'Morphine').
drug_interaction('Meprobamate', 'Nelfinavir').
drug_interaction('Meprobamate', 'Phenytoin').
drug_interaction('Meprobamate', 'Pregabalin').
drug_interaction('Meprobamate', 'Prochlorperazine').
drug_interaction('Meprobamate', 'Secobarbital').
drug_interaction('Meprobamate', 'Ticlopidine').
drug_interaction('Meprobamate', 'Topiramate').
drug_interaction('Meprobamate', 'Triflupromazine').
drug_interaction('Meprobamate', 'Venlafaxine').
drug_interaction('Treprostinil', 'Valsartan').
drug_interaction('L-Tryptophan', 'Venlafaxine').
drug_interaction('Ampicillin', 'Atenolol').
drug_interaction('Secobarbital', 'Sotalol').
drug_interaction('Secobarbital', 'Tenoxicam').
drug_interaction('Secobarbital', 'Theophylline').
drug_interaction('Secobarbital', 'Topiramate').
drug_interaction('Secobarbital', 'Treprostinil').
drug_interaction('Secobarbital', 'Triflupromazine').
drug_interaction('Secobarbital', 'Valsartan').
drug_interaction('Secobarbital', 'Venlafaxine').
drug_interaction('Prochlorperazine', 'Secobarbital').
drug_interaction('Prochlorperazine', 'Sotalol').
drug_interaction('Prochlorperazine', 'Ticlopidine').
drug_interaction('Prochlorperazine', 'Topiramate').
drug_interaction('Prochlorperazine', 'Triflupromazine').
drug_interaction('Prochlorperazine', 'Venlafaxine').
drug_interaction('Codeine', 'Desmopressin').
drug_interaction('Codeine', 'Duloxetine').
drug_interaction('Codeine', 'Hydromorphone').
drug_interaction('Codeine', 'Indinavir').
drug_interaction('Codeine', 'Lovastatin').
drug_interaction('Codeine', 'Meprobamate').
drug_interaction('Codeine', 'Methyclothiazide').
drug_interaction('Codeine', 'Metoprolol').
drug_interaction('Codeine', 'Morphine').
drug_interaction('Codeine', 'Nelfinavir').
drug_interaction('Codeine', 'Phenytoin').
drug_interaction('Codeine', 'Pregabalin').
drug_interaction('Codeine', 'Prochlorperazine').
drug_interaction('Codeine', 'Secobarbital').
drug_interaction('Codeine', 'Succinylcholine').
drug_interaction('Codeine', 'Thiethylperazine').
drug_interaction('Codeine', 'Ticlopidine').
drug_interaction('Codeine', 'Topiramate').
drug_interaction('Codeine', 'Triflupromazine').
drug_interaction('Codeine', 'Venlafaxine').
drug_interaction('Lansoprazole', 'Lovastatin').
drug_interaction('Lansoprazole', 'Mefloquine').
drug_interaction('Lansoprazole', 'Meprobamate').
drug_interaction('Lansoprazole', 'Metoprolol').
drug_interaction('Lansoprazole', 'Morphine').
drug_interaction('Lansoprazole', 'Nelfinavir').
drug_interaction('Lansoprazole', 'Phenytoin').
drug_interaction('Lansoprazole', 'Secobarbital').
drug_interaction('Lansoprazole', 'Ticlopidine').
drug_interaction('Lansoprazole', 'Topiramate').
drug_interaction('Lansoprazole', 'Triflupromazine').
drug_interaction('Lansoprazole', 'Valsartan').
drug_interaction('Lansoprazole', 'Venlafaxine').
drug_interaction('Aminoglutethimide', 'Trastuzumab').
drug_interaction('Ticlopidine', 'Topiramate').
drug_interaction('Ticlopidine', 'Tositumomab').
drug_interaction('Ticlopidine', 'Treprostinil').
drug_interaction('Ticlopidine', 'Valsartan').
drug_interaction('Ticlopidine', 'Venlafaxine').
drug_interaction('Phenylpropanolamine', 'Sotalol').
drug_interaction('Phenylpropanolamine', 'Venlafaxine').
drug_interaction('Aminosalicylic Acid', 'Anagrelide').
drug_interaction('Aminosalicylic Acid', 'Argatroban').
drug_interaction('Aminosalicylic Acid', 'Glimepiride').
drug_interaction('Aminosalicylic Acid', 'Hyaluronidase').
drug_interaction('Aminosalicylic Acid', 'Metformin').
drug_interaction('Aminosalicylic Acid', 'Ramipril').
drug_interaction('Aminosalicylic Acid', 'Ticlopidine').
drug_interaction('Aminosalicylic Acid', 'Treprostinil').
drug_interaction('Pyridoxine', 'Secobarbital').
drug_interaction('Basiliximab', 'Trastuzumab').
drug_interaction('Phenytoin', 'Pregabalin').
drug_interaction('Phenytoin', 'Prochlorperazine').
drug_interaction('Phenytoin', 'Pyridoxine').
drug_interaction('Phenytoin', 'Secobarbital').
drug_interaction('Phenytoin', 'Tenoxicam').
drug_interaction('Phenytoin', 'Theophylline').
drug_interaction('Phenytoin', 'Ticlopidine').
drug_interaction('Phenytoin', 'Topiramate').
drug_interaction('Phenytoin', 'Treprostinil').
drug_interaction('Phenytoin', 'Triflupromazine').
drug_interaction('Phenytoin', 'Valsartan').
drug_interaction('Phenytoin', 'Venlafaxine').
drug_interaction('Botulinum Toxin Type B', 'Succinylcholine').
drug_interaction('Diethylstilbestrol', 'Hyaluronidase').
drug_interaction('Diethylstilbestrol', 'Indinavir').
drug_interaction('Diethylstilbestrol', 'Indomethacin').
drug_interaction('Diethylstilbestrol', 'Lansoprazole').
drug_interaction('Diethylstilbestrol', 'Lovastatin').
drug_interaction('Diethylstilbestrol', 'Mefloquine').
drug_interaction('Diethylstilbestrol', 'Meprobamate').
drug_interaction('Diethylstilbestrol', 'Metoprolol').
drug_interaction('Diethylstilbestrol', 'Morphine').
drug_interaction('Diethylstilbestrol', 'Nelfinavir').
drug_interaction('Diethylstilbestrol', 'Phenytoin').
drug_interaction('Diethylstilbestrol', 'Ramipril').
drug_interaction('Diethylstilbestrol', 'Secobarbital').
drug_interaction('Diethylstilbestrol', 'Theophylline').
drug_interaction('Diethylstilbestrol', 'Topiramate').
drug_interaction('Diethylstilbestrol', 'Trastuzumab').
drug_interaction('Diethylstilbestrol', 'Triflupromazine').
drug_interaction('Diethylstilbestrol', 'Venlafaxine').
drug_interaction('Gemtuzumab ozogamicin', 'Trastuzumab').
drug_interaction('Hyaluronidase', 'Phenylpropanolamine').
drug_interaction('Hyaluronidase', 'Phenytoin').
drug_interaction('Duloxetine', 'Glimepiride').
drug_interaction('Duloxetine', 'Hydromorphone').
drug_interaction('Duloxetine', 'Indinavir').
drug_interaction('Duloxetine', 'L-Tryptophan').
drug_interaction('Duloxetine', 'Meprobamate').
drug_interaction('Duloxetine', 'Metformin').
drug_interaction('Duloxetine', 'Methyclothiazide').
drug_interaction('Duloxetine', 'Metoprolol').
drug_interaction('Duloxetine', 'Morphine').
drug_interaction('Duloxetine', 'Phenylpropanolamine').
drug_interaction('Duloxetine', 'Phenytoin').
drug_interaction('Duloxetine', 'Pregabalin').
drug_interaction('Duloxetine', 'Prochlorperazine').
drug_interaction('Duloxetine', 'Ramipril').
drug_interaction('Duloxetine', 'Secobarbital').
drug_interaction('Duloxetine', 'Sotalol').
drug_interaction('Duloxetine', 'Tenofovir').
drug_interaction('Duloxetine', 'Theophylline').
drug_interaction('Duloxetine', 'Ticlopidine').
drug_interaction('Duloxetine', 'Topiramate').
drug_interaction('Duloxetine', 'Triflupromazine').
drug_interaction('Duloxetine', 'Valsartan').
drug_interaction('Duloxetine', 'Venlafaxine').
drug_interaction('Acetyldigitoxin', 'Amikacin').
drug_interaction('Acetyldigitoxin', 'Aminoglutethimide').
drug_interaction('Acetyldigitoxin', 'Anagrelide').
drug_interaction('Acetyldigitoxin', 'Atenolol').
drug_interaction('Acetyldigitoxin', 'Azithromycin').
drug_interaction('Acetyldigitoxin', 'Calcitriol').
drug_interaction('Acetyldigitoxin', 'Diethylstilbestrol').
drug_interaction('Acetyldigitoxin', 'Gemtuzumab ozogamicin').
drug_interaction('Acetyldigitoxin', 'Leuprolide').
drug_interaction('Acetyldigitoxin', 'Methyclothiazide').
drug_interaction('Acetyldigitoxin', 'Metoprolol').
drug_interaction('Acetyldigitoxin', 'Moxifloxacin').
drug_interaction('Acetyldigitoxin', 'Rituximab').
drug_interaction('Acetyldigitoxin', 'Sotalol').
drug_interaction('Acetyldigitoxin', 'Succinylcholine').
drug_interaction('Acetyldigitoxin', 'Tositumomab').
drug_interaction('Acetyldigitoxin', 'Trastuzumab').
drug_interaction('Acetyldigitoxin', 'Trifluridine').
drug_interaction('Theophylline', 'Ticlopidine').
drug_interaction('Theophylline', 'Valsartan').
drug_interaction('Theophylline', 'Venlafaxine').
drug_interaction('Indinavir', 'Indomethacin').
drug_interaction('Indinavir', 'Lansoprazole').
drug_interaction('Indinavir', 'Lovastatin').
drug_interaction('Indinavir', 'Mefloquine').
drug_interaction('Indinavir', 'Meprobamate').
drug_interaction('Indinavir', 'Metformin').
drug_interaction('Indinavir', 'Metoprolol').
drug_interaction('Indinavir', 'Morphine').
drug_interaction('Indinavir', 'Nelfinavir').
drug_interaction('Indinavir', 'Phenytoin').
drug_interaction('Indinavir', 'Prochlorperazine').
drug_interaction('Indinavir', 'Tenoxicam').
drug_interaction('Indinavir', 'Theophylline').
drug_interaction('Indinavir', 'Ticlopidine').
drug_interaction('Indinavir', 'Treprostinil').
drug_interaction('Indinavir', 'Triflupromazine').
drug_interaction('Indinavir', 'Valsartan').
drug_interaction('Indinavir', 'Venlafaxine').
drug_interaction('Morphine', 'Nelfinavir').
drug_interaction('Morphine', 'Phenytoin').
drug_interaction('Morphine', 'Pregabalin').
drug_interaction('Morphine', 'Prochlorperazine').
drug_interaction('Morphine', 'Ramipril').
drug_interaction('Morphine', 'Secobarbital').
drug_interaction('Morphine', 'Sotalol').
drug_interaction('Morphine', 'Succinylcholine').
drug_interaction('Morphine', 'Thiethylperazine').
drug_interaction('Morphine', 'Ticlopidine').
drug_interaction('Morphine', 'Topiramate').
drug_interaction('Morphine', 'Triflupromazine').
drug_interaction('Morphine', 'Valsartan').
drug_interaction('Morphine', 'Venlafaxine').
drug_interaction('Interferon gamma-1b', 'Theophylline').
drug_interaction('Ramipril', 'Rituximab').
drug_interaction('Ramipril', 'Secobarbital').
drug_interaction('Ramipril', 'Sotalol').
drug_interaction('Ramipril', 'Tenoxicam').
drug_interaction('Ramipril', 'Theophylline').
drug_interaction('Ramipril', 'Treprostinil').
drug_interaction('Ramipril', 'Valsartan').
drug_interaction('Mefloquine', 'Meprobamate').
drug_interaction('Mefloquine', 'Metoprolol').
drug_interaction('Mefloquine', 'Morphine').
drug_interaction('Mefloquine', 'Moxifloxacin').
drug_interaction('Mefloquine', 'Nelfinavir').
drug_interaction('Mefloquine', 'Phenytoin').
drug_interaction('Mefloquine', 'Pregabalin').
drug_interaction('Mefloquine', 'Prochlorperazine').
drug_interaction('Mefloquine', 'Sotalol').
drug_interaction('Mefloquine', 'Succinylcholine').
drug_interaction('Mefloquine', 'Thiethylperazine').
drug_interaction('Mefloquine', 'Ticlopidine').
drug_interaction('Mefloquine', 'Topiramate').
drug_interaction('Mefloquine', 'Triflupromazine').
drug_interaction('Mefloquine', 'Venlafaxine').
drug_interaction('Argatroban', 'Atomoxetine').
drug_interaction('Argatroban', 'Conjugated Equine Estrogens').
drug_interaction('Argatroban', 'Diethylstilbestrol').
drug_interaction('Argatroban', 'Indinavir').
drug_interaction('Argatroban', 'Indomethacin').
drug_interaction('Argatroban', 'Lovastatin').
drug_interaction('Argatroban', 'Nelfinavir').
drug_interaction('Argatroban', 'Phenytoin').
drug_interaction('Argatroban', 'Tenoxicam').
drug_interaction('Argatroban', 'Theophylline').
drug_interaction('Argatroban', 'Ticlopidine').
drug_interaction('Argatroban', 'Tositumomab').
drug_interaction('Argatroban', 'Treprostinil').
drug_interaction('Argatroban', 'Venlafaxine').
drug_interaction('Glimepiride', 'Indinavir').
drug_interaction('Glimepiride', 'Leuprolide').
drug_interaction('Glimepiride', 'Lovastatin').
drug_interaction('Glimepiride', 'Metformin').
drug_interaction('Glimepiride', 'Methyclothiazide').
drug_interaction('Glimepiride', 'Metoprolol').
drug_interaction('Glimepiride', 'Moxifloxacin').
drug_interaction('Glimepiride', 'Nelfinavir').
drug_interaction('Glimepiride', 'Phenytoin').
drug_interaction('Glimepiride', 'Secobarbital').
drug_interaction('Glimepiride', 'Sotalol').
drug_interaction('Glimepiride', 'Ticlopidine').
drug_interaction('Glimepiride', 'Trastuzumab').
drug_interaction('Glimepiride', 'Valsartan').
drug_interaction('Glimepiride', 'Venlafaxine').
drug_interaction('Topiramate', 'Triflupromazine').
drug_interaction('Topiramate', 'Venlafaxine').
drug_interaction('Tenofovir', 'Tenoxicam').
drug_interaction('Tenofovir', 'Theophylline').
drug_interaction('Chlorpromazine', 'Citalopram').
drug_interaction('Chlorpromazine', 'Codeine').
drug_interaction('Chlorpromazine', 'Conjugated Equine Estrogens').
drug_interaction('Chlorpromazine', 'Dapsone').
drug_interaction('Chlorpromazine', 'Desmopressin').
drug_interaction('Chlorpromazine', 'Diethylstilbestrol').
drug_interaction('Chlorpromazine', 'Duloxetine').
drug_interaction('Chlorpromazine', 'Hydromorphone').
drug_interaction('Chlorpromazine', 'Indinavir').
drug_interaction('Chlorpromazine', 'Indomethacin').
drug_interaction('Chlorpromazine', 'Lansoprazole').
drug_interaction('Chlorpromazine', 'Leuprolide').
drug_interaction('Chlorpromazine', 'Lovastatin').
drug_interaction('Chlorpromazine', 'Mefloquine').
drug_interaction('Chlorpromazine', 'Meprobamate').
drug_interaction('Chlorpromazine', 'Methyclothiazide').
drug_interaction('Chlorpromazine', 'Metoprolol').
drug_interaction('Chlorpromazine', 'Morphine').
drug_interaction('Chlorpromazine', 'Moxifloxacin').
drug_interaction('Chlorpromazine', 'Nelfinavir').
drug_interaction('Chlorpromazine', 'Phenytoin').
drug_interaction('Chlorpromazine', 'Pregabalin').
drug_interaction('Chlorpromazine', 'Prochlorperazine').
drug_interaction('Chlorpromazine', 'Ramipril').
drug_interaction('Chlorpromazine', 'Secobarbital').
drug_interaction('Chlorpromazine', 'Sotalol').
drug_interaction('Chlorpromazine', 'Tenofovir').
drug_interaction('Chlorpromazine', 'Theophylline').
drug_interaction('Chlorpromazine', 'Ticlopidine').
drug_interaction('Chlorpromazine', 'Topiramate').
drug_interaction('Chlorpromazine', 'Treprostinil').
drug_interaction('Chlorpromazine', 'Triflupromazine').
drug_interaction('Chlorpromazine', 'Valsartan').
drug_interaction('Chlorpromazine', 'Venlafaxine').
drug_interaction('Carboprost Tromethamine', 'Indomethacin').
drug_interaction('Carboprost Tromethamine', 'Methylergometrine').
drug_interaction('Carboprost Tromethamine', 'Tenoxicam').
drug_interaction('Desmopressin', 'Duloxetine').
drug_interaction('Desmopressin', 'Hydromorphone').
drug_interaction('Desmopressin', 'Indomethacin').
drug_interaction('Desmopressin', 'Morphine').
drug_interaction('Desmopressin', 'Tenoxicam').
drug_interaction('Desmopressin', 'Venlafaxine').
drug_interaction('Tenoxicam', 'Ticlopidine').
drug_interaction('Tenoxicam', 'Treprostinil').
drug_interaction('Tenoxicam', 'Valsartan').
drug_interaction('Tositumomab', 'Trastuzumab').
drug_interaction('Conjugated Equine Estrogens', 'Hyaluronidase').
drug_interaction('Conjugated Equine Estrogens', 'Indinavir').
drug_interaction('Conjugated Equine Estrogens', 'Indomethacin').
drug_interaction('Conjugated Equine Estrogens', 'Lansoprazole').
drug_interaction('Conjugated Equine Estrogens', 'Lovastatin').
drug_interaction('Conjugated Equine Estrogens', 'Mefloquine').
drug_interaction('Conjugated Equine Estrogens', 'Meprobamate').
drug_interaction('Conjugated Equine Estrogens', 'Metoprolol').
drug_interaction('Conjugated Equine Estrogens', 'Morphine').
drug_interaction('Conjugated Equine Estrogens', 'Nelfinavir').
drug_interaction('Conjugated Equine Estrogens', 'Phenytoin').
drug_interaction('Conjugated Equine Estrogens', 'Ramipril').
drug_interaction('Conjugated Equine Estrogens', 'Secobarbital').
drug_interaction('Conjugated Equine Estrogens', 'Tenofovir').
drug_interaction('Conjugated Equine Estrogens', 'Theophylline').
drug_interaction('Conjugated Equine Estrogens', 'Ticlopidine').
drug_interaction('Conjugated Equine Estrogens', 'Topiramate').
drug_interaction('Conjugated Equine Estrogens', 'Triflupromazine').
drug_interaction('Conjugated Equine Estrogens', 'Venlafaxine').
drug_interaction('Amphetamine', 'Atomoxetine').
drug_interaction('Amphetamine', 'Chlorpromazine').
drug_interaction('Amphetamine', 'Citalopram').
drug_interaction('Amphetamine', 'Codeine').
drug_interaction('Amphetamine', 'Duloxetine').
drug_interaction('Amphetamine', 'Hydromorphone').
drug_interaction('Amphetamine', 'Indinavir').
drug_interaction('Amphetamine', 'Lansoprazole').
drug_interaction('Amphetamine', 'Metoprolol').
drug_interaction('Amphetamine', 'Morphine').
drug_interaction('Amphetamine', 'Phenylpropanolamine').
drug_interaction('Amphetamine', 'Phenytoin').
drug_interaction('Amphetamine', 'Prochlorperazine').
drug_interaction('Amphetamine', 'Ticlopidine').
drug_interaction('Amphetamine', 'Triflupromazine').
drug_interaction('Amphetamine', 'Venlafaxine').
drug_interaction('Leuprolide', 'Mefloquine').
drug_interaction('Leuprolide', 'Metformin').
drug_interaction('Leuprolide', 'Moxifloxacin').
drug_interaction('Leuprolide', 'Nelfinavir').
drug_interaction('Leuprolide', 'Sotalol').
drug_interaction('Leuprolide', 'Trastuzumab').
drug_interaction('Leuprolide', 'Treprostinil').
drug_interaction('Leuprolide', 'Venlafaxine').
drug_interaction('Atenolol', 'Azithromycin').
drug_interaction('Atenolol', 'Bupivacaine').
drug_interaction('Atenolol', 'Chlorpromazine').
drug_interaction('Atenolol', 'Citalopram').
drug_interaction('Atenolol', 'Conjugated Equine Estrogens').
drug_interaction('Atenolol', 'Diethylstilbestrol').
drug_interaction('Atenolol', 'Duloxetine').
drug_interaction('Atenolol', 'Glimepiride').
drug_interaction('Atenolol', 'Indinavir').
drug_interaction('Atenolol', 'Indomethacin').
drug_interaction('Atenolol', 'Lansoprazole').
drug_interaction('Atenolol', 'Lovastatin').
drug_interaction('Atenolol', 'Mefloquine').
drug_interaction('Atenolol', 'Meprobamate').
drug_interaction('Atenolol', 'Methyclothiazide').
drug_interaction('Atenolol', 'Metoprolol').
drug_interaction('Atenolol', 'Morphine').
drug_interaction('Atenolol', 'Nelfinavir').
drug_interaction('Atenolol', 'Phenylpropanolamine').
drug_interaction('Atenolol', 'Phenytoin').
drug_interaction('Atenolol', 'Prochlorperazine').
drug_interaction('Atenolol', 'Ramipril').
drug_interaction('Atenolol', 'Rituximab').
drug_interaction('Atenolol', 'Secobarbital').
drug_interaction('Atenolol', 'Sotalol').
drug_interaction('Atenolol', 'Tenoxicam').
drug_interaction('Atenolol', 'Theophylline').
drug_interaction('Atenolol', 'Thiethylperazine').
drug_interaction('Atenolol', 'Treprostinil').
drug_interaction('Atenolol', 'Triflupromazine').
drug_interaction('Atenolol', 'Valsartan').
drug_interaction('Atenolol', 'Venlafaxine').
drug_interaction('Nelfinavir', 'Phenytoin').
drug_interaction('Nelfinavir', 'Prochlorperazine').
drug_interaction('Nelfinavir', 'Sotalol').
drug_interaction('Nelfinavir', 'Theophylline').
drug_interaction('Nelfinavir', 'Ticlopidine').
drug_interaction('Nelfinavir', 'Topiramate').
drug_interaction('Nelfinavir', 'Triflupromazine').
drug_interaction('Nelfinavir', 'Venlafaxine').
drug_interaction('Sotalol', 'Tenoxicam').
drug_interaction('Sotalol', 'Theophylline').
drug_interaction('Sotalol', 'Thiethylperazine').
drug_interaction('Sotalol', 'Treprostinil').
drug_interaction('Sotalol', 'Triflupromazine').
drug_interaction('Sotalol', 'Valsartan').
drug_interaction('Sotalol', 'Venlafaxine').
drug_interaction('Pregabalin', 'Prochlorperazine').
drug_interaction('Pregabalin', 'Ramipril').
drug_interaction('Pregabalin', 'Secobarbital').
drug_interaction('Pregabalin', 'Topiramate').
drug_interaction('Pregabalin', 'Triflupromazine').
drug_interaction('Pregabalin', 'Venlafaxine').
drug_interaction('Famciclovir', 'Indinavir').
drug_interaction('Famciclovir', 'Lovastatin').
drug_interaction('Famciclovir', 'Nelfinavir').
drug_interaction('Famciclovir', 'Phenytoin').
drug_interaction('Famciclovir', 'Ticlopidine').
drug_interaction('Famciclovir', 'Venlafaxine').
drug_interaction('Bupivacaine', 'Chlorpromazine').
drug_interaction('Bupivacaine', 'Citalopram').
drug_interaction('Bupivacaine', 'Codeine').
drug_interaction('Bupivacaine', 'Duloxetine').
drug_interaction('Bupivacaine', 'Hyaluronidase').
drug_interaction('Bupivacaine', 'Hydromorphone').
drug_interaction('Bupivacaine', 'Indinavir').
drug_interaction('Bupivacaine', 'Lovastatin').
drug_interaction('Bupivacaine', 'Meprobamate').
drug_interaction('Bupivacaine', 'Methyclothiazide').
drug_interaction('Bupivacaine', 'Metoprolol').
drug_interaction('Bupivacaine', 'Morphine').
drug_interaction('Bupivacaine', 'Nelfinavir').
drug_interaction('Bupivacaine', 'Phenytoin').
drug_interaction('Bupivacaine', 'Pregabalin').
drug_interaction('Bupivacaine', 'Prochlorperazine').
drug_interaction('Bupivacaine', 'Ramipril').
drug_interaction('Bupivacaine', 'Secobarbital').
drug_interaction('Bupivacaine', 'Sotalol').
drug_interaction('Bupivacaine', 'Tenofovir').
drug_interaction('Bupivacaine', 'Theophylline').
drug_interaction('Bupivacaine', 'Ticlopidine').
drug_interaction('Bupivacaine', 'Topiramate').
drug_interaction('Bupivacaine', 'Triflupromazine').
drug_interaction('Bupivacaine', 'Valsartan').
drug_interaction('Bupivacaine', 'Venlafaxine').
drug_interaction('Azithromycin', 'Bupivacaine').
drug_interaction('Azithromycin', 'Chlorpromazine').
drug_interaction('Azithromycin', 'Citalopram').
drug_interaction('Azithromycin', 'Conjugated Equine Estrogens').
drug_interaction('Azithromycin', 'Diethylstilbestrol').
drug_interaction('Azithromycin', 'Duloxetine').
drug_interaction('Azithromycin', 'Indinavir').
drug_interaction('Azithromycin', 'Indomethacin').
drug_interaction('Azithromycin', 'Lansoprazole').
drug_interaction('Azithromycin', 'Leuprolide').
drug_interaction('Azithromycin', 'Lovastatin').
drug_interaction('Azithromycin', 'Mefloquine').
drug_interaction('Azithromycin', 'Metoprolol').
drug_interaction('Azithromycin', 'Morphine').
drug_interaction('Azithromycin', 'Moxifloxacin').
drug_interaction('Azithromycin', 'Nelfinavir').
drug_interaction('Azithromycin', 'Phenytoin').
drug_interaction('Azithromycin', 'Sotalol').
drug_interaction('Azithromycin', 'Theophylline').
drug_interaction('Azithromycin', 'Ticlopidine').
drug_interaction('Azithromycin', 'Treprostinil').
drug_interaction('Azithromycin', 'Venlafaxine').
drug_interaction('L-Phenylalanine', 'Trastuzumab').
drug_interaction('Dapsone', 'Indinavir').
drug_interaction('Dapsone', 'Lovastatin').
drug_interaction('Dapsone', 'Mefloquine').
drug_interaction('Dapsone', 'Nelfinavir').
drug_interaction('Dapsone', 'Phenytoin').
drug_interaction('Dapsone', 'Prochlorperazine').
drug_interaction('Dapsone', 'Secobarbital').
drug_interaction('Dapsone', 'Thiethylperazine').
drug_interaction('Dapsone', 'Ticlopidine').
drug_interaction('Dapsone', 'Topiramate').
drug_interaction('Dapsone', 'Triflupromazine').
drug_interaction('Dapsone', 'Valsartan').
drug_interaction('Dapsone', 'Venlafaxine').
drug_interaction('Citalopram', 'Codeine').
drug_interaction('Citalopram', 'Conjugated Equine Estrogens').
drug_interaction('Citalopram', 'Dapsone').
drug_interaction('Citalopram', 'Desmopressin').
drug_interaction('Citalopram', 'Diethylstilbestrol').
drug_interaction('Citalopram', 'Duloxetine').
drug_interaction('Citalopram', 'Glimepiride').
drug_interaction('Citalopram', 'Hydromorphone').
drug_interaction('Citalopram', 'Indinavir').
drug_interaction('Citalopram', 'Indomethacin').
drug_interaction('Citalopram', 'L-Tryptophan').
drug_interaction('Citalopram', 'Lansoprazole').
drug_interaction('Citalopram', 'Leuprolide').
drug_interaction('Citalopram', 'Lovastatin').
drug_interaction('Citalopram', 'Mefloquine').
drug_interaction('Citalopram', 'Meprobamate').
drug_interaction('Citalopram', 'Metformin').
drug_interaction('Citalopram', 'Methyclothiazide').
drug_interaction('Citalopram', 'Metoprolol').
drug_interaction('Citalopram', 'Morphine').
drug_interaction('Citalopram', 'Moxifloxacin').
drug_interaction('Citalopram', 'Nelfinavir').
drug_interaction('Citalopram', 'Phenytoin').
drug_interaction('Citalopram', 'Pregabalin').
drug_interaction('Citalopram', 'Prochlorperazine').
drug_interaction('Citalopram', 'Secobarbital').
drug_interaction('Citalopram', 'Sotalol').
drug_interaction('Citalopram', 'Theophylline').
drug_interaction('Citalopram', 'Thiethylperazine').
drug_interaction('Citalopram', 'Ticlopidine').
drug_interaction('Citalopram', 'Topiramate').
drug_interaction('Citalopram', 'Treprostinil').
drug_interaction('Citalopram', 'Triflupromazine').
drug_interaction('Citalopram', 'Venlafaxine').
drug_interaction('Atomoxetine', 'Azithromycin').
drug_interaction('Atomoxetine', 'Benzatropine').
drug_interaction('Atomoxetine', 'Bupivacaine').
drug_interaction('Atomoxetine', 'Calcitriol').
drug_interaction('Atomoxetine', 'Chlorpromazine').
drug_interaction('Atomoxetine', 'Citalopram').
drug_interaction('Atomoxetine', 'Codeine').
drug_interaction('Atomoxetine', 'Conjugated Equine Estrogens').
drug_interaction('Atomoxetine', 'Dapsone').
drug_interaction('Atomoxetine', 'Duloxetine').
drug_interaction('Atomoxetine', 'Famciclovir').
drug_interaction('Atomoxetine', 'Hydromorphone').
drug_interaction('Atomoxetine', 'Indinavir').
drug_interaction('Atomoxetine', 'Lansoprazole').
drug_interaction('Atomoxetine', 'Leuprolide').
drug_interaction('Atomoxetine', 'Lovastatin').
drug_interaction('Atomoxetine', 'Mefloquine').
drug_interaction('Atomoxetine', 'Metoprolol').
drug_interaction('Atomoxetine', 'Morphine').
drug_interaction('Atomoxetine', 'Moxifloxacin').
drug_interaction('Atomoxetine', 'Nelfinavir').
drug_interaction('Atomoxetine', 'Phenylpropanolamine').
drug_interaction('Atomoxetine', 'Phenytoin').
drug_interaction('Atomoxetine', 'Prochlorperazine').
drug_interaction('Atomoxetine', 'Sotalol').
drug_interaction('Atomoxetine', 'Theophylline').
drug_interaction('Atomoxetine', 'Ticlopidine').
drug_interaction('Atomoxetine', 'Topiramate').
drug_interaction('Atomoxetine', 'Venlafaxine').
drug_interaction('Anagrelide', 'Argatroban').
drug_interaction('Anagrelide', 'Atomoxetine').
drug_interaction('Anagrelide', 'Azithromycin').
drug_interaction('Anagrelide', 'Chlorpromazine').
drug_interaction('Anagrelide', 'Citalopram').
drug_interaction('Anagrelide', 'Leuprolide').
drug_interaction('Anagrelide', 'Mefloquine').
drug_interaction('Anagrelide', 'Moxifloxacin').
drug_interaction('Anagrelide', 'Nelfinavir').
drug_interaction('Anagrelide', 'Sotalol').
drug_interaction('Anagrelide', 'Tenofovir').
drug_interaction('Anagrelide', 'Theophylline').
drug_interaction('Anagrelide', 'Ticlopidine').
drug_interaction('Anagrelide', 'Tositumomab').
drug_interaction('Anagrelide', 'Trastuzumab').
drug_interaction('Anagrelide', 'Treprostinil').
drug_interaction('Anagrelide', 'Venlafaxine').
drug_interaction('Rituximab', 'Trastuzumab').
drug_interaction('Rituximab', 'Treprostinil').
drug_interaction('Rituximab', 'Valsartan').
drug_interaction('Triflupromazine', 'Venlafaxine').
drug_interaction('Lovastatin', 'Mefloquine').
drug_interaction('Lovastatin', 'Metoprolol').
drug_interaction('Lovastatin', 'Morphine').
drug_interaction('Lovastatin', 'Nelfinavir').
drug_interaction('Lovastatin', 'Phenytoin').
drug_interaction('Lovastatin', 'Prochlorperazine').
drug_interaction('Lovastatin', 'Ramipril').
drug_interaction('Lovastatin', 'Tenoxicam').
drug_interaction('Lovastatin', 'Theophylline').
drug_interaction('Lovastatin', 'Ticlopidine').
drug_interaction('Lovastatin', 'Treprostinil').
drug_interaction('Lovastatin', 'Valsartan').
drug_interaction('Lovastatin', 'Venlafaxine').
drug_interaction('Benzatropine', 'Botulinum Toxin Type B').
drug_interaction('Benzatropine', 'Chlorpromazine').
drug_interaction('Benzatropine', 'Citalopram').
drug_interaction('Benzatropine', 'Codeine').
drug_interaction('Benzatropine', 'Duloxetine').
drug_interaction('Benzatropine', 'Hydromorphone').
drug_interaction('Benzatropine', 'Indinavir').
drug_interaction('Benzatropine', 'Mefloquine').
drug_interaction('Benzatropine', 'Methyclothiazide').
drug_interaction('Benzatropine', 'Metoprolol').
drug_interaction('Benzatropine', 'Morphine').
drug_interaction('Benzatropine', 'Nelfinavir').
drug_interaction('Benzatropine', 'Phenytoin').
drug_interaction('Benzatropine', 'Ticlopidine').
drug_interaction('Benzatropine', 'Topiramate').
drug_interaction('Benzatropine', 'Venlafaxine').
drug_interaction('Hydromorphone', 'Indinavir').
drug_interaction('Hydromorphone', 'Lovastatin').
drug_interaction('Hydromorphone', 'Meprobamate').
drug_interaction('Hydromorphone', 'Methyclothiazide').
drug_interaction('Hydromorphone', 'Metoprolol').
drug_interaction('Hydromorphone', 'Morphine').
drug_interaction('Hydromorphone', 'Nelfinavir').
drug_interaction('Hydromorphone', 'Phenytoin').
drug_interaction('Hydromorphone', 'Pregabalin').
drug_interaction('Hydromorphone', 'Prochlorperazine').
drug_interaction('Hydromorphone', 'Secobarbital').
drug_interaction('Hydromorphone', 'Succinylcholine').
drug_interaction('Hydromorphone', 'Thiethylperazine').
drug_interaction('Hydromorphone', 'Ticlopidine').
drug_interaction('Hydromorphone', 'Topiramate').
drug_interaction('Hydromorphone', 'Triflupromazine').
drug_interaction('Hydromorphone', 'Valsartan').
drug_interaction('Hydromorphone', 'Venlafaxine').
drug_interaction('Methyclothiazide', 'Metoprolol').
drug_interaction('Methyclothiazide', 'Morphine').
drug_interaction('Methyclothiazide', 'Phenylpropanolamine').
drug_interaction('Methyclothiazide', 'Ramipril').
drug_interaction('Methyclothiazide', 'Secobarbital').
drug_interaction('Methyclothiazide', 'Sotalol').
drug_interaction('Methyclothiazide', 'Tenoxicam').
drug_interaction('Methyclothiazide', 'Topiramate').
drug_interaction('Methyclothiazide', 'Valsartan').
drug_interaction('Methyclothiazide', 'Venlafaxine').
drug_interaction('Calcitriol', 'Indinavir').
drug_interaction('Calcitriol', 'Lovastatin').
drug_interaction('Calcitriol', 'Methyclothiazide').
drug_interaction('Calcitriol', 'Nelfinavir').
drug_interaction('Calcitriol', 'Phenytoin').
drug_interaction('Calcitriol', 'Sucralfate').
drug_interaction('Calcitriol', 'Ticlopidine').
drug_interaction('Calcitriol', 'Venlafaxine').
drug_interaction('Venlafaxine', 'Valsartan').
drug_interaction('Ampicillin', 'Amikacin').
drug_interaction('Botulinum Toxin Type B', 'Amikacin').
drug_interaction('Indomethacin', 'Amikacin').
drug_interaction('Succinylcholine', 'Amikacin').
drug_interaction('Tenofovir', 'Amikacin').
drug_interaction('Tenoxicam', 'Amikacin').
drug_interaction('Trifluridine', 'Trastuzumab').
drug_interaction('Lansoprazole', 'Indomethacin').
drug_interaction('Lovastatin', 'Indomethacin').
drug_interaction('Mefloquine', 'Indomethacin').
drug_interaction('Meprobamate', 'Indomethacin').
drug_interaction('Methyclothiazide', 'Indomethacin').
drug_interaction('Metoprolol', 'Indomethacin').
drug_interaction('Morphine', 'Indomethacin').
drug_interaction('Moxifloxacin', 'Indomethacin').
drug_interaction('Nelfinavir', 'Indomethacin').
drug_interaction('Phenytoin', 'Indomethacin').
drug_interaction('Ramipril', 'Indomethacin').
drug_interaction('Secobarbital', 'Indomethacin').
drug_interaction('Sotalol', 'Indomethacin').
drug_interaction('Tenofovir', 'Indomethacin').
drug_interaction('Tenoxicam', 'Indomethacin').
drug_interaction('Ticlopidine', 'Indomethacin').
drug_interaction('Topiramate', 'Indomethacin').
drug_interaction('Treprostinil', 'Indomethacin').
drug_interaction('Triflupromazine', 'Indomethacin').
drug_interaction('Valsartan', 'Indomethacin').
drug_interaction('Venlafaxine', 'Indomethacin').
drug_interaction('Nelfinavir', 'Moxifloxacin').
drug_interaction('Sotalol', 'Moxifloxacin').
drug_interaction('Sucralfate', 'Moxifloxacin').
drug_interaction('Tenoxicam', 'Moxifloxacin').
drug_interaction('Theophylline', 'Moxifloxacin').
drug_interaction('Trastuzumab', 'Moxifloxacin').
drug_interaction('Treprostinil', 'Moxifloxacin').
drug_interaction('Venlafaxine', 'Moxifloxacin').
drug_interaction('Morphine', 'Metoprolol').
drug_interaction('Nelfinavir', 'Metoprolol').
drug_interaction('Phenylpropanolamine', 'Metoprolol').
drug_interaction('Phenytoin', 'Metoprolol').
drug_interaction('Prochlorperazine', 'Metoprolol').
drug_interaction('Ramipril', 'Metoprolol').
drug_interaction('Rituximab', 'Metoprolol').
drug_interaction('Secobarbital', 'Metoprolol').
drug_interaction('Sotalol', 'Metoprolol').
drug_interaction('Tenoxicam', 'Metoprolol').
drug_interaction('Theophylline', 'Metoprolol').
drug_interaction('Thiethylperazine', 'Metoprolol').
drug_interaction('Ticlopidine', 'Metoprolol').
drug_interaction('Topiramate', 'Metoprolol').
drug_interaction('Treprostinil', 'Metoprolol').
drug_interaction('Triflupromazine', 'Metoprolol').
drug_interaction('Valsartan', 'Metoprolol').
drug_interaction('Venlafaxine', 'Metoprolol').
drug_interaction('Methyclothiazide', 'Metformin').
drug_interaction('Moxifloxacin', 'Metformin').
drug_interaction('Nelfinavir', 'Metformin').
drug_interaction('Topiramate', 'Metformin').
drug_interaction('Venlafaxine', 'Metformin').
drug_interaction('Metoprolol', 'Meprobamate').
drug_interaction('Morphine', 'Meprobamate').
drug_interaction('Nelfinavir', 'Meprobamate').
drug_interaction('Phenytoin', 'Meprobamate').
drug_interaction('Pregabalin', 'Meprobamate').
drug_interaction('Prochlorperazine', 'Meprobamate').
drug_interaction('Secobarbital', 'Meprobamate').
drug_interaction('Ticlopidine', 'Meprobamate').
drug_interaction('Topiramate', 'Meprobamate').
drug_interaction('Triflupromazine', 'Meprobamate').
drug_interaction('Venlafaxine', 'Meprobamate').
drug_interaction('Valsartan', 'Treprostinil').
drug_interaction('Venlafaxine', 'L-Tryptophan').
drug_interaction('Atenolol', 'Ampicillin').
drug_interaction('Sotalol', 'Secobarbital').
drug_interaction('Tenoxicam', 'Secobarbital').
drug_interaction('Theophylline', 'Secobarbital').
drug_interaction('Topiramate', 'Secobarbital').
drug_interaction('Treprostinil', 'Secobarbital').
drug_interaction('Triflupromazine', 'Secobarbital').
drug_interaction('Valsartan', 'Secobarbital').
drug_interaction('Venlafaxine', 'Secobarbital').
drug_interaction('Secobarbital', 'Prochlorperazine').
drug_interaction('Sotalol', 'Prochlorperazine').
drug_interaction('Ticlopidine', 'Prochlorperazine').
drug_interaction('Topiramate', 'Prochlorperazine').
drug_interaction('Triflupromazine', 'Prochlorperazine').
drug_interaction('Venlafaxine', 'Prochlorperazine').
drug_interaction('Desmopressin', 'Codeine').
drug_interaction('Duloxetine', 'Codeine').
drug_interaction('Hydromorphone', 'Codeine').
drug_interaction('Indinavir', 'Codeine').
drug_interaction('Lovastatin', 'Codeine').
drug_interaction('Meprobamate', 'Codeine').
drug_interaction('Methyclothiazide', 'Codeine').
drug_interaction('Metoprolol', 'Codeine').
drug_interaction('Morphine', 'Codeine').
drug_interaction('Nelfinavir', 'Codeine').
drug_interaction('Phenytoin', 'Codeine').
drug_interaction('Pregabalin', 'Codeine').
drug_interaction('Prochlorperazine', 'Codeine').
drug_interaction('Secobarbital', 'Codeine').
drug_interaction('Succinylcholine', 'Codeine').
drug_interaction('Thiethylperazine', 'Codeine').
drug_interaction('Ticlopidine', 'Codeine').
drug_interaction('Topiramate', 'Codeine').
drug_interaction('Triflupromazine', 'Codeine').
drug_interaction('Venlafaxine', 'Codeine').
drug_interaction('Lovastatin', 'Lansoprazole').
drug_interaction('Mefloquine', 'Lansoprazole').
drug_interaction('Meprobamate', 'Lansoprazole').
drug_interaction('Metoprolol', 'Lansoprazole').
drug_interaction('Morphine', 'Lansoprazole').
drug_interaction('Nelfinavir', 'Lansoprazole').
drug_interaction('Phenytoin', 'Lansoprazole').
drug_interaction('Secobarbital', 'Lansoprazole').
drug_interaction('Ticlopidine', 'Lansoprazole').
drug_interaction('Topiramate', 'Lansoprazole').
drug_interaction('Triflupromazine', 'Lansoprazole').
drug_interaction('Valsartan', 'Lansoprazole').
drug_interaction('Venlafaxine', 'Lansoprazole').
drug_interaction('Trastuzumab', 'Aminoglutethimide').
drug_interaction('Topiramate', 'Ticlopidine').
drug_interaction('Tositumomab', 'Ticlopidine').
drug_interaction('Treprostinil', 'Ticlopidine').
drug_interaction('Valsartan', 'Ticlopidine').
drug_interaction('Venlafaxine', 'Ticlopidine').
drug_interaction('Sotalol', 'Phenylpropanolamine').
drug_interaction('Venlafaxine', 'Phenylpropanolamine').
drug_interaction('Anagrelide', 'Aminosalicylic Acid').
drug_interaction('Argatroban', 'Aminosalicylic Acid').
drug_interaction('Glimepiride', 'Aminosalicylic Acid').
drug_interaction('Hyaluronidase', 'Aminosalicylic Acid').
drug_interaction('Metformin', 'Aminosalicylic Acid').
drug_interaction('Ramipril', 'Aminosalicylic Acid').
drug_interaction('Ticlopidine', 'Aminosalicylic Acid').
drug_interaction('Treprostinil', 'Aminosalicylic Acid').
drug_interaction('Secobarbital', 'Pyridoxine').
drug_interaction('Trastuzumab', 'Basiliximab').
drug_interaction('Pregabalin', 'Phenytoin').
drug_interaction('Prochlorperazine', 'Phenytoin').
drug_interaction('Pyridoxine', 'Phenytoin').
drug_interaction('Secobarbital', 'Phenytoin').
drug_interaction('Tenoxicam', 'Phenytoin').
drug_interaction('Theophylline', 'Phenytoin').
drug_interaction('Ticlopidine', 'Phenytoin').
drug_interaction('Topiramate', 'Phenytoin').
drug_interaction('Treprostinil', 'Phenytoin').
drug_interaction('Triflupromazine', 'Phenytoin').
drug_interaction('Valsartan', 'Phenytoin').
drug_interaction('Venlafaxine', 'Phenytoin').
drug_interaction('Succinylcholine', 'Botulinum Toxin Type B').
drug_interaction('Hyaluronidase', 'Diethylstilbestrol').
drug_interaction('Indinavir', 'Diethylstilbestrol').
drug_interaction('Indomethacin', 'Diethylstilbestrol').
drug_interaction('Lansoprazole', 'Diethylstilbestrol').
drug_interaction('Lovastatin', 'Diethylstilbestrol').
drug_interaction('Mefloquine', 'Diethylstilbestrol').
drug_interaction('Meprobamate', 'Diethylstilbestrol').
drug_interaction('Metoprolol', 'Diethylstilbestrol').
drug_interaction('Morphine', 'Diethylstilbestrol').
drug_interaction('Nelfinavir', 'Diethylstilbestrol').
drug_interaction('Phenytoin', 'Diethylstilbestrol').
drug_interaction('Ramipril', 'Diethylstilbestrol').
drug_interaction('Secobarbital', 'Diethylstilbestrol').
drug_interaction('Theophylline', 'Diethylstilbestrol').
drug_interaction('Topiramate', 'Diethylstilbestrol').
drug_interaction('Trastuzumab', 'Diethylstilbestrol').
drug_interaction('Triflupromazine', 'Diethylstilbestrol').
drug_interaction('Venlafaxine', 'Diethylstilbestrol').
drug_interaction('Trastuzumab', 'Gemtuzumab ozogamicin').
drug_interaction('Phenylpropanolamine', 'Hyaluronidase').
drug_interaction('Phenytoin', 'Hyaluronidase').
drug_interaction('Glimepiride', 'Duloxetine').
drug_interaction('Hydromorphone', 'Duloxetine').
drug_interaction('Indinavir', 'Duloxetine').
drug_interaction('L-Tryptophan', 'Duloxetine').
drug_interaction('Meprobamate', 'Duloxetine').
drug_interaction('Metformin', 'Duloxetine').
drug_interaction('Methyclothiazide', 'Duloxetine').
drug_interaction('Metoprolol', 'Duloxetine').
drug_interaction('Morphine', 'Duloxetine').
drug_interaction('Phenylpropanolamine', 'Duloxetine').
drug_interaction('Phenytoin', 'Duloxetine').
drug_interaction('Pregabalin', 'Duloxetine').
drug_interaction('Prochlorperazine', 'Duloxetine').
drug_interaction('Ramipril', 'Duloxetine').
drug_interaction('Secobarbital', 'Duloxetine').
drug_interaction('Sotalol', 'Duloxetine').
drug_interaction('Tenofovir', 'Duloxetine').
drug_interaction('Theophylline', 'Duloxetine').
drug_interaction('Ticlopidine', 'Duloxetine').
drug_interaction('Topiramate', 'Duloxetine').
drug_interaction('Triflupromazine', 'Duloxetine').
drug_interaction('Valsartan', 'Duloxetine').
drug_interaction('Venlafaxine', 'Duloxetine').
drug_interaction('Amikacin', 'Acetyldigitoxin').
drug_interaction('Aminoglutethimide', 'Acetyldigitoxin').
drug_interaction('Anagrelide', 'Acetyldigitoxin').
drug_interaction('Atenolol', 'Acetyldigitoxin').
drug_interaction('Azithromycin', 'Acetyldigitoxin').
drug_interaction('Calcitriol', 'Acetyldigitoxin').
drug_interaction('Diethylstilbestrol', 'Acetyldigitoxin').
drug_interaction('Gemtuzumab ozogamicin', 'Acetyldigitoxin').
drug_interaction('Leuprolide', 'Acetyldigitoxin').
drug_interaction('Methyclothiazide', 'Acetyldigitoxin').
drug_interaction('Metoprolol', 'Acetyldigitoxin').
drug_interaction('Moxifloxacin', 'Acetyldigitoxin').
drug_interaction('Rituximab', 'Acetyldigitoxin').
drug_interaction('Sotalol', 'Acetyldigitoxin').
drug_interaction('Succinylcholine', 'Acetyldigitoxin').
drug_interaction('Tositumomab', 'Acetyldigitoxin').
drug_interaction('Trastuzumab', 'Acetyldigitoxin').
drug_interaction('Trifluridine', 'Acetyldigitoxin').
drug_interaction('Ticlopidine', 'Theophylline').
drug_interaction('Valsartan', 'Theophylline').
drug_interaction('Venlafaxine', 'Theophylline').
drug_interaction('Indomethacin', 'Indinavir').
drug_interaction('Lansoprazole', 'Indinavir').
drug_interaction('Lovastatin', 'Indinavir').
drug_interaction('Mefloquine', 'Indinavir').
drug_interaction('Meprobamate', 'Indinavir').
drug_interaction('Metformin', 'Indinavir').
drug_interaction('Metoprolol', 'Indinavir').
drug_interaction('Morphine', 'Indinavir').
drug_interaction('Nelfinavir', 'Indinavir').
drug_interaction('Phenytoin', 'Indinavir').
drug_interaction('Prochlorperazine', 'Indinavir').
drug_interaction('Tenoxicam', 'Indinavir').
drug_interaction('Theophylline', 'Indinavir').
drug_interaction('Ticlopidine', 'Indinavir').
drug_interaction('Treprostinil', 'Indinavir').
drug_interaction('Triflupromazine', 'Indinavir').
drug_interaction('Valsartan', 'Indinavir').
drug_interaction('Venlafaxine', 'Indinavir').
drug_interaction('Nelfinavir', 'Morphine').
drug_interaction('Phenytoin', 'Morphine').
drug_interaction('Pregabalin', 'Morphine').
drug_interaction('Prochlorperazine', 'Morphine').
drug_interaction('Ramipril', 'Morphine').
drug_interaction('Secobarbital', 'Morphine').
drug_interaction('Sotalol', 'Morphine').
drug_interaction('Succinylcholine', 'Morphine').
drug_interaction('Thiethylperazine', 'Morphine').
drug_interaction('Ticlopidine', 'Morphine').
drug_interaction('Topiramate', 'Morphine').
drug_interaction('Triflupromazine', 'Morphine').
drug_interaction('Valsartan', 'Morphine').
drug_interaction('Venlafaxine', 'Morphine').
drug_interaction('Theophylline', 'Interferon gamma-1b').
drug_interaction('Rituximab', 'Ramipril').
drug_interaction('Secobarbital', 'Ramipril').
drug_interaction('Sotalol', 'Ramipril').
drug_interaction('Tenoxicam', 'Ramipril').
drug_interaction('Theophylline', 'Ramipril').
drug_interaction('Treprostinil', 'Ramipril').
drug_interaction('Valsartan', 'Ramipril').
drug_interaction('Meprobamate', 'Mefloquine').
drug_interaction('Metoprolol', 'Mefloquine').
drug_interaction('Morphine', 'Mefloquine').
drug_interaction('Moxifloxacin', 'Mefloquine').
drug_interaction('Nelfinavir', 'Mefloquine').
drug_interaction('Phenytoin', 'Mefloquine').
drug_interaction('Pregabalin', 'Mefloquine').
drug_interaction('Prochlorperazine', 'Mefloquine').
drug_interaction('Sotalol', 'Mefloquine').
drug_interaction('Succinylcholine', 'Mefloquine').
drug_interaction('Thiethylperazine', 'Mefloquine').
drug_interaction('Ticlopidine', 'Mefloquine').
drug_interaction('Topiramate', 'Mefloquine').
drug_interaction('Triflupromazine', 'Mefloquine').
drug_interaction('Venlafaxine', 'Mefloquine').
drug_interaction('Atomoxetine', 'Argatroban').
drug_interaction('Conjugated Equine Estrogens', 'Argatroban').
drug_interaction('Diethylstilbestrol', 'Argatroban').
drug_interaction('Indinavir', 'Argatroban').
drug_interaction('Indomethacin', 'Argatroban').
drug_interaction('Lovastatin', 'Argatroban').
drug_interaction('Nelfinavir', 'Argatroban').
drug_interaction('Phenytoin', 'Argatroban').
drug_interaction('Tenoxicam', 'Argatroban').
drug_interaction('Theophylline', 'Argatroban').
drug_interaction('Ticlopidine', 'Argatroban').
drug_interaction('Tositumomab', 'Argatroban').
drug_interaction('Treprostinil', 'Argatroban').
drug_interaction('Venlafaxine', 'Argatroban').
drug_interaction('Indinavir', 'Glimepiride').
drug_interaction('Leuprolide', 'Glimepiride').
drug_interaction('Lovastatin', 'Glimepiride').
drug_interaction('Metformin', 'Glimepiride').
drug_interaction('Methyclothiazide', 'Glimepiride').
drug_interaction('Metoprolol', 'Glimepiride').
drug_interaction('Moxifloxacin', 'Glimepiride').
drug_interaction('Nelfinavir', 'Glimepiride').
drug_interaction('Phenytoin', 'Glimepiride').
drug_interaction('Secobarbital', 'Glimepiride').
drug_interaction('Sotalol', 'Glimepiride').
drug_interaction('Ticlopidine', 'Glimepiride').
drug_interaction('Trastuzumab', 'Glimepiride').
drug_interaction('Valsartan', 'Glimepiride').
drug_interaction('Venlafaxine', 'Glimepiride').
drug_interaction('Triflupromazine', 'Topiramate').
drug_interaction('Venlafaxine', 'Topiramate').
drug_interaction('Tenoxicam', 'Tenofovir').
drug_interaction('Theophylline', 'Tenofovir').
drug_interaction('Citalopram', 'Chlorpromazine').
drug_interaction('Codeine', 'Chlorpromazine').
drug_interaction('Conjugated Equine Estrogens', 'Chlorpromazine').
drug_interaction('Dapsone', 'Chlorpromazine').
drug_interaction('Desmopressin', 'Chlorpromazine').
drug_interaction('Diethylstilbestrol', 'Chlorpromazine').
drug_interaction('Duloxetine', 'Chlorpromazine').
drug_interaction('Hydromorphone', 'Chlorpromazine').
drug_interaction('Indinavir', 'Chlorpromazine').
drug_interaction('Indomethacin', 'Chlorpromazine').
drug_interaction('Lansoprazole', 'Chlorpromazine').
drug_interaction('Leuprolide', 'Chlorpromazine').
drug_interaction('Lovastatin', 'Chlorpromazine').
drug_interaction('Mefloquine', 'Chlorpromazine').
drug_interaction('Meprobamate', 'Chlorpromazine').
drug_interaction('Methyclothiazide', 'Chlorpromazine').
drug_interaction('Metoprolol', 'Chlorpromazine').
drug_interaction('Morphine', 'Chlorpromazine').
drug_interaction('Moxifloxacin', 'Chlorpromazine').
drug_interaction('Nelfinavir', 'Chlorpromazine').
drug_interaction('Phenytoin', 'Chlorpromazine').
drug_interaction('Pregabalin', 'Chlorpromazine').
drug_interaction('Prochlorperazine', 'Chlorpromazine').
drug_interaction('Ramipril', 'Chlorpromazine').
drug_interaction('Secobarbital', 'Chlorpromazine').
drug_interaction('Sotalol', 'Chlorpromazine').
drug_interaction('Tenofovir', 'Chlorpromazine').
drug_interaction('Theophylline', 'Chlorpromazine').
drug_interaction('Ticlopidine', 'Chlorpromazine').
drug_interaction('Topiramate', 'Chlorpromazine').
drug_interaction('Treprostinil', 'Chlorpromazine').
drug_interaction('Triflupromazine', 'Chlorpromazine').
drug_interaction('Valsartan', 'Chlorpromazine').
drug_interaction('Venlafaxine', 'Chlorpromazine').
drug_interaction('Indomethacin', 'Carboprost Tromethamine').
drug_interaction('Methylergometrine', 'Carboprost Tromethamine').
drug_interaction('Tenoxicam', 'Carboprost Tromethamine').
drug_interaction('Duloxetine', 'Desmopressin').
drug_interaction('Hydromorphone', 'Desmopressin').
drug_interaction('Indomethacin', 'Desmopressin').
drug_interaction('Morphine', 'Desmopressin').
drug_interaction('Tenoxicam', 'Desmopressin').
drug_interaction('Venlafaxine', 'Desmopressin').
drug_interaction('Ticlopidine', 'Tenoxicam').
drug_interaction('Treprostinil', 'Tenoxicam').
drug_interaction('Valsartan', 'Tenoxicam').
drug_interaction('Trastuzumab', 'Tositumomab').
drug_interaction('Hyaluronidase', 'Conjugated Equine Estrogens').
drug_interaction('Indinavir', 'Conjugated Equine Estrogens').
drug_interaction('Indomethacin', 'Conjugated Equine Estrogens').
drug_interaction('Lansoprazole', 'Conjugated Equine Estrogens').
drug_interaction('Lovastatin', 'Conjugated Equine Estrogens').
drug_interaction('Mefloquine', 'Conjugated Equine Estrogens').
drug_interaction('Meprobamate', 'Conjugated Equine Estrogens').
drug_interaction('Metoprolol', 'Conjugated Equine Estrogens').
drug_interaction('Morphine', 'Conjugated Equine Estrogens').
drug_interaction('Nelfinavir', 'Conjugated Equine Estrogens').
drug_interaction('Phenytoin', 'Conjugated Equine Estrogens').
drug_interaction('Ramipril', 'Conjugated Equine Estrogens').
drug_interaction('Secobarbital', 'Conjugated Equine Estrogens').
drug_interaction('Tenofovir', 'Conjugated Equine Estrogens').
drug_interaction('Theophylline', 'Conjugated Equine Estrogens').
drug_interaction('Ticlopidine', 'Conjugated Equine Estrogens').
drug_interaction('Topiramate', 'Conjugated Equine Estrogens').
drug_interaction('Triflupromazine', 'Conjugated Equine Estrogens').
drug_interaction('Venlafaxine', 'Conjugated Equine Estrogens').
drug_interaction('Atomoxetine', 'Amphetamine').
drug_interaction('Chlorpromazine', 'Amphetamine').
drug_interaction('Citalopram', 'Amphetamine').
drug_interaction('Codeine', 'Amphetamine').
drug_interaction('Duloxetine', 'Amphetamine').
drug_interaction('Hydromorphone', 'Amphetamine').
drug_interaction('Indinavir', 'Amphetamine').
drug_interaction('Lansoprazole', 'Amphetamine').
drug_interaction('Metoprolol', 'Amphetamine').
drug_interaction('Morphine', 'Amphetamine').
drug_interaction('Phenylpropanolamine', 'Amphetamine').
drug_interaction('Phenytoin', 'Amphetamine').
drug_interaction('Prochlorperazine', 'Amphetamine').
drug_interaction('Ticlopidine', 'Amphetamine').
drug_interaction('Triflupromazine', 'Amphetamine').
drug_interaction('Venlafaxine', 'Amphetamine').
drug_interaction('Mefloquine', 'Leuprolide').
drug_interaction('Metformin', 'Leuprolide').
drug_interaction('Moxifloxacin', 'Leuprolide').
drug_interaction('Nelfinavir', 'Leuprolide').
drug_interaction('Sotalol', 'Leuprolide').
drug_interaction('Trastuzumab', 'Leuprolide').
drug_interaction('Treprostinil', 'Leuprolide').
drug_interaction('Venlafaxine', 'Leuprolide').
drug_interaction('Azithromycin', 'Atenolol').
drug_interaction('Bupivacaine', 'Atenolol').
drug_interaction('Chlorpromazine', 'Atenolol').
drug_interaction('Citalopram', 'Atenolol').
drug_interaction('Conjugated Equine Estrogens', 'Atenolol').
drug_interaction('Diethylstilbestrol', 'Atenolol').
drug_interaction('Duloxetine', 'Atenolol').
drug_interaction('Glimepiride', 'Atenolol').
drug_interaction('Indinavir', 'Atenolol').
drug_interaction('Indomethacin', 'Atenolol').
drug_interaction('Lansoprazole', 'Atenolol').
drug_interaction('Lovastatin', 'Atenolol').
drug_interaction('Mefloquine', 'Atenolol').
drug_interaction('Meprobamate', 'Atenolol').
drug_interaction('Methyclothiazide', 'Atenolol').
drug_interaction('Metoprolol', 'Atenolol').
drug_interaction('Morphine', 'Atenolol').
drug_interaction('Nelfinavir', 'Atenolol').
drug_interaction('Phenylpropanolamine', 'Atenolol').
drug_interaction('Phenytoin', 'Atenolol').
drug_interaction('Prochlorperazine', 'Atenolol').
drug_interaction('Ramipril', 'Atenolol').
drug_interaction('Rituximab', 'Atenolol').
drug_interaction('Secobarbital', 'Atenolol').
drug_interaction('Sotalol', 'Atenolol').
drug_interaction('Tenoxicam', 'Atenolol').
drug_interaction('Theophylline', 'Atenolol').
drug_interaction('Thiethylperazine', 'Atenolol').
drug_interaction('Treprostinil', 'Atenolol').
drug_interaction('Triflupromazine', 'Atenolol').
drug_interaction('Valsartan', 'Atenolol').
drug_interaction('Venlafaxine', 'Atenolol').
drug_interaction('Phenytoin', 'Nelfinavir').
drug_interaction('Prochlorperazine', 'Nelfinavir').
drug_interaction('Sotalol', 'Nelfinavir').
drug_interaction('Theophylline', 'Nelfinavir').
drug_interaction('Ticlopidine', 'Nelfinavir').
drug_interaction('Topiramate', 'Nelfinavir').
drug_interaction('Triflupromazine', 'Nelfinavir').
drug_interaction('Venlafaxine', 'Nelfinavir').
drug_interaction('Tenoxicam', 'Sotalol').
drug_interaction('Theophylline', 'Sotalol').
drug_interaction('Thiethylperazine', 'Sotalol').
drug_interaction('Treprostinil', 'Sotalol').
drug_interaction('Triflupromazine', 'Sotalol').
drug_interaction('Valsartan', 'Sotalol').
drug_interaction('Venlafaxine', 'Sotalol').
drug_interaction('Prochlorperazine', 'Pregabalin').
drug_interaction('Ramipril', 'Pregabalin').
drug_interaction('Secobarbital', 'Pregabalin').
drug_interaction('Topiramate', 'Pregabalin').
drug_interaction('Triflupromazine', 'Pregabalin').
drug_interaction('Venlafaxine', 'Pregabalin').
drug_interaction('Indinavir', 'Famciclovir').
drug_interaction('Lovastatin', 'Famciclovir').
drug_interaction('Nelfinavir', 'Famciclovir').
drug_interaction('Phenytoin', 'Famciclovir').
drug_interaction('Ticlopidine', 'Famciclovir').
drug_interaction('Venlafaxine', 'Famciclovir').
drug_interaction('Chlorpromazine', 'Bupivacaine').
drug_interaction('Citalopram', 'Bupivacaine').
drug_interaction('Codeine', 'Bupivacaine').
drug_interaction('Duloxetine', 'Bupivacaine').
drug_interaction('Hyaluronidase', 'Bupivacaine').
drug_interaction('Hydromorphone', 'Bupivacaine').
drug_interaction('Indinavir', 'Bupivacaine').
drug_interaction('Lovastatin', 'Bupivacaine').
drug_interaction('Meprobamate', 'Bupivacaine').
drug_interaction('Methyclothiazide', 'Bupivacaine').
drug_interaction('Metoprolol', 'Bupivacaine').
drug_interaction('Morphine', 'Bupivacaine').
drug_interaction('Nelfinavir', 'Bupivacaine').
drug_interaction('Phenytoin', 'Bupivacaine').
drug_interaction('Pregabalin', 'Bupivacaine').
drug_interaction('Prochlorperazine', 'Bupivacaine').
drug_interaction('Ramipril', 'Bupivacaine').
drug_interaction('Secobarbital', 'Bupivacaine').
drug_interaction('Sotalol', 'Bupivacaine').
drug_interaction('Tenofovir', 'Bupivacaine').
drug_interaction('Theophylline', 'Bupivacaine').
drug_interaction('Ticlopidine', 'Bupivacaine').
drug_interaction('Topiramate', 'Bupivacaine').
drug_interaction('Triflupromazine', 'Bupivacaine').
drug_interaction('Valsartan', 'Bupivacaine').
drug_interaction('Venlafaxine', 'Bupivacaine').
drug_interaction('Bupivacaine', 'Azithromycin').
drug_interaction('Chlorpromazine', 'Azithromycin').
drug_interaction('Citalopram', 'Azithromycin').
drug_interaction('Conjugated Equine Estrogens', 'Azithromycin').
drug_interaction('Diethylstilbestrol', 'Azithromycin').
drug_interaction('Duloxetine', 'Azithromycin').
drug_interaction('Indinavir', 'Azithromycin').
drug_interaction('Indomethacin', 'Azithromycin').
drug_interaction('Lansoprazole', 'Azithromycin').
drug_interaction('Leuprolide', 'Azithromycin').
drug_interaction('Lovastatin', 'Azithromycin').
drug_interaction('Mefloquine', 'Azithromycin').
drug_interaction('Metoprolol', 'Azithromycin').
drug_interaction('Morphine', 'Azithromycin').
drug_interaction('Moxifloxacin', 'Azithromycin').
drug_interaction('Nelfinavir', 'Azithromycin').
drug_interaction('Phenytoin', 'Azithromycin').
drug_interaction('Sotalol', 'Azithromycin').
drug_interaction('Theophylline', 'Azithromycin').
drug_interaction('Ticlopidine', 'Azithromycin').
drug_interaction('Treprostinil', 'Azithromycin').
drug_interaction('Venlafaxine', 'Azithromycin').
drug_interaction('Trastuzumab', 'L-Phenylalanine').
drug_interaction('Indinavir', 'Dapsone').
drug_interaction('Lovastatin', 'Dapsone').
drug_interaction('Mefloquine', 'Dapsone').
drug_interaction('Nelfinavir', 'Dapsone').
drug_interaction('Phenytoin', 'Dapsone').
drug_interaction('Prochlorperazine', 'Dapsone').
drug_interaction('Secobarbital', 'Dapsone').
drug_interaction('Thiethylperazine', 'Dapsone').
drug_interaction('Ticlopidine', 'Dapsone').
drug_interaction('Topiramate', 'Dapsone').
drug_interaction('Triflupromazine', 'Dapsone').
drug_interaction('Valsartan', 'Dapsone').
drug_interaction('Venlafaxine', 'Dapsone').
drug_interaction('Codeine', 'Citalopram').
drug_interaction('Conjugated Equine Estrogens', 'Citalopram').
drug_interaction('Dapsone', 'Citalopram').
drug_interaction('Desmopressin', 'Citalopram').
drug_interaction('Diethylstilbestrol', 'Citalopram').
drug_interaction('Duloxetine', 'Citalopram').
drug_interaction('Glimepiride', 'Citalopram').
drug_interaction('Hydromorphone', 'Citalopram').
drug_interaction('Indinavir', 'Citalopram').
drug_interaction('Indomethacin', 'Citalopram').
drug_interaction('L-Tryptophan', 'Citalopram').
drug_interaction('Lansoprazole', 'Citalopram').
drug_interaction('Leuprolide', 'Citalopram').
drug_interaction('Lovastatin', 'Citalopram').
drug_interaction('Mefloquine', 'Citalopram').
drug_interaction('Meprobamate', 'Citalopram').
drug_interaction('Metformin', 'Citalopram').
drug_interaction('Methyclothiazide', 'Citalopram').
drug_interaction('Metoprolol', 'Citalopram').
drug_interaction('Morphine', 'Citalopram').
drug_interaction('Moxifloxacin', 'Citalopram').
drug_interaction('Nelfinavir', 'Citalopram').
drug_interaction('Phenytoin', 'Citalopram').
drug_interaction('Pregabalin', 'Citalopram').
drug_interaction('Prochlorperazine', 'Citalopram').
drug_interaction('Secobarbital', 'Citalopram').
drug_interaction('Sotalol', 'Citalopram').
drug_interaction('Theophylline', 'Citalopram').
drug_interaction('Thiethylperazine', 'Citalopram').
drug_interaction('Ticlopidine', 'Citalopram').
drug_interaction('Topiramate', 'Citalopram').
drug_interaction('Treprostinil', 'Citalopram').
drug_interaction('Triflupromazine', 'Citalopram').
drug_interaction('Venlafaxine', 'Citalopram').
drug_interaction('Azithromycin', 'Atomoxetine').
drug_interaction('Benzatropine', 'Atomoxetine').
drug_interaction('Bupivacaine', 'Atomoxetine').
drug_interaction('Calcitriol', 'Atomoxetine').
drug_interaction('Chlorpromazine', 'Atomoxetine').
drug_interaction('Citalopram', 'Atomoxetine').
drug_interaction('Codeine', 'Atomoxetine').
drug_interaction('Conjugated Equine Estrogens', 'Atomoxetine').
drug_interaction('Dapsone', 'Atomoxetine').
drug_interaction('Duloxetine', 'Atomoxetine').
drug_interaction('Famciclovir', 'Atomoxetine').
drug_interaction('Hydromorphone', 'Atomoxetine').
drug_interaction('Indinavir', 'Atomoxetine').
drug_interaction('Lansoprazole', 'Atomoxetine').
drug_interaction('Leuprolide', 'Atomoxetine').
drug_interaction('Lovastatin', 'Atomoxetine').
drug_interaction('Mefloquine', 'Atomoxetine').
drug_interaction('Metoprolol', 'Atomoxetine').
drug_interaction('Morphine', 'Atomoxetine').
drug_interaction('Moxifloxacin', 'Atomoxetine').
drug_interaction('Nelfinavir', 'Atomoxetine').
drug_interaction('Phenylpropanolamine', 'Atomoxetine').
drug_interaction('Phenytoin', 'Atomoxetine').
drug_interaction('Prochlorperazine', 'Atomoxetine').
drug_interaction('Sotalol', 'Atomoxetine').
drug_interaction('Theophylline', 'Atomoxetine').
drug_interaction('Ticlopidine', 'Atomoxetine').
drug_interaction('Topiramate', 'Atomoxetine').
drug_interaction('Venlafaxine', 'Atomoxetine').
drug_interaction('Argatroban', 'Anagrelide').
drug_interaction('Atomoxetine', 'Anagrelide').
drug_interaction('Azithromycin', 'Anagrelide').
drug_interaction('Chlorpromazine', 'Anagrelide').
drug_interaction('Citalopram', 'Anagrelide').
drug_interaction('Leuprolide', 'Anagrelide').
drug_interaction('Mefloquine', 'Anagrelide').
drug_interaction('Moxifloxacin', 'Anagrelide').
drug_interaction('Nelfinavir', 'Anagrelide').
drug_interaction('Sotalol', 'Anagrelide').
drug_interaction('Tenofovir', 'Anagrelide').
drug_interaction('Theophylline', 'Anagrelide').
drug_interaction('Ticlopidine', 'Anagrelide').
drug_interaction('Tositumomab', 'Anagrelide').
drug_interaction('Trastuzumab', 'Anagrelide').
drug_interaction('Treprostinil', 'Anagrelide').
drug_interaction('Venlafaxine', 'Anagrelide').
drug_interaction('Trastuzumab', 'Rituximab').
drug_interaction('Treprostinil', 'Rituximab').
drug_interaction('Valsartan', 'Rituximab').
drug_interaction('Venlafaxine', 'Triflupromazine').
drug_interaction('Mefloquine', 'Lovastatin').
drug_interaction('Metoprolol', 'Lovastatin').
drug_interaction('Morphine', 'Lovastatin').
drug_interaction('Nelfinavir', 'Lovastatin').
drug_interaction('Phenytoin', 'Lovastatin').
drug_interaction('Prochlorperazine', 'Lovastatin').
drug_interaction('Ramipril', 'Lovastatin').
drug_interaction('Tenoxicam', 'Lovastatin').
drug_interaction('Theophylline', 'Lovastatin').
drug_interaction('Ticlopidine', 'Lovastatin').
drug_interaction('Treprostinil', 'Lovastatin').
drug_interaction('Valsartan', 'Lovastatin').
drug_interaction('Venlafaxine', 'Lovastatin').
drug_interaction('Botulinum Toxin Type B', 'Benzatropine').
drug_interaction('Chlorpromazine', 'Benzatropine').
drug_interaction('Citalopram', 'Benzatropine').
drug_interaction('Codeine', 'Benzatropine').
drug_interaction('Duloxetine', 'Benzatropine').
drug_interaction('Hydromorphone', 'Benzatropine').
drug_interaction('Indinavir', 'Benzatropine').
drug_interaction('Mefloquine', 'Benzatropine').
drug_interaction('Methyclothiazide', 'Benzatropine').
drug_interaction('Metoprolol', 'Benzatropine').
drug_interaction('Morphine', 'Benzatropine').
drug_interaction('Nelfinavir', 'Benzatropine').
drug_interaction('Phenytoin', 'Benzatropine').
drug_interaction('Ticlopidine', 'Benzatropine').
drug_interaction('Topiramate', 'Benzatropine').
drug_interaction('Venlafaxine', 'Benzatropine').
drug_interaction('Indinavir', 'Hydromorphone').
drug_interaction('Lovastatin', 'Hydromorphone').
drug_interaction('Meprobamate', 'Hydromorphone').
drug_interaction('Methyclothiazide', 'Hydromorphone').
drug_interaction('Metoprolol', 'Hydromorphone').
drug_interaction('Morphine', 'Hydromorphone').
drug_interaction('Nelfinavir', 'Hydromorphone').
drug_interaction('Phenytoin', 'Hydromorphone').
drug_interaction('Pregabalin', 'Hydromorphone').
drug_interaction('Prochlorperazine', 'Hydromorphone').
drug_interaction('Secobarbital', 'Hydromorphone').
drug_interaction('Succinylcholine', 'Hydromorphone').
drug_interaction('Thiethylperazine', 'Hydromorphone').
drug_interaction('Ticlopidine', 'Hydromorphone').
drug_interaction('Topiramate', 'Hydromorphone').
drug_interaction('Triflupromazine', 'Hydromorphone').
drug_interaction('Valsartan', 'Hydromorphone').
drug_interaction('Venlafaxine', 'Hydromorphone').
drug_interaction('Metoprolol', 'Methyclothiazide').
drug_interaction('Morphine', 'Methyclothiazide').
drug_interaction('Phenylpropanolamine', 'Methyclothiazide').
drug_interaction('Ramipril', 'Methyclothiazide').
drug_interaction('Secobarbital', 'Methyclothiazide').
drug_interaction('Sotalol', 'Methyclothiazide').
drug_interaction('Tenoxicam', 'Methyclothiazide').
drug_interaction('Topiramate', 'Methyclothiazide').
drug_interaction('Valsartan', 'Methyclothiazide').
drug_interaction('Venlafaxine', 'Methyclothiazide').
drug_interaction('Indinavir', 'Calcitriol').
drug_interaction('Lovastatin', 'Calcitriol').
drug_interaction('Methyclothiazide', 'Calcitriol').
drug_interaction('Nelfinavir', 'Calcitriol').
drug_interaction('Phenytoin', 'Calcitriol').
drug_interaction('Sucralfate', 'Calcitriol').
drug_interaction('Ticlopidine', 'Calcitriol').
drug_interaction('Venlafaxine', 'Calcitriol').

